### ISSUE TITLE
Investigate unique secondary index possibilites

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1716]
Many people want Rethink to support a unique secondary index feature (see https://news.ycombinator.com/item?id=6804275 for the discussion). Currently people have to resort to code like this:

``` javascript
r.branch(r.table("users").getAll(email, {index: "email"}).isEmpty(),
         r.table("users").insert(user),
         {})
```

The main problem with this code is of course that it isn't atomic -- there is no guarantee that the result is unique. This would also be an issue with any reasonably doable implementation of a unique index feature. However, this may be an acceptable tradeoff, or there may be some other creative solution here. We should brainstorm and see if we can come up with some options.

**Comment by juancampa** [comment]
@coffeemug just out of curiosity: What's special about primary indexes that secondary indexes don't have.

**Comment by larkost** [comment]
@juancampa: as @coffeemug hinted at above there is a much larger potential cost to enforcing uniqueness on a secondary index. This is because what server (or more specifically: shard) manages the data is decided based on the primary key. So a record with a primary key of `4` will always go to the same server. So when you go to add a second record with that same primary key the single server knows that it already has that record, and can immediately take action.

In contrast a secondary index does not have any bearing on where the record is stored. So when a new record comes in the server storing that value would have to ask every other primary shard-holder if it had a value with the same value. Not only is there a cost in terms of time in making all of those requests, but there is also a large complexity cost in guaranteeing that this sort of thing works reliably in a complex environment. This complexity is the reason you will probably not find distributed systems that offer unique secondary indexes.

**Comment by juancampa** [comment]
> So a record with a primary key of 4 will always go to the same server

Thanks @larkost. Makes sense.

Now, [this SO answer](http://stackoverflow.com/questions/35006761/rethinkdb-replace-with-getall/35006881#35006881) suggests that one way to guarantee uniqueness is to create another table  but I just realized that you end up with data split across shards. i.e. user data is in one shard but the user's email might be in a different one (different PKs)

Is there a best practice to this problem or is this just an inherent problem of distributed DBs which must be handled at the application layer?

**Comment by coffeemug** [comment]
This is an inherent problem in distributed DBs (can't have a unique secondary index without dramatically slowing everything down). The best way to get around it is to use compound primary keys and make one of the components the bit of data you'd normally store in a secondary index. This is fairly counterintuitive to a lot of people, so a long term solution might be to allow unique secondary indexes and making them a part of a primary key under the hood, but this solution has a bunch of problems. We'll try to look into it and come up with something viable in 2016.

**Comment by juancampa** [comment]
> The best way to get around it is to use compound primary keys and make one of the components the bit of data you'd normally store in a secondary index

Hmm this option sounds worth exploring (let's call it option 3). Let's say I go ahead and create a table ```user``` with primary key ```[r.row('id'), r.row('email')]```. How would I then create a robust query that checks to see if the email exists insert a new one if it doesn't? Using this approach, don't I need to know the ```id``` of the existing user to check if it exists?

So far the three options are:
 1. Use a single table: consistency is compromised due to lack of atomicity
 1. Use two tables: performance is compromised due to join require and data being spread across shards
 1. Use a single table with a compound index: **?**

Thanks for the feedback btw. You guys are awesome

**Comment by coffeemug** [comment]
Well, in this case you'd just create a primary key with `email` and drop the `id` entirely. But in a more general case where you can't drop the second field, it would have to be a field you already know (or can query). Then you insert both fields, and if they fail you know the row already exists. (Again, not ideal, but a reasonable workaround in many cases)

**Comment by jab** [comment]
> Well, in this case you'd just create a primary key with email and drop the id entirely

The advantage of also having an id field is it allows users to change their email address, and other records that refer to user records can still refer to them by the same id without having to be updated.

**Comment by thelinuxlich** [comment]
this approach fails if the unique id needs to be updatable :(

**Comment by devinivy** [comment]
How does this relate to dynamodb's dealings with global secondary indices? (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html)

**Comment by danielmewes** [comment]
@devinivy Yeah, from the document you linked:

> In a DynamoDB table, each key value must be unique. However, the key values in a global secondary index do not need to be unique. 

Non-unique global secondary indexes are already supported by RethinkDB.

**Comment by titoBouzout** [comment]
Been reading about rethinkdb for years, last days intensively as I finally had opportunity to scale a project and decided to use it. I was very puzzled for long hours, even took of my sleep time figuring out how to keep a unique username and also a unique email for a user. It seems to me I reached the deepest of the ocean on this thread and is not possible. I may or may not regret in future, but I want to offer a far from ideal workaround for these people that really want to use rethinkdb which seems really nice and also solve this problem, just force it via the application: 

`if(taken[email] !== undefined || taken[username] !== undefined) throw Error('username or email already taken!'); else taken[email] = taken[username] = null`

I believe this should workaround the situation for most websites. By adding new instances syncing this could also get really complicated. In that case I wish you success with the project and you will probably found a way to do it right.  Now I only have one doubt, you may be able to help, I don't know, how much memory will consume in a nodejs server an object like this with 100.000 avg length usernames and emails. Thanks!

**Comment by jedwards1211** [comment]
Just a note: the link about MongoDB unique indexes is no longer present in the docs for version 3.2.  Instead (it took some digging) I found out [here](https://docs.mongodb.com/manual/core/sharding-shard-key/) that MongoDB doesn't even let you shard a collection with unique secondary indexes.

**Comment by jedwards1211** [comment]
@neumino actually I discovered that it's not entirely true that you can't have unique secondary indexes in sharded Mongo collections.  [If the shard key is a prefix of the index, Mongo *can* guarantee uniqueness](https://docs.mongodb.com/manual/core/sharding-shard-key/), because guaranteeing uniqueness within an individual chunk is easy, and the chunks are guaranteed to be disjoint.

**Comment by riyadhzen** [comment]
Just to confirm @jedwards1211. In mongodb you can enforce a secondary compound index to become unique index if the shard key is part of that compound secondary index.
ex:
```
// userObject = {email: "foo@example.com", ownerId: 23333}

// shardKey = email (this is primary key in rethinkdb land)
// secondaryIndex = { email, ownerId } can be unique
// secondaryIndex = { ownerId } can't be unique
```

**Comment by robertjpayne** [comment]
@jedwards1211 @riyadhzen the MongoDB behaviour is allowed because requests are routed to the responsible shard based on the primary key, you can then enforce uniqueness based on a compound of the primary key and the secondary field since you guarantee the data will be local on that shard requiring no distributed lock.

But in MongoDB's I'd say that secondary index is pretty useless as a unique constraint both these records would probably pass:

```
a@a.com, 5
b@b.com, 5
```

The primary key is still unique (has to be) but the owner id is only unique against the primary key?

**Comment by riyadhzen** [comment]
@robertjpayne That's a good point, yet I think that @jedwards1211 explained the issue. 

As far as the choice of shard key is concerned, I think that the most important thing is to avoid keys that will lead to jumbo chunks (These are chunks of data that exist in a shard that can't be split); Imagine the following shard key {country: 1}, this will put all 'China' people on the same chunk and your database will not be able to split that data any more (However this is irrelevant in Rethinkdb land because you can't give 2 entities the same ID, yet a multi key index can also lead to such a case). Monotonically increasing keys are to be careful with too, because they will always hit one shard before data can be split, and in RethinkDB this can mean a short down time.
