### ISSUE TITLE
Sharding while keeping docs available. 

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#1774]
Would be great if having a replica of a table and then sharding will shard from one replica while allowing reads and writes to still fall on the other members and then when the rebalancing is done with the first group it then does the next. Just would be great for rebalaning live data sets.

**Comment by danielmewes** [comment]
The strategy described here is implemented in 2.1.
For paving over the last few seconds of unavailability when switching over shards, we need to implement something like https://github.com/rethinkdb/rethinkdb/issues/4331 . Closing this, since it's 90% done and we have a separate issue to follow up for the remaining 10%.
