### ISSUE TITLE
Add 'rethinkdb shell' command

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#189]
We already provide a gui data explorer. We should provide a CLI data explorer based on javascript. It's really easy to do with node.js, and we should help users by shipping a repl.

**Comment by larkost** [comment]
I have implemented something similar to this in the Python driver in df57248. That allows you to `python -m rethinkdb repl` and it will get you a shell/repl with the driver imported (as `r` and `rethinkdb`) and a connection (`conn`) established to a server if possible (even using `.repl` to make `run` easy).

**Comment by danielmewes** [comment]
We should maybe just have `rethinkdb shell` call the Python repl, similar to how `rethinkdb import` calls the Python import script etc.

**Comment by larkost** [comment]
This is now in `next` with 1e868573 from branch `larkost/189-add-rethinkdb-shell` after review CR 3694. We decided to use `rethinkdb repl` since that is the command we have both in the Python driver and in ReQL.

Note for integration: this has both Python driver and server components, so needs to be done with some care. We should also make care to note the rev-lock in the release notes.
