### ISSUE TITLE
XSS in Web-based admin UI

### ISSUE THREAD

**Issue by medina** [rethinkdb/rethinkdb#2018]
Attempting to rename a table `<script>alert('newtablename');</script>` gives

```
Sorry, something went wrong with the ajax request. Please try again. 
Error 400: invalid name: <script>alert('newtablename');</script>
```

and generates a log entry of:

```
info: HTTP request throw a schema_mismatch_exc_t with what = invalid name: <script>alert('newtablename');</script>
```

which looks like:

![rethinkdb_xss](https://f.cloud.github.com/assets/54688/2262931/55f5f78e-9e5f-11e3-9841-8edc8ece5013.png)

This is:

```
$ rethinkdb --version
rethinkdb 1.11.3 (CLANG 5.0 (clang-500.2.79))
```

**Comment by danielmewes** [comment]
Turns out we are still vulnerable. At least as of v2.0.x our HTTP does not check any headers to verify the origin.

**Comment by danielmewes** [comment]
Currently we generate a connection ID when setting up an HTTP-backed ReQL connection. These IDs are very predictable and so an attacker doesn't need to get the reply of the connection setup POST request before they can send a query (the web browser would reject the reply because of the same origin policy).
A decent way of fixing this issue would be to generate a cryptographic random hash instead and use that as the the connection ID, so the attacker couldn't guess it.

**Comment by danielmewes** [comment]
An implementation of secret hard to guess connection IDs is in code review 2884.

**Comment by danielmewes** [comment]
Fixed in `next` through the use of cryptographic connection IDs as of commit https://github.com/rethinkdb/rethinkdb/commit/b14a9c233342d24844efda141e6c03cc6560d25c .
Backported to v2.0.x in https://github.com/rethinkdb/rethinkdb/commit/1b8e492ea551887e2a80a22cb839cba48a551eca
