### ISSUE TITLE
Automatic failover/rebalance and lossless rebalance.

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#223]
Details being migrated from our deprecated repo.

**Comment by iamthemuffinman** [comment]
Might I suggest https://github.com/coreos/raft?

**Comment by kofalt** [comment]
There are currently working on various Raft features actually, see #3594 for example

**Comment by danielmewes** [comment]
Thank you @iamthemuffinman for the suggestion. As @kofalt noted, we're indeed actively working on integrating Raft into RethinkDB, though we won't be using the CentOS implementation.

**Comment by jonathanepollack** [comment]
:+1: 

(Given todays desire to make nearly everything stateless--even ironically data base applications--it's going to become crucial that RethinkDB clusters behave like true clusters. That means: gossip, leader election, self-healing and all that other good jazz.)

**Comment by josephglanville** [comment]
I hope the LogCabin Raft implementation is used, it's very much the canonical implementation.

I am confused somewhat by the linked issue though, it suggests that all nodes won't be aware of the metadata whilst suggesting that all nodes will be participating in the Raft quorum? I would have thought the naive solution would be to change the semi-lattice replication mechanism to use a consensus backed state machine instead of the current model rather than drastically changing the current state of affairs.
This does concern me some but perhaps I am not seeing the whole picture?

It would be good to see a cohesive design document for how Raft would be used to implement things like primary failover and cluster membership changes.

**Comment by c4milo** [comment]
FWIW, https://github.com/hashicorp/raft is a pretty decent implementation.

**Comment by danielmewes** [comment]
We've actually implemented our own based on the original Raft paper, since the existing implementations would have required significant work for integrating them into our networking and concurrency stack. You can find our implementation in https://github.com/rethinkdb/rethinkdb/tree/raft/src/clustering/generic (raft_core.hpp is probably the best starting point).

@josephglanville We're going to split up the coordination into one raft cluster per table. This has a couple of benefits. First of all, we get better scalability for the cluster size since not every server has to be involved in the administration of every table.
Furthermore you get the nice effect that you can still administer a table if most of the servers involved in that specific table (i.e. the ones hosting a replica) are still up, even if you wouldn't be able to get a quorum for the whole cluster. This is useful if you have multiple data centers for example, with some tables being bound to one data center.
(@timmaxw might be able to elaborate a bit more on this)

Descriptions of our algorithms for primary failover and membership changes currently exist primarily as comments in the source code, though I'm not sure how much of it is merged into the `raft` branch yet. If you're interested in the details, @timmaxw can probably point you to the relevant branches/files.

**Comment by danielmewes** [comment]
See the "raft" milestone for ongoing work on this https://github.com/rethinkdb/rethinkdb/issues?q=is%3Aopen+is%3Aissue+milestone%3Araft

**Comment by danielmewes** [comment]
This is done and will ship with the raft release.

**Comment by c4milo** [comment]
:dancer:

**Comment by danielmewes** [comment]
For completeness: 2.1 will have automatic failover and semi-lossless rebalance (the time where the table is unavailable during a rebalance will be a lot shorter), but it won't have automatic rebalancing.

**Comment by shimonmagal** [comment]
Specifically for my use of RethinkDB - I have some queries with .changes() opened by nodejs servers (running a rethinkdb driver). Are there currently ways to recover from both RethinkDB failure/planned-shutdown and/or server communication-failure/planned-shutdown - without making the front end having to re-run the query and register for changes all over again?

By the way, I really like RethinkDB and thinking about using it in multiple projects I'm working on. I have compared it with meteorjs, and it has much better performace - I'm guessing due to meteor running on NodeJs (I can give more details about the comparison I did...).

(Also, on one of my projects - there is an already existing code in Java + OracleDB and I have written a replicator from Oracle to RethinkDB/Mongo (for meteor). Oracle is used for Buisness logic (which is already implemented in java and has tens of thousands of lines of code and needs a DB with ACID) and RehinkDB is for data distribution to web clients (former client was swing over Java). I'm about to finish the replicator soon(matter of days) - I hope it will help people with already existing code and  systems to create new web client sides for their data and help increase RethinkDB popularity - I will let you know when I'm done - if this should interest you)

**Comment by danielmewes** [comment]
@shimonmagal Currently changefeeds will always be terminated if a server shuts down or a table is resharded.
We do have some improvements to that in the pipeline. The first step is going to ship with RethinkDB 2.2 and allow changefeeds to survive brief disconnects between the client and the server (see https://github.com/rethinkdb/rethinkdb/issues/3471 ). Later we also plan to add a type of changefeed that can survive server failures.

I'm looking forward to your Oracle -> RethinkDB replicator! :-)

**Comment by larkost** [comment]
@shimonmagal: The (probably) subsequent feature to allow changefeeds to natively survive these transitions (in most cases) is #3549. There have been a few informal conversations, and a proper implementation of this might well require the infrastructure of #3471.

**Comment by adamkdean** [comment]
@danielmewes 

> For completeness: 2.1 will have automatic failover and semi-lossless rebalance (the time where the table is unavailable during a rebalance will be a lot shorter), but it won't have automatic rebalancing.

Is this still the case with 2.3? I thought with 2.2 onwards we could do a rebalance and still be able to write documents but we get an error that the primary shard is not available if we try to insert a document while the rebalance is in progress.

**Comment by danielmewes** [comment]
@adamkdean This is still the current state. Individual primaries are still becoming unavailable intermittently during a reconfiguration. Most documents should be writeable individually most of the time, but especially queries that need to touch multiple documents or use secondary indexes will more frequently fail while rebalancing.

**Comment by danielmewes** [comment]
@adamkdean We're going to look into whether we can significantly reduce the downtime by tweaking RethinkDB's reconfiguration strategy... Maybe there are some small improvements we can do relatively quickly that will have a big impact on improving availability.

**Comment by adamkdean** [comment]
Thanks @danielmewes, appreciate the effort!
