### ISSUE TITLE
Build the OS X package on OS X 10.9

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2230]
We currently build the OS X package on 10.7. Our machine that runs 10.7 is slow and has very little memory.

We might be able to build the package on 10.9 using the `-macosx-version-min` flag.

**Comment by danielmewes** [comment]
https://github.com/rethinkdb/rethinkdb/issues/4619 suggests that there is some bug that happens when building on 10.7, but not on 10.9.

We should do this for 2.2.


Review 2130 was cancelled, but most of the disagreement seemed to stem from subjective questions about what's the "right" thing to do. The latest implementation in the review looks ok to me though.
The only open technical question that I could see was whether this could cause incompatibilities due to the flag impacting header files, while not being passed into the `CXXFLAGS` for the libraries we're compiling (compare https://github.com/rethinkdb/rethinkdb/issues/3473). I'm not too concerned about this though. The risk of this introducing an ABI incompatibility seems very very low.

@AtnNn did you have any remaining technical concerns about this change (ignoring questions of whether this should be a buildbot flag or default etc.)?

**Comment by AtnNn** [comment]
I can't ignore the location of this change. I think the fetched dependencies should be built with this flag so that they to can also be compatible with older versions of OS X. Related to #3473.

**Comment by danielmewes** [comment]
From recent experience (in particular https://github.com/rethinkdb/rethinkdb/issues/4619), I think it's almost strictly preferable to use as similar a configuration for every build as possible. This is particularly true on OS X, where many people are installing through Homebrew and not using the .dmg.

So I think it's a good idea to not make this be passed in through the environment, but to have this as a part of our default CXX flags that are filled in by `configure`.

As I understand, the effect of this flag is primarily that you get a compilation error rather than a runtime error if you're using a newer feature. So I don't think it's *critical* to use it for all libraries, though probably preferable.

@AtnNn You mention in the other issue that the build system wasn't designed for applying our build configuration to the external dependencies. Would it be possible to special case this flag in the existing system (maybe similar to the `-stdlib=libc++` work-around)?

**Comment by danielmewes** [comment]
The easiest and least controversial option seems to be defining the following environment variables in the buildbot script:
```
LDFLAGS=-mmacosx-version-min=10.7
CXXFLAGS=-mmacosx-version-min=10.7
```

Any substantial objections to this @larkost @AtnNn ?

Otherwise I'm going to go ahead and add an alternative buildbot configuration to build on gantz with these flags in the environment.

**Comment by danielmewes** [comment]
I additionally had to set `MACOSX_DEPLOYMENT_TARGET=10.7` in the environment, or else those options weren't getting applied to all external libraries.

Still need to test the generated DMG on 10.7.

**Comment by danielmewes** [comment]
This is done for 2.3.0, though @larkost is still working on an improved solution.
Going to close this.
