### ISSUE TITLE
ReQL proposal: consider using indexes by default

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2356]
```python
# Automatically use index `bar` if it exists
# Otherwise, sort by attribute `bar`
r.table('foo').order_by('bar').run()

# Sort by attribute `bar` even if index `bar` exists
r.table('foo').order_by('bar').run(no_autoindex=True)
```

This would make user experience *much* nicer.

**Comment by internalfx** [comment]
I think this issue deserves a bump....

**Comment by mike-marcacci** [comment]
While I do feel that there is a very attractive simplicity to explicit index usage, I'd like to echo @kofalt's note about auto-generated queries. There are a couple projects at my company that build very dynamic RQL queries, and because it's impossible to use multiple different indexes in a chain (#2670), I've found it very difficult to use more than a single index. Because of this limitation, only something with insight into the final generated query can make decisions on where indexes should be used.

Additionally, it isn't currently possible (at least by my understanding) for a client to digest the binary RQL index definition into something meaningful. For example, my query generator can't request the details of compound indices to determine when to use them.

And... despite those points, I do still appreciate explicit index usage for some reason. Just some more anecdotes/use-cases for consideration.

**Comment by danielmewes** [comment]
@mike-marcacci thanks for the feedback! That's very useful.

We now have a second proposal that aims to solve the main issues with building dynamic indexed queries. You can find it here: https://github.com/rethinkdb/rethinkdb/issues/4150
Would that work for you?

Getting out the details of an index function would be addressed by https://github.com/rethinkdb/rethinkdb/issues/3231 .

**Comment by mike-marcacci** [comment]
Thanks @danielmewes – I hadn't seen #4150 before, which looks like a really good solution for my use case. #3231 would also be great, even if just for human-readability!

**Comment by kofalt** [comment]
I appreciate your linking #4150! For my part, I am not as amicable to the current proposal as an alternative to the above conversation, but I'll happily go participate in the discussion there.

**Comment by danielmewes** [comment]
I'm going to close this in favor of https://github.com/rethinkdb/rethinkdb/issues/4150, which is now more active.
