### ISSUE TITLE
split('') and special characters

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2518]
This query
```
r.expr('été').split('')
```

Returns
```
["�","�","t","�","�"]
```

When I would expect
```
[é, t, é]
```

Putting in polish

**Comment by mlucy** [comment]
This all looks great to me.

**Comment by gchpaco** [comment]
CR 2754.

**Comment by mlucy** [comment]
@danielmewes -- do you think we need to support the old behavior and force people to upgrade their indexes, or should we just assume nobody's depending on the old incorrect `split` behavior in an sindex function?

**Comment by danielmewes** [comment]
We should definitely bump the index ReQL version. (Maybe at some point we should think about scanning sindex functions for whether certain terms are used to decide whether an index is outdated, but let's not do that now.)

We should only provide a backwards-compatible implementation for older indexes if it isn't much work.

**Comment by mlucy** [comment]
It should be pretty easy; the old code doesn't need to be changed, we just need to branch and call it.

**Comment by mlucy** [comment]
@gchpaco -- +1

Do you know off the top of your head what other unicode-unaware operations we have lying around, if any?  (Aside from lexicographic ordering, that is.)

**Comment by gchpaco** [comment]
#2950 comes to mind.  There's the upcase/downcase thing, which is unicode unawares but not unicode-breaking.  `r.js` needs to be inspected, but I'm not especially concerned because JS strings are supposed to be UTF-8 anyway.  I will probably need to give `r.match` a once over to be sure.

We just don't have very many string operations at present.
