### ISSUE TITLE
Write load seems to interfere with aggregations (or at least count)

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2646]
See https://github.com/rethinkdb/rethinkdb/issues/1271#issuecomment-47776998

It looks like write load can bump a full-table `count` from 10s to >5m on Ubuntu, which feels wrong.  Maybe something's wrong with the snapshotting code?

**Comment by danielmewes** [comment]
Just did another quick test on 2.0 with a different aggregation query and it works as expected.

I think the issue might have been fixed as part of some other change.
Closing for now, unless anyone encounters this problem again.

**Comment by lucasjans** [comment]
Should this referenced ticket be closed @danielmewes? I am not sure they are the same issue. I want to do a simple .`count` against a `.getAll` index but it is incredibly slow. I think it is reading all records and not simply going off the b-tree index. #1271

**Comment by danielmewes** [comment]
@lucasjans This ticket was about aggregation queries slowing down in the presence of concurrent write operations. Unless you also have lots of background writes and the `count` is fast without the writes, but extremely slow with the writes, those are different issues.
The issue to follow is https://github.com/rethinkdb/rethinkdb/issues/3949 , which will include making `count` efficient.

We currently don't store table sizes in the b-tree index, and there are some complications to this due to sharding that make the solution non-trivial. So `count()` has no other way but to traverse the whole index (though it will skip loading the individual documents). This can be especially slow if the index doesn't fit into the cache, and things need to be fetched from disk.

**Comment by hungnt-me** [comment]
Hi @danielmewes,

Can you prioritize the index tree into cache higher than document data cache? I think query speed on index should be warranted & index tree still needs to store to disk for backup in case database is restarted or entering slow growth mode

**Comment by danielmewes** [comment]
@hungnt-me I'm not sure how useful that would be to be honest. LRU cache replacement should get fairly close to optimal cache allocation. A part of an index that's rarely used will be kicked out to free up space for more frequently required data, but frequently used indexes (or parts of indexes) will be kept in cache. That being said there might be optimizations to the pure LRU strategy that improve overall performance. It will likely depend on the type of workload which strategy works best. We could maybe allow some user-tuning of cache replacement strategies.

Would you mind opening a new issue as a feature request for that?
(Though I can't give a promise right now when we might get to this, since it's a very complex problem with uncertain pay-off in terms of performance.)
