### ISSUE TITLE
Add a way to permanently remove servers in the ReQL admin API

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#2873]
I suggest `r.server_permanently_remove(name)`. Perhaps `name` could also be a UUID, for the convenience of people writing automated tools.

**Comment by ntquyen** [comment]
I'm trying to a remove a server node from a live cluster of 4 nodes (version 2.2.0) but there was the error. 
```
t's illegal to delete rows from the `rethinkdb.server_config` system table.
```

So this functionality has been removed? Now how can I permanently remove a dead/live server from a cluster?

**Comment by coffeemug** [comment]
@ntquyen -- the functionality has been removed because it's no longer necessary. In earlier versions of RethinkDB when a server joined a cluster it was added to the metadata. If the server ever left the cluster, it would show up as an issue until it was explicitly removed, even if the server wasn't responsible for any data.

In more recent RethinkDB versions servers can freely join and leave clusters -- removing them manually is no longer necessary.

**Comment by danielmewes** [comment]
@ntquyen If you want to remove a live server, you might want to make sure that it doesn't host any table replicas before shutting it down.

An easy way for accomplishing this is as follows:
1. Remove the `"default"` tag from the server you want to remove: `r.db('rethinkdb').table('server_config').get(<server id>).update({tags: []})`
2. Reconfigure all tables through the web UI or the `reconfigure` command to the desired number of replicas and shards
3. Wait for all tables to reach a stable state (until all of them are "green" in the web UI)

Both the web UI and the `reconfigure` command (by default) only assign servers that have the `"default"` tag. Hence, after following the above steps, the server that's to be removed will no longer be assigned for any table and you can shut it down safely.

**Comment by ntquyen** [comment]
@danielmewes and @coffeemug Thanks for your clarification. What I want to do is moving one of the databases in the cluster into a new cluster so that it won't affect each other in term of resources. So I think I can try:
1. Reconfigure the moving db's tables to one of the nodes, 
2. Shutdown that node and start it again without joining the existing cluster. 
3. In the old cluster, delete the moved database
4. In the separated node, delete all missing databases that's not on the node

I'm testing that strategy but it doesn't work as expected. Other things, shutdown that node will cause downtime which I don't really want, but it seems impossible to avoid that.

**Comment by danielmewes** [comment]
@ntquyen Unfortunately in order to accomplish that you'll also need to briefly shut down all other nodes, or they will still "remember" the server you want to remove and will keep connecting to it.

It's also somewhat risky to delete the database on one of the clusters. If in the future you accidentally join the clusters together again, that deletion would propagate and blow away your data.

It might be better to start with a fresh cluster and to use `rethinkdb dump` / `rethinkdb restore` to move the database over. Is that an option for you?

**Comment by ntquyen** [comment]
@danielmewes I see. `dump & restore` is my second option. Too bad that my database is around 100GB and it would take a whole day to move and index it. Thanks for your help!

**Comment by gamename** [comment]
@danielmewes Re your comment above about removing a live server, what would be the programmatic (reql I guess) equivalent of step 3?  That is, how can I verify the tables are all 'green' via the api?  I'm working on an automated restore process, so looking at a web page isn't an option.

**Comment by danielmewes** [comment]
@gamename Something like this:
`r.dbList().filter(r.row.ne("rethinkdb")).forEach(r.db(r.row).wait({waitFor: 'all_replicas_ready'}))`

**Comment by mbroadst** [comment]
@danielmewes we have a case where we would like to remove a rethinkdb node from a cluster, disregarding the data loss (so different than the above case) but without the requirement to shut down all other nodes in the cluster in the process. Is this as easy as clearing out those entries from the `server_config` table? What other mechanisms are in place to maintain the "memory" of the node we are trying to remove, causing the cluster to attempt to rejoin the node to the cluster.

**Comment by danielmewes** [comment]
@mbroadst If you plan not to restart that server, there's no need to shut down the other nodes. They will occasionally try reconnecting, but it won't have any other effects.

However if you're going to set up a new RethinkDB server on the same host and you don't want it to join the same cluster, I believe there's no way around restarting all servers at the moment from the RethinkDB point of view. You could theoretically set up a firewall of course to stop the other servers from reconnecting.

I don't think you can delete from `server_config`. We should consider adding a feature to disable further reconnect tries to a given server.

**Comment by mbroadst** [comment]
@danielmewes yeah we are trying to do the latter, so I think we'll have to come up with a clever way to temporarily block incoming reconnect attempts.

Interestingly enough, in our experimentation we see that there is no need to manually delete from `server_config`: the entries disappear. This leads me to believe that the information used for reconnects  is probably kept in the internal raft structures, rather than picked up from `server_config`. 

Is there sufficient interest for supporting these scenarios with rethink? I'd be willing to investigate what changes would be required on a source level, as this would be particularly useful in our case.

**Comment by danielmewes** [comment]
@mbroadst The reconnect information isn't even kept in Raft, but locally in a temporary data structure on each server. That's why restarting the servers gets rid of it.
Now that you mention it, I'm actually not sure if you have to restart all servers at the same time. I don't think they communicate the information if they aren't actually able to connect to the server, though I could be wrong. It might be enough to restart one server in the remaining cluster at a time to make sure nobody remembers the absent server anymore.

**Comment by mbroadst** [comment]
@danielmewes can you point me towards that internal structure in the code? We're going to try a temporary workaround for disabling cluster port activity on the server, but I'm trying to figure out how long it would take to get the other clustered nodes to "forget" about the one we are trying to unjoin

**Comment by timmaxw** [comment]
@mbroadst The logic for trying to reconnect to disconnected servers lives in the `auto_reconnector_t` type at https://github.com/rethinkdb/rethinkdb/blob/next/src/clustering/administration/servers/auto_reconnect.hpp

**Comment by danielmewes** [comment]
There's also an `initial_joiner_t`, but that's only used for the first connection to a given node passed in through `--join`, and not for subsequent reconnect attempts. So `auto_reconnector_t` is the relevant one here.

**Comment by mbroadst** [comment]
@dalanmiller @timmaxw am I seeing this correctly that we would have to wait a fixed 24 hours in order to get the other nodes to forget about a node you're attempting to remove from the cluster: https://github.com/rethinkdb/rethinkdb/blob/next/src/clustering/administration/servers/auto_reconnect.cc#L57

**Comment by danielmewes** [comment]
@mbroadst Yes that is correct.

**Comment by mbroadst** [comment]
@danielmewes is there any way to perhaps make this configurable? This basically means the answer to our solution is to either: 

1. block traffic on that node to port 29015 for 24 hours
2. iterate through previous cluster members and restart them

Both of these are not exactly desirable..

**Comment by danielmewes** [comment]
We can think about a way for making them configurable. I'd like to understand better how common this use case is though.

Do you mind explaining a bit why you need to take down nodes, and then restart a new node on the same server that should not become part of the previous cluster? Is this a testing scenario or are you running multiple independent clusters in production?

**Comment by mbroadst** [comment]
@danielmewes yeah we're running multiple independent clusters in production. The primary use case at the moment is simply to remove a single node and repurpose it - even if its a shard, we aren't interested in the data being maintained.

**Comment by phil-hildebrand** [comment]
I've run into this issue as well, but even if I restart each node of the old cluster while all nodes in the new cluster are down, the old cluster still sees the removed node as part of it's cluster when the removed node comes online. (IE: cluster 1 = node 01/02/03, cluster 2 = 04

**Comment by phil-hildebrand** [comment]
We were able to get it working by having all nodes of the cluster shutdown and then started one at a time.  Our use case was around re-allocating resources without rebuilding he VM.  Perhaps just the documentation for it would suffice.

**Comment by mbroadst** [comment]
@phil-hildebrand the problem is that any node that has ever been up and a part of a cluster maintains an immutable internal list of nodes they have "known" for a hardcoded 24 hour period. The only solution at the moment, as you have noted, is to shut _everything_ down. I have a PR up [here](https://github.com/rethinkdb/rethinkdb/pull/5596) to allow users to specify a custom timeout for those cached entries.

Theoretically you could set that timeout to something incredibly small and allow for easy removals, but I haven't tested that yet. I did mention a desire for a deeper conversation on that PR about perhaps bundling in the node's name as part of a "handshake" to enable more dynamic node configurations, maybe you have some thoughts to contribute over there?
