### ISSUE TITLE
Update web UI to use new ReQL admin API

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#2878]
Once the new ReQL admin API is mature enough, we should make the web UI use it.

**Comment by danielmewes** [comment]
> We're missing a 4th Monitor since consistency is out 

Here's a suggestion:
  Indexes
  <n> issues detected
  <n> indexes under construction

Or alternatively:
  Indexes
  <n> issues detected
  <N-n>/<N> indexes up to date

The second variant is definitely better, but requires running `indexStatus()` on each table to collect the total number of indexes (N) that exist. This could become expensive, but we have to test it.
For the first variant it's sufficient to filter index post construction jobs from the `jobs` table, which should be faster.

**Comment by mglukhovsky** [comment]
@danielmewes -- indexes is a great choice for the fourth monitor.

**Comment by deontologician** [comment]
I broke out the monstrous todo list into individual issues, some in the 1.16 milestone and some lower priority into the 1.16-polish milestone.

This issue is now moot, and is replaced by #3490, #3491, #3492, #3493, #3994, #3495, #3496, #3497, #3498, #3499, and #3500. In addition, it referred to issues that were already independent: #2884, #3229, #3256, and #3452.
