### ISSUE TITLE
Make backtraces in the ReQL code not be large and slow

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2900]
I think we used to have an issue for this, but I can't find it any more.

`ql2_extensions.proto` should probably go away as part of this; there's no reason to be using protobuf backtraces any more.

**Comment by danielmewes** [comment]
@Tryneus has recently been doing some more investigation in this direction (as part of getting rid of protocol buffer data structures). Re-assigning.

**Comment by Tryneus** [comment]
Backtraces are now generated only on the query's home thread using a much more efficient data structure, and are passed around the cluster as IDs.  Review was 2818.  Merged into `next` in commits 4d0a80e and a54ac14.

**Comment by mlucy** [comment]
@Tryneus -- do we have any numbers on how this affects performance for deeply nested queries?

**Comment by danielmewes** [comment]
Was finally able to run a benchmark with data from a user who had issues with performance because of complex documents before.

Inserting those big documents without these changes with a single client does ~7 inserts per second (soft durability). With these changes it reaches 10-11 inserts per second. A significant improvement.

With 10 concurrent clients the throughput before was ~47 inserts/s. With improved backtraces it is ~65.

**Comment by coffeemug** [comment]
@danielmewes -- how big are the documents? Do you know where the slowdown is coming from?

**Comment by danielmewes** [comment]
@coffeemug About 1 MB. Actually it turns out that the insert speed with a single client is bound by the driver. Even at 10 clients, each Python instance is using 99-100% of their core, while the RethinkDB server uses about 700% overall.
I'm not sure why the speedup for 10 clients isn't exactly 10x compared to a single one, but it might be because of hyperthreading making each logical core slower when the other one on the same physical core is also utilized.
