### ISSUE TITLE
Edge and graph collections

### ISSUE THREAD

**Issue by pengux** [rethinkdb/rethinkdb#3142]
Would it be possible to add edge and graph collections features to Rethinkdb?

**Comment by Eliakos** [comment]
I support too the idea for rethinkdb to be a multi model db by adding graph capabilities and so, go beyond too simple relationships management such exposed here https://rethinkdb.com/docs/data-modeling/.
I were asked on slack to a bring the specific use case i exposed on slack : 

Based on betting exchange gaming, players match their bets (at a given stake and odd) with others players. There a lot of cross relationships in that just simple scenario for which graph capabilities help a lot in a simple and natural way (if possible with sort of ACID transaction).

**Comment by felixis-1** [comment]
Is there any road map for this? Also, If we use a multi index to model graph relationships, what would be the best possible way to calculate a set of strongly connected nodes? We have a use case internally where we currently do this in our application logic but I am wondering if some crafty reql query can do the trick.

**Comment by danielmewes** [comment]
@felixis-1 Unfortunately we don't have a schedule for this currently.

Since ReQL doesn't support recursion or non-functional loops at the moment, it's probably tricky to calculate strongly connected nodes directly in ReQL. It might be possible somehow, but I suspect that it's significantly easier to do it in a piece of application code that runs multiple ReQL queries to request the next set of nodes from the graph.

**Comment by makeshyft-tom-g** [comment]
I would love to see this feature as well.....I can't say much about my use case unfortunately....only to say its a valid use case.

**Comment by lavvy** [comment]
+1

**Comment by thelinuxlich** [comment]
@srh I think this should be closed since it is too broad and doesn't have a proposal.
