### ISSUE TITLE
Simplify setup of encrypted RethinkDB clusters

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3151]
Right now users have to manually set up SSL tunnels / VPN / SSH tunnels to securely run a RethinkDB cluster on an open network (see e.g. the guide at http://rethinkdb.com/docs/security/).

It would be great if we could make that easier, e.g. by providing some scripts to partially automate the setup process of an encrypted RethinkDB cluster.

I imagine the user experience to work somewhat like this:
- Generate a key (-pair)
- Copy the key to all RethinkDB servers
- Provide the key to the RethinkDB instances through some configuration or command line option
- Have some magic that sets up for example SSH tunnels as needed to get the cluster up

I'm not sure how practical this is, given that it would have to work in a lot of different environments, different versions of OpenSSH etc.
I think it's worth investigating though, as it would significantly improve the user experience for many people.

Maybe we can also do something to make encrypted client access easier to setup? (*Edit:* This is now tracked in #3158)

**Comment by kevincox** [comment]
I would like to add my proposal so that it can be chewed at.

I propose that TLS is included in RethinkDB. This allows encrypted connections by default and you don't have to worry about ensuring that all the nodes in the cluster know about they encrypted port, Rethink will know it's encrypted port and can advertise that to the rest of the cluster.

More importantly, integrating TLS allows the use of the authentication methods built into TLS. This allows flexible setup and authentication of servers.

For example:
- One company may wish to maintain a CA cetificate that it uses to sign client certificates for each Rethink node. Then the cluster can be told to allow any server with a certificated signed by that CA to join the cluster.
- Other company might want to keep it simple and just generates a single certificate and put it on each node, then that single certificate can be authorized to join the cluster.
- A third company which wants a little more granular security can generate a certificate for each node and maintains a list of valid certificates that can be used to connect to the cluster.

The nice things about both of these is that the authentication can be managed in RethinkDB tables and will always be kept up to date throughout the entire cluster. 

I believe the third scenario would make a good default configuration. On initial boot each node generates a certificate and attempts to join with that. Then the join request could be accepted via the webui. This would make it very easy to set up a secure cluster.

Sorry for the massive comment but using TLS provides a lot of flexibility and easy to manage security that I feel is important to maintaining a cluster such as Rethink. Furthermore the client authentication could be handled very similarly (but separately) making the whole system very consistent.

**Comment by danielmewes** [comment]
@kevincox Thanks for writing your proposal up here!
It sounds like we can gain a lot of flexibility with respect to key management from using TLS.

I think the pre-shared key might be the easiest option to do in practice for people who don't want to set up their own CA.

I'm not sure how well managing the certificates in a RethinkDB table would work, since tables can become unavailable and the table would need to be maintained. It's probably easier to specify the certificate file in the server configuration on each server.

That being said, your proposal of joining with a self-generated certificate that just needs to be confirmed through the web UI sounds like it would make for a great user experience when setting up a distributed cluster, since it removes the need to share any certificates prior to setup between the servers.
I think if we support TLS connections with a pre-shared certificate first, then adding this type of interactive join process could be the second step. It's a bit more involved since it requires us to dynamically manage and distribute keys throughout the cluster.

**Comment by kevincox** [comment]
> I think the pre-shared key might be the easiest option to do in practice for people who don't want to set up their own CA.

For sure, the CA system might be easier to maintain for larger deployments but that can always be added later as a progressive enhancement.

> I'm not sure how well managing the certificates in a RethinkDB table would work, since tables can become unavailable and the table would need to be maintained. It's probably easier to specify the certificate file in the server configuration on each server.

TBH I don't know all of the details about this. I think it would be very nice to do it this way but it might not be practical. It might be a situation where these can be cached locally so that "fresh enough" information is stored on a node during reboots. I imagine this could be similar to saving the IP's of other nodes so that rejoining works even if the original node used to join has since disappeared. I think I'm getting off topic but it seems like a useful mechanic that would solve the problem and a similar one.

> That being said, your proposal of joining with a self-generated certificate that just needs to be confirmed through the web UI sounds like it would make for a great user experience when setting up a distributed cluster, since it removes the need to share any certificates prior to setup between the servers.

This is similar to how Puppet does it. When a node first checks in to the master it uses a freshly generated certificate. Then the server maintains a list of "new" certificates that can easily be accepted and then those clients can connect.

> I think if we support TLS connections with a pre-shared certificate first, then adding this type of interactive join process could be the second step. It's a bit more involved since it requires us to dynamically manage and distribute keys throughout the cluster.

I agree. It also follows the awesome method in Rethink of adding the base features then adding the icing on top. Also if the credentials aren't stored in RethinkDB itself this could be hard to implement well.

**Comment by jlhawn** [comment]
I am very interested in getting TLS working (or at least forking it and hacking together a build for my use case) and I would like some guidance from the maintainers on how to begin. I've started to familiarize myself with the code in `src/arch/io/network.hpp` and `src/arch/io/network.cc` and since openSSL is already a dependency (though I've seen other issues which talk about removing it) this looks like a good place to start adding openSSL integration for securing the `tcp_conn_t` type.

My main goal is to secure the intra-cluster connections with mutual TLS and secure the client driver to server connections with TLS with the option to require and verify a client cert (since RethinkDB already provides the existing authentication key method for authenticating clients).

>> I think the pre-shared key might be the easiest option to do in practice for people who don't want to set up their own CA.
>
> For sure, the CA system might be easier to maintain for larger deployments but that can always be added later as a progressive enhancement.

If you all want to spend more time designing an alternative easy-to-bootstrap/setup system, that's fine, but it will still, in general, have to reduce down to the common TLS requirements that each side of the connection needs. PKI can seem unwieldy to those not familiar with it, but configuring it mostly boils down to having these 3 things:

1. A private key (`key.pem`).
2. A certificate signed by a trusted key (`cert.pem`).
3. A bundle of those trusted public keys (`ca.pem`).

For your goal of easing setup, 2 and 3 could just be the same self-signed cert and you just need to distribute the private key to every server and/or client. You could even distribute them together in one PEM file. This is atypical though since the common security best-practice is for each party to have a its own private key, but at least the private key will never be transmitted over the network when clients connect, making it strictly better than the existing plaintext symmetric authentication key scheme in my opinion. 

So for now I think it's best to work towards having the PKI/CA system that most everyone is already familiar with and expects when securing systems like this.

For securing the intra-cluster connections, each RethinkDB node needs a `key.pem` and `cert.pem` to authenticate to the peer, and a `ca.pem` to verify the peer's certificate against. We can add extra config file fields for these with the values being the path to these files. Each would have a corresponding command line argument when starting the server. If you want to go with standard names for these files then configuration is even simpler: just specify a directory containing these files.

For securing the client driver connections, each node would again need to know the key to use and the cert to present to the client, however, since most client drivers don't have support for mutual TLS (as far as I know most only have the ability to verify the server cert against a CA), client authentication would only be required if you specify a CA to verify the clients' certificate against. The (unofficial) Golang driver does seem to support mutual TLS authentication and this is what I use personally. In the case that the server does not authenticate client certs it would be highly recommended to use the authentication key method. Specifying the key, cert, and CA to use for client connections could also be added to the config file and command line args as separate arguments. This allows system administrators to use separate CAs for clients and nodes in the cluster, but there's no reason why you couldn't use the same values.

I like using RethinkDB very much but not having TLS builtin is a complete showstopper for my team. Using tunnels/proxies to secure connections is not an option due to more stringent security requirements: we need end-to-end security at the application level. The way forward on this seems pretty clear to me, then again I may not be your target audience for what you're trying to do with the product - for example, I don't use the web UI and never intend to. I just want to build secure applications that use RethinkDB for highly-available storage and realtime change streams.

Have any contributors already started working on this at all? (It has been almost 2 and a half years after all) I've already started looking into what would need to be done and I wouldn't mind contributing it back upstream. I've looked through the code and I can see why people may not be looking forward to modifying it with comments like:

```c++
/* linux_tcp_conn_t provides a disgusting wrapper around a TCP network connection. */
```

and method names like:

```c++
void linux_tcp_conn_descriptor_t::make_overcomplicated(scoped_ptr_t<linux_tcp_conn_t> *tcp_conn)
```

I haven't done any C++ in a few years but I'm pretty confident that I can get something acceptable with guidance.

Thanks.

**Comment by danielmewes** [comment]
Hi @jlhawn, nobody has started working on this as far as I know. Help on this would be awesome!
Your proposal sounds great to me. We can look into a bootstrapping mechanism later.

Could you drop by on our Slack http://slack.rethinkdb.com and ping me there (my user is danielmewes)? I can connect you to our engineers to give you some pointers through the code and to help you with the implementation.

**Comment by kevincox** [comment]
That proposal looks awesome, I hope you get the help you need!

**Comment by jlhawn** [comment]
Good news everyone! It seems like I've made some progress:

```
$ openssl s_client -connect localhost:28015 -CAfile cert.pem 
CONNECTED(00000003)
     ... [omitted for brevity] ...
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-521, 521 bits
---
SSL handshake has read 1788 bytes and written 521 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: zlib compression
Expansion: zlib compression
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 9FE618C7C2EF9ED5F50F78AD61E309F2485C79D903D5A7F17E37217F21AE1EB8
    Session-ID-ctx: 
    Master-Key: 12F35B3A99E8795A6CCB1E84ACCA982EC3CF1698F3D46033EC42DD415C764E9AAF662F2888F86875D2C536BF5D559AA7
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 26 c4 42 48 80 f4 b0 8b-c5 a7 09 24 b9 3b 39 ea   &.BH.......$.;9.
    0010 - 5c 59 c1 22 c0 b8 d4 93-3a d9 94 7a 5a 4d 08 20   \Y."....:..zZM. 
    0020 - 05 b2 6b f1 c3 9f 1b b1-ec 21 06 da 8e bf c2 35   ..k......!.....5
    0030 - fa 1f 5d 39 d2 6b 23 6d-13 5d d1 44 d3 93 5a 77   ..]9.k#m.].D..Zw
    0040 - b5 2b bc ac 8d ef 1a 38-9b 26 9d 8e a6 0d 44 72   .+.....8.&....Dr
    0050 - 2a c7 ec 64 f5 b2 a5 76-6f 43 02 22 57 9f 1f 5d   *..d...voC."W..]
    0060 - 91 25 3d cf 5c 54 85 7c-b7 45 7f 8a 97 73 ee 4d   .%=.\T.|.E...s.M
    0070 - f1 8e 7e cd ee 11 1e 70-37 32 33 c0 b2 35 f7 61   ..~....p723..5.a
    0080 - 57 c0 f5 df de fd 24 ce-fe cd c9 c6 95 80 c5 24   W.....$........$
    0090 - 8b 55 2f fb 3d 8b 3f 87-64 51 8a 96 bc bc 39 0c   .U/.=.?.dQ....9.

    Compression: 1 (zlib compression)
    Start Time: 1454749556
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
hello
ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
closed
```

So far I've only got the query server accepting TLS connections. In the above snippet you can see that after the TLS handshake I wrote `hello` to the server to which it responded with: `ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?`. I also ran simple app that I have against the server to confirm that queries still work and they do!

Hooking up the intra-cluster connections shouldn't be too difficult now that most of the connection and read/write handling stuff is out of the way.

**Comment by danielmewes** [comment]
:clap: That's great news @jlhawn !

**Comment by jlhawn** [comment]
I've spent the past day or so figuring out how to add command line options for TLS (haven't looked into config file stuff yet) and I've come up with the following (this is what it prints out when you run `rethinkdb --help`):

```
TLS options:
  --web-tls                                   secure the web administration console
                                              with TLS
  --web-tls-key                               private key to use for web
                                              administration console TLS
  --web-tls-cert                              certificate to use for web
                                              administration console TLS
  --driver-tls                                secure client driver connections with
                                              TLS
  --driver-tls-key                            private key to use for client driver
                                              connection TLS
  --driver-tls-cert                           certificate to use for client driver
                                              connection TLS
  --driver-tls-ca                             CA certificate bundle used to verify
                                              client certificates; TLS client
                                              authentication disabled if omitted
  --cluster-tls                               secure intra-cluster connections with
                                              TLS
  --cluster-tls-key                           private key to use for intra-cluster
                                              connection TLS
  --cluster-tls-cert                          certificate to use for intra-cluster
                                              connection TLS
  --cluster-tls-ca                            CA certificate bundle used to verify
                                              cluster peer certificates
```

It's divided into 3 sections - one each for the Admin Web Interface, client driver connections, and intra-cluster connections. Each has a flag `--{web|driver|cluster}-tls` which if specified enables TLS for those connections. If any of those flags are given, then the rest of the flags in that section must also be specified. Each section has an option for specifying the key and certificate files. The driver section's `--driver-tls-ca` is optional (if you want mutual TLS for client drivers) but the `--cluster-tls-ca` is required as I figured you'd want mutual TLS for intra-cluster connections.

**Comment by danielmewes** [comment]
@jlhawn this is amazing!

About the command line arguments:
Those look good to me.

We currently have options `--driver-port`, `--cluster-port` and `--http-port`, rather than `--web-port`. 
However I actually prefer the `web` prefix over the `http` prefix, since `http` makes it sound as if we had an HTTP-based query API.

I actually think we should deprecate the `--http-port` option and rename it to `--web-port` as well. That will be a separate step though outside the TLS pull request.

@Tryneus what do you think about these command line option names?

**Comment by danielmewes** [comment]
Just a thought: Could there be a use case for binding the TLS listeners to separate ports in addition to the unencrypted ones? Probably this isn't too useful as long as the `--bind` parameters apply to all of them right?

One thing to consider is what happens if a non-TLS-enabled client, browser or cluster node connects to a TLS listener. We should at least test this. One thing we could probably do is using a different default port for the TLS listeners, so that it's harder to get mixups by accident.

**Comment by jlhawn** [comment]
I quickly tried joining a new node (without `--cluster-tls`) to another node (which was using `--cluster-tls`) and the new node exited immediately with a segmentation fault :disappointed:

```
$ ~/workspace/rethinkdb/build/release_clang/rethinkdb --bind 127.0.0.1 -n rdb_02 --cluster-port 10201 --driver-port 10202 --join localhost:10101 --no-http-admin --canonical-address localhost
WARNING: ignoring --server-name because this server already has a name.
OpenSSL 1.0.2f  28 Jan 2016
Running rethinkdb 2.2.4-dirty (CLANG 7.0.2 (clang-700.1.81))...
Running on Darwin 14.5.0 x86_64
Loading data from directory /Users/jlhawn/rdb-02/rethinkdb_data
Listening for intracluster connections on port 10201
Version: rethinkdb 2.2.4-dirty (CLANG 7.0.2 (clang-700.1.81))
error: Error in src/arch/runtime/thread_pool.cc at line 359:
error: Segmentation fault from reading the address 0x0.
error: Backtrace:
error: Tue Feb  9 17:16:33 2016
error: Exiting.
Trace/BPT trap: 5
```

However, the existing node stayed up and just reported in the output that the TLS handshake failed.

**Comment by danielmewes** [comment]
@jlhawn Interesting. The segmentation fault is not good. We'll look into that.

**Comment by jlhawn** [comment]
@danielmewes Looks like that segmentation fault is actually an error from my added code. I forgot that in C/C++ struct fields are not automatically initialized with zero. I have been spoiled by this feature of Golang. I have some logic that is basically this:

```C++
if (NULL == tls_ctx) {
    make_tcp_conn();
} else {
    make_secure_tcp_conn();
}
```

My assumption was that if TLS is not configured then `tls_ctx` will be `NULL`. However, by default the value of `tls_ctx` is just arbitrary garbage data (not `NULL`) it would attempt to make a TLS connection with invalid context.

**Comment by danielmewes** [comment]
@jlhawn Ah I see. Sorry I haven't gotten around to taking a deeper look at your code yet. I'll hopefully be able to do that soon.

(I originally posted this in https://github.com/rethinkdb/rethinkdb/pull/5381#issuecomment-186426069 because I got confused about the different threads)

**Comment by jlhawn** [comment]
Since this issue is titled **Simplify setup of encrypted RethinkDB clusters**, it's probably a good idea to cross-post [this gist that I put together](https://gist.github.com/jlhawn/43f84f86579012470dc9) which is now probably *the simplest* guide to setting up an encrypted RethinkDB cluster. It uses an experimental build of my pull request. @kevincox, you should try it out!
