### ISSUE TITLE
Rename `concatMap` to something less scary

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#334]
While `concatMap` is a descriptive name, it has a strange academic feel to it that confuses a lot people. We should find a nicer name (no doubt there is something clearer in the underscore.js/mongo world). `emit`, `extract` or something of the sort (I don't have a really good one, unfortunately)

**Comment by mlucy** [comment]
I don't object strongly to `union_map`, but it's worth noting that while currently `union` concatenates streams, we've never explicitly *promised* that, and it would be more efficient in a lot of cases to intersperse elements from the different streams, so I could imagine a future in which `union` means "give me the elements from all of these streams in whatever way is most efficient" rather than "concatenate these streams".

If we decide to commit to the current concatenation semantics for `union`, then `union_map` seems fine to me, and might be more obvious to people.

**Comment by danielmewes** [comment]
@mlucy that's a good point. I think especially with changefeeds we don't want to guarantee any particular ordering for `union`.

I personally am tempted to close this and stick with `concatMap`, since none of the discussed alternatives seem to be without caveats.
Does anyone still believe strongly that we should rename `concatMap`?

**Comment by coffeemug** [comment]
:+1: for closing

**Comment by danielmewes** [comment]
I interpret the lack of protest as a no.
Of course we can always re-open it later.

**Comment by briant5q** [comment]
FWIW: I spent an hour today looking for the functionality that concatMap provides. However, coming from the MongoDB world, I was more familiar with the term 'unwind'. I wouldn't advocate changing the name at this point, but including the term "unwind" or "flatten" in the docs would help recovering MongoDB devs identify/google the term. 

In my case, I'm looking to map reduce on arrays of objects, which is often how unwind is used with Mongo. Might be helpful to include that use case some where in the docs, if it isn't already there.

**Comment by danielmewes** [comment]
Thanks for the feedback @briant5q 
@chipotle Do you think we could sneak those terms into the concat_map documentation? We could say something like
"This operation is also known as "flattening" or "unwinding" the sequence."
