### ISSUE TITLE
external modules should be passed CXXFLAGS, LDFLAGS, etc...

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3473]
When external modules get build (e.g.: v8, libcurl, etc...) they are not getting the CXXFLAGS, LDFLAGS, or CFLAGS that the rest of the build is getting. That seems wrong to me for items that are going to be linked in to our binary. For example on MacOS we are setting `-stdlib=libc++`, and it would probably be bad if anything were to be compiled with a different C++ standard library.

**Comment by AtnNn** [comment]
This was by design.

* Variables passed to the `configure` script were used for building RethinkDB only (`./configure CXXFLAGS=-DARWIN; make`)
* Variables in the environment were used for building both RethinkDB and the libraries in `external/` (`export CXXFLAGS=-DARWIN; ./configure; make`)

This allowed passing build options specific to RethinkDB, which is a very common use case of the build system.

The `configure` script adds `-stdlib=libc++` on OS X to work around the outdated `libstdc++` that is the default on older systems. It looks like this hack is duplicated in `protobuf.sh` and `re2.sh`.

**Comment by larkost** [comment]
What flags would we want used in compiling RethinkDB that we would not want the libraries we are compiling not to use as well? And while it is nice that we are coving this base in `protobuf.sh` and `re2.sh` it sounds like we are only making up for the deficiency in a couple of cases, rather than doing the easier thing and getting it right in all cases.

If we do need to have separate `CXXFLAGS` for the `rethinkdb` binary only, then it seems to me that we need to make that the special case, not the default one.

**Comment by AtnNn** [comment]
Sorry for the late reply. I'm adding a comment now because this issue came up in #2230.

> What flags would we want used in compiling RethinkDB that we would not want the libraries we are compiling not to use as well?

Some examples are optimisation and debugging flags such as `-O`, `-fsanitize`, `-p` and `-flto`.

I consider it a bug in older versions of clang that it linked will a crippled standard library by default, requiring us to pass `-stdlib=libc++`. If the need arose, the small block of code that sets this flag in the packages that need it could be replaced by a set of `CXXFLAGS` and `LDFLAGS` set in the `configure` script that are shared with the fetched dependencies and are separate from those specifically used to build RethinkDB.

> we need to make that the special case, not the default one

I think flags passed on the command line, such as `./configure CXXFLAGS=-p` should not be shared with the fetched dependencies by default.

Perhaps my disagreement with the ideas in this issue stems from seeing the fetched dependencies differently. To me they are just a hack, a tacked on mess whose purpose is to make it easier to build RethinkDB on systems in which the dependencies are unavailable or hard to install. They are designed to be built separately and independently from RethinkDB, and this is reflected in the design. For example, after re-running `./configure`, the dependencies are not rebuilt. Making changes such as sharing some `CXXFLAGS` would make me want to reconsider that decision and others.

I realise however that these scripts that were originally designed to build optional, fetched dependencies are now used to build mandatory, checked-in dependencies such as v8 and re2. I'm ashamed to say that the [v8 build script](https://github.com/rethinkdb/rethinkdb/blob/next/mk/support/pkg/v8.sh#L21) still looks like a big hack. I'm amazed it has worked so well so far.

**Comment by larkost** [comment]
From my read of things as it stands now, it seem that we already have the rethinkdb-specific flags in `RT_CXXFLAGS`, and so the only debate would be whether additional flags given through `./configure CXXFLAGS=` should be included into `CXXFLAGS` or `RT_CXXFLAGS`.

Since this has come up in #2230 (build on 10.9) again, @AtnNn could you comment please? I see both pitfalls and advantages to both approaches.

**Comment by danielmewes** [comment]
We decided to pass `LDFLAGS` and `CXXFLAGS` through to the packages, to avoid having to duplicate code that switches `-stdlib` and potentially other generic options like that in a bunch of places (the logic that does this is currently inconsistent across different places, which has caused compilation issues on some configurations).

We verified that all optimization-related flags and other compile flags that are RethinkDB-specific are already in the separate variables `RT_CXXFLAGS` and `RT_LDFLAGS`. So we should be good on that end.

I also think that having flags passed through `make CXXFLAGS=...` apply to the third-party packages is ok. This is what I personally expected, though I'm sure there are different ways to think about this. Ultimately I think it doesn't matter too much, since you can still specify `RT_CXXFLAGS` instead once you know about it.

**Comment by larkost** [comment]
This was done in branch `larkost/3473-CXXFLAGS-to-external`, but was merged into work for 5926 in branch `vexocide/5926`, which was reviewed in CR 3708 and merged into `next` with 4986dbf.
