### ISSUE TITLE
RethinkDB export format

### ISSUE THREAD

**Issue by internalfx** [rethinkdb/rethinkdb#3503]
I noticed in the commit log that @Tryneus just committed support for secondary indexes. I was planning on adding "export to file" capability to [Thinker](https://github.com/internalfx/thinker) as well. Now that the official export tool supports secondary indexes, I think it should be possible for the file formats to be compatible.

Is there any kind of "spec" on the export files. At the very least they could save me the trouble of inventing a format.

**Comment by Tryneus** [comment]
There is no 'official' export format, but I can describe what the `rethinkdb export` tool produces.  It may be useful to add this to our docs.  Note that all code examples are given in Python.

This should be fairly clear, but if you see any mistakes or have questions or comments, let me know.

#### Overview

The `rethinkdb export` tool by default will export all tables in a cluster, each to a separate `.json` file, accompanied by a similarly-named `.info` file.  Both files are in a plain UTF-8 JSON format, with no additions or extensions.  The `.json` file contains each row from the table, and the `.info` file contains table metadata.

Using the option `--format csv` (along with `--fields`), a `.csv` (comma-separated value) file will be produced instead.  `--format csv` can only be used to export a single table at a time.

#### Directory Structure

By default, `rethinkdb export` will choose a directory name in the current working directory based on the system time, e.g. `./rethinkdb_export_2015-01-06T09:01:11`.  The export directory will have `_part` appended to the name until the export is completed, upon which it will be renamed.

Inside the export directory, there will be one directory for each exported database.  Each directory will have two files for each exported table, depending on the format (detailed below).  Here is an example directory structure for exporting three tables: `foo.bar`, `foo.baz`, and `test.data`:

```
rethinkdb_export_2015-01-06T09:01:11/
    foo/
        bar.info
        bar.json
        baz.info
        baz.json
    test/
        data.info
        data.json
```

#### `.info` File

The `.info` file contains the table metadata available from the `info` ReQL term.  Before 1.16, the contents of this file were equivalent to a JSON dump of `r.table(...).info()`:
```
{
    "db": {"name": "foo", "type": "DB"},
    "indexes": ["value"],
    "name": "bar",
    "primary_key": "id",
    "type": "TABLE"
}
``` 

Following 1.16, the indexes field was changed to use the output of the `index_status` ReQL term, which includes a binary representation of the function used to build the secondary index.  The output here is equivalent to `r.table(...).info().merge({'indexes': r.db(r.row['db']['name']).table(r.row['name']).index_status()}).run(..., binary_format='raw')`:
```json
{
    "db": {"name": "foo", "type": "DB"},
    "doc_count_estimates": [2],
    "indexes": [
        {
            "function": { "$reql_type$": "BINARY", "data": "JHJlcWxfaW5kZXhfZnVuY3Rpb24kBAICAgAAAAAAAAHt/////////3IAAAAIHxo5CAoaIggBEgsI\r\nAxkAAAAAAAAzwILxBA8KDQgBEP7//////////wGC8QQPCg0IARD+//////////8BGiAIARIJCAQi\r\nBXZhbHVlgvEEDwoNCAEQ/v//////////AYLxBA8KDQgBEP7//////////wEPAAAACg0IARD+////\r\n//////8BAAA="},
            "geo": false,
            "index": "value",
            "multi": false,
            "outdated": false,
            "ready": true
        }
    ],
    "name": "bar",
    "primary_key": "id",
    "type": "TABLE"
}
```

Note that we specify `binary_format='raw'`, see the `.json` format description for why.

#### `.json` File
When exporting to the JSON format, we produce an array of dicts, each dict corresponding to a row.

The query used to dump a table is `r.db(...).table(...).order_by(index=...).run(..., time_format='raw', binary_format='raw')`

This file is ordered by the primary key of the table (particularly to allow us to resume in the case of an interrupted connection).  In addition, we specify `time_format='raw'` and `binary_format='raw'`.  This is for proper JSON serialization of types that are not supported by the JSON specification.  The 'raw' format is equivalent to what we send on the wire between the server and client, and allows us to later send the data back to the server with no modifications to recreate the original data structure.  There should be API docs detailing these formats, but to summarize: binary objects use base64, and time objects use a float for seconds since the UNIX epoch.

Aside from these caveats, the JSON file format is the most straightforward when importing/exporting.  The file produced is encoded using UTF-8.  With an import we can simply parse the JSON into native objects and write the rows directly to the table.

#### `.csv` File
CSV export/import is not meant as a backup path so much as migrating to or from other tools, due to the limitations of the format.  Because of these limitations, we have the following behavior:

* When exporting, any fields which are not a string or number will be dumped as inline-JSON (e.g. objects, arrays, times, nulls, binary).
* When importing, all fields will be read as a string

This means we always produce and always accept valid CSV, and we do not do anything 'unexpected' with the data.  This also means users may need to add a post-processing step when importing CSV data.

Example CSV file:
```
id,value
foo,524
```

Would result in one row:
```json
{
    "id": "foo",
    "value": "524"
}
```

This could be post-processed to turn all `value` fields into numbers using `r.table(...).update({"value": r.row["value"].coerce_to("NUMBER")})`, resulting in:
```json
{
    "id": "foo",
    "value": 524
}
```

Similarly, more-complex fields that were saved as inline-JSON could be converted using `r.table(...).update({"value": r.json(r.row["value"])})`.

As for the file format itself, the user must explicitly specify which fields will be exported using the `--fields` option.  Any rows that do not have the field will result in an empty field in the file.  The file produced is encoded using UTF-8.  CSV is not a well-standardized format, but we use the default `csv.writer` serializer in Python (https://docs.python.org/2/library/csv.html).

Example row to be exported:
```json
{
    "id": "foo",
    "value": 524,
    "array": [ 1, 2, 3 ],
    "dummy": "string",
    "none": null
}
```

When exported using `--fields value,none,missing,array`, the resulting CSV file should be:
```
value,none,missing,array
524,null,,"[1, 2, 3]"
```

**Comment by danielmewes** [comment]
This is a great writeup @Tryneus . We should totally make that part of our official documentation. I'll open an issue on the docs tracker.

**Comment by internalfx** [comment]
wow, thanks @Tryneus. This should help immensely.

**Comment by fvm** [comment]
Thanks @Tryneus . Is this information still valid? I couldn't find it in the docs, but perhaps it's not been incorporated yet. I'd like to rely on the above to write a script for migrating data (replication isn't an option)

**Comment by internalfx** [comment]
@fvm if you just need to migrate data between 2 databases, try [thinker](https://github.com/internalfx/thinker)

**Comment by fvm** [comment]
Thanks for the tip, it's actually between MySQL and RethinkDB. I will keep it in mind for future reference though.

(Yes, from MySQL to RethinkDB)
