### ISSUE TITLE
Make 'or' / 'and' return a boolean?

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3562]
As far as I understand, `r.or(arg1, arg2, ..., argn)` currently returns the first argument that's not `false` or `null`, and `false` otherwise.
`r.and(arg1, arg2, ..., argn)` returns the last argument if none of them are `false` or `null`, or otherwise the first argument that's either `false` or `null`.
(@mlucy: Is this correct?)

I think this behavior is more confusing than necessary, and it's not intuitive at least to me what exactly the return value is.
Especially confusing:
* `r.or(null, null) -> false` (note `false` isn't any of the arguments to `or`)
* but `r.and(null, null) -> null`

Even in less confusing cases, I have to think quite a bit about what the term is going to return for different inputs.

I propose we make `or` and `and` always return a boolean, either `true` or `false`.

This change would avoid some ambiguity in what we're discussing in https://github.com/rethinkdb/rethinkdb/issues/1721#issuecomment-69824399 .

**Comment by danielmewes** [comment]
To copy @mlucy from the other thread:
> I would be strongly opposed to that. The reason we don't do that is that it's common to write code like val_or_null || backup_val_or_null || default_val in Ruby (and I would guess a lot of other dynamic languages). The idea is that if val_or_null returns a val, you return that, and otherwise you return default_val. Supporting that use case is about a third of why we adopted the idea of truthy values in the first place.

**Comment by mlucy** [comment]
X-post from #1721:

---

> I wonder if we should take this as a chance to simplify any/all behavior in this respect, and make them always return either true or false. I'll open a separate thread to discuss that.

I would be strongly opposed to that.  The reason we don't do that is that it's common to write code like `val_or_null || backup_val_or_null || default_val` in Ruby (and I would guess a lot of other dynamic languages).  The idea is that if `val_or_null` returns a val, you return that, and otherwise you return `default_val`.  Supporting that use case is about a third of why we adopted the idea of truthy values in the first place.

I've been thinking about this a little more, and I think we should adopt the following rules (which mimic Ruby's behavior pretty closely):
* `or` returns the first truthy value it encounters or, if it encounters no truthy values, the last value it encounters.  If the last value is a non-existence error, it rethrows it (`false` and `null` are returned).
* `and` returns the first falsey value it encounters or, if it encounters no falsey values, the last value it encounters.  If the first falsey value is a non-existence error, it rethrows it (`false` and `null` are returned).

---

> r.or(null, null) -> false (note false isn't any of the arguments to or)

That seems like a bug to me; I would expect that to return `null`, and that's what Ruby does.

**Comment by mlucy** [comment]
(Worth noting: CL has the same convention, you frequently write `(or X Y Z)` to return the first true value.)

**Comment by danielmewes** [comment]
Fair enough.
The expectation of what `or` and `and` do in this respect seems to depend a lot on the user's background. I personally would always think of them as strictly boolean operations first.

I can certainly see some use cases for `or` returning the first truthy value in ReQL...

**Comment by mlucy** [comment]
I think it's probably a static vs. dynamic thing: cursory testing suggests both Python and JS do the same thing for `or` (return the first truthy value).

**Comment by larkost** [comment]
The `or` behavior is much more familiar to me under the name `coalesce`. I would vote for changing this to `coalesce`, and returning `null` in the case that nothing is provided. The `and` behavior is new, and very counter-intuitve to me.

Given the change to `coalesce` above you could simulate `and` with:
```python
r.coalesce(r.coalesce(None, None), False).run()
```

**Comment by deontologician** [comment]
Over in #1721, there is a lot of discussion about the behavior of `r.and` and `r.or`, and some of it hinges on what to return in the face of `undefined`.

I know or returning values themselves is sometimes used as an idiom to do defaulting, but we already have `.default`, so I don't know why we'd need that.

```
val_or_null || backup_val_or_null || default_val
```
is expressed in ReQL as:
```
val_or_null.defaul(backup_val_or_null).default(default_val)
```

It's more explicit than these idiomatic uses of `or`. In addition, I haven't ever seen anyone take advantage of `and` returning non-boolean values. It seems it's only done to be consistent with `or`. 

I guess my point is that we already have an explicit way to do defaults. Are there any other examples for why `r.or` and `r.and` returning non-booleans is useful?

**Comment by danielmewes** [comment]
I don't think we're going to change this, especially now that we agreed on JS semantics for these terms in #1721.
