### ISSUE TITLE
Add `SUCCESS_ORDERED_FEED` return type.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3715]
See https://github.com/rethinkdb/rethinkdb/issues/3714 .

**Comment by danielmewes** [comment]
Would we need more types like this for other types of upcoming changefeeds? What about `group().changes()` changefeeds for example?

I'm a bit concerned that we will end up with lots of different return types for different sorts of changefeeds, in which case we should probably think about a different way of passing the "changefeed type" to the client.

@neumino any opinions or insights on this?

**Comment by mlucy** [comment]
We could update the protobuf to have both a `ResponseType` (what it has now) **and** a `ResponseNotes` field.  We would then remove `SUCCESS_FEED` and `SUCCESS_ATOM_FEED` (they would both go back to being `SUCCESS_PARTIAL`).  `ResponseNotes` would be an array of enum values where we could put any information we want that isn't essential to writing a functioning driver but might allow people to implement extra functionality.

**Comment by danielmewes** [comment]
Yeah that sounds better to me.
It would make it easier to keep old drivers working with new changefeed features.

**Comment by gchpaco** [comment]
Folding all the various types of feeds that are only incrementally different from one another into one idea of `ResponseNotes` sounds good to me.  Speaking as the guy who did the `SUCCESS_ATOM_FEED` work I found it very frustrating due to it duplicating a lot of code for, apparently, no meaningful benefit at all :)

**Comment by neumino** [comment]
@danielmewes -- Folding all the types into one is probably a good idea, no objection here as long as I can know what type of feed I get.

**Comment by danielmewes** [comment]
Should we call it `ResponseNotes` or `ResponseHints` maybe (or `ResponseAnnotations`)?
I think we should also make it an array, so that we can attach multiple hints to a response (e.g. an additional one for `includes_all`, see https://github.com/rethinkdb/rethinkdb/issues/3719#issuecomment-72767566).

**Comment by mlucy** [comment]
I like `notes` better than `hints`, personally.  I usually associate hints with performance tuning.

**Comment by mlucy** [comment]
Planning to mark this as settled on Monday with `ResponseNotes` as the name, unless anyone really doesn't like it.

**Comment by danielmewes** [comment]
I think we should try to get this into 2.0. It will simplify drivers.

**Comment by danielmewes** [comment]
Assigning to @mlucy . We should try to get the `ResponseNotes` interface into 2.0.

**Comment by mlucy** [comment]
This is in next, CR 2692 by @Tryneus .
