### ISSUE TITLE
virtual tables should give an error when used with `changes(squash=False)`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3725]
For virtual tables `squash=false` is not a meaningful attribute for `changes` and so should probably generate an error. For example this should generate an error:

```python
r.db('rethinkdb').table('table_status').changes(squash=False).run()
# should generate an error
```

Instead the `squash=False` is being silently ignored.

A sub-test showing this will be in `./test-runner polyglot/changefeeds/point` in the new future.

**Comment by coffeemug** [comment]
Presumably the same is true for `vt.changes(squash=1)` (where the value of `squash` is a number, not a bool).

FWIW, I remember discussing this and we decided to to ignore values of `squash` that don't apply instead of erroring, but now I'm not sure if that was a good decision. We should probably discuss what we want to happen a bit; I could see both points of view and am not sure what's best.

**Comment by danielmewes** [comment]
I think failing is better.

Setting `squash` to a number is something that we could actually support for pseudo tables at some point, but as long as it's not I think we should fail for that as well.

**Comment by mlucy** [comment]
I think we should fail for `squash: false` because users write that to ask for a guarantee.

I think we shouldn't fail for `squash: number` because in my mind that's a hint that the server is free to ignore (i.e. we don't offer any hard guarantees about what will happen if you write that, unlike `squash: false` where we offer a hard guarantee that you will not miss any changes).

**Comment by danielmewes** [comment]
I'd be fine with `squash: number` being silently ignored, though failing still seems like the better behavior to me.
What exactly is the argument for not failing?

**Comment by coffeemug** [comment]
I'm ok with whatever you guys decide.

**Comment by mlucy** [comment]
The argument for not failing would be that if you have global run options that you use for all your queries, it's a pain in the ass to special case some of them.

**Comment by danielmewes** [comment]
I'm not sure how many people are actually doing that, but as mentioned before I'm ok with it either way.

So let's just make `squash: False` fail, and ignore `squash: Number` like we're already doing now.

**Comment by VeXocide** [comment]
Since `squash` now defaults to `False` implementing this would lead to every query using `.changes()` on an artificial table producing an error, thus together with @danielmewes we decided we'll silently ignore this for now.
