### ISSUE TITLE
scan command for operating on ordered sequences

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3736]
I have had in mind a command that could be used to implement many operations on sequences that are not currently possible. It would behave a little like `concat_map`, but with state. In pseudo-code, it would be something like this:

```
sequence.scan(state, f, end) ≡
  case f(state, head(sequence)) of
    [state′, out] → out.union(tail(sequence).scan(state′, f, end))
    null → ∅
∅.scan(state, f, end) ≡
  end(state)
```

The function `f` would be given the current state and the next input row, and it would produce the next state, and possibly generate output rows. `f` could also return `null` to end the sequence. The optional third argument `end` would be called when the input sequence is exhausted.

For example, it could be used to return every third row:

```
sequence.scan(0, lambda n, row: [n+1, r.branch(n.mod(3) == 0, [row], [])])
```

To group rows without loading the whole table in memory:

```
table.order_by(index='time').scan({'val': null, 'group':[]}, lambda state, row:
  r.branch(state['val'] == row['time'].truncate('seconds'),
    [{'val': state['val'], 'group': state['group'].add([row])}, []],
    [{'val': row['time'].truncate('seconds'), 'group': [row]}), [state['group']]],
  lambda state: [state['group']])
```

To count added and deleted rows:

```
changefeed.scan(0, lambda n, change:
  r.branch(change['new_val'],1,0).add(
    r.branch(change['old_val'],-1,0)).do(
      lambda new_n: [new_n, [new_n]])))
```

Or to compute the Fibonacci sequence (compare to http://rethinkdb.com/blog/fib/):

```
r.range().scan(1, lambda a, b: [a + b, [a]])
```

With #3579 it would also open a lot of possibilities for operating on changefeeds.

I also wonder if better abstractions exists for operating on sequences in order and with state.

**Comment by danielmewes** [comment]
This is kind of related to something that @wojons suggested just a few days ago https://github.com/rethinkdb/rethinkdb/issues/3724, though `scan` is a lot more general.

**Comment by coffeemug** [comment]
Note that this also might be related to #2664.

**Comment by neumino** [comment]
It would help for things like this too:
http://stackoverflow.com/questions/28371303/funnels-and-rethinkdb

**Comment by mlucy** [comment]
Here's an alternate proposal:

* We implement `fold`.  We've needed this for a while.
  - `fold` would be like `reduce`, except it would always proceed left-to-right, and you're able to specify a `base`.  (So the function signature is `.fold(lambda acc, el: ...` or `.fold(lambda acc, el: ..., base=...)`.
  - If no base is specified, `fold` will treat the first element of the sequence as the base.
  - If the stream is empty, the base is returned.  Otherwise the result of the last function invocation is returned.
  - If the stream is empty and no base is specified, it's a non-existence error.
* We add an optarg `emit` to `fold`.  `emit` will be set to another function that also receives the accumulated value and the current value, but instead of returning a new accumulated value returns an array of elements to be added to the output.
  - If `emit` is set, then we accumulate the emitted values and return that rather than returning the result of the last call to the accumulator function.

I sort of like this because it kills two birds with one stone, and it lets people get scan functionality by building on a term that's easier to understand.

Another advantage is that the emitter function and base are labeled as such, rather than relying on returning an array where the positions have semantic meaning.

---

Here are two optional extensions to this proposal:
* Allow people to receive the result of the accumulator function in the `emit` function.  This lets you avoid a lot of code duplication sometimes (you would otherwise have to include a copy of the accumulator function in the emit function).
  - Option 1: if the `emit` function takes 3 arguments instead of 2, we pass the result of the accumulator function to it.  So `emit=function(acc, row, new_acc) { ... }`.  (I think I prefer this option.)
  - Option 2: You can specify `emit_after` to receive the new value.  So `emit=function(new_acc, row) { ... }`.
* Allow people to also specify a function that runs once the entire stream is processed and receives the last return value of the accumulator function.  Maybe something like `final_emit=function(final_acc) { ...}`.  I'm not sure we need this, but it might be useful.

---

Here are the examples Etienne gave redone in this syntax:

Return every 3rd row:
```
seq.fold(lambda acc, row: acc+1,
             base=0,
             emit=lambda acc, row: r.branch(acc%3 == 0, [row], []))
```

Count added and deleted rows (Etienne's implementation looks incorrect to because it never uses the variable `n`):
```
changes.fold(lambda acc, change: acc + r.branch(change['new_val'], 1, 0) + r.branch(change['old_val'], -1, 0),
                     base=0,
                     emit=lambda acc, change, new_acc: [new_acc])
```

(Notably, the first two lines of this are the **same thing** you'd write if you just wanted to count the number of changes rather than keeping a running tally!  I think that's cool.)

Compute fibonacci sequence (Etienne's implementation of this looks incorrect to me too, unless I'm misunderstanding his proposal, because he seems to be adding the accumulator variable to the elements of the range rather than summing the last two accumulated values):
```
r.range().fold(lambda acc, _: [acc[1], acc[0] + acc[1]],
                     base=[0, 1],
                     emit=lambda acc, _: [acc[1]])
```

**Comment by mlucy** [comment]
Or, here's another example: computing a running average of 10 elements:
```
seq.fold(lambda acc, row: ([row] + acc).limit(10),
         base=[],
         emit=lambda acc, row, new_acc: r.branch(new_acc.size() == 10, [new_acc.avg()], []))
```

**Comment by AtnNn** [comment]
@mlucy I like your proposal a lot better than mine! I believe you are correct that those two hypothetical examples were wrong.

I think `final_emit` would be very useful. For example it would allow doing chunking.

**Comment by danielmewes** [comment]
I *really* like that proposal.

The one thing I find minimally confusing is when the `emit` function is run compared to the accumulator function. In the proposal, `emit` is semantically run *before* the accumulator is updated right? That is the `row` that's passed into `emit` is not yet reflected in `acc`.

The extension with `emit=function(old_acc, row, new_acc)` makes it more obvious (and I like that syntax).

I suspect this likely isn't an issue, but I could see someone getting confused by not realizing which version of the accumulator a two-argument `emit` function is going to get passed in. I think we shouldn't worry about it, and just make sure that we always call the argument `old_acc` or `prev_acc` instead of just `acc` in the documentation.

Could `fold` be used with an `emit` argument but without a `base` argument? In that case we need to figure out what to pass into `emit` for the first row. We could pass in `null`, or we could require a `base` argument when `emit` is being used.
I have a slight preference for passing in `null`, so that `default` can be used inside of `emit` to handle the initial case.

**Comment by mlucy** [comment]
I think if `fold` is used with an `emit` but no `base` we should have the same behavior as when `fold` is used with no `emit` and no `base` (i.e. that we consider the first element of the stream the base), just to be consistent.  

That would have the nice property that you can take any `fold` and add `emit=function(acc, row, new_acc) { return [new_acc]; }` to it in order to get a stream of the partial computations.  If we passed `null` as the base then `r.range(10).fold(lambda a, b: a+b)` would be correct, but `r.range(10).fold(lambda a, b: a+b, lambda acc, row, new_acc: [new_acc])` wouldn't be.

**Comment by danielmewes** [comment]
So the value of `new_acc` on the first call to `emit` would be the first element of the stream, but what would be the value of `acc`?
Maybe I'm not understanding something correctly.

**Comment by mlucy** [comment]
I'm proposing that `r([1, 2, 3, 4, 5]).fold(FUNC1, emit=FUNC2)` be identical to `r([2, 3, 4, 5]).fold(FUNC1, base=1, emit=FUNC2)` in the same way that `r([1, 2, 3, 4, 5]).fold(FUNC1)` is identical to `r([2, 3, 4, 5]).fold(FUNC1, base=1)`.

**Comment by danielmewes** [comment]
Oh, so `emit` wouldn't be called on the first element at all if there is no `base` argument?
I find that a bit confusing.

I think for the fold function it makes sense, because it obviously needs two values to work. But conceptually `emit` seems more like an iterator over the input to me, not unlike the function passed to `concatMap`. Basically expected `seq.fold(ANYTHING, emit=lambda _, x, _: f(x))` to be equivalent to `seq.concatMap(lambda x: f(x))`. I'm no longer sure if that's really a useful property though.

**Comment by mlucy** [comment]
Maybe it would be better to require the `base` if you use `emit`.  (Actually, we could consider requiring the `base` every time you call `fold`; if you don't need a `base` then you can use `reduce` instead.)

**Comment by deontologician** [comment]
It might still be useful to use fold because it goes in a specific order, you know the type of the accumulation argument and don't have to check. Reduce is really annoying in the case where the sequence type and the output type are different

**Comment by mlucy** [comment]
> Reduce is really annoying in the case where the sequence type and the output type are different

In those cases you would need to specify a `base`, right?

**Comment by deontologician** [comment]
Ah, that's true. I withdraw my objection

**Comment by danielmewes** [comment]
> we could consider requiring the base every time you call fold; if you don't need a base then you can use reduce instead.

That sounds good to me.

It's also easy to make it optional later without breaking compatibility if it turns out that users expect it to be optional.

Should we make the base a positional argument then?
`fold(f, base [, {emit: emitFunc}])`

**Comment by mlucy** [comment]
If we make it positional it would be harder to make it optional later, but yeah, I think positional argument is better.  I would have a moderately strong preference for putting `base` before `f` though.

**Comment by danielmewes** [comment]
Looking at https://en.wikipedia.org/wiki/Fold_%28higher-order_function%29#Folds_in_various_languages, about half of the languages seem to put the base first and half the function. Most functional languages (but also JavaScript and Python) seem to take the function first, while some traditionally procedural languages (C#, C++, D, Java) have the base first.

I think `fold(base, f)` might read better, because you have all the data to the left, and the function body to the right, rather than having `data.fold(function {...........}, data)`.

I'm happy with either option. Let's go with `fold(base, f[, {emit: emitFunc}])` unless someone has strong other opinions.

**Comment by AtnNn** [comment]
I think having the base first and function second would be nicer too. What about the order of the arguments to the function?

The type of `foldl` in Haskell places the accumulator first, which produce a nice symmetry in the order or arguments: `(b -> a -> b) -> (b -> [a] -> b)`.

To get a similar symmetry in ReQL, the order of the arguments would have to be like in Erlang: `els.fold(acc0){ |el acc| ... }`

**Comment by mlucy** [comment]
If you handed me a new language with a function called `fold` or `reduce`, I would assume the accumulator is on the left, personally.  I agree that it's a little weird because we but the base after the sequence, but I still think the accumulator being the first argument seems more natural.

**Comment by AtnNn** [comment]
@mlucy: I didn't seem as natural to me at first, but after thinking about it more I fully agree with you.

**Comment by danielmewes** [comment]
Marking settled with `fold(base, function(acc, el)[, {emit: function(old_acc, el, new_acc)}, final_emit: function(acc)])`

**Comment by nighelles** [comment]
This is in review 3431
Implemented in branch nighelles_3736
https://github.com/rethinkdb/rethinkdb/tree/nighelles_3736

**Comment by nighelles** [comment]
This is in next.

**Comment by danielmewes** [comment]
:clap: Yay, have been waiting for this term for a long time :)
