### ISSUE TITLE
Multiple nodes and multiple servers causing cluster management issues in the UI

### ISSUE THREAD

**Issue by esatterwhite** [rethinkdb/rethinkdb#3737]
Running rethinkdb 1.16.0+1~0trusty

When I try to start a Node 1 on a Second machine, the ui is complaining that it is disconnected from Node 2 on Machine 1.

### Machine 1 / Node 1

```
docker run -d -h `hostname` -p 28015:28015 -p 29015:29015 -p 8080:8080 -v $HOME/data/rethink:/data dockerfile/rethinkdb rethinkdb --bind all --canonical-address 192.168.0.2
```

### Machine 1 / Node 2
```
 docker run -d -p 28015 -p 29015 dockerfile/rethinkdb rethinkdb --join 192.168.0.2:29015 --bind all
```

### Machine 2 / Node 1
```
docker run -t -i -p 28015:28015 -p 29015:29015 -p 8080:8080 dockerfile/rethinkdb rethinkdb --bind all --join 192.168.0.2:29015
```

### Issues Table Output

```
{
	"critical": true,
	"description": "Server `nightcrawler` is disconnected from `61f7cb63c8c1_xw1`. Here are some reasons why the server may be disconnected:

		- The server process has crashed. 
		- The network connection between the two servers was interrupted. 
		- The server 's canonical address is not configured properly. 
		- The server has experienced a hardware failure.

		If the server 's data has been permanently lost (for example, a disk failure) you can resolve this issue by deleting the server's entry from the `rethinkdb.server_config` system table.Once you 've deleted the server's entry, its data and configuration will be discarded.
	" ,
	"id": "b1bf40a3-f5a7-524a-a47b-2590e2f62b28",
	"info": {
		"disconnected_server": "nightcrawler",
		"reporting_servers": [
			"61f7cb63c8c1_xw1"
		]
	},
	"type": "server_disconnected"
}

```

**Comment by Tryneus** [comment]
@esatterwhite, it looks like there is a conflict between the network configurations you are providing for docker and the server.

You should be providing a `--canonical address` option for every container, which should correspond to the host machine's ip:port for a given node's intracluster port.  In the given example:

* Machine 1 / Node 1 - appears to have the correct canonical address `192.168.0.2:29015`
* Machine 1 / Node 2 - does not have a statically available port - it looks like the port will be assigned to a random host port on each run.  The `-p 28015 -p 29015` options should instead bind these to a static host port, like `-p 28016:28015 -p 29016:29015`.  Then, the canonical address should be `192.168.0.2:29016`.
* Machine 2 / Node 1 - should have a canonical address based on the host's IP: `<ip>:29015`

This configuration is important because even if nodes can connect to each other at startup, one of the connections may go down during operations, and both peers should know the proper `ip:port` to reconnect to.

Let me know if this solves your problem or if you have any questions or suggestions.

**Comment by esatterwhite** [comment]
no, i still get the same error. 

* M1 N1 - same as before
* M1 N2 - `docker run -d -p 28016:28015 -p 29016:29015 dockerfile/rethinkdb rethinkdb --join 192.168.0.2:29015 --canonical-address 192.168.0.2:29016`
* M2 N1 - `docker run -t -i -p 28015:28015 -p 29015:29015 -p 8080:8080 dockerfile/rethinkdb rethinkdb --bind all --join 192.168.0.2:29015 --canonical-address 192.168.0.56:29015`

**Comment by Tryneus** [comment]
M1 N2 should probably be using `--bind all` as well.

It looks like the problem here is that M2N1 connects to M1N1, and is told how to connect to M1N2 (`192.168.0.2:29016`), but connection attempts towards it fail.  M1N2 should be attempting to connect to M2N1 in the same manner, and it looks like that should work, so there may be something else going on here.

Out of curiosity (though I'm not sure it'll tell us anything we don't already know), could you paste the output of `r.db('rethinkdb').table('server_status')`, preferably with a client connected to M1N1?

**Comment by Tryneus** [comment]
Ok, I just tested this on three separate servers without docker, and the behavior is that the the last server to join will attempt to connect to all other existing nodes, but existing nodes do not initiate connections to new members of the cluster.  This behavior should be fine, as it's only a problem if the network configuration is not transitive, which is a problem in other situations and we shouldn't try to support it.

**Comment by Tryneus** [comment]
@esatterwhite, at this point, I am fairly sure that adding `--bind all` to M1 N2 should solve the problem.

**Comment by esatterwhite** [comment]
@Tryneus Yes, specifying the canonical address, and `--bind all` on all of the nodes corrected the problem. Is there any reason one would not specify bind all? Maybe that should be the default behavior?

**Comment by danielmewes** [comment]
@esatterwhite we only bind to `localhost` by default for security reasons.
That makes it easy to run RethinkDB locally without having to set up a firewall or other access control.
