### ISSUE TITLE
Request: Cloudfoundry/Heroku buildpack

### ISSUE THREAD

**Issue by kevinSuttle** [rethinkdb/rethinkdb#3738]
Would be so nice to use Rethink in a PAAS environment. 
http://docs.cloudfoundry.org/buildpacks/custom.html

**Comment by deontologician** [comment]
I've built heroku buildpacks in the past, but usually they aren't a good fit for something like a database because Heroku's drives are mounted read-only when they're deployed. I assume cloudfoundry has other buildpacks for databases?

If you want to get started now, compose.io has instructions for using them with Heroku: https://docs.compose.io/partners/heroku.html

**Comment by kevinSuttle** [comment]
Sorry, I meant service. Buildpacks are for runtimes. http://blog.pivotal.io/pivotal/features/how-to-add-your-service-to-cloud-foundry-architecture-code-boilerplate-and-mongodb-example
