### ISSUE TITLE
consider making the JavaScript runopts be snake case

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3743]
The runopts for the Python and Ruby drivers are currently snake case, like `group_format`, but in JavaScript they are heads-down camel case (e.g.: `groupFormat`). Previously this difference has been masked by some name mangling by our test infrastructure, but I thought a conversation on whether we should have consistency is in order.

I am currently doing re-doing this mangling in the "test driver".

**Comment by mlucy** [comment]
I thought we accepted either version for optargs in JS?

**Comment by deontologician** [comment]
camelCase is the default in the js world. We may use a lot of snake_case in the code, but the api is supposed to feel natural for js developers.

**Comment by danielmewes** [comment]
I think @mlucy is right, both variants should now work for the JS driver (at least since @gchpaco took the global opt arg validation out of the JS driver and into the server).
So I think we can get away without doing any translation in the test infrastructure, as long as we always use snake_case in the tests.

I don't think we should change the official JS API to using snake_case for everything. That would be a very big API change and would make the JS driver feel much less natural.

**Comment by danielmewes** [comment]
My impression is that we generally agree to keep the camel case in the JS driver.

@larkost do you think this needs more discussion or can I close the issue?
