### ISSUE TITLE
Adding limit() makes query ~4 times slower

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3756]
Noticed while testing https://github.com/rethinkdb/rethinkdb/issues/3703:

```
r.table('en2').limit(5000).merge( r.js("(function(row) {return {mime2: row.mime}; })") ).coerceTo('ARRAY').count()
```
takes 3.78 seconds.

```
r.table('en2').merge( r.js("(function(row) {return {mime2: row.mime}; })") ).coerceTo('ARRAY').count()
```
takes 0.95 seconds.

The only difference is the missing `limit(5000)` in the second query. The table `en2` has 3,203 documents, so the `limit(5000)` shouldn't have any effect.

@mlucy any ideas why this might happen? Does `limit` change anything else apart from the batch spec?

**Comment by danielmewes** [comment]
I'm going to put the data set on newton (internal server) later.

**Comment by mlucy** [comment]
The `limit` turns the stream into an eager stream and stops the transformation from being pushed to the shards.  `r.table.merge.limit` should be as fast as the non-limited version because it will push the merge to the shards.  (For other workloads the first one might be faster because e.g.`r.table.filter.merge.limit` will sometimes evaluate the `merge` function more times than it needs to, whereas `r.table.filter.limit.merge` will always evaluate it the minimum number of times at the expense of doing every evaluation on the machine handling the query.)

**Comment by danielmewes** [comment]
Ohh that makes sense. Thanks for explaining.
