### ISSUE TITLE
inactivity timeout on a tcp socket in the js driver won't properly close the socket

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3768]
Currently in the JS driver,  when a raw socket raises a `timeout` event, we just set the `@open` flag to false and re-raise the event. According to [the node documentation](http://nodejs.org/api/net.html#net_event_timeout), the socket isn't actually closed, unlike with normal connection errors. The user must close it themselves.

**Comment by avaer** [comment]
Ran into this as well.

The effect is quite nasty since there's a default timeout (20 secs), by default nothing is closed, but after 20 secs the connection just silently stops working (you won't even get errors, promises just won't resolve).

Basically the JS driver is completely broken by default, but you won't find out in tests because the repro requires 20 seconds of idling.

**Comment by deontologician** [comment]
I found this in the driver recently. Should be easy to fix

**Comment by deontologician** [comment]
Fix is up in CR 2638

**Comment by deontologician** [comment]
OK, I believe this is not an issue. This isn't our handshake timeout here, but rather a completely optional inactivity timeout the Node.js net library supports on sockets. Since we don't expose the socket directly, and we never user [socket.setTimeout](http://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback), this event should never be raised. Essentially our handling of that event is dead code.

@avaer I think the issue you're experiencing is actually caused by the recently fixed issue here: #3733 

I'm closing this as invalid
