### ISSUE TITLE
Erronious behavior after dropping a table with a dead shard.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3783]
I started up two servers, created a table sharded across both of them, then shut down one of the servers

After that, the following hung forever for me:

```
> r.table('test').run()
RqlRuntimeError: Cannot perform read: Primary replica for shard ["", +inf) not available in:
r.table('test')
^^^^^^^^^^^^^^^
> r.table_drop('test').run()
Out[23]:
{u'config_changes': [{u'new_val': None,
   u'old_val': {u'db': u'test',
    u'durability': u'hard',
    u'id': u'7b8cb2a5-51e1-433f-a116-fabd5094e138',
    u'name': u'test',
    u'primary_key': u'id',
    u'shards': [{u'primary_replica': u'newton_y91',
      u'replicas': [u'newton_y91']}],
    u'write_acks': u'majority'}}],
 u'tables_dropped': 1}
> r.table_create('test').run()
HANGS_FOREVER
```

@timmaxw, any idea what might be going on?

**Comment by timmaxw** [comment]
Yeah. This actually has nothing to do with dropping the table. If you spin up two servers, then shut one of them down, then try to create a table, it will hang forever. This is because it's waiting for the table to finish becoming ready before returning, and the table can't finish becoming ready when there's a missing server. The short-term solution is to bail out early (before trying to create the table) if there's a dead server. The long-term solution is Raft.

**Comment by mlucy** [comment]
Ah, OK.  Sorry for the red herring.

**Comment by danielmewes** [comment]
Since we have lots of other things to do, I think we should just leave this alone until we switch to Raft.
