### ISSUE TITLE
Not possible to set auth key in config

### ISSUE THREAD

**Issue by soplakanets** [rethinkdb/rethinkdb#3808]
The manual states you should set auth key via a query (http://www.rethinkdb.com/docs/security/) and I can not find a way to pass this key via config file/startup param. Is there any way?

**Comment by danielmewes** [comment]
@soplakanets There's no way currently.

It might be a bad idea to allow passing it as a command line argument, because you can then end up with different servers setting a different auth key.
However the auth key is a cluster-wide setting, and so it would end up picking one more or less randomly (actually depending on which server in the cluster was started last).

**Comment by soplakanets** [comment]
Thanks @danielmewes. It might be a bad idea indeed. 
However, I was try to automate RethinkDB cluster setup (ansible) and found that without ability to pass auth_key in config I am stuck with firewall as my only option for securing cluster.

**Comment by danielmewes** [comment]
@soplakanets First of all a quick note that the auth key is not meant as a sole mean of protection for a RethinkDB server on the Internet (it's mostly meant for providing additional protection in internal networks).

Regarding your specific case: You could use for example a Python script for automatically setting the auth key (e.g. run it on startup):
```py
import rethinkdb as r
conn = r.connect('localhost', 28015)

r.db('rethinkdb').table('cluster_config').get('auth').update({'auth_key': 'secret key'}).run(conn)
```

**Comment by danielmewes** [comment]
Closing because I don't think we can really change this, but please feel free to ask further questions in this thread @soplakanets.
