### ISSUE TITLE
Suggestion: pluck should preserve attribute order

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3817]
For those in an interactive session (via command line or the web interface), it would be nice to have the attributes returned in the same order as specified in a pluck command, just like it happens when using 'select a,b' in traditional SQL dbs.

**Comment by danielmewes** [comment]
Thanks for the suggestion.
Unfortunately that is not easily possible because attributes in ReQL generally don't have a defined order (though in practice they're always alphabetically ordered).

This is related to https://github.com/rethinkdb/rethinkdb/issues/3194 . I just added a ReQL proposal to that issue, so we can implement that at some point (but it will probably take a bit until we get there).

**Comment by timmaxw** [comment]
I wonder if we could do this in the web UI only, without changing the server logic. It would look something like this: For each column in the result, scan the query string for a string literal with the column's name. Show the columns in the order that the string literals were found. Put any columns that weren't found at the end in alphabetical order.

For example, `r.table("foo").pluck("bar", "baz").merge({"blah": 1})` would order the columns as `bar`, `baz`, `blah`. Of course it's easy to get false positives: `r.table("x").pluck("y", "x")` would put `x` before `y`. So I'm not sure if this is useful or confusing.

**Comment by danielmewes** [comment]
@timmaxw: @elifarley suggested something similar over here https://github.com/rethinkdb/rethinkdb/issues/3848 . I think it would be reasonable to do, though there are more important things at the moment.
