### ISSUE TITLE
Read from a majority of replicas

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3895]
`raft` currently guarantees that if a write is acked to the client, it will be preserved during auto-failover. Some writes will be lost in auto-failover, but those writes will not be acked to the client, so it's OK. But under the current implementation, reads will sometimes see those writes. We could offer a flag to make reads go to a majority of replicas before being acked to the client; reads run with this flag would never see lost writes.

The main thing this is useful for is passing the Jepsen tests (see #1493). As a workaround, it's possible to use a write instead of a read. Writes run in "majority" mode will never see lost writes. So we could send a write that makes a trivial change to the document, just for the purpose of fetching the current value of the document.

**Comment by timmaxw** [comment]
We also need to make sure that reads run in this mode don't see data which has not been committed to disk yet. An easy but not terribly performant solution is to perform the read, then wait for the data to be flushed to disk before returning.

**Comment by danielmewes** [comment]
I think we should use an implementation that's non-intrusive to how we run writes and other non-majority reads.

@timmaxw suggested at some point that we could run `sync` query after the read from the primary, before we return the result of the read. This will not only make sure that a majority of replicas has processed all writes before the read, but it will also make sure that those writes have been written to disk, even if they were soft durability writes.

I really like that solution. I think the performance of the majority read / repeatable read mode under this wouldn't be much worse than under a more complicated / more intrusive solution either (but I could be missing something).

**Comment by Tryneus** [comment]
Working on this.

**Comment by Tryneus** [comment]
The implementation is done, but the user interface is not well-defined; pinging @coffeemug and @timmaxw to discuss.

Current plan at the moment is to replace `use_outdated` with `read_mode`, with the possible values:
 * `committed` - perform the read on the primary, but only return once the data has been committed to disk on a majority of replicas
 * `primary` - perform the read on the primary, but do not wait for the data to be committed to disk
 * `secondary` - allow reads from secondary replicas, and do not wait for the data to be committed to disk

Obviously these names are up for debate.  Since `use_outdated` is an optarg on `r.table`, I imagine this will be as well.

**Comment by coffeemug** [comment]
I would name it like this:

- `committed` -> `majority`
- `primary` is fine
- `secondary` -> `outdated`

Other than that I like this!

**Comment by timmaxw** [comment]
Maybe `primary` -> `single` for consistency with the write modes?

**Comment by coffeemug** [comment]
That sounds great.

**Comment by Tryneus** [comment]
Fix is up in review 2942.

**Comment by coffeemug** [comment]
:clap:

**Comment by Tryneus** [comment]
Approved and merged to `raft` as of commit 0acdfd1.
