### ISSUE TITLE
Better server metadata behavior

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3897]
Currently the server metadata system in `raft` acts the same as it always has: new servers make entries in the semilattices, and these entries stay until the user deletes them, and then they can never come back. This made sense when the reactor was using the server metadata to decide when it was safe to do operations, but it doesn't make sense with Raft. We should do something better.

This is closely related to #3594. There are basically two options:

* Make server metadata only visible when the server is visible. It would automatically disappear from `server_config` and `server_status` when the server disconnected. We'd have to do something special for servers that were not connected, but were supposed to be used by tables.

* Something similar to the current system, but make servers automatically un-delete themselves if they rejoin the cluster.

**Comment by danielmewes** [comment]
For completeness: We decided in #3594 that it would be best to implement the first of the options, i.e. don't keep a permanent record of servers - at least from a user's point of view.

It's worth discussing whether we should make an exception for servers that are participating in an otherwise reachable table.
I think it's probably not necessary as far as `server_config` and `server_status` are concerned.

The most important piece of information I can think of that we would want to make available to users when a server participating in a table goes missing is its name. This is useful for showing an issue like "Table ... is missing replica ..." with the server name rather than having to display the server UUID.

If it's easier to implement, I think it would be fine to keep the current metadata and have users delete servers explicitly. We would only need to change that servers can "undelete" themselves later. Though even that is probably a relatively rare case, which we could ignore for the first release.

**Comment by danielmewes** [comment]
Moving to polish.

**Comment by timmaxw** [comment]
Fixed in 42d7ed236951156925a7dbe6767f26a4a86f3b70.
