### ISSUE TITLE
Python driver `next(wait=1)` should throw something based on `RqlError`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3937]
Currently if `cursor.next` is given a value for `wait` and it exceeds that it will raise a `socket.timeout`. We should probably not allow that error to escape, for two reasons:
1. It is a violation of the encapsulation: the user has no need to know that there might have been a `socket` used. It might be obvious, but they don't need to know that.
2. If they are going to catch the error they are going to need to `import socket`. Needing to import a different module to catch common errors is a poor interface.

I would propose that we create a new error, something like `RqlTimeout`,`RqlCursorTimeout`, or `RqlEmpty `, `RqlCursorEmpty`. I favor the last two, since it gets away from the idea of a timeout error, and focuses more on the Cursor being empty.

**Comment by danielmewes** [comment]
I agree, it should throw a custom exception type.
We have to fix that for 2.0.
Assigning @Tryneus .

**Comment by Tryneus** [comment]
I put this into the Python driver refactor (for #2622), which is up in review 2732.  This includes two new exceptions:

* `RqlTimeoutError` - raised when an operation times out (typically `connect` or `Cursor.next`)
* `RqlCursorEmpty` - raised when attempting to iterate past the end of a cursor (only used in the Tornado implementation at the moment, but I may make it more ubiquitous before this hits `next`).

Changed the driver's exception class structure a bit to facilitate this.  Before, `RqlDriverError` inherited from exception rather than `RqlError`, because `RqlError` was only for errors on a query, with a backtrace.  Now `RqlError` is the base class for all python driver exceptions, and `RqlQueryError` now inherits from it and forms the base class for `RqlRuntimeError`, `RqlCompileError`, and `RqlClientError`.

**Comment by Tryneus** [comment]
Just noting here that `RqlCursorEmpty` is now gone from the review, as it was inconsistent between the two implementations.  I've added a workaround allowing us to throw a StopIteration in the Tornado implementation.

**Comment by Tryneus** [comment]
This has been merged to `next` and `v2.0.x` as part of the python driver net refactor an will be in release 2.0.
