### ISSUE TITLE
`r.hasFields('id').nth(0).update({foo: 'bar'})` returns error

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/rethinkdb#3943]
Running a query like: `r.db('ti').table('users').hasFields('id').nth(0).update({foo: 'bar'})` returns `RqlRuntimeError: Expected type SELECTION but found DATUM:`

I would expect it to... work :wink: 

It does work if you remove the `.hasFields`

Similar to #3939

Reproduced in Web UI on RethinkDB 1.16.2-1

**Comment by chrisvariety** [comment]
`r.db('ti').table('users').hasFields('pendingSubscriptions').update({foo: 'bar'})` also doesn't work (`Expected type SELECTION but found SEQUENCE:`), seems like there are issues in general chaining updates after `hasFields`

**Comment by mlucy** [comment]
Hi @chrisvariety -- Sorry you ran into that!  This is a known bug (https://github.com/rethinkdb/rethinkdb/issues/3851) that should be fixed in 2.1 (and probably backported to 2.0.x).

You can work around it for now by writing `r.db('ti').table('users').filter(function(row){return row.hasFields('id')})` instead of `r.db('ti').table('users').hasFields('id')`.

Closing as a duplicate.

**Comment by chrisvariety** [comment]
@mlucy thanks, I missed that issue!
