### ISSUE TITLE
Tweak Web UI color scheme

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3946]
@mglukhovsky suggested a while ago that we could slightly tweak the Web UI color scheme for 2.0 to match our new website.

**Comment by deontologician** [comment]
I should note that if this is being put into 2.0, you should pay attention to the branch josh/3660 which is currently in review (and is slated for 2.1, not the 2.0 branch). It should hopefully be just css changes, but if any js changes are made it'll be important to take into account since #3660 is just a sweeping change

**Comment by danielmewes** [comment]
Good to know. I think it's probably just going to be a CSS change.

**Comment by danielmewes** [comment]
This isn't happening for 2.0. Maybe later.
