### ISSUE TITLE
Having the Ruby driver send a `STOP` query to the server for a write it issued doesn't seem to interrupt the write

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3960]
Not sure yet if this is a driver or a server bug.

**Comment by Tryneus** [comment]
This case is fairly untested, since it hasn't been possible to do this through any of the drivers before, but I attempted to test some of the behavior in `unittest/rdb_interruptor.cc`.  That said, we don't have proper query interruption if a query goes cross-cluster, so we'll need to fix that at some point (see #2630).

**Comment by mlucy** [comment]
This no longer seems to be the case, I think I was testing something incorrectly before.
