### ISSUE TITLE
Add `in` or `contains` operator to ReQL

### ISSUE THREAD

**Issue by cadina** [rethinkdb/rethinkdb#3995]
Could be useful when doing subqueries with lambda function.
Example:
`query.filter(lambda x: x['id'] in (subquery))`

**Comment by deontologician** [comment]
We have [contains](http://rethinkdb.com/api/python/contains/) but we don't use `__contains__` as syntactic sugar to allow the `in` operator because it coerces the return value into a boolean, and we need it to return a reql term type.

So for example, if you write this class:

```python

class Bar(object):
    pass

class Foo(object):
    def __contains__(self, other):
        return Bar()
```

It won't do what you expect:

```bash
>>> f = Foo()
>>> 13 in f
True
```
