### ISSUE TITLE
TTL syntax suggestions

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#4008]
Here are some examples on how TTL can be used.

Defines a default value of 1000 ms for TTL (but each document can have its own 'ttl' attribute),
creates a read-only attribute 'date-created' for every document and creates an index called 'date-created':

``` Javascript
db.tableCreate("foo", {ttl: 1000} )

// Uses an alternate index name:
db.tableCreate("foo", {ttl: {'my-timestamp': 1000}} ) // ttl based on a user-created index named 'my-timestamp'
```

``` Javascript
// checks table-defined TTL (if there is one, like the above example) and returns a NOT-FOUND error if doc is too old
r.table("foo").get(1)

// checks table-defined TTL (if there is one, like the above example) and returns only those documents that are not too old
r.table("foo").getAll('man_of_steel', {index:'code_name'})

overriding a document's TTL:

// If the doc doesn't have a column named 'date-created', returns it. Otherwise, checks doc age according to the TTL passed as argument and returns a NOT-FOUND error if doc is too old
r.table("foo").get(1, {ttl: 500})

// Omits only docs that have an attr named 'date-created' AND are too old, according to the TTL passed as argument
r.table("foo").getAll('man_of_steel', {index:'code_name', ttl: 500})

// Omits only docs that have an attr named 'my-timestamp' AND are too old, according to the TTL passed as argument
r.table("foo").getAll('man_of_steel', {index:'code_name', ttl: {'my-timestamp': 500}})
```

If a table is creaetd with a 'ttl' option, then the TTL garbage collector will take care of it. But this garbage collector doesn't have to be coded first - we can have passive TTL functionality for now (as suggested on a comment on #746).

Or there could also be a command that asks the cluster to purge old entries, like:
´´´Javascript
r.db('test').purge({sync: _boolean_})
db.table('foo').purge({sync: _boolean_})
´´´
When _sync_ is true, the command only returns after all changes have been committed to storage.
When it's false (the default), the return is immediate, much like the way indexCreate works.

The **purge** command can be used to get a changefeed, like this:

``` Javascript
// shows documents as soon as they are purged either by the GC or by a get
r.db('test').purge().changes()
db.table('foo').purge().changes()
```

And here's an alternate way to purge old entries which gives more flexibility:

``` Javascript
// delete all entries that have already expired but haven't been collected by the GC
r.db('test').expired().delete()
db.table('foo').expired().delete()

// As soon as an entry expires (but before it's deleted), it'll be seen on these changefeeds:
// (this one will be expensive)
r.db('test').expired().changes()
db.table('foo').expired().changes()
```

**Comment by thelinuxlich** [comment]
I don't see much value in fixing ttl table-wide, is that common in other databases?

**Comment by elifarley** [comment]
The TTL isn't fixed for the whole table. It acts like a default, in a hierarchival way (leftmost items with higher precedence):

ReQL query's TTL argument > document's TTL attribute > table's TTL value

1. If a TTL is specified when fetching the document (like in ´´´r.table("foo").get(1, {ttl: 500})´´´), then this value will be used.
2.  If a TTL is NOT specified when fetching the document (like in ´´´r.table("foo").get(1)´´´), then the document's ttl attribute will be used, if it has one. If it doesn't, then...
3. The table's TTL value will be used. If it doesn't have one, then no TTL is taken into account (or maybe a database-wide value could be used)

**Comment by elifarley** [comment]
BTW, I was inclined to suggest defining TTL in seconds, but then I thought that someone could require TTL in ms for some reason.

For my own use cases, I don't see much need for ms precision, so I'd stick with TTL in seconds.

**Comment by danielmewes** [comment]
Thank you @elifarley, that's a great proposal!

We'll discuss it for one of the upcoming releases.

**Comment by tatsujin1** [comment]
Because I really wish some kind of TTL feature be implemented in RethinkDB, I thought I'd take a stab at an API proposal as well :)

Akin to another popular nosql db, my variant is index-based.

#### Shared/general expiration time
```
table.index_create('field', expiration=30.0)
...
table.get(...).update({ 'field': 'anything' })
```
After 30 seconds, the document will be deleted (emitting the usual changefeed event).

#### Document-specific expiration time
```
table.index_create('field', expiration=True)    # value must be a time stamp
...
table.get(...).update({ 'field': r.now() + 60 })
```
After 60 seconds, the document will be deleted (emitting the usual changefeed event).

#### Extra features
These could be added later, but I'd really like to see them; I already have many use cases where will make things really neat, as opposed to clumsy and ugly. :)

An `expiration_action` argument to `index_create`. It may specify what the server should do when the index has expired:
```
table.index_create('field',
					expiration=True,
					expiration_action='delete')    # the default
```
Which will delete the document as usual.

Or - and this is where it gets interesting - even more flexible, a custom action.
```
table.index_create('field',
					expiration=True,
					expiration_action={ 'do_something': 'yes' })
```
Which would then update the document with the expired index using the supplied data, which in this case would set a field, `do_something = 'yes'`. (again emitting the appropriate changefeed message)

Overriding the `expiration_action` per document might be useful as well, but I couldn't figure out an appropriate way to do that, only as an extra argument to `update` & `insert`:
```
table.update({ 'field': r.now() + 60 }, expiration_action={ 'crap': 'example })
```
But it feels hacky :-/

I suppose other values for `expiration_action` could also be added later.

Finally, as a bonus, the expiration could be explicitly specified in the changefeed messages, e.g.:
```
{ 'new_val': ..., 'old_val': ..., 'expired': [ 'field' ] }
```

Ok, I think that was all...

**Comment by danielmewes** [comment]
Thanks for the writeup @tatsujin1 .
One thing where I'm not sure if I understand it correctly:

In the second case, "document-specific expiration", the `field` of the secondary index is assumed to contain a datetime value, and eviction is triggered when that value reaches `r.now()`, correct?

Now what does the field mean in the first case, "Shared/general expiration time"? You say you can set it to anything, and that will start/reset the expiration timeout. But does it matter at all which `field` I create the index on? If I insert a document that doesn't have `field`, would that document still expire? Similarly if I update a document in the table, but don't update `field`, would the expiration timeout be reset for that document?

**Comment by tatsujin1** [comment]
Yes, in the shared variant it does indeed become kind of hidden functionality, it implies some kind of internal timer.
I think the explicit version is much better, "document-specific". In fact, now that you laid out the logic that plainly, the "shared/generic" variant seems kind of bad. :)

**Comment by thelinuxlich** [comment]
@srh should close in favor of #5823, which has a working implementation
