### ISSUE TITLE
Ruby driver does not handle signals well

### ISSUE THREAD

**Issue by nviennot** [rethinkdb/rethinkdb#4029]
The following self contained test:

```ruby
#!/usr/bin/env ruby
require 'rethinkdb'
include RethinkDB::Shortcuts

r.connect(:host => 'localhost', :port => 28015, :db => :test).repl
r.db_drop(:test).run rescue nil
r.db_create(:test).run
r.table_create(:table).run

Signal.trap(:USR2) { }
Thread.new { sleep 0.2; Process.kill(:USR2, 0) }

r.db(:test).table(:table).changes().run().each { }
```

Results in the following error:

    ..../rethinkdb-1.16.0.1/lib/net.rb:248:in `wait': Internal driver error, no response found. (RethinkDB::RqlDriverError)

The expect behavior is that the test program should just hang waiting for changes.

**Comment by danielmewes** [comment]
Thanks for the report @nviennot.
I'm not sure how this works in Ruby, but in C I'd suspect that we're not handling an EINTR error correctly.

@nviennot how important is this for you?

@mlucy do you have an idea why this is happening and if we could avoid it?

**Comment by nviennot** [comment]
@danielmewes not important. I was just trying to play with the changefeed feature, and the connection died when I tried to resize my terminal (as it got a SIGWINCH).

I think this `wait`: https://github.com/rethinkdb/rethinkdb/blob/next/drivers/ruby/lib/net.rb#L570 is getting a spurious wakeup.

Instead of dying, it's probably better to loop until the wakeup condition is true (example of code: https://github.com/nviennot/synapse/blob/master/lib/promiscuous/redis/async.rb#L47-L52)

The wakeup condition should be something like `data_is_available || !is_connection_open()`

**Comment by danielmewes** [comment]
That sounds plausible, thanks for looking into it @nviennot.

**Comment by nviennot** [comment]
Oh, and a quick note to @mlucy :
the method `safe_synchronize` defined here: https://github.com/rethinkdb/rethinkdb/blob/next/drivers/ruby/lib/net.rb#L619-L629 is actually not safe.
1) The naming is weird, consider using `reentrant_synchronize`
2) the variable `@rdb_owner` is set before getting into the synchronize block, and thus the whole thing is racy.

But there is no need to implement such thing: In Ruby, if you want reentrant Mutexes, you use Monitors instead: http://ruby-doc.org/stdlib-2.1.2/libdoc/monitor/rdoc/Monitor.html

**Comment by mlucy** [comment]
@nviennot -- thanks for the bug reports.

**Comment by mlucy** [comment]
Both fixes are in CR 2790 by @Tryneus .  It ended up being a little bit complicated because `Monitor::wait_while` doesn't take a timeout, `Monitor::wait` does take a timeout but doesn't appear to indicate whether it was woken up by the timeout or by a signal, and wrapping `Monitor::wait` in `Timeout::timeout` confuses the synchronization logic in Ruby 1.9.1, so we have do call `.wait(timeout)` and then check ourselves whether it's been long enough to trip the timeout and/or whether or not we actually got data.

(Also, I decided to just replace the mutex with a monitor rather than using the monitor mixin because we apparently reset the mutex (and now the monitor) when you call reconnect.  I'm not sure why we did that, but I could see how it would make certain sorts of bugs less likely so I didn't want to change it.)

**Comment by mlucy** [comment]
@nviennot -- it's still in code review, but if you want to check out the new code and see if it looks right to you it's at https://github.com/rethinkdb/rethinkdb/compare/mlucy_4029 .  Thanks again for the bug reports!

**Comment by nviennot** [comment]
Yeah, never use `timeout {}` in ruby, it will break things in very unexpected ways.

I'm looking at the code on mlucy_4029, and is doesn't fit the patterns I'm use to see.
Typically, I'm expecting a pattern like this:

```ruby
loop do
  break if condition
  @mon.wait
end
```

checking the condition after the wait would be a problem as the signal may never come.

To me, this would be more readable:

```ruby
start_time = Time.now.to_f
@mon.synchronize {
  loop {
    res = @data.delete(token)
    return res if res

    unless @waiters[token] || !is_open()
      raise RqlRuntimeError, "Connection is closed."
    end

    if timeout && Time.now.to_f >= start_time + timeout
      raise Timeout::Error, "Timed out waiting for cursor response."
    end

    @waiters[token].wait(timeout)
  }
}
```

This code takes care of the 3 timeout checks that were previously, in only one place.

The `* 0.9` thingy seems inappropriate to me. `wait(timeout)` will not return before timeout has elapsed (but may return much longer after timeout). Internally, wait calls `sleep(timeout)`.
Ideally, we would want to decrement the value of timeout based on the amount of time spent in `wait`, but whatever.

**Comment by mlucy** [comment]
@nviennot -- I didn't realize `wait` offered that guarantee in Ruby, I'll remove the 10% hack.

I think that switching to checking `is_open()` instead of `!@waiters.has_key?(token) && !@data.has_key?(token)` doesn't work unfortunately because of the behavior of `reconnect` (specifically, if you open a cursor on `conn`, call `conn.reconnect`, and then try to consume data from the cursor, I think it will hang rather than producing an error).  We don't repeat tokens even if you reconnect, which is why the other predicate works.

There's also a small bug that was in my first version too where if you're woken up by a signal partway through the timeout you sleep for longer than intended (e.g. if you're woken up by a signal at `0.8t` you'll end up sleeping `1.8t` total).

Aside from those, though, that logic looks identical to me; I'll change the code to look like that unless @Tryneus objects.

**Comment by mlucy** [comment]
@nviennot -- I updated the branch.

@Tryneus -- I put up a new review.

**Comment by nviennot** [comment]
> I think that switching to checking is_open() instead of !@waiters.has_key?(token) && !@data.has_key?(token) doesn't work

I'm not sure I follow.

To deal with the reconnecting issue, you could implement Connection to be a thin wrapper around InternalConnection. When you reconnect, you instantiate a new InternalConnection, with its own pumping thread, its own @waiters and everything, and you atomically swap the @internal_connection reference to that new internal_connection object. This way, the old stuff still operate on the dead internal connection state, which avoid difficult synchronization issues.
A piece of code might be clearer:

```ruby
class Connection
  class InternalConnection
    # old connection code
    # manages its own thread, etc.
  end

  attr_accessor :internal_connection
  def connect(*args)
    @connection_args = args
    spawn_connection
  end

  def reconnect
    spawn_connection
  end

  def spawn_connection
    @internal_connection = InternalConnection.new(@connection_args)
  end

  delegate :run, :register_query, :use, ... :to => :internal_connection
  # delegate is from active support, but you get the idea
end
```

**Comment by nviennot** [comment]
I've looked at your changes, loosk good :+1: .

You can remove `res = nil` at the top.

Also, minor personal style preference: I'd write  `end_time = timeout ? Time.now.to_f + timeout : nil` like so: `end_time = Time.now.to_f + timeout if timeout` which has the same semantics.

**Comment by mlucy** [comment]
@nviennot -- yeah, moving to a separate internal connection might be a better way to do things.  Honestly the whole driver could stand to be refactored at some point (especially the pretty-printing).

Thanks for catching the `res = nil` thing, missed that.

**Comment by nviennot** [comment]
I agree, but I didn't want to say it to avoid being negative and hurt some feelings unnecessarily.
I'd be happy to pair with you on the refactoring. I'll have time in June after I'm done with my phd (yay! finally!)

**Comment by mlucy** [comment]
Thanks for the offer!  We should definitely check in with each other around then and see whether it makes sense.  I haven't refactored it yet because I've been too busy with server work, but if there's a lull in the changefeed stuff in June it would be pretty useful to take a week or two and whip it into shape.

**Comment by nviennot** [comment]
great!
might as well think about the connection pool. but I'm not sure how that relates to other drivers.

**Comment by mlucy** [comment]
This is in 2.0.x and next.
