### ISSUE TITLE
Integrate SSH into client driver

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#4074]
As originally proposed (obliquely) in https://github.com/rethinkdb/rethinkdb/issues/266#issuecomment-18477141

As long as SSH tunneling is the official way to secure RethinkDB traffic ([and the only supported interface to RethinkDB by Compose](https://blog.compose.io/tunneling-from-heroku-to-compose-rethinkdb/)), it should be a feature of the client driver to handle connecting to the remote through an SSH tunnel (if the options to r.connect include a `privateKey` and `username`).

In the JS driver, this could be handled with the [ssh2](https://github.com/mscdex/ssh2) module - I don't know about Python or Ruby, but it sounds like they have analogous native-SSH modules such functionality could be built upon.

Also, this is unrelated, but while we're on the subject of SSH-as-mechanism in RethinkDB, I should probably add `sshd` (and maybe `iptables` although the Docker bridge already handles 50% of what you'd use `iptables` for) to the official RethinkDB Docker images, y/n?

**Comment by danielmewes** [comment]
Hi @stuartpb, thanks for the suggestion.

I think we will use SSL for this instead of SSH. We still have to figure out how to do proper client-authentication with SSL, but I think it's the better choice for this. At least in my experience SSH has a pretty slow connection setup, which would be a problem for client connections.

Actually @jipperinbham from Compose has just submitted a pull request to allow the Ruby driver to connect over SSL (not SSH) https://github.com/rethinkdb/rethinkdb/pull/4075 . I hear he's working on support for other drivers as well.

With SSL coming to our drivers, another option you could consider for the Docker image is https://www.stunnel.org/index.html .

**Comment by joaojeronimo** [comment]
@danielmewes Why deal with authentication over SSL ? Why not just do it with the `authKey` ? IMHO SSL should be there just for encryption. Do you meant certificate chain validation on the client ?

Sidenote: If in the future you guys come up with user accounts and an ACL, since the protocol accepts an arbitrary string for the authKey, you could send something like the Authorization http header (Authorization method + ' ' + base64encode(username + ':' + password))

**Comment by danielmewes** [comment]
@joaojeronimo Using the auth key will work in many cases, but we haven't written the connection logic with public access in mind. Hence there might be some vulnerabilities for DoS attacks or other issues there. With SSL client authentication, we could rely on the SSL proxy to take care of these issues for us until we have gotten around to thoroughly test and audit the relevant code paths.
I think SSL + auth key will be good though as long as there's an additional firewall.

**Comment by joaojeronimo** [comment]
Understood, so the clients will have to supply an SSL certificate too ? Are you talking about mutual authentication ? And when you mean rely on a proxy do you mean something like use [stunnel for mutual authentication](http://blog.siphos.be/2012/12/using-stunnel-for-mutual-authentication/) or equivalent ?

**Comment by stuartpb** [comment]
> @danielmewes Why deal with authentication over SSL ? Why not just do it with the authKey ? IMHO SSL should be there just for encryption.

I agree with this.

> @joaojeronimo Using the auth key will work in many cases, but we haven't written the connection logic with public access in mind. Hence there might be some vulnerabilities for DoS attacks or other issues there. With SSL client authentication, we could rely on the SSL proxy to take care of these issues for us until we have gotten around to thoroughly test and audit the relevant code paths.

On the subject of public-hardness, my general opinion is that the primary use case for client encryption is still privacy within a shared datacenter like EC2, where there may be large-scale malicious (read: NSA) *listeners*, but not *actors*. For both perf and privacy reasons, it's still not a good idea to span the Internet for backing store connections. (As far as non-client connections like clustering are concerned, you should probably have some kind of persistent encrypted VPN bridge for your inter-datacenter communications, or even a direct hard link in the big players' case).

From the angle of DoS resilience, I would expect that an in-datacenter DoS attack on something like EC2 would be detected and shut down fairly quickly by the hypervisor (or, at worst, a technician, shortly after receiving a page about degredated service reports). If you're spanning untrusted public networks, it's up to you to come up with some other DoS mitigation strategy (beyond just *not advertising the location of your datastore*), like SSH tunneling, as part of your platform.

Besides, even *with* an authentication step around the connection, would that *really* add protection against a sheer SYN-flood DDoS? The way you fight distributed denial of service with a distributed database is to *distribute back*: when 100 attackers have to attack 100 nodes, the end effect comes back down to a measly one-on-one DoS. (This is likely why you never see Amazon slow down under fire.)

> I think SSL + auth key will be good though as long as there's an additional firewall.

This is pretty much what I'm trying to say: everything about the current design is either good enough that adding SSL authentication wouldn't help, or inherently vulnerable in a way that SSL authentication *couldn't* help. HTTPS worked by just adding SSL on top of basic authentication schemes, *and HTTPS is doing just fine*.

The only real potential vulnerability that I know of in server implementations of basic auth under HTTPS, in terms of mass attacks by bad actors (which, like in-datacenter DDoS, is something 90% of installations will not have to worry about), is [timing attacks](http://en.wikipedia.org/wiki/Timing_attack), and those can be fixed by doing a constant-time comparison of the authKey.

**Comment by neumino** [comment]
I got the pull request https://github.com/neumino/rethinkdbdash/pull/69#issuecomment-94568676, which is similar than https://github.com/rethinkdb/rethinkdb/pull/4080 and the two others.

It feels wrong to me to have the driver connect to something that is not a RethinkDB server for a few reasons:
- If someone just look at the signature of `connect`, they will think that RethinkDB natively support SSL and they will hit an error when they will try to connect
- The proxy is one more thing in the network chain that may fail and result in undefined behaviors. I've seen pretty weird thing when I was connecting to RethinkDB via a SSH tunnel (though it's not exactly the same as using the `tls` module).


I haven't looked at the Python and Ruby pull request, but for the JS one, the proposed implementation uses `readFileSync`, which is pretty bad since it will block your whole node.js server the time to load the certificate. The current implementation also load the certificate for every connection making the connection not light anymore. I believe that's overall a pretty big hit in term of performance (though it's possible to fix it by caching the certificate).

Shouldn't the server support encryption before updating the driver?

**Comment by danielmewes** [comment]
@stuartpb Thanks for your feedback, I agree with what you say about the scenario of running in an EC2 semi-private network.
What I meant by vulnerability to DoS and possibly other attacks is that the RethinkDB connection logic isn't written to deal with malicious attackers at all. Existing SSL tunnelling software most likely *is* written with that in mind, and has been tested for years. RethinkDB might well have some vulnerability where it uses unproportionally many resources, or might even have a buffer overflow that you can attack *before* you pass through the auth key validation. So if malicious users can be dropped at the SSL/TLS tunneling server because of a bad client certificate before even reaching the RethinkDB server, that will avoid these issues.

@neumino Thanks for your feedback on `readFileSync`. I forwarded that to the pull request thread. I think loading the certificate for every connection isn't that bad because the OS will have it in its cache after the first load. Would probably be better if we could cache it in Node though.

About having SSL in the client but not in the server: I think it makes sense. Fact is that you currently have to connect to something that is not RethinkDB from the client if you need encryption. The only difference is that right now you have to setup and maintain a tunnel, which in addition to the additional tunnelling infrastructure on the server, means that you also need to maintain an additional piece on each client (e.g. an SSH tunnel which for some people have had a bad tendency of dying from time to time). With SSL support in the client, you can cut out the part on the client. You only have to setup something on the server. So I'm pretty sure it will make it more reliable than the existing solutions.
In the future I imagine we will provide documentation and/or predefined configuration files for making that very easy. Or we will put it directly into the server.

I think we can avoid the misconception that RethinkDB supports SSL without additional infrastructure by making the need for it very clear in the API documentation of `connect`.

**Comment by neumino** [comment]
@danielmewes -- You can have a server than communicate to your Haproxy/nginx server (that communicates with RethinkDB) and your driver can communicate with this new server. I believe @joaojeronimo was doing this before.

Drawback;
- It's one more thing in the network stack, so more weird behaviors
- It's more complicated to setup.

Pros:
- The driver doesn't know about SSL
- It feels cleaner to me, though that's kind of subjective

**Comment by danielmewes** [comment]
@neumino Yes I understand.
I think that even while we don't have encryption fully built in yet, we should make it as easy as possible for our users to use encrypted connections with third-party tools though. Removing the need for additional setup on the client is a significant improvement I think.

**Comment by neumino** [comment]
Fair point, it's true that it's still more friendly at the end of the day :)

**Comment by stuartpb** [comment]
Oh, if we're only saying the *client* should *support* SSL client certificates, for when ops choose to use them for authentication when putting a proxy like stunnel in front of `rethinkdb`, that's fine with me.

**Comment by danielmewes** [comment]
@stuartpb Oh I see what you meant now.

I guess we were mixing together two different questions here, and I became a bit confused. (a) the question of whether you need an external wrapper like `stunnel` on the server or have RethinkDB server SSL directly and (b) the question of whether SSL client certificates would provide additional benefits over the auth key.

So if we a) rely on stunnel, then for b) it makes sense to support a client certificate because that allows stunnel (or another similar server) to keep malicious attackers away from RethinkDB.

If on the other hand we a) build SSL into RethinkDB directly, then b) client certificates don't provide  benefit over the existing auth key anymore as you pointed out.

What I was missing was that the two questions were connected. I implicitly assumed we would have SSL in a separate process, and I think your argument applies to the case where it's built into the RethinkDB server. It makes absolute sense then.

**Comment by danielmewes** [comment]
@stuartpb Do you think SSL will work fine for you? Do you mind if I close this issue (since it's about SSH specifically)?

**Comment by stuartpb** [comment]
Since most of the conversation has pertained to integrating SSL into the client driver, I'd rather we renamed it to reflect that, or continued the discussion for client-driver-integrated SSL in a new issue (that would be higher-level than #4075 or any pull request for the JS/Python driver).

Also, is there an open issue regarding the server's SSL/TLS integration?

**Comment by danielmewes** [comment]
@stuartpb we already have such an issue. Forgot to mention it earlier. https://github.com/rethinkdb/rethinkdb/issues/3158

**Comment by joaojeronimo** [comment]
Yes I have been using TLS with RethinkDB for a while now (wrote my own TLS termination thing in Go, the reverse of tcp-to-tls), and last night I wrote [this](https://github.com/joaojeronimo/tcp-to-tls) which I intended to use on the clients, I'm so glad it won't be needed :+1:

**Comment by rclai** [comment]
So compose.io has RethinkDB hosting, which is set up only to support SSH tunneling, but we can't connect to it via the Node.js driver, therefore we can't use RethinkDB with them. What do we do?

**Comment by mglukhovsky** [comment]
@rclai: you might find [this article](https://www.compose.io/articles/connecting-to-composes-rethinkdb-deployments-with-ssh/) from Compose on setting up SSH tunnels handy.

From the machine opening the connection via the Node.js driver, you'll need to first open an SSH tunnel using the commands provided by Compose, and then open a connection to the RethinkDB server using the ports forwarded by the tunnel.

**Comment by rclai** [comment]
Oh, so under the Overview section that has those three lines of IPs, once I've set up the ssh tunnel, I would plug the `connect` statement like this?

```js
r.connect({ host: '127.0.0.2',
            port: 8080,
            db: 'marvel'
          function(err, conn) { ... })
```

And if one of those nodes fail, I would need somehow handle it to try to connect to the other ones?

**Comment by mglukhovsky** [comment]
@rclai: that's correct, since the tunnel presents a port via localhost (or in this case, 127.0.0.x). If you reach out to the Compose folks, they can probably guide you better than I can.

If a server fails, you'd have to pick a new server regardless in the current JavaScript driver, as we don't yet have connection pooling (see #281). If you need that, you might want to take a look at the alternative [rethinkdbdash](https://github.com/neumino/rethinkdbdash) driver for JavaScript that includes connection pooling and a few other nifty features.

**Comment by rclai** [comment]
Yeah, I asked them for help and told me to go find help somewhere else -_-, so that's why I'm here, but this time I actually got a solution, so I'm good now. Thanks for letting me know about rethinkdbdash.

**Comment by jipperinbham** [comment]
hi @rclai, JP@compose here,

We do typically try to point developers to the driver maintainers for questions like this but I'm very sorry if you were put off by support.

re: SSL support, once the changes [here](https://github.com/rethinkdb/rethinkdb/pull/4080) are released in the next driver version (2.2 I believe), we (compose.io) will be offering an additional way to connect to your RethinkDB database that should make things easier from a connection failover standpoint.

However, we do also recommend drivers implement some form of connection pooling/failover as it's a pretty common feature for most drivers. If I can some time soon, I will likely work to add connection pooling to the drivers maintained by RethinkDB.

**Comment by rclai** [comment]
Okay, thanks @jipperinbham. That would be cool.

**Comment by mwielbut** [comment]
hi @jipperinbham , any timeline on Compose supporting the new SSL connection options as an alternative to the SSH tunnel?

**Comment by jipperinbham** [comment]
hi @mwielbut, yes, we have some changes coming out for our RethinkDB offering within a week.
