### ISSUE TITLE
Cannot do `count()` on `r.row('name')` or `r.row('id')`

### ISSUE THREAD

**Issue by dlee** [rethinkdb/rethinkdb#4079]
I'm on RethinkDB 2.0.0.

I tried to run the following in DataExplorer
```javascript
r.table('users').filter(r.row('name').count().lt(3))
```
but I got the following error:
```
RqlRuntimeError: Cannot convert STRING to SEQUENCE in:
r.table("users").filter(r.row("name").count().lt(3))
                        ^^^^^^^^^^^^^^^^^^^^^
```

It's the same when I use "id" instead of "name".

If I change 'name' to any other value, it seems to work. An example of a working query, though identical in structure to the one above, would be:
```javascript
r.table('users').filter(r.row('posts').count().lt(3))
```

It seems as if somehow "id" and "name" are reserved in the driver when using `r.row()`, and not blocked from the server, as I have no problems inserting arrays into the `id` and `name` fields:
```javascript
r.table('users').insert([{id: [1,2,3]}, {name: [1,2,3]}])
```

**Comment by danielmewes** [comment]
Hi @dlee, the reason why this doesn't work is because the "id" and "name" fields contain a string in your case, while `count` in ReQL is only defined on arrays.
We might change this in the future (see https://github.com/rethinkdb/rethinkdb/issues/264 ), but at the moment you can use the following work-around to find out the length of a string:
```
r.table('users').filter(r.row('name').split("").count().lt(3))
```

The `split("")` splits the name string into an array of individual characters, which you can then count. Note that this can become a bit slow for large strings, but it's the best option currently available.
