### ISSUE TITLE
Feature req / think about: RethinkDB as an eventstore

### ISSUE THREAD

**Issue by gebrits** [rethinkdb/rethinkdb#4083]
Has anybody ever thought of using RethinkDB as an distributed [eventstore](http://martinfowler.com/eaaDev/EventSourcing.html)?

Basically: 

1. having a replayable log of events that update state. 
2. These changes are then pushed to anyone subscribing. 

Rethinkdb  has 2. covered with changefeeds. 

What would be needed to get 1 done properly?
 
I feel this would open up RethinkDB to a whole new set of use-cases and customers, especially since Eventsourcing/ [CQRS](http://martinfowler.com/bliki/CQRS.html) is finally getting some of the love it deserves imho.

**Comment by danielmewes** [comment]
Hi @gebrits, thank you for the suggestion.

I'm still reading up on what exactly it requires to work well as an event store, but maybe you can help me by clarifying point 1:
Are the events we would store events generated by an application? In that case I imagine they could just be stored as regular documents that you insert into a RethinkDB table. As you mention, changefeeds would then make sure that those events are distributed to all subscribers.

Or should the events be generated by RethinkDB itself, like a changelog of a given RethinkDB table that keeps track of every change that has ever been done to the data in it? In that case it sounds like it would require redirecting the output of a changefeed into another table (related: https://github.com/rethinkdb/rethinkdb/issues/3902 , https://github.com/rethinkdb/rethinkdb/issues/3367).

**Comment by gebrits** [comment]
hi @danielmewes. 

beware: braindump ahead.

Yep, events would be generated by an application. In the basis storing them in 'just' as table might work. What's different of course is that events are timestamped and always need to be returned in chronological order, nothing else. Moreover they're generally small and their payloads may differ widely. Given that, perhaps storing them in a table would: 

* give too much overhead? Events wouldn't need to have keys, which would need to sit in RAM (if I;m correct to assume to happens with RethinkDB tables)
* be not as performant as possible, since a lot of processing of course happens in indexing, etc. 

Not to say that it couldn't work, but could a potential eventstore perhaps feed of some lower RethinkDb construct? I.e.: the write-ahead log? In essence the write-ahead log itself (were it to store events) would by definition keep the ordered structure of events. Updating subscribers would 'simply' be replaying the write-ahead log (sequential data access etc.) Of course it's not as simple as that, but I'm just braindumping here. 

As for the changefeeds, I believe I've read somewhere (an open issue?) that it may soon be possible to replay changefeeds? How would this work, could we, say, replay starting from a specific timestamp?

**Comment by danielmewes** [comment]
@gebrits thanks, that makes sense.

As things are now, one would probably create a secondary index over the timestamp, or use the timestamp as the primary key directly.
Keys do not need to sit in RAM, but they are stored with each document of course and do increase storage overhead. However if you use the timestamp as the primary key, that would avoid that overhead because it's a piece of information that you need to store anyway.
Two things have to be considered when using the timestamps as primary keys:
- the timestamps have to be unique. I imagine that this is already the case in this application because the events need to be ordered.
- Since our sharding is based on key ranges, the shards will become unbalanced over time since new events will always be inserted at the end of the timestamp range. The table would need an occasional `rebalance()` to work around that (currently this makes the table unavailable for a moment, but that will change with RethinkDB 2.2). On a single server this isn't a problem of course.

RethinkDB doesn't really use a write-ahead log. Its data format itself is based on append-only principles, but it currently doesn't keep a proper history (old data is garbage collected, and multiple changes might be written together). Changing that would be pretty complicated.

I think if you need every bit of efficiency, I imagine there are more efficient specialized systems out there. RethinkDB should work well enough in other cases.

About changefeeds: Yes, in fact we're currently discussing which API and guarantees we should provide in https://github.com/rethinkdb/rethinkdb/issues/3471 (it's a pretty long thread, no need to read it unless you're interested).
One thing which we will probably support eventually is indeed to resume from an arbitrary past timestamp. This sounds like it would require us to store every change in a log, but we would be making some compromises:
- multiple changes to the same document/key will be squashed together: if at some point the document `{id: x, value: "a"}` was changed to {id: x, value: "b"} and then later to {id: x, value: "c"}, we would *not* replay the intermediate change, but instead just say that the document with ID `x` has been set to {id: x, value: "c"}.
- occasionally we will lose pieces of history, and we will resend documents that had not actually changed.

The implementation would build on the infrastructure which we currently use for backfilling from one replica of a table to another. It uses timestamps internally, but makes the mentioned compromises to avoid storage overhead. It's designed to bring an outdated copy of a table (or a part of a table) back up to its current state with a reasonably small amount of traffic.

Since it can lose parts of the history, I don't think that feature really helps with the case where you want to store arbitrary events, does it?

**Comment by gebrits** [comment]
@danielmewes Thanks for the thoughts put into this. 

Using a table might work with timestamps as key, might give that a go. 

Yeah, squashing changes would indeed make the replay unusable to function as an eventstore: I'd need every event to be replayed, not just the endresult; that's the premise of using an eventstore in the first place. 

Thanks for clarifying!

**Comment by danielmewes** [comment]
I'm going to close the issue. Our current features are enough to use RethinkDB for this, and I don't think we'll be able to add specialized support / optimizations for this application any time soon.

**Comment by gebrits** [comment]
Cheers @danielmewes. I agree

**Comment by wmertens** [comment]
For future interested readers: [This is a great explanation of events-first app data](http://blog.confluent.io/2015/03/04/turning-the-database-inside-out-with-apache-samza/) (AKA event sourcing).

Basically you need a strictly ordered event log and then calculate the application data from that log, storing it into a database of choice.

I think RethinkDB could be used for this but indeed using timestamps as primary or secondary keys has some tradeoffs. The derived data could also be stored in RethinkDB, and change feeds would make it all great.

Certainly a nicer solution than having multiple database products to maintain, and it seems like this would  easily scale from a single host to many? For a small app, using generated keys and a secondary timestamp index looks like the correct choice.

**Comment by wmertens** [comment]
hmm I just found out that change feeds do not guarantee delivery : "Since changefeeds are unidirectional with no acknowledgement returned from clients, they cannot guarantee delivery. If you need real-time updating with delivery guarantees, consider using a model that distributes to the clients through a message broker such as RabbitMQ."

So the event sourcing use case is not a good fit for rethinkdb :cry:.

**Comment by gebrits** [comment]
@wmertens: "... Cannon guarentee delivery".  I may be wrong, but i believe this will be circumventable when 'changefeed resume' lands. 

This will effectively give a consumer the option to signal from which timestamp it wants to start consuming / is done consuming.

This feels more akin to pull-based consumers ala Kafka.

@danielmewes: care to chime in if this is correct?

**Comment by danielmewes** [comment]
@gebrits Yes that's true. Once we have the full version of https://github.com/rethinkdb/rethinkdb/issues/3471, "at least once" delivery is going to be possible (with the limitation that multiple changes on the same document might get merged into a single event).

Note that the solution that we currently settled on in #3471 is not sufficient for this though, since it doesn't work if a server goes down or a table is reconfigured. We're planning a more sophisticated solution for later, but there's no ETA on that yet.

**Comment by gebrits** [comment]
cheers @danielmewes . 

> We're planning a more sophisticated solution for later, but there's no ETA on that yet.

Is there a specific issue to track for this or just watch #3471 ?

**Comment by danielmewes** [comment]
@gebrits Currently there's just https://github.com/rethinkdb/rethinkdb/issues/3471 . We will open a follow up issue eventually, once we have the initial implementation in place. We'll mention it in https://github.com/rethinkdb/rethinkdb/issues/3471 , so if you just follow that issue you shouldn't be missing anything.

**Comment by pavetok** [comment]
> with the limitation that multiple changes on the same document might get merged into a single event

It seems Kafka has similar feature: [compaction](https://cwiki.apache.org/confluence/display/KAFKA/Log+Compaction).

**Comment by pouledodue** [comment]
would it be resistant to clock drifts?
