### ISSUE TITLE
skewed document distribution in sharded cluster

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#4085]
So I sharded a table when i created the table and using r.uuid() to make doc ids. I am finding docs not being located evenly. The only thing i can say that could be odd is uuid is being made on rethinkdb 1.15x and cluster getting writes is 2.0

![doc locations](http://i58.tinypic.com/2rhbqlz.png)

**Comment by timmaxw** [comment]
The document distribution estimates are really unreliable. I'd guess that the documents are actually distributed evenly between the shards, and the graph is just wrong.

Can you paste the output of `r.db("rethinkdb").table("_debug_table_status")`? That will tell us the actual shard boundaries that were chosen, and we can use that to find out more.

**Comment by wojons** [comment]
https://gist.github.com/wojons/55b0e1d74ff032a8ca49

**Comment by timmaxw** [comment]
The approximate locations of your shard split points are as follows: `["53\x1f"]`, `["8d\xa0"]`, `["ae4"]`, `["c\xe2i"]`. You can measure the number of documents in each shard by running e.g. `r.table("8cc37b90_436c_4f77_ba81_f02b9491db20_metrics").between(["53\x1f"], ["8d\xa0"]).count()`. Could you do that for each shard and report back? We can compare the results of those queries against the results given in the graph to figure out of the table is actually unbalanced or not.

Also, I noticed that your primary keys are arrays. What are the elements of each array and how are they generated? Is it possible that the distribution of data has changed since you sharded your table?

**Comment by wojons** [comment]
r.db('et_metrics').table("8cc37b90_436c_4f77_ba81_f02b9491db20_metrics").between(["53\x1f"], ["8d\xa0"]).count()
560633

r.db('et_metrics').table("8cc37b90_436c_4f77_ba81_f02b9491db20_metrics").between(["8d\xa0"], ["ae4"]).count()
310566

r.db('et_metrics').table("8cc37b90_436c_4f77_ba81_f02b9491db20_metrics").between(["ae4"], ["c\xe2i"]).count()
328156

**Comment by wojons** [comment]
i dont know how to do -inf to  53\x1f  and cxe2i to +inf

**Comment by timmaxw** [comment]
As of RethinkDB 2.0, you can do `.between(r.minval, ["53\x1f"])` and `.between(["c\xe2i"], r.maxval)`.

In any case, it's clear that the shards are actually misbalanced; it's not just an error in the graph. I'd guess that the distribution of the data has changed since you sharded your table. RethinkDB won't automatically choose new shard boundaries unless you increase the number of shards. So if you sharded the table early on, but then inserted more data in a way that wasn't evenly distributed across the existing shards, you could get the situation you're seeing.

You can run the `r.table(...).rebalance()` command to force RethinkDB to pick new evenly-distributed shard boundaries, but you'll lose availability until RethinkDB finishes copying the data.

**Comment by wojons** [comment]
Yeah i am aware of that i was thinking that maybe there should be something that should help with picking some of these ranges early on / making it so reblaancing does not knock the table out all the time because when building an app thats running and the shard distbution is keep changing andyou need to rebalance it can disrubt the customers.

**Comment by timmaxw** [comment]
When the auto-failover changes land (probably RethinkDB 2.2) then RethinkDB will no longer lose availability during a rebalance.

Until then, I don't think there's much more we can do for this issue.

**Comment by wojons** [comment]
Thanks @timmaxw can you expalin how auto fail over will help with this case.

**Comment by timmaxw** [comment]
When we implemented auto-failover, we rewrote some of the clustering logic, and a side-effect of that rewrite is that RethinkDB will remain available during a rebalance. Previously, the previous primary for the shard would shut down as soon as the rebalance began, but the new primary wouldn't come up until the rebalance was finished. But under the new auto-failover logic, the old primary will stay up until the new primary is ready to take over.

**Comment by wojons** [comment]
so ur what ur saying is that the secondraies will be hammered during this process

**Comment by danielmewes** [comment]
@wojons Queries will still be routed to the primary while rebalancing in the new system. The old primary will stay the active primary, and gradually "hand over" parts of its shard range to the new one.
So it won't really hammer the secondaries any more than usual. Hope I understood what you meant.

**Comment by rchukka** [comment]
r.tableCreate("test");
    r.table("test").reconfigure({replicas: 1, shards: 1});
    r.range(1500).forEach(function(i) { return r.table("test").insert({id: i, a: 1,b: 1,c: 1,d: 1,e: 1,f: 1,g: 1,h: 1, arr: [  45, 6, 8, 10]}, {durability: "soft"}); });
    r.table("test").reconfigure({replicas: 2, shards: 2});

then run below query...

    r.range(1500, 3000).forEach(function(i) { return r.table("test").insert({id: i, a: 1,b: 1,c: 1,d: 1,e: 1,f: 1,g: 1,h: 1, arr: [ 45, 6, 8, 10]}, {durability: "soft"}); });

all the documents seemed to go into second shard. This is on RethinkDB 2.0. Above code was copied from earlier issues.

![rdb_unbalanced](https://cloud.githubusercontent.com/assets/1387753/7280362/c818af4a-e8e7-11e4-8b63-56aed1580e99.png)

**Comment by danielmewes** [comment]
@rchukka This is expected behavior, since RethinkDB uses range-based shards on the primary key.
In your example, RethinkDB will see that all documents are in the key range 0 to 1499 when you run the `r.table("test").reconfigure({replicas: 2, shards: 2})`.

To create to balanced shards, it will split the shards so that everything below (approximately) 750 will go into the first shard, and everything above it will go into the second shard.
Then when you insert more documents with keys from 1500 to 2999, they will all end up in the second shard.

To make your shards balanced again, you can run
`r.table("test").rebalance()`

This will shift the split point between the shards to make them approximately the same size again.
Not that at the moment rebalancing make the table unavailable while it is shifting the data between the shards. We're already working on changing that, but it will take until version 2.2 for this to ship (it's part of a bigger change, and we want to do enough testing before putting it out).

**Comment by adamkdean** [comment]
@danielmewes thanks for the above post, that really helped us out today, but I have a question. When we insert say, 1m rows, we get them all sticking on one shard as you stated above should happen, but when we insert smaller batches of say, 200, they seem to balance out. Why would this be?
