### ISSUE TITLE
Max results per query not observed when using orderBy() in Data Explorer

### ISSUE THREAD

**Issue by jezzball** [rethinkdb/rethinkdb#4115]
Hi there,

On RethinkDB 2.0.1 using the official EL6 RPM packages.

If I dump a table's contents in Data Explorer using:
r.db('test').table('test')

Data Explorer returns the first 40 rows as expected (Executed in 619ms. 40 rows returned, 40 displayed, more available).

If I run the same query including orderBy():
r.db('test').table('test').orderBy('id')

Data Explorer returns all rows, the 40 row max results is not observed (Executed in 17.68s. 2976 rows returned).

Also, the nice formatting in the tree view of the results is missing (collapsable groups etc) when orderBy() is used, even when followed by .limit().

**Comment by coffeemug** [comment]
@jezzball -- thanks for reporting this, but this is done by design.

When you run `r.table('test')` the database returns a stream of data (it would be a cursor to your drivers). Cursors are pageable, so the data explorer can go through documents batch by batch.

When you call `orderBy` without specifying an index, the database has to load the whole table in memory to sort the data. When that happens, the database server returns an array of documents instead of a stream to indicate that there are different memory and performance implications involved. Arrays aren't pageable, so the data explorer presents them all at once.

To get a stream of data instead, try ordering with an index like this: `r.table('users').orderBy({index: 'id'})`. The data explorer will be able to paginate the data.

The reason you don't see the formatting is that on large arrays such complex DOM elements dramatically slow down the browsers, so we turn formatting off. If you set the limit to a smaller value (say, 40 rows), you should be able to see the formatting again.

**Comment by danielmewes** [comment]
Actually this is a regression and not intended in this form. We already have an issue open for it: https://github.com/rethinkdb/rethinkdb/issues/3912

**Comment by jezzball** [comment]
@danielmewes - apologies, I failed to spot the existing issue when searching.

@coffeemug - thanks for the detailed explanation. W.r.t. formatting on smaller result sets, I still get no formatting with:
r.db('cdrs').table('cdrs').orderBy('id').limit(10)

but I do with:
r.db('cdrs').table('cdrs').orderBy({ index: 'id' }).limit(10)

**Comment by coffeemug** [comment]
@jezzball -- ah, sorry, I was wrong about the bug (though my explanation was still correct).

Wrt to formatting, I can't seem to reproduce. I inserted 20,000 documents into the database. When I can `orderBy` without an index I get no formatting (as expected), but when I add `.limit(10)` the results are formatted.

Could you give me a better idea of how to reproduce?

Also, I opened #4116 to address some other polish issues I noticed, FYI.

**Comment by jezzball** [comment]
@coffeemug - I've managed to reproduce it with a test table of just 20 documents. As it's small enough I'm happy to send the set to you to try yourself. Can you send me your email? It is real data I would rather not post in public.

The same issue you mention in #4116 also occurs here.

**Comment by coffeemug** [comment]
@jezzball -- that would be great. Could you shoot me an e-mail to slava@rethinkdb.com? If you could e-mail me the data, the query, and preferably steps to reproduce, it would be great (as I really can't seem to reproduce it here).
