### ISSUE TITLE
Complex math functions in ReQL

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#4124]
Unless I'm mistaken (I'm not really a math guy), there's no way to do math with logarithms/exponents in an orderBy or secondary index expression right now.

**Comment by danielmewes** [comment]
@stuartpb 
You can use `r.js` as a work-around for most cases except for secondary index functions (because we cannot guarantee it's deterministic):
`table.orderBy(r.js("(function(x) { return Math.log(x.field); })"))`

I think we'll add more math functions to ReQL in the long term, though for these more complex operations we'll first need to figure out https://github.com/rethinkdb/rethinkdb/issues/3009 before we can allow using them in a secondary index.
