### ISSUE TITLE
python: dublicate key error does not raise an exception

### ISSUE THREAD

**Issue by digi604** [rethinkdb/rethinkdb#4128]
Instead i get: 

{u'first_error': u'Duplicate primary key `id`:\n{\n\t"count":\t10000,\n\t"id":\t25972098,\n\t"success":\tfalse,\n\t"time":\t{\n\t\t"$reql_type$":\t"TIME",\n\t\t"epoch_time":\t1430143377.4159998894,\n\t\t"timezone":\t"+00:00"\n\t}\n}\n{\n\t"count":\t10000,\n\t"id":\t25972098,\n\t"success":\tfalse,\n\t"time":\t{\n\t\t"$reql_type$":\t"TIME",\n\t\t"epoch_time":\t1430152072.4930000305,\n\t\t"timezone":\t"+00:00"\n\t}\n}', u'errors': 1, u'deleted': 0, u'unchanged': 0, u'skipped': 0, u'replaced': 0, u'inserted': 0}

**Comment by danielmewes** [comment]
Hi @digi604, this is by design because we want the result of a write operation to remain in the same format if you insert or change multiple documents at once.
If we threw an exception, the results of the other operations would get lost.

That being said, we have been considering adding an alternative mode that throws on the first error: https://github.com/rethinkdb/rethinkdb/issues/3440 . Please feel free to chime in over there.
