### ISSUE TITLE
BSD targets for build system

### ISSUE THREAD

**Issue by RaitoBezarius** [rethinkdb/rethinkdb#4130]
Currently, it is impossible to build RethinkDB on a *BSD machine.

I get this error: `* Error: unsupported operating system: x86_64-unknown-freebsd10.0`

I think that I can help to implement it, what is necessary in order to make it work?
Thanks!

**Comment by danielmewes** [comment]
Hi @RaitoBezarius , I think the build system is the smallest problem for making this work actually. The code itself will need some changes too (mostly things in the `src/arch` hierarchy).

@hungte made RethinkDB compile on FreeBSD a while back, and you might find his patches to be a good starting point if you want to give it another shot https://github.com/rethinkdb/rethinkdb/pull/688 . The patches will probably need a few adaptions to our current code base.
If you're on IRC,  feel free to drop by in #rethinkdb on freenode for any questions.

Unfortunately we don't have the capacity at the moment to work on a fully supported FreeBSD (or other *BSD) port.

**Comment by kgaughan** [comment]
I'm considering making a FreeBSD port. The biggest build issues with it as it stands is that the configure script doesn't take advantage of pkg-config when present (which would remove many portability issues to not only FreeBSD but many other OSs) and assumes that `make` is GNU make. There are some issues where clang will stop compilation with -Werror on too, which ought to be merged into upstream anyway.

Some of these issues appear to be fixed in @hungte's patch, but the changes could do with being generalised. Some of the changes (such as the use of pkg-config when available, and fixes for issues flagged by clang) could certainly be merged upstream, which would help with general RethinkDB portability. Others could be maintained in the port where it makes sense.

**Comment by rodomar705** [comment]
I'm trying to port this software to FreeBSD. Luckily, thanks to @hungte's patches, all the work was significantly easier, lots of define and a few reimplementations here and there. Anyway, now the codebase compiles, i'm still struggling with the assumption that make is gnu make, as said above, especially on the dependencies, some of them unfortunately require compile from sources, either way because the ports are not enough recent (for example, V8 javascript engine). As soon as i can get to fully build and test if it works, i will commit a patch, if you are interested to add FreeBSD compatibility.

**Comment by danielmewes** [comment]
@rodomar705 We'll not be able to fully test and maintain a FreeBSD port at the moment, but if you can submit a patch (set of patches) that make it compile on FreeBSD, we'll try to merge them.
