### ISSUE TITLE
limit not working for aggregate?

### ISSUE THREAD

**Issue by digi604** [rethinkdb/rethinkdb#4136]
``r.db('events').table('all_events').withFields(['lat', 'lon']).distinct().limit(100)`` will time out with some 20mil rows.

``r.db('events').table('all_events').limit(100).withFields(['lat', 'lon']).distinct()``

works but does return less then 100 results as expected.

**Comment by danielmewes** [comment]
Hi @digi604, the reason that the limit isn't applied early enough is that `distinct()` - the way it's currently implemented - works by leading all rows first, then sorting them, and then filtering duplicates.
So the full result of `distinct` is computed first, and only then is the `limit` applied.

If you can use an index for distinguishing distinct rows, you can pass that index to `distinct` and it should work as expected.

A more general question/comment:
Is this the full query? The `distinct` here won't really do anything because every row will be distinct (at least their primary key will be different). You might want to add a `without('id')` before the `distinct` to only compare the remaining document fields. Or you can use an index over the property that you want to make distinct as mentioned before.

**Comment by danielmewes** [comment]
Hmm actually looking at the API documentation for `distinct` http://rethinkdb.com/api/javascript/distinct/ I'm now unsure if my explanation was correct. It suggests that `distinct` even without an index *does* return a stream. I'm not sure if the API docs or my memory are wrong (technically there shouldn't be a reason for why it cannot return a stream).
Investigating now... (@mlucy?)

**Comment by danielmewes** [comment]
Ok both the API docs and my memory is correct, I just read the docs wrong. They say that `distinct` without an index returns a stream when applied to a table directly (is there any use in doing that?).
However when applied to a selection, that falls in the `sequence` overload and that results in an array (i.e. it will load the whole result into memory first).

**Comment by danielmewes** [comment]
@digi604 I opened https://github.com/rethinkdb/rethinkdb/issues/4138 for optimizing `distinct` without an index for scenarios like this, and https://github.com/rethinkdb/docs/issues/740 to clarify the documentation.
