### ISSUE TITLE
Windows event queue, network and disk IO

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4168]
A lot of IO code needs to be ported to run on Windows.

A possible solution is to use the [event flags](http://h71000.www7.hp.com/doc/82final/5841/5841pro_020.html#event_flag_sec) API.

**Comment by fuwaneko** [comment]
How about libuv? It could also solve threads and timers problem.

**Comment by AtnNn** [comment]
In the windows branch:

* Network IO is done using overlapped IO and IOCP
* Disk IO uses the thread pool

The IOCP implementation is not efficient because HANDLEs cannot be moved from one IOCP to another, and the current design has one IOCP per thread. An alternative would be to never rethread handles or possibly to use APC instead of IOCP.

It might be better to use overlapped IO for disk IO.

**Comment by danielmewes** [comment]
@AtnNn Hadn't you changed disk IO to overlapped IO already to avoid the seek race condition?

**Comment by AtnNn** [comment]
@danielmewes not exactly. To be able to seek and read or write atomically, I used some of the overlapped IO API, but on a blocking HANDLE.

**Comment by danielmewes** [comment]
I see. On Windows I suspect this might actually work. Though I wouldn't bother with changing this until we start looking into tuning performance on Windows, which probably won't be for a bit.

On Linux, one reason that I remember for why we switched from asynchronous disk i/o to a thread pool with synchronous i/o was that async i/o didn't work reliably. On certain file systems and block device backends (especially some network-mounted ones, like those you'd find on cloud servers), the supposedly asynchronous kernel calls would suddenly become blocking under certain circumstances. This was really bad in our case, since they were stalling the whole thread which we were also using for other operations. In retrospect I'm not sure why we didn't just move the async i/o calls into their own threads, one per file. There might have been a reason for it that I don't remember.

**Comment by danielmewes** [comment]
I'm going to close this, since the current implementation seems to be working fine. We can open new issues later if any performance issues show up.
