### ISSUE TITLE
`.changes` hint is not present in data-explorer

### ISSUE THREAD

**Issue by Slava** [rethinkdb/rethinkdb#4214]
- Open the Data Explorer in Rethink's admin panel
- Type in `r.table('cities').orderBy({index:"name"}).limit(3).`
- Observe `changes` not being present in the list of hints

Expected:

`.changes` is part of the hint box. It is a valid method that works.

**Comment by danielmewes** [comment]
Hi @Slava , thanks for opening an issue.
I can reproduce this and I think it's because the `changes` type signature in our API documentation is too strict. I'll open a new issue in the docs repository. Once we've fixed the type signature, it should work in the upcoming RethinkDB 2.1 in the Data Explorer as well.
