### ISSUE TITLE
Javascript: How to parse a reql statement?

### ISSUE THREAD

**Issue by rclai** [rethinkdb/rethinkdb#4256]
For example:

```js
var processQuery = function (expression) {
  // Try to get the table name
};
processQueryt(r.table('myTable'));
```

When I `console.log` that expression, it literally gives me `r.table('myTable')` as a string, probably because of some `.toString()` being implemented somewhere? How can I look at the properties in that object?

**Comment by deontologician** [comment]
Hi @rclai . Check out the [ast.js file in the javascript driver](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/ast.coffee#L121). If you want to see what will be sent over the wire, you can use the `.build()` method on a term.

I'm closing this issue since it isn't a bug, but feel free to ask further questions and I'll help you out.

**Comment by rclai** [comment]
Ah that's great, that method definitely helps.

**Comment by deontologician** [comment]
In general, I'd say try not to rely on the output of that function for anything except tests etc. We change the protocol often, so that representation isn't guaranteed to stay stable
