### ISSUE TITLE
What do you think about this article ?

### ISSUE THREAD

**Issue by Geocloud** [rethinkdb/rethinkdb#4282]
Hi team.

What do you think about this article ? Is it true ?
https://www.amon.cx/blog/rethinkdb-reviewed-by-a-mongo-fan/

Thank you

**Comment by coffeemug** [comment]
The benchmark numbers are completely wrong for both databases.

* The "Read/Find" section states that MongoDB performed 100,000 read operations sequentially in 0.5s. For that to be true, the average latency for each read would have to be 5 *micro*seconds, which is implausible -- there is no commodify disk that will support latency *that* low for this kind of throughput.
* The "Read/Find" section also states that RethinkDB performed 100,000 sequential unindexed read operations in 1.4 seconds. That's far too fast for us, and I think the reason is that the author forgets to add `.run()` to the query, so nothing actually gets executed. The number measures the time it takes to build the query object, not the time for the query to be executed (but that doesn't explain the impossibly fast MongoDB numbers).
* The "Updates" section states that 10 RethinkDB updates take 61 seconds and 100,000 MongoDB updates take 22 seconds (so RethinkDB is 30,000 times slower). The reason is that the code uses an indexed scan on MongoDB and an unindexed one on RethinkDB. So RethinkDB is scanning the entire table from start to finish for each update. The benchmark should use an indexed read (`.get_all(random_timestamp(), index="last_update")` instead of `.filter({"last_update": random_timestamp()})`).
* The benchmark is running the queries sequentially from a single thread, so this is basically a test of latency under no load. But the article reports throughput numbers, not latency numbers (to measure throughput one would need to run queries concurrently from multiple threads, or to use asynchronous driver functions).

The benchmarking code needs a lot of work before it can report real numbers.

Also, the article states that there is no way to get stats, which isn't true. RethinkDB provides programmatic access to stats data through the `rethinkdb.stats` system table. Documentation for stats access is on http://rethinkdb.com/docs/system-stats/.

**Comment by xquery** [comment]
excellent refutation of some silly numbers ...

**Comment by martinrusev** [comment]
I stand corrected about the lack of stats metrics. I still can't see reporting for slow queries. An amateur developer like me is going to miss creating an index here and there and debuging those is a nightmare without slow query logging.

Updated the Read/Find section to actually run the query, my mistake. 

In updates - the results are for 100 000, I made a typo in the code block. It has an index on 'last_update' (https://github.com/martinrusev/rethinkvsmongo-benchmark/blob/master/benchmark.py#L65)

About the benchmarks - I said in the post, that these are not "proffesionally" done and I would love to see RethinkDB support here - https://github.com/brianfrankcooper/YCSB

**Comment by morphar** [comment]
There is no shame in being a beginner or not professional - but you **NEED** to know at least some stuff, before you can compare anything.

Otherwise I could compare my soap box car with your car: my soap box car is **MUCH** faster - as long as both cars are pushed uphill by a kid.

You can not compare a query on an indexed dataset in one db with a non indexed dataset in another db.

Benchmarking is extremely hard to do - even more so, when you don't have enough knowledge.

E.g. what is the insurance of the data actually being written to disk?
MongoDB has a lot of ways to respond to an insert - the most loose will respond back, as soon as the software layer has received your request.
That is NO guarantee that it will actually end up on your disk.

Another problem is the data load you create - sure you might be able to insert 100.000 docs in x secs.
But how does that look in a "real" applications with 20+ connections and 100.000 updates, read and deletes going on at the same time?

What about bulk queries?

**Comment by martinrusev** [comment]
Hi @morphar 

One lesson I learned from this experiment - put all the code from your experiments in the blog post, not in Github repository were most people are going to miss it anyway(https://github.com/martinrusev/rethinkvsmongo-benchmark/blob/master/benchmark.py)

All the queries I make are on indexed fields. The one difference between Mongo and Rethink here is that with Mongo I do: 

`mongo_collection.ensure_index([('last_update', pymongo.DESCENDING)], background=True)`

and in RethinkDB I only have the create_index function and then not sure when it updates the index?

If you have a "real" application - you will benchmark and optimize your db specifically for your use case - some people have a lot of reads, some updates and someone like me - mostly inserts. 

Bulk queries are another very specific topic - you can bulk insert a data from a crawler for example, but  it is rare to have those in a user facing applications for example.

A valid argument about the data actually been written on the disk by the time the benchmark finishes. Mongo has journaling which ensures that it will eventually be written, but it is asynchronous, so it could be later. (This has been the default behavior since 2012 http://emptysqua.re/blog/pymongos-new-default-safe-writes/)

In Rethink we have durability=soft|hard options for the same functionality, so to compare those results - Mongo is comparable to RethinkDB with durability=soft. I will updated my code to include the real numbers - when all the 100 00 documents are actually written to the disk.

**Comment by morphar** [comment]
Hi @martinrusev 

That's the thing... You still don't know, if it has actually been written - there are still possibility for errors, conflicts and disk errors:
http://hackingdistributed.com/2013/01/29/mongo-ft/
It seems MongoDB has NO way of responding only when the disk write has been confirmed.

It's an old article though, so maybe it has been fixed...
WiredTiger is probably a VERY different engine than the one in earlier versions than 3.
I tried a http://www.tokutek.com/tokumx-for-mongodb/ at one point, which was the fastest engine I have yet tried for handling billions of documents on a single (very large) server.

Anyway - my experience with MongoDB is that the indexes *can* be extremely slow to update under load.

MongoDB has a query threshold for when it will start updating the indexes.
So if you insert 100k docs and try to find right after, it can be extremely fast - or extremely slow if you depend on the index, when running indexing in the background.

That alone can interfere extremely with benchmarking (and real apps of course ;)

By the way, I'm not more for or against any of the DBs - I only have experience with MongoDB and currently we are moving our data from MongoDB to PostgreSQL.

Just a final note: I believe that your numbers are pointing in the right direction - I just think we should be really careful with benchmarks.
The can tell so many things and risks leaving out some of the most important things when it comes to decision making.

E.g. what is the "cost" of joins in RethinkDB vs none in MongoDB.
If I need to "join" my data, how much will it cost to do in code with MongoDB vs having joins in RethinkDB.

Our reason for returning to PostgreSQL is that after our application has matured, we have settled more and more on a predefined structure, which we rely on being so.
That means we have effectively created schemas and joins in the code.

We could probably have chosen RethinkDB and gained some speed, but are choosing to go with the "safe" choice ;)

Enough ranting from me.

**Comment by deontologician** [comment]
> and in RethinkDB I only have the create_index function and then not sure when it updates the index?

You can use [index_wait](http://rethinkdb.com/api/python/index_wait/) for this. It returns only when the index is done building

**Comment by coffeemug** [comment]
@martinrusev -- I might have been too edgy in my response above, I'm sorry if my tone was tetchy. Temperatures can run a little high when benchmarking is involved  :smile:

**Comment by timmaxw** [comment]
@martinrusev: RethinkDB won't use an index unless you explicitly specify it in your query, even if there exists an index on that field. So `.filter({"last_update": ...})` will not use the index on `last_update` even though the index exists. You need to instead do `.get_all(..., index="last_update")`. This affects both your Read and Update benchmarks.

There's something else strange going on as well. You're reporting that RethinkDB does 100,000 updates with `.filter()` in 60 seconds, which is completely implausible; RethinkDB cannot scan 100,000 non-indexed documents in only 600 microseconds. There's a similar problem with the read benchmark.

**Comment by mollice** [comment]
Hello, 
In order to make sure that I'm not repeating the same mistake with the non-used index here, I suppose I need _get_all_ only in the case of secondary indexes, right? I am benchmarking RethinkDB with YCSB (https://github.com/rethinkdb/YCSB) and I am using the Client .java as it is (so with _get_, not _getAll_ in reads and updates).. I have a sharded cluster so I know an index has been created with the primary key of my collection. Is this index used correctly? Can someone please confirm?

**Comment by chrisvariety** [comment]
@mollice `get` queries are automatically indexed with the primary key.

**Comment by mollice** [comment]
Thank you! So, with this out of the way, can someone please comment on #6132 ?
