### ISSUE TITLE
How can I check, how much disk storage used by any table in rethinkdb

### ISSUE THREAD

**Issue by hsen-dev** [rethinkdb/rethinkdb#4295]
I need to report/warn to my customer about disk usage of any data structure. How can I do this.
or is it possible to limit storage usage for any table in any clusters?

**Comment by deontologician** [comment]
Hi @hsen-dev , you can check the 'stats' system table to find out how much disk space a replica is using: http://rethinkdb.com/docs/system-stats/#replica-tableserver-pair

The way you'd do it in reql is like this:

```js
r.db('rethinkdb').table('stats')
    .get(['table_server', tableId, serverId])('storage_engine')('disk')('space_usage')
```

This will return a document with what you're looking for. Since it's just accessed with ReQL, you can get the total bytes for a server with:

```js
r.db('rethinkdb').table('stats')
  .filter(function(row){
      return row('id')(0).eq('table_server').and(
             row('id')(2).eq(serverId))
})('storage_engine')('disk')('space_usage')('data_bytes').sum()
```

or total bytes for a table with:

```js
r.db('rethinkdb').table('stats')
  .filter(function(row){
      return row('id')(0).eq('table_server').and(
             row('id')(1).eq(tableId))
})('storage_engine')('disk')('space_usage')('data_bytes').sum()
```

I'm closing this since it isn't a bug, but feel free to ask more questions here

**Comment by deontologician** [comment]
Also, to answer your question, it's not currently possible to limit the size of a table directly.

**Comment by hsen-dev** [comment]
Hi, an awesome answer. very tanks.
