### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [rethinkdb/rethinkdb#4297]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/rethinkdb/rethinkdb/blob/5da1da6764fb94d4281b16e1546c2420ddf03d02/src/main.cc#L10 "main function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "stack unwinding") like they are described by Danny Kalev?

**Comment by AtnNn** [comment]
The RethinkDB code runs in many separate threads and coroutines. If an exception was accidentally left uncaught, in most cases it would not bubble up to `main`.

Instead, the C++ RTS would call [`terminate`](http://en.cppreference.com/w/cpp/error/terminate), which RethinkDB handles here:

https://github.com/rethinkdb/rethinkdb/blob/27180d45218c71f280493f7f1bf4f80c1b5acf96/src/errors.cc#L148

**Comment by elfring** [comment]
Do you expect more from your "C++ run time system" eventually than what will be provided by a specific compiler implementation?
Would you like to reuse [catch-all handlers](http://en.cppreference.com/w/cpp/language/try_catch "Catching of C++ exceptions") at more source code places?

**Comment by mlucy** [comment]
@elfring -- I'm a little confused by your question.  My understanding of the C++ standard is that a terminate handler is called whenever exception handling has to be aborted, e.g. because there is no catch handler available.  So we aren't depending on a particular compiler implementation, and there are theoretically other situations where the terminate handler could be called that we would want to handle even if we explicitly caught exceptions at the top of all coroutines.

**Comment by elfring** [comment]
Do you care if [appropriate stack-unwinding](https://www.securecoding.cert.org/confluence/display/cplusplus/ERR51-CPP.+Handle+all+exceptions "Handle all exceptions.") will happen for your software after a thrown C++ exception?

**Comment by mlucy** [comment]
@elfring -- there are many situations where `std::terminate` will be called.  One is an exception thrown without an appropriate exception handler, but it will also be called if you throw an exception in a destructor while another exception is active, or if if you throw an exception that violates a `noexcept` specification.  (All three of those are logic errors, obviously, and will only occur if there's a bug in RethinkDB, which unfortunately is a reality you have to deal with.)

Since we don't want RethinkDB to behave poorly in the event of a logic error (an example of behaving poorly would be losing data), we have to code in such a way that `std::terminate()` behaves safely.  Specifically, we can't assume that stack unwinding occurs.

In practice, we would usually prefer that stack unwinding not occur because it allows us to print a better backtrace when we crash, which aids in later debugging, but it isn't essential to the correct operation of the system.

**Comment by elfring** [comment]
Are there any situations where it would be better to let destructors of remaining C++ objects perform their final work?
