### ISSUE TITLE
Distinct is very slow

### ISSUE THREAD

**Issue by Cidan** [rethinkdb/rethinkdb#4337]
When running the following query on the web UI, the request simply times out after 300 seconds:

```
r.db('test_table').table('images').distinct({index: 'tag'}).count()

```

The dataset is 9.4 million rows at about 8 gigs, all of which fits into memory. The machine is a fairly powerful EC2 box, c4.2xlarge, and all CPU cores are almost entirely idle. The dataset is sitting on an SSD.

Let me know what else I can provide. Thanks.

**Comment by thelinuxlich** [comment]
Indeed, this and count() are the biggest flaws of RethinkDB for me, at the moment

**Comment by danielmewes** [comment]
Thanks for the report @Cidan , and sorry you're running into this.

Since the data should fit into memory, the first thing to check is the cache size that RethinkDB is using. If you go to the web UI and click on the "Logs" tab, there should be a message in there saying something like "Automatically using cache size of ... MB ". Can you let me know what that value is?

There's another optimization specific to indexed `distinct` which we are not currently doing but probably should do at some point, which is that (I believe) we currently always read the full document to compute the secondary index value, even if we could actually extract it from the index directly without needing to load the full data.
I talked about a similar case with @ha1331, and I'm going to open a separate issue for that optimization later.

**Comment by danielmewes** [comment]
No response from @Cidan about the cache size in a while. Closing for now, but feel free to re-open.

The indexes `distinct` optimization I mentioned is being tracked in https://github.com/rethinkdb/rethinkdb/issues/4342 .
