### ISSUE TITLE
indexCreate geo fails with [column]

### ISSUE THREAD

**Issue by donpdonp** [rethinkdb/rethinkdb#4351]
I have some code that creates an index based on an array of field names. This may be more of a misunderstanding than a bug, but when the index is created at (name, [column], { opts }), geospacial queries fail. The same index created as (name, column, { opts }) works. Is this expected behaviour? 

```javascript
r.db('geowtf').table('fences').indexCreate('geojson',[r.row('geojson')], {geo:true})
r.db('geowtf').table('fences').getIntersecting(r.point(-122.5,45.5), {index:'geojson'})
no rows returned
```

## Huge polygon for testing
```javascript
r.db('geowtf').table('fences').insert({
    "created_at": "Fri Jun 05 2015 00:07:11 GMT+00:00" ,
    "geojson": {
        "$reql_type$": "GEOMETRY" ,
        "coordinates": [
            [
                [
                    -151.5234375 ,
                    74.3863994649695
                ] ,
                [
                    -23.203125 ,
                    68.50677624352112
                ] ,
                [
                    -14.765625 ,
                    -14.66154202536376
                ] ,
                [
                    -153.28125 ,
                    -7.071821357259741
                ] ,
                [
                    -151.5234375 ,
                    74.3863994649695
                ]
            ]
        ] ,
        "type": "Polygon"
    } ,
    "id": "7f9a44db-abd6-4d49" ,
    "name": "World" ,
    "user_id": "f4e347fe-16b6-4199-b3bb-93b576088a2e"
})
```

**Comment by thejsj** [comment]
I think all you need to do is make that index into a multi index. You can easily do that by passing the `multi` flag to the `indexCreate` function:

```
r.db('geowtf').table('fences').indexCreate('geojson',[r.row('geojson')], {geo:true, multi: true})
```

[http://rethinkdb.com/api/javascript/index_create/](http://rethinkdb.com/api/javascript/index_create/)

[http://rethinkdb.com/docs/secondary-indexes/javascript/#multi-indexes](http://rethinkdb.com/docs/secondary-indexes/javascript/#multi-indexes)

**Comment by danielmewes** [comment]
To explain why this doesn't work:
The expression `[r.row('geojson')]` generates an array with a single element. The single element is a geometry object, but the array itself is not. So the geo index ignores it, since it can only index geometry objects.
Like @thejsj said you can use a multi index if you need to index multiple geometry objects per document (in that case the index expression has to be an array of geometry objects). Or if you only have a single geometry in your object as seems to be the case here, the normal
`r.db('geowtf').table('fences').indexCreate('geojson', r.row('geojson'), {geo:true})`
will do the job, or even easier in this case:
`r.db('geowtf').table('fences').indexCreate('geojson', {geo:true})`
(since the field name is the same as the index name, it will be deduced automatically in that case).

**Comment by donpdonp** [comment]
thanks for the detail. the subtlety I'm questioning is, is a one-element compound index the same as a simple index? I made a little index builder helper where the index fields are specified to a function as an array. For a non-geo index a one element array appears to be equivalent to the simple index, which is why the geo exception was surprising.

**Comment by danielmewes** [comment]
@donpdonp A compound index in RethinkDB is actually just an index with arrays as its values. We currently don't support compound geospatial indexes.
