### ISSUE TITLE
Specifying Shard Key

### ISSUE THREAD

**Issue by neilunadkat** [rethinkdb/rethinkdb#4379]
I have been having a look at these issues (#364, #4237 ) which talk about configurable sharding. 
For range based sharding is it possible for me to provide compound sharding keys ?
Something like what mongo does (http://docs.mongodb.org/manual/tutorial/choose-a-shard-key/#shard-using-a-compound-shard-key)
Basically I shall be storing time series data collected from sensors. 
And the consumption is see is mostly about data between some time. 
So if I could use the sensor id + timestamp as the sharding key, then it would help in balancing the shard I guess.

**Comment by deontologician** [comment]
Hi @neilunadkat, you can do this by using an array for the primary key:

```json
{
   "id": [sensor_id, timestamp],
   ...
}
```

However, this could make the data significantly less well distributed across your shards if some sensors put out a lot more data than others. You can periodically rebalance the table (`r.table('foo').rebalance()`) to ameliorate this, but you'd want to make sure it's worth the trouble before going with this scheme.

Specifically, you should profile `.between` queries (on a decently sized cluster) with both the default uuid key and the compound key. I would imagine if it all ends up on the same shard (as is likely) you'll get the faster reads you're hoping for, but the performance benefit may not be worth the maintenance overhead of needing to rebalance regularly.

@danielmewes may have some other insights here

**Comment by danielmewes** [comment]
Using sensor_id + timestamp sounds reasonable. That should avoid the problem that you usually have with range sharding and time series data where you frequently have to rebalance because new data is always added at the end of the key range.
Due to how RethinkDB picks shard boundaries based on the current data distribution, it will work best if the rate at which each sensor is adding new data is approximately proportional to the data that it currently has stored in the table. If this is not the case, you might still need to rebalance the table from time to time, though probably less often than when just using the timestamp as the shard key.

I don't have anything else to add to @deontologician's description. Currently the shard key has to be the primary key of the documents.

Alternatively, you can consider using our default random generated IDs, and create a secondary index for the timestamp and sensor ID instead to allow for efficient queries. Since the default document IDs are picked uniformly from the UUID space, the data will always be balanced. However you will see a performance impact from the additional secondary index during inserts and other write operations.

**Comment by neilunadkat** [comment]
@deontologician @danielmewes sorry for a late reply.
My sensor id are also incremental (using a variation of the twitter snowflake algo). 
I just realised that with new devices being added, and the older ones still being out there sending the data, things might just become out of balance if I use the sensor id + timestamp.

And if I use the random generated IDs, apart from the performance impact during inserts (I doubt there will be updates, until and unless I go down the route of storing 10 min of data in one document which would help in improving reads), a read for the data for a particular sensor between a start and stop time, would go to all the shards.  
My sharding philosophy should be dependant on the way I am going to consume the data right?
Well, 90% of the time the data consumption will be a between certain time search, which will be on the latest data. This is going to be used by the algorithms, who will get certain information out of it and then store the results. And mostly, these results would be used for the algorithms ahead.
As of now I do not see this data to be consumed as is (because it would not necessarily make sense).

So based on this what route do you guys think I should follow?

**Comment by deontologician** [comment]
I think you should use random uuids, and have a secondary index for timestamp. Until #364 is implemented, that's the best way to evenly distribute your data over the cluster, and get the best performance. If you try to shard by timestamp, all your writes will end up hammering one server, and rebalancing will be sort of equivalent to archiving older data. You won't get the benefits of sharding really.

**Comment by danielmewes** [comment]
> And if I use the random generated IDs, apart from the performance impact during inserts (I doubt there will be updates, until and unless I go down the route of storing 10 min of data in one document which would help in improving reads), a read for the data for a particular sensor between a start and stop time, would go to all the shards.

With RethinkDB that's usually what you want actually. This is what allows queries to be parallelized over servers.
Inserts will also usually be faster if they cross multiple shards, because again that allows them to utilize more servers in parallel.

**Comment by neilunadkat** [comment]
@deontologician @danielmewes thanks a lot.
Will get back to you if I have any more questions.
