### ISSUE TITLE
Push responses for queries

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#4400]
Hi folks

Apologies if RethinkDB already does this or has another solution, but looking at the drivers I couldn't see one. If I've issued a changefeed query for something and the driver is waiting for results, I think this means that the driver needs to keep polling the RethinkDB server. It would be great if the RethinkDB server could push changes to the driver, rather than having to keep polling for changes.

Is this something that would be useful or possible?

**Comment by danielmewes** [comment]
Hi @danielcompton , the only reason for why you have to send CONTINUE requests to the server repeatedly is that in versions of RethinkDB before 2.0, there could only be one request running at a time per connection. To make changefeeds better usable in an interactive environment, we decided to time CONTINUE requests to a changefeed out after just 500ms so that another query could get a chance to run.

We've changed this in RethinkDB 2.0. To enable the new behavior, you have to use the `V0_4` version magic. This will have two effects:
1. The server will execute multiple requests in parallel on the same connection. For the driver that means that query responses can arrive in any order. For example if you send a query with token 1 and then send a query with token 2 without waiting for receiving the response for the first query, you might get a response for token 2 before you get the response for token 1.
2. Changefeed requests don't time out anymore.

So once you change your driver to the V0_4 protocol, the server will just send you a response with the right token whenever a change happens.
Is that what you have in mind?

**Comment by danielcompton** [comment]
Hi @danielmewes that's exactly what I had in mind. The driver I'm working on is still using `V0_3`. I knew about 1 on `V0_4`, but didn't know about 2, or its effects. That's exactly what I was looking for. Thanks!

**Comment by danielmewes** [comment]
One small additional note: Once the server has sent a reply for a changefeed, you still have to send a new CONTINUE query to receive subsequent changes.
Also it will send the *first* (often empty) reply quickly after opening a changefeed (this is so the client knows that it needs to create a cursor without having to wait for the first change).
