### ISSUE TITLE
Anomalies on server page

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4454]
Here's what the server page looks like for a server I just launched:

![server](https://cloud.githubusercontent.com/assets/706854/8360522/c25b15c8-1b5c-11e5-84e0-225919cc0525.png)

It would be very helpful to include the full server version (in this case `2.0.0-1-1244-g6b76ae`).

The actual uptime is about 10 seconds, but it reports 8 minutes. Also, the uptime doesn't update until the page is refreshed.

It would be nicer if the cache size was reported as *~25 GiB* instead of *25374.076171875 MB*.

In firefox, when hovering over each entry, the cursor changes into a question mark, but:
 * for the hostname and the cache size, the text that appears is "null"
 * for the uptime, something that looks like the launch time appears, but it isn't styled.
 * for tags, the styled infobox appears, but it isn't aligned the same as the version infobox.
 * for the version, here is both "null" and an infobox with a confusing error message appears

![server2](https://cloud.githubusercontent.com/assets/706854/8361053/4c0ec49c-1b60-11e5-9a4b-36f27d6be523.png)

**Comment by danielmewes** [comment]
Fully agree that we need to round the cache size. If not to GB, at least to full MB. I think this is actually release critical (I guess we didn't catch this because if you specify it manually it will always be exact MB).

I think we should keep the version as it is on this page. @AtnNn do you want the full version here for making support easier or for other reasons as well? Are there actually cases where the remaining parts of the version matter?

@deontologician How is the uptime computed? Does it use the `time_started` field in `server_status` and then subtract that from the current time on the client/browser? Maybe we need to use `r.now()` instead to avoid wrong values due to clock differences between the client and the server?

We should also look into the info boxes, and maybe just remove them completely.

**Comment by deontologician** [comment]
Ok, here's my plan:
- [ ] remove info boxes
- [ ] Use the SI notation pretty printing function for the cache size

I'd like to leave the version as is, the full version for debugging purposes is still available by clicking the gear at the top of the web ui

I don't feel the clock differences are a huge problem. Clock skew is ever-present, and if the client and server are 8 minutes off from each other, I think the web-ui shouldn't paper over it.

**Comment by AtnNn** [comment]
Yes, one of the first questions I ask users who are having issues is "What version are you using?". If they are running a patched, debug or development version they might mis-report the version.

Users might also run into this themselves, for example if they build a patched version of RethinkDB and don't see a version change.

**Comment by deontologician** [comment]
What if we give the full version in the title attribute, so when you hover over it it shows up?

**Comment by deontologician** [comment]
![selection_056](https://cloud.githubusercontent.com/assets/1366/8364406/f46ce9dc-1b3a-11e5-870a-fa13fd3ef007.png) This is what I'm talking about with the version by the way. It does require connecting directly to the server however, vs. using the admin api

**Comment by danielmewes** [comment]
Hmm maybe if it's an additional step to get the full version that would be bad because it might cause an additional round-trip with users who are having an issue ("You have already reported your version, but could you check this specific thing to get us the full version?").
I'm relatively neutral on the issue. I think in 2.0.x we are showing the full version, so maybe we should just keep that.

**Comment by deontologician** [comment]
Currently we're showing major.minor.patch on 2.0.3. The logic for stripping out the git hash etc has been around a while.

Is just having the full version in the settings panel acceptable then?

**Comment by danielmewes** [comment]
On 2.0.3 I'm seeing "2.0.3~0precise" on that page. Is that the same we will get with the new implementation?

**Comment by deontologician** [comment]
The code is `version.split(' ')[1].split('-')[0]` so I think it will leave the ~ separator alone.

I'm not sure how the version gets into the webui, I think it's part of the build process. Checking now

**Comment by danielmewes** [comment]
Ok. Basically I think we should leave the version as it is for now.

**Comment by marshall007** [comment]
It would be kinda nifty if you could click on each attribute to toggle the more precise notation.

**Comment by danielmewes** [comment]
@marshall007 I think we should keep it simple for 2.1, but I agree that for example having the detailed values in an info box when hovering over a field would be neat at some point.
