### ISSUE TITLE
Crashing with invalid global optargs

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#4473]
I have been working on providing a global DB optarg with queries. The server was crashing whenever I would execute this query:

```json
[1,[15,["todos"]],{"db":[15,["rethinkdb_ex"]]}]
```

where the first element in the vector is the token, second is the query, third is the global optargs.

with these logs:

```
error: Error in src/arch/runtime/thread_pool.cc at line 352:
error: Callstack overflow in a coroutine
error: Backtrace:
error: Tue Jun 30 15:04:10 2015
error: Exiting.
Trace/BPT trap: 5
```

The issue was that I was providing 15 (TABLE) instead of 14 (DB) for my global optarg. So the programming error was all mine, but I wouldn't expect an invalid query to crash the database? Let me know if I can provide more info to help with this.

**Comment by mike-thompson-day8** [comment]
Yikes.  So a bad query crashes the database.  That's rocked my faith a bit.

**Comment by mlucy** [comment]
Thanks for the bug report!

> So the programming error was all mine, but I wouldn't expect an invalid query to crash the database?

It looks like the problem here is that when setting the `db` optarg we try to evaluate `r.table(...)`, which itself involves looking up the `db` optarg, and we blow the stack in the resulting recursion.  I was under the impression that we didn't allow global optargs to reference themselves like that, so I'm not quite sure why the query doesn't get discarded earlier; I'm looking into that now.

(There's also the separate problem of why we aren't detecting the runaway recursion and aborting the query.  https://github.com/rethinkdb/rethinkdb/issues/2639 should have fixed that, so I'll look into that too.)

**Comment by danielmewes** [comment]
@mlucy regarding the overflow detection / #2639: Note that there currently are some known insufficiencies of the current implementation, see https://github.com/rethinkdb/rethinkdb/issues/4359#issuecomment-110465985 . Not sure if that one is relevant in this case.

**Comment by mlucy** [comment]
It looks like my memory was wrong; currently we allow global optargs to reference other global optargs without any special limits.  This is obviously incorrect in the case where a global optarg references itself, but it might make sense in other contexts (even `r.table`, which references the `db` global optarg, might make sense in another global optarg).

The overflow detector from #2639 started working when I bumped the `MIN_EVAL_STACK_SPACE` up to 8k; I think 4k just wasn't large enough for this particular code path (we go through a lot of function calls before wrapping around and arriving back in `eval`).

@danielmewes -- do you think it's worth special-casing it to make sure global optargs can't reference themselves (this is a bit of a pain and would probably require adding more information to the `env_t`), or should we just fix the overflow detector and rely on it for cases like this?

**Comment by neumino** [comment]
It would be simpler to just enforce options to be passed as primitives?
I've always found weird the fact that the optional database is passed as a DB term.

**Comment by danielcompton** [comment]
@neumino I found this a little odd too, given that it was already going inside `{"db":`, but I guess the parsing would be simpler and follow the same code path?

**Comment by mlucy** [comment]
@neumino -- it was arguably a bad decision to let people pass arbitrary terms as global optargs, and to require that the `db` term in particular be a database rather than the name of a database.  I'm hesitant to change it now though because of backwards compatibility concerns.

**Comment by danielmewes** [comment]
@mlucy Bumping the free stack limit to 8 KB sounds like a good idea. Would you mind checking if that also fixes it on OS X? If it does I think that's good enough. This should be a pretty rare case.

@mike-thompson-day8 Generally ReQL isn't currently designed to allow users to execute their own queries directly without an intermediate layer. There are loads of ways to write queries that use arbitrary amounts of resources (memory, CPU) or even crash the server by exhausting memory (like in this case). We're trying to detect an increasing amount of cases like this and fail gracefully instead of terminating the server, but it will be a while until we can control all types of resource usage that might be caused by queries.

**Comment by mike-thompson-day8** [comment]
@danielmewes fair enough.  I now understand a bit better the cause. Thanks for the quick response.

**Comment by marshall007** [comment]
@mike-thompson-day8 see also #1375 which is related to the point @danielmewes was making.

**Comment by mlucy** [comment]
@danielmewes -- bumping it to 16KB fixes it on both Linux and OS X.  That's getting to be quite a bit of buffer though.  Does that seem fine?

**Comment by danielmewes** [comment]
That's about 13% of the stack. It seems ok. We should probably do https://github.com/rethinkdb/rethinkdb/issues/4348 a bit sooner though than I had originally anticipated.

**Comment by mlucy** [comment]
Bumped it up to 16KB in both `next` and `v2.0.x` (CR 3037 by @danielmewes).
