### ISSUE TITLE
Testing: possible to preserve line numbers in polyglot tests?

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#4490]
I don't know how difficult this would be to do so it may not be worth the effort, but when I was working on the polyglot tests it would have been really useful to know the location of the failing test case in the YAML file. Currently you get the index of the failing case like `polyglot/geo/geojson.js/5`, but this isn't that helpful in locating the actual line, especially for the larger files.

http://stackoverflow.com/a/13319530

**Comment by danielmewes** [comment]
@larkost any ideas for this?

**Comment by larkost** [comment]
Currently it would not be possible since we run things through the PyYAML so don't have access to the original line numbers. But I have a good chunk of our own variation of a yam-like parser already written, and it would not be too difficult for it to keep the line numbers of the items it parses out for us.

I don't have a bug for that effort at the moment, but am grabbing this to remind me to do that then.

Usually I ignore the case count (unless it is really small), and grep for either the expected or test text (not always perfect since some things get translated).

**Comment by larkost** [comment]
This has been merged into `next` with c88aeabe
