### ISSUE TITLE
Proposal: User accounts + access permissions

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4519]
__Scope__
This is a concrete proposal to address https://github.com/rethinkdb/rethinkdb/issues/1805 and https://github.com/rethinkdb/rethinkdb/issues/218 .

It does *not* address resource quotas, DoS attacks, and assumes generally benign users. It is hence not suitable for things like direct DB access from the browser, which I think is a separate problem with very different requirements that we should address separately.
This proposal addresses restricting access to data in settings where you're either concerned about access to sensitive data, or where you want to provide some extra protection against user mistakes that could otherwise damage important data.

__Authentication__
Instead of our current auth key, I propose that we have a list of user name+auth key pairs.
There is always one default user (let's call it "admin"). You cannot delete that user.
We should also add a command line option that resets the "admin" auth key to a new value in case you lose it.

The drivers are going to send a user name + auth key combination instead of just an auth key during the connection setup. Existing clients will have their auth key mapped to the "admin" user name implicitly.

__Permissions__
Each user with the exception of "admin" has a white list of permissions assigned to it.
An entry in the list is of the following form: `(<scope>, <access>)`.

`<scope>` is one of:
* `database <uuid>` Grants access to all tables in the given database
* `table <uuid>` Grants access to the given table
* `all` Grants access to all tables

`<access>` is one of:
* `read` allows reading documents from the tables
* `write` allows modifying documents in the tables. There is one exception: tables in the `rethinkdb` database do not become writeable through this, even if they're part of the `<scope>`.
* `admin` allows creating/dropping indexes, and running `reconfigure`, `rebalance` and writing to the result of `table.config()`. If they are part of `<scope>`, this also grants write access to the `rethinkdb` system tables. If the `<scope>` is `all` or `database <uuid>`, it also allows creating and dropping tables. If it is `all`, it also allows creating and dropping databases.

Each access level includes the lower ones.

The "admin" user always has the single permission `(all, admin)`.

__Enforcement__
The following terms check permissions upon evaluation and throw an error if the required permissions are not met:
* `r.db` (including implicit database terms through the default database)
* `table`
* `insert`, `update`, `replace`, `delete`
* `reconfigure`, `rebalance` (and `config` if it doesn't work automatically due to the checks on the write terms)
* `r.http` This is special, and is *only* allowed if the permissions are `(all, admin)`. Otherwise firewall boundaries could be circumvented, and web UI access could be misused to escalate privileges.

__Updating permissions__
Permissions can be configured cluster-wide through the `r.db('rethinkdb').table('cluster_config')` table. This replaces the current auth key document. Alternatively we could introduce a new system table for this `r.db('rethinkdb').table('users')`?

When updating permissions, the new permissions will propagate to all servers in the cluster and apply to all existing connections eventually. However we don't guarantee *when* this takes place. In particular withdrawing permissions or changing an auth key is not guaranteed to take effect immediately, and if there is a network partition, the propagation might take an arbitrarily long time.

__Implementation suggestion__
We can use a semilattice to propagate the user and permission information (there are different options to how we resolve conflicts in it, I think this is of secondary concern).

The authentication data itself could get stored in the environment I guess, so that it can be accessed by ReQL terms.

For the write operations `insert`, `update`, `replace` and `delete`, we might need to add a way for them to identify the db+table that they are applied on if we don't have that yet.

__Optional improvements__
While we're at it, it would be nice if we could make the web UI require an authentication key as well. For simplicity, I think it should always use the "admin" user. To make that happen we would need to add auth key support to the HTTP protocol implementation, and add a modal or special page to the web UI itself to allow entering the password.
This would avoid the problem that you need to use a firewall to restrict web UI access even in a generally trusted network, if you want to make sure that the access permissions are met.

It would also be great if we could make the auth key exchange more secure on the protocol level. Here's one proposal:
1. When connecting, the server generates a cryptographic random string and sends it to the client (the challenge).
2. The client concatenates the string with the auth key and hashes it using a secure hash function
3. The client transmits the hash to the server, which verifies it

This removes the problem that we're transmitting the auth key in plain text over the network.

--
I think it would be really amazing if we could get this into 2.2 since it would make RethinkDB more suitable for many large scale enterprise deployments out of the box.

**Comment by marshall007** [comment]
How would this affect `r.dbList` and `db.tableList`? Would you return a filtered list that only includes what you have `read` access to?

If the web UI authentication piece is implemented would that be optional? Keeping it behind a firewall and SSH tunneling like we do now seems easier to manage.

**Comment by deontologician** [comment]
> It would also be great if we could make the auth key exchange more secure on the protocol level. Here's one proposal:
1. When connecting, the server generates a cryptographic random string and sends it to the client (the challenge).
2. The client concatenates the string with the auth key and hashes it using a secure hash function
3. The client transmits the hash to the server, which verifies it

> This removes the problem that we're transmitting the auth key in plain text over the network.

Depending on how this is implemented, this could still open us up to replays. For this to work, the server would need to send a challenge for every query, otherwise anyone listening on the network could replay the hashed challenge+authkey to run any queries they wanted.

Personally, I feel like if we're going in the authorization direction, it seems like a good time to implement SSL on the server. It's kind of awkward to explain "Well we restrict a user's access, but it's trivial to circumvent unless you do these extra steps". People will assume it's secure because they have to provide a key.

**Comment by mlucy** [comment]
#### Permission Levels

I like the permission levels, but I think we should also add an append-only permission level for use in e.g. log tables (so people can log events but not delete things).

#### Permissions format

I don't really like the permissions format.  I think it should use names instead of UUIDs and generally be more human-readable.

A row in the permissions table would have four fields: `user` (the name of the account the permissions are for), `access` (a document describing access permissions), `http_access` (whether or not the user can use `r.http`), and `admin` (whether or not the user can do global configuration tasks like add other users).  It would also have an auth key attached, maybe as an unreadable field?

The access document would be a document that maps from database names to subdocuments.  The subdocuments would map from table names to permission documents.  Permission documents would be objects with the fields `write`, `read`, `admin`, or `append`.  If the field is set to true that permission is granted, if it's set to `null`, `false` or is missing permission is denied.

So, for example, here's a permissions document granting access to some tables in the production database and http access but not global admin access:

```
{
  user: 'danielmewes',
  auth_key: <hidden>,
  access: {
    production: {customers: {read: true}, orders: {read: true, write: true}, logs: {append: true}},
  },
  http_access: true,
  admin: false
}
```

I think it's fine to use database/table names instead of permissions here.  I don't think anyone would expect dropping a table and recreating a table with the same name to invalidate existing sets of permissions for that table.

#### Updating Permissions

I think a new system table is probably the best option.

I'm not sure whether or not it's OK to return from permissions updates before the new permissions have propagated to the whole cluster.  If it's a lot easier than we should probably do that and only do something else if people complain.

#### Security

I agree with Josh, if we're going to be making authentication a bigger part of the product we should use a library designed for it rather than homerolling our own thing with hashing concatenated strings.  SSL seems fine if it isn't too hard.

**Comment by mlucy** [comment]
An advantage of the format I specified is you can write queries like:

```rb
r.table('rethinkdb').table('permissions').get('danielmewes').update(
  {access: {production: {orders: {write: false}}}}
)
```

Which is very natural.

**Comment by VeXocide** [comment]
__Authentication__
Integrating into existing authentication systems such as LDAP and PAM is going to be important to enterprise clients and something we should support in my opinion. As @deontologician rightly the authentication should either be challenge-based or over a secure connection, with SSL being the obvious route.

We should also consider security the connections between the database instances if we're going to propagate the configuration via those.

__Permissions__
The listed scopes of `cluster`, `database <uuid>`, and `table <uuid>` make perfect sense but we should support more fine-grained `<access>` levels, and I'd like to propose the following.

* `get` allows reading of documents from `<scope>`
* `insert` allows documents to be inserted into `<scope>` but not modified
* `update` allows existing documents in `<scope>` to be modified
* `delete` allows documents in `<scope>` to be deleted
* `create` allows the creation of tables and / or databases depending on `<scope>`, this could essentially be an `admin` that allows rebalancing and reconfiguration
* `connect` allows connections to the outside to be made, currently enabling `r.http`, as only enabling this on `(all, admin)` will lead to those access level to be granted unnecessarily to enable `r.http`
* `execute` allows the execution of code, currently enabling `r.js`

Most importantly this allows `get`, `insert`, `update`, and `delete` to be distinguished as you may commonly want to allow someone to insert documents but not modify or delete them. Secondly it adds an access level for `r.js` which I think is required due to the impact of a simple query such as `r.js("while(true) {}")`.

Last of all the question of how to deal with the `rethinkdb` database is an important one, and I'm not quite sure how we should go about this.

**Comment by NicolasLM** [comment]
:+1: This proposal opens new use cases for RethinkDB. I'm not sure the integration with LDAP and PAM needs to be in the first iteration though.

**Comment by PhilipGarnero** [comment]
:+1:

**Comment by RubenKelevra** [comment]
Currently we use fastd and batman-adv for database-interconnections. It would be nice if it's possible to do it over clear-net in future. :)

**Comment by VeXocide** [comment]
__Authentication__
In order to support authentication we'll unfortunately have to change our client protocol. We'll be removing the current auth key in favour of a challenge-response based authentication, almost certainly SCRAM-SHA-2 as described in https://tools.ietf.org/html/rfc7677. In the future this can be extended with X.509, Kerberos, and potentially others.

A default user named `"admin"` with global privileges will exist and as long as it does not have a password set we will allow unauthenticated connections. These connections will be mapped onto this user, but once a password is set on it all connections from that point forward must be authenticated.

__Permissions__
We will initially introduce four permissions.

* `read` allows reading documents from a given scope.
* `write` allows inserting and modifying documents in the given scope.
* `config` allows the creation and deletion of indexes, running `reconfigure`, `rebalance`, and writing to the result of `table.config()`. In the database scope this will also allow the creation and deletion of tables, and similarly in the global scope this allows the creation and deletion of databases.
* `connect` allows connecting to the outside world, currently facilitating `r.http` and only available at the global scope.

There will be three scopes, a global scope, a database scope, and a table scope. The smaller scopes will inherit the permissions of the larger scope, and the smaller scopes will overrule the larger scope. There is one exception though, the `rethinkdb` database will not inherit the `write` permission from the global scope, and will ignore the `config` permission.

__Enforcement__
The following terms check permissions upon evaluation and will throw an error if the required permissions are not met.

* `db` including the implicit database terms through the default database
* `table`
* `insert`, `update`, `replace`, `delete`
* `db_create`, `db_drop`
* `table_create`, `table_drop`, `index_create`, `index_drop`, `index_rename`
* `reconfigure`, `rebalance`
* `http` to preserve firewall boundaries and prevent the Web UI to be misused

__Interface__
We will introduce a new system table `rethinkdb.users` containing the users and their associated permissions formatted as follows.
```
{
  "access": {
    "access": [
      "read", "write"
    ],
    "databases": {
      "access": [
        "read"
      ],
      "tables": {
        "foo": {
          "access": [
            "read"
          ]
        }
      }
    }
  },
  "username": "danielmewes",
  "password": "<hidden>"
}
```

New users can be added and removed by inserting and deleting from the table respectively, and the password and access can be set by updating the appropriate fields.

Given the complexity of the `"access"` field we will also introduce a new ReQL term `grant` which accepts a username and an object with a boolean per permission such as `{"read": true, "write": false}`. `r.grant` will operate on the global scope, `r.db("foo").grant` will operate on the database and `r.db("foo").table("bar").grant` will similarly operate on the respective table.

Initially we will not secure the Web UI, this can either be bound to localhost or disabled altogether.

__Implementation__
The permissions will initially be stored in the semilattices and propagated through this, though there may be a better way in the future. Once authenticated the username will become part of the environment that is passed down to the evaluation of the query.

**Comment by danielmewes** [comment]
@VeXocide The schema should have the table / database `name` in it right? We might also want to find a better name for the top level `access` field in the user document. It feels a bit redundant (maybe `global` or `permissions`?)

**Comment by danielmewes** [comment]
Oh wait is `foo` the table name in there? Did you mean to have a similar thing for the database?

**Comment by marshall007** [comment]
@danielmewes yea, maybe it makes sense to just flatten everything out? `access.*` in this example would be equivalent to `access.access` in @VeXocide's proposal:

```json
{
  "access": {
    "*": [
      "read"
    ],
    "<db>": [
      "read", "config"
    ],
    "<db>.<table>": [
      "read", "write"
    ]
  },
  "username": "danielmewes",
  "password": "<hidden>"
}
```

**Comment by VeXocide** [comment]
@danielmewes -- I did indeed mean something similar for the database name and have updated the original comment to reflect this. It means the nesting is even deeper, to the point of it being unreadable which is exactly what we were trying to prevent.

@marshall007 -- I quite like this idea, we only allow `A-Za-z0-9_` in database and table names thus it would work nicely. With our current lexicographical sorting for object keys the `"*"` would even be shown as the first item. I'm not sure we use `.` as a namespace separator anywhere else though, and whether we want to start doing so.

**Comment by VeXocide** [comment]
Actually, we could even use `"*.*"`, `"<db>.*"`, and `"<db>.<table>"` which would fit the usual glob pattern.

**Comment by marshall007** [comment]
> we only allow `A-Za-z0-9_` in database and table names thus it would work nicely.

@VeXocide yep, exactly what I was thinking!

> we could even use `"*.*"`, `"<db>.*"`, and `"<db>.<table>"`

I thought about that, but isn't `<db>.*` the same as `<db>` or would `<db>` itself not imply table level permissions? If they are in fact completely different, how would you represent `<db>.*` vs `<db>` using the `.grant()` term?

In regards to the `.` namespace separator, that's how it's displayed in the table details page of the Web UI. I thought I had seen it in the output of some system table, but now that I'm looking, I can't seem to find it anywhere.

**Comment by VeXocide** [comment]
@marshall007 -- Yes, `"<db>.*"` is the same as `"<db>"`, the only difference is that the former fits the idea of using `"*"` for the global level.

**Comment by marshall007** [comment]
@VeXocide only downside to `*.*` and `<db>.*` is that people might expect to be able to use wildcards in arbitrary ways (ex. `*.<table>` or `<db>.prefix-*`). If `*` is only used to represent the global permissions, I think it's more clear what can and cannot be done.

**Comment by deontologician** [comment]
One argument against using a dot instead of actual nesting is that doing `table['access'][db_name][table_name]` is more natural in reql than splitting on '.' This isn't a problem for `.grant` since it can do arbitrary stuff under the hood, but it'd be nice if accessing the table in reql wasn't painful

**Comment by deontologician** [comment]
Also yeah, we only use this dot separator thing in the web-ui, it is not a convention elsewhere in reql. Generally we tend to use something that's parseable by json or your language to denote this structure, rather than put it into a string for `.split` parsing

**Comment by deontologician** [comment]
What about something like:

```json
{
  "username": "foo",
  "password_hash": "bar",
  "access": {
    "$read": true,
    "$write": true,
    "db_name": {
      "$read": true,
      "table_name": {
       "$read": false
      }
    }
  }
}
```

The dollar signs are a bit ugly, but they can't appear in db/table names (so they allow us to put table and db names alongside them rather than adding another nesting level) and they're valid for identifiers in JavaScript and for symbols in Ruby. So you can do things like:

```js
r.db('rethinkdb').table('users').get(userId)
  .update({access: {myDb: {$read: true}, yourDb: {$read: true}}})
r.db('rethinkdb').table('users').get(userId)('access')(dbName)(tableName)('$read')
```

**Comment by VeXocide** [comment]
@marshall007 -- That's a good point, it might make sense to simply use the empty string for the global scope.

@deontologician -- Exactly, that was my initial worry regarding the `.` separator. In an offline discussion with @danielmewes yesterday we decided we'd rather not have a prefix before the permissions. I'm currently rethinking that as it's considerably more readable than the deep nesting in the original proposal.

**Comment by marshall007** [comment]
@deontologician I agree with that and it would certainly be tricky to write a query to "give me users with `read` permissions on `<table>`", but that is mostly true either way. Regardless, it seems we'd probably want a helper term for reads that takes into account cascading permissions and lets you do lookups accordingly:

```js
var users = r.db('rethinkdb').table('users')
users.access('read', { db: '...', table: '...' })
users.access('write', { db: '...' }).grant({ read: true, write: false })
```

I also definitely like having the permissions as boolean properties rather than in arrays from your example.

**Comment by deontologician** [comment]
> I also definitely like having the permissions as boolean properties

It seemed nicer for my example but it's possible it would be more cluttered with all of the permissions in it. Then again, is "uncluttered permissions document" a thing we should optimize for? As long as querying it and modifying it are straightforward, maybe that doesn't matter

**Comment by marshall007** [comment]
@deontologician `.filter(r.row('access')('$read'))` is slightly nicer than `.filter(r.row('access')('*').contains('read'))` in raw ReQL, but with a term like `.access()` suggested above document structure wouldn't matter as much. Like I said, I think we need something like that anyway because computing the cascade in a `filter` would be a huge pain regardless of structure.

**Comment by deontologician** [comment]
Yeah, I agree it's nicer to query

**Comment by VeXocide** [comment]
We've currently been optimising `r.db("rethinkdb").table("users")` for readability, as its main purpose is to display the current settings. The idea is to add `r.grant` to set permissions, but querying them is still problematic.

We could have `r.grant("user")` give a list of permissions, then set them through `r.grant("user", {"read": true, "write": false})`. In that case using the name `r.access` might be better.

**Comment by danielmewes** [comment]
Looking at the actual example the `$read` / `$write` / `$config` syntax described by @deontologician actually looks nice I think.

I'm not sure if the `r.access()` method is necessary in the first version. The permission system in its first version isn't going to be granular enough to restrict access to particular documents in a given table, so it wouldn't be very useful in a `filter`.
@marshall007 do you have a particular use case in mind?

**Comment by marshall007** [comment]
> The permission system in its first version isn't going to be granular enough to restrict access to particular documents in a given table, so it wouldn't be very useful in a `filter`.

@danielmewes sorry if I was unclear, that wasn't the intention behind `r.access()`. I only meant for it to be used in conjunction with the `users` system table. If I want to filter users who have `read` access on a particular table, that needs to take into account users with `*`, `<db>`, or `<db>.<table>` level `read` permissions. I was saying we might need something like `r.access()` to do all that for you.

**Comment by danielmewes** [comment]
Oh got it. Thanks for the clarification @marshall007, that makes sense given your original `.access()` proposal above. I have to think about that a bit.

**Comment by mlucy** [comment]
* How attached are we to the name `r.grant`?  I think something like `r.permit` might be clearer.  (If you're already primed to think of permissions than `grant` clearly means "grant permission", but if you aren't then it's pretty vague.)
* I much prefer @deontologician's syntax to the one with the `*`s and `db.table`s.  I think we should avoid special symbols if we can, for the reasons other people mentioned above.

---

> The permission system in its first version isn't going to be granular enough to restrict access to particular documents in a given table, so it wouldn't be very useful in a filter.

We're adding this now at least partially because Fusion needs it, right?  If that's the case, isn't "restricting access to particular documents" a necessary part of the spec?  Or are we going to do that part outside of the database?

**Comment by VeXocide** [comment]
@mlucy -- Fusion will have user accounts and permissions as well, but this is unrelated.

**Comment by VeXocide** [comment]
I named `r.grant` after `GRANT` which is commonly used by SQL, though it's certainly up for discussion.

**Comment by kamilion** [comment]
So, I've been at this for a while myself.
Right now, I'm using SCRYPT to store passwords in rethinkdb.

http://www.tarsnap.com/scrypt.html
links to these two at the bottom of the page:
https://pypi.python.org/pypi/scrypt/
The python/C extension version which I use myself..
https://github.com/scintill/scrypt
And the javascript version for use in the browser.

Here's the methods I use for storage in rethinkdb.
https://github.com/kamilion/kaizen/blob/master/auth/authmodel.py#L125

SCRYPT has some interesting properties in this situation.

The python driver itself is aware of a successful decryption.
scrypt.error will be raised if the password to the container is not correct.


**THIS IS IMPORTANT: IT DOES NOT MATTER WHAT I STORE INSIDE THE CONTAINER.**

In this case, I'm simply storing 64 bytes of garbage inside. I'll get the same 64 bytes back out, if the decryption succeeds. But for my purpose of authentication, the action of encryption and decryption occurs... NOT HASHING. If the decryption fails, an error's raised. In my source, I have it set to take 0.5 seconds per attempt.

NOW. That being explained... SCRYPT of course can encrypt anything you want. I provide a system to operate a Virtual Machine Host. At one point, I planned to store unlocked SSH private keys inside of SCRYPT. The only way to get them out is to provide the correct passphrase.

Now, I have a remarkably naive implementation linked above, but one could easily use it to provide a challenge response, where the SCRYPT blob is sent to the client, who uses javascript to open it, extract the real secret, hash it, and return it to the server, who performs roughly the same process, and compares the hashes. Or SHA512 hash the password before transmitting it over HTTP/HTTPS.
I have not done any of these things; because honestly? I use my yubikey to log in, and I simply ordered more for our web staff as needed...

Of course, thinking about implementing SCRYPT into rethinkdb is not a part of the discussion about RBAC; but it ties so closely together, AND provides security for data at rest, it may well be the time to take a hard look at pulling it in as part of the RBAC implementation and have the access roles truly enforce their semantics. 
```


Sorry mario, the key to unlock this document's contents is in another castle. . .


```
Two drivers agree to play chicken with each-other. One of them removes his steering wheel and throws it out the window. 

Which driver will win the game of chicken, in which the win condition is intimidating the other driver into swerving first?

The one who simply says he's not going to swerve... 
**or the one who has removed the ability to swerve entirely?**

**Comment by kamilion** [comment]
Anyway, the main idea here is to pick a single cipher that is secure, flexible, operates as a component in a chain, and has support from most of the languages rethinkdb targets.

One could implement it as a datatype directly, as a subclass of the BINARY record type to protect data at-rest, as a stream cipher for data in-transit but not at-rest, in an authentication chain to provide boolean pass/fail, a double-decrypt as I described above where both parties perform the same dance (DH handshakes work in a similar vein), or many other combinations of access control and cryptography.

Key escrow can be done in-process for performance or optionally out-of-process for additional security or utilizing a hardware assistance module.

I would advocate against implementing something like the openssl cipher suite... It's too easy to misuse those components into something that wastes processor time giving you no real protection at all.

**Pick something secure, *stick with it for ten years*.**

SCRYPT's had a lot of rocks thrown at it, and it's always gotten right back up for another hit.
If it's good enough for litecoin, it should be good enough for rethinkdb...

**Comment by danielmewes** [comment]
@kamilion Thanks for the write up.
At the moment we're primarily looking for a simple challenge/response authentication method for the driver protocol. We're currently looking into this standard method: https://tools.ietf.org/html/rfc7677

Encrypting the whole connection is a separate project, and is tracked in https://github.com/rethinkdb/rethinkdb/issues/3158 .

**Comment by VeXocide** [comment]
I just created a first user, granted it permissions, and deleted it again. There's still a _lot_ that needs to happen, but there is progress!

The following snippet now does something.
```
r.db("test").tableCreate("foo")
r.db("rethinkdb").table("users")
r.db("rethinkdb").table("users").insert({"id": "vexocide", "access": {"$read": true, "$write": true, "$config": true}})
r.db("rethinkdb").table("users")
r.db("test").grant("vexocide", {"$read": true, "$write": true, "$config": false})
r.db("test").table("foo").grant("vexocide", {"$read": true, "$write": true, "$config": true})
r.db("rethinkdb").table("users")
r.db("rethinkdb").table("users").get("vexocide").delete()
r.db("rethinkdb").table("users")
```

Along the way that spits out the following.
```
[
    {
        "access":{
            "$config":true,
            "$read":true,
            "$write":true
        },
        "id":"admin",
        "password":false
    },
    {
        "access":{
            "$config":true,
            "$read":true,
            "$write":true,
            "test":{
                "$config":false,
                "$read":true,
                "$write":true,
                "foo":{
                    "$config":true,
                    "$read":true,
                    "$write":true
                }
            }
        },
        "id":"vexocide",
        "password":false
    }
]
```

**Comment by kamilion** [comment]
Looks good to me! Congrats!

**Comment by coffeemug** [comment]
:clap: 

I have a few comments on the UX of this (field names, document structure, etc.) -- will talk to @VeXocide in person about some of this to make sure I'm not missing anything, and then comment here.

**Comment by mlucy** [comment]
I still think the name `permit` is much more obvious than `grant`, especially if it's called directly on a table (`r.table('test').permit('user', {$read: true}))`).

I generally like the current proposal, but @coffeemug mentioned that he might have an alternate one that avoids the `$` so we should probably wait for him to write that up before debating the exact format too much.

**Comment by danielmewes** [comment]
`r.grant` sounds more familiar to me, but that's because I know it from SQL. I think this might be similar for a lot of users.
I have a slight preference for `grant` over `permit`.

**Comment by coffeemug** [comment]
I also have a preference for `grant` over `permit` (but it's fairly slight, I wouldn't be opposed to `permit`, I think it would be fine).

**Comment by deontologician** [comment]
Was there any consensus on the syntax?

**Comment by coffeemug** [comment]
No, I'm doing that right now.

**Comment by coffeemug** [comment]
I propose breaking up the `users` table into two tables: `users` and `permissions`.

The `users` table would look like this:

```
[
        "id":"admin",
        "password":false
    },
    {
        "id":"vexocide",
        "password":false
    }
]
```

The `permissions` table will look like this:

```
[
    {
        "config":true,
        "read":true,
        "write":true
        "id": ["admin"],
    },
    {
        "config":true,
        "read":true,
        "write":true,
        "id": ["vexocide"],
    },
    {
        "config":false,
        "read":true,
        "write":true,
        "id": ["vexocide", "test"]
    },
    {
        "config":true,
        "read":true,
        "write":true
        "id": ["vexocide", "test", "foo"]
    }
]
```

The `id` for the `permissions` table will be a triple `[user, db, table]` (with `db` and `table` possibly omitted). I think this is much cleaner, is pretty easy to understand, and avoids the whole dollar sign issue.

**Comment by VeXocide** [comment]
I like the idea of splitting the `users` table up into a `users` and `permissions`, and agree the `users` table should look as follows.
```
[
    {
        "id": "admin",
        "password": true,
        "description": "The default administrative users"
    },
    {
        "id": "vexocide",
        "password": true,
        "description": "Jeroen Habraken"
    }
]
```
The `description` field is simply a string in which the user can store arbitrary data.

In my opinion the `permissions` table is a step backwards as it no longer visually represents the hierarchy. I'll be the first to admit that the dollar signs are far from great, thus here's a another proposal.
```
[
    {
        "config": false,
        "connect": false,
        "databases": {
            "foo": {
                "config": false,
                "tables": {
                    "bar": {
                        "read": true,
                        "write": true,
                    },
                    "baz": {
                        "config": false,
                        "read": true,
                        "write": false,
                    }
                }
                "read": true,
                "write": true
            },
            "test": {
                "config": true,
                "read": true,
                "write": true
            }
        },
        "id": "vexocide",
        "read": true,
        "write": true
    }
]
```

**Comment by coffeemug** [comment]
I personally think it's worse but I wouldn't be opposed to it.

/cc @mlucy @encryptio (and anyone else who wants to pay attention) -- what do you think?

**Comment by danielmewes** [comment]
For the record, I think this is better.

If you have a bunch of users and tables, having a flat hierarchy with all permissions in one list will get hard to read I think.

In practice you will often need to filter or group on the flat table to get useful results, and the variable-length primary key array makes those operations non-trivial to perform.

Having permissions grouped by users on the other hand is immediately useful (you can easily get an answer to the question "what are the permissions for user X"), and it intuitively represents how table permissions override the permissions of the containing database, which in turn override the global permissions of the given user.

**Comment by mlucy** [comment]
As much as I usually hate special string syntax, I think the `$` one is the best, and my second choice would be @VeXocide's alternate proposal.  I think the hierarchical structure is better, and the `$` one is the easiest to read.

(I think the usual concerns about about string munging don't really apply here because you're extremely unlikely to be generating these field names based on user input in a way that lets users inject permissions, and if you are you probably have deeper problems.)

I don't really like the idea of having two tables: it seems unnecessarily complicated, and it introduces new problems like "what do you do if a rule refers to a user who no longer exists" and "can users be created with the same ID as a previously deleted user, and if so do they inherit that user's old rules".

**Comment by mlucy** [comment]
Another reason I'm fine with the `$` syntax: it's assigning special meaning to a symbol, but only in a *specific admin table*, where I think that's a lot more appropriate than having a special symbol that means something database-wide.  It's the difference between having special syntax in config files for a particular program and having special syntax in all text files.

**Comment by danielcompton** [comment]
If you're going to have the nested map describing permissions, then it probably makes sense to add it to the user records, as I don't think there is any benefit to normalisation at that point.

**Comment by danielmewes** [comment]
Having the user entries and passwords in a separate table has the nice property that it's more obvious what parts of the data in those tables a user can change and what parts they don't.
The plan is that every user can change their own password, but they can't add or delete users, or change permissions without having additional permissions themselves.

With a separate `users` table, the rule becomes "every user can update their own entry in `users`". With a combined table for both, the rule would be something like "every user can update the `password` field of their own entry in `auth`, but not any other fields" (or whatever the table would be called).

@mlucy I think consistency between the tables isn't really an issue. Keep in mind that this is just how we represent the data in the ReQL artificial table interface. It doesn't necessarily reflect how the data is stored internally. Basically deleting a user from `users` would remove the associated document in `permissions` as well. Creating a user by inserting info `users` would "insert" a new (almost empty) document into `permissions` as well.
I think the valid operations should be as follows:
* On `users`: Inserting creates a user, deleting deletes a user, updates can change the `password` field
* On `permissions`: Neither inserts nor deletes are allowed. Updates change the permissions of a given user.

**Comment by coffeemug** [comment]
Ok, I recuse myself from this issue -- I don't know what's right anymore! (If we want to stick with the `$` syntax, I'd be ok with that, at this point I've stared at this for so long that I don't trust my own opinion)

**Comment by encryptio** [comment]
I like @VeXocide's latest proposal (separate `users` and `permissions`, single `permissions` entry per user.)

I think the benefit from using special meta-characters like `$` in these dicts is when they can be combined with user data _at the same level_, which is why I think they're acceptable in the MongoDB query language. _That's not the case here_; the hierarchy is `type/id/type/id/type`, which extends cleanly to new types (which only we can define) and new ids for any type (which the user already manages conflicts for.)

*In this structure, there are no dicts where predefined type names and user defined collection names are keys at the same level.* Because of that, I prefer no `$`.

**Comment by mlucy** [comment]
@encryptio -- the syntax in https://github.com/rethinkdb/rethinkdb/issues/4519#issuecomment-155516220 has `$read` at the same levels as database and table names, which is why you need the `$`.  It lets you avoid two unnecessary nesting levels, which I think makes it much easier to read.  Even if we have separate user and permission tables, I like that syntax better.

@danielmewes -- I think people will understand "you can update your own password but nothing else" just fine.  (We could even add a toplevel term for it if it's a common operation.)

> I think consistency between the tables isn't really an issue. Keep in mind that this is just how we represent the data in the ReQL artificial table interface. It doesn't necessarily reflect how the data is stored internally. Basically deleting a user from users would remove the associated document in permissions as well. Creating a user by inserting info users would make a new (almost empty) document in permissions appear as well.

Splitting into two tables still seems unnecessarily complicated to me.  Especially if inserting or deleting in one of the tables *automatically inserts and deletes in the other one*.  Those semantics really make it seem like you want a single table.

Another advantage of a single table is that it will let you create a new user with certain permissions and a certain password in a single ReQL command.

---

As a total aside, we should make sure to censor the passwords people put in the `update` command from things like the jobs table.

**Comment by mlucy** [comment]
Since it worked so well in the other issue, here's how I'd rank the current options:

* One table with `$` syntax.
* One table with deeper-nested non-`$` syntax.
* Two tables with `$` syntax.
* Two tables with deeper-nested non-`$` syntax.
* Two tables with Slava's syntax.

**Comment by danielmewes** [comment]
> Another advantage of a single table is that it will let you create a new user with certain permissions and a certain password in a single ReQL command.

Ok I think that's a pretty strong argument.

I personally have a slight preference for the syntax without `$`

As far as I can tell, we're all at least ok with that syntax and a single table.

I'll wait another 1-2 hours in case there's strong opposition, but otherwise I'm going to mark this settled with:
One table with deeper-nested non-$ syntax.

**Comment by danielmewes** [comment]
Oh what should we call the combined table? I suggest either `auth` or `users`.

**Comment by mlucy** [comment]
@danielmewes -- OK, that works for me.

**Comment by sontek** [comment]
Is there an ETA on this? :)

**Comment by coffeemug** [comment]
We're shooting for end of February/beginning of March.

**Comment by VeXocide** [comment]
Just a thought, extending the `conn.server()` from https://github.com/rethinkdb/rethinkdb/issues/3934 to include the user the connection is currently logged in as.

**Comment by VeXocide** [comment]
Note to self, @nighelles just claimed 187 for `FOLD` which I was using for `GRANT` in `ql2.proto`, thus I need to change that when merging.

**Comment by jlhawn** [comment]
I want to mention that this is somewhat related to #3151. If TLS client authentication is used, it would be really cool if the user could be identified by the client certificate as an alternative to using a secret auth key.

**Comment by danielmewes** [comment]
Using client certs for user authentication is an interesting thought.
I think we'll leave that to version 2 though, to keep things a bit simpler in the first release.

**Comment by VeXocide** [comment]
X.509 is definitely on the list, but not for the first release as @danielmewes mentioned.

**Comment by danielmewes** [comment]
It's in next! :)
