### ISSUE TITLE
OrderBy returns cursor for index and array for unindexed property

### ISSUE THREAD

**Issue by thejsj** [rethinkdb/rethinkdb#4530]
If you run the following script in Node.js:

```
/*jshint esnext:true, node:true */
"use strict";
var r = require('rethinkdb');
var isCursor = function (cursorOrArray) {
  return !Array.isArray(cursorOrArray);
};

r
  .connect()
  .then(function (conn) {
    // #1
    r.db('rethinkdb_workshop')
     .table('messages')
     .run(conn)
     .then(function (cursorOrArray) {
       console.log('#1 Table:', isCursor(cursorOrArray));
     });
    // #2
    r.db('rethinkdb_workshop')
     .table('messages')
     .orderBy('created')
     .run(conn)
     .then(function (cursorOrArray) {
       console.log('#2 OrderBy (Property):', isCursor(cursorOrArray));
     });
    // #3
    r.db('rethinkdb_workshop')
     .table('messages')
     .orderBy({ index: 'created' })
     .run(conn)
     .then(function (cursorOrArray) {
       console.log('#3 OrderBy (Index):', isCursor(cursorOrArray));
     });
    // #4
    r.db('rethinkdb_workshop')
     .table('messages')
     .orderBy({ index: r.desc('created') })
     .run(conn)
     .then(function (cursorOrArray) {
       console.log('#4 OrderBy (Index, DES)', isCursor(cursorOrArray));
     });
    // #5
    r.db('rethinkdb_workshop')
     .table('messages')
     .coerceTo('array')
     .run(conn)
     .then(function (cursorOrArray) {
       console.log('#5 CoerceTo Array:', isCursor(cursorOrArray));
     });
  });
```
It returns the following: 

```
#1 Table: true
#2 OrderBy (Property): false
#3 OrderBy (Index): true
#4 OrderBy (Index, DES) true
#5 CoerceTo Array: false
```
I would have expected all `orderBy`s to either return `true` or `false`, but not some `true` and some `false` depending on wether the property was an index or not. Is this the expected behavior? It does make sense why this would happen, but the inconsistency seems a little confusing.

**Comment by mlucy** [comment]
This is the expected behavior.  If you `orderBy` a field we load the whole table into memory at once to sort it.  The `stream` type is only for data we can generate lazily (usually by reading off disk).

This is good for three reasons:
* We want to enforce the array size limit on the result of unindexed `orderBy`s, and the most straightforward way to do that is to return an array.
* We want users to be able to figure out the performance characteristics of their queries by looking at the result type (arrays are eager, streams are lazy).
* If we returned a stream here we'd have to keep the extra data around in memory while sending batches, which means a user who opened a cursor on `table.orderBy('field')` and then didn't consume the whole thing would be taking up a huge amount of memory on the server indefinitely.

**Comment by danielmewes** [comment]
I think we should keep the current behavior. It's consistent with the meaning arrays vs streams have elsewhere in ReQL.
