### ISSUE TITLE
r.min(a, b) / r.max(a, b) variants

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4594]
Currently you have to write these as
```js
r.expr([a, b]).min()
r.expr([a, b]).max()
```

It would be nice if you could just write
```js
r.min(a, b)
r.max(a, b)
```

probably these should be variadic and allow for an arbitrary number of arguments (at least 2 to distinguish them from the other case).

Suggested by @weshoke

**Comment by AtnNn** [comment]
It might be better to not overload the `min` and `max` names, and just support `r.min([a, b])` and `r.max([a, b])` because:

* It is inconsistent with the use of `args`, for example in `r.min(r.args(l))`
* It is inconsistent with other similar operations. Should we do the same for `avg`, `distinct`, `sum`?

Looking at associative operations I noticed that `add` corresponds to `sum`, but for `mul` there is no corresponding `product` operation. Similarly, `and`, `or`, `union`, `setUnion`, `setIntersection` and `merge` also have no corresponding reduction (related to #1312). I also noticed a small inconsistency between `add` and `sum`: `r.add()` fails but `r.expr([]).sum()` doesn't.

**Comment by danielmewes** [comment]
Good points. I think @VeXocide also didn't like this overload.

The `r.min([a, b])` syntax looks like a good compromise to me.

**Comment by VeXocide** [comment]
Indeed, and I agree that `r.min([a, b])` is a good compromise.

**Comment by mlucy** [comment]
+1 for `r.min([a, b])`.  That's already supported in the Ruby driver, and in general I think we should default to letting people write terms either infix or prefix unless there's a strong reason not to.

**Comment by marshall007** [comment]
Working on a PR for this. Any reason not to include `distinct`, `sum` and `avg` terms as well?

**Comment by danielmewes** [comment]
@marshall007 Including `distinct`, `sum` and `avg` in this sounds good to me. (that is I can't think of any issue with that, and it sounds reasonable)

**Comment by marshall007** [comment]
@danielmewes thanks, PR up now.
