### ISSUE TITLE
Heartbeat timeouts

### ISSUE THREAD

**Issue by mcadam** [rethinkdb/rethinkdb#4597]
Hello,

I am having some problems while trying to run a Rethinkdb cluster in production using Kubernetes.
I use your docker image from public registry. Once I launch a couple nodes which connect fine to each other, every 5 minutes or so I am having heartbeat timeouts.
 It is not usable as is in production as every time the connection timeouts, the connection is lost and the tables become unavailable until the server is connected again...

Under Kubernetes the docker version is 1.6, when you say the docker image is officially supported on docker version 1.7, could that cause my problem of heartbeat timeouts ?

I tried on version 1.16.0-1 and version 2.0.4, same problem on both.

Thanks

**Comment by danielmewes** [comment]
Hi @mcadam, sorry you're running into issues. Does this happen even on an idle cluster, or only if you run certain queries?

In many cases where we have seen heartbeat timeouts, those were caused by one of the servers running out of RAM and going into swap. Assuming that the servers (either inside the container or on the host) are configured with swap enabled, could you check the output of `free -m` to see if any swap space has been used? For testing, it might be helpful to disable swap on the host and in the containers, so that running out of memory will cause the process to be terminated rather than becoming overly slow.

I don't suspect the docker version to be the problem here.

**Comment by mcadam** [comment]
I dont think it is ram related for me, even on a new cluster with nothing running and 8 or 16 go of rams i am having the problems. I dont need to run queries, i launched the nodes and even with no traffic I see the heartbeat timeouts. 

There is no swap enabled on the host, and I dont think there is swap inside the container as well.

Any other ideas ?


--

Cordialement,

Adam Guldemann

**Comment by danielmewes** [comment]
Ok that's weird. Just to make sure: If you keep a `ping` running between the containers, does that show any occasional packet losses or high latencies?

**Comment by mcadam** [comment]
Here is a ping from one container to another:

PING 10.244.2.8 (10.244.2.8): 56 data bytes
64 bytes from 10.244.2.8: icmp_seq=0 ttl=64 time=0.117 ms
64 bytes from 10.244.2.8: icmp_seq=1 ttl=64 time=0.074 ms
64 bytes from 10.244.2.8: icmp_seq=2 ttl=64 time=0.061 ms
64 bytes from 10.244.2.8: icmp_seq=3 ttl=64 time=0.062 ms
64 bytes from 10.244.2.8: icmp_seq=4 ttl=64 time=0.104 ms
64 bytes from 10.244.2.8: icmp_seq=5 ttl=64 time=0.059 ms
64 bytes from 10.244.2.8: icmp_seq=6 ttl=64 time=0.071 ms
64 bytes from 10.244.2.8: icmp_seq=7 ttl=64 time=0.062 ms
64 bytes from 10.244.2.8: icmp_seq=8 ttl=64 time=0.077 ms
64 bytes from 10.244.2.8: icmp_seq=9 ttl=64 time=0.065 ms

So not bad...

**Comment by danielmewes** [comment]
@mcadam that looks good. You mentioned that the heartbeat timeouts happen about once per 5 minutes. Can you try keeping the ping running for a bit longer as well?

**Comment by mcadam** [comment]
I did some pings for like 10 minutes and no packet were lost.

Other ideas ? :)


--

Cordialement,

Adam Guldemann

**Comment by danielmewes** [comment]
@mcadam Thanks for trying that out. I'm currently out of good ideas. My only guesses are that either one of the instances gets really slow occasionally or completely pauses execution (maybe something is happening on the hosts?), or that there is some firewall / router weirdness going on that doesn't affect ICMP packages. A third option could be a problem with our timer code, so that heartbeat timeouts are triggered either too early, or heartbeats are not sent from the other side quickly enough.

It's particularly odd that this happens even without any queries running. I don't think I've seen anything like that before.
I know this is some work, but the best way to debug this at this point might be taking a network sniffer (e.g. ettercap or wireshark), and checking what's going on with the connections. In an otherwise completely idle cluster (make sure you don't have the web UI open either, since that would cause additional traffic), you should see a short message exchanged on the cluster connections (port 29015) every 2 seconds. If the interval sometimes gets significantly longer than 2 seconds, we might need to take a closer look at our timing code.

RethinkDB 2.1 will also introduce a configuration option to increase the heartbeat timeout. However I doubt that this will help much in this case, given that the fact that it's currently being hit indicates a ~10 second stall in communication and/or processing. Even if a longer heartbeat timeout can help to avoid the disconnects (which I'm not sure it will), there will still be ~10 second stalls in query processing.

**Comment by mcadam** [comment]
You can close the thread, it was coming from the kubernetes network stack. I was actually having packet loss when communicating between two docker containers, I think I misread the results of the previous ping, because now I cant get past 5 minutes without 10-15% packet loss. 
RethinkDB is not the problem here for sure, sorry about the inconvenience and the time. I worked with the kubernetes team and they managed to get rid of the problem, as soon as I can test I think everything will be fine.

**Comment by danielmewes** [comment]
Ah, thanks for letting us know @mcadam .
