### ISSUE TITLE
r.branch/hasFields has a strange behaviour

### ISSUE THREAD

**Issue by gjuchault** [rethinkdb/rethinkdb#4604]
Hi,

My database « test » contains only one table « Session ».
Here is how I would like to use Session : one primary key « _sessionId » which is working of cource.
Some various data next.
A special object « flash » that contains one-time data, and that is cleared after every http server request.
So this is what I managed to do :
```js
r.db('test').table('Session').get('c5ce22e2-3587-4841-b9a5-bd4520de8deb').do(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      source.merge({ flash: {} }),
      source.merge({ flash: source('flash').merge({ emptyFlash: true }) })
    ),
    source.merge({ flash: {} })
  );
})
```

What should happen :
1. If no flash object, create it
2. If flash object and no emptyFlash property, set emptyFlash to true
3. If emptyFlash to true, set flash object to `{}`

If the object is :
```js
{
    "_sessionId":  "c5ce22e2-3587-4841-b9a5-bd4520de8deb" ,
    "flash": { }
}
```

The result is the addition of emptyFlash (ok). If you relaunch the command, there is stillEmpty flash.

I then used this script just to see what was happening :
```js
r.db('test').table('Session').get('c5ce22e2-3587-4841-b9a5-bd4520de8deb').do(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      'Reset', //source.merge({ flash: {} }),
      source.merge({ flash: source('flash').merge({ emptyFlash: true }) })
    ),
    'Reset' //source.merge({ flash: {} })
  );
})
```

Which creates the emptyFlash variable in the flash object.
Then I called this script :
```js
r.db('test').table('Session').get('c5ce22e2-3587-4841-b9a5-bd4520de8deb').do(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      'Reset', //source.merge({ flash: {} }),
      source //source.merge({ flash: source('flash').merge({ emptyFlash: true }) })
    ),
    'Reset' //source.merge({ flash: {} })
  );
})
```

And the emptyFlash was gone.

**Comment by gjuchault** [comment]
Here are 3 screenshots of the behaviour just to be clear :
![image](https://cloud.githubusercontent.com/assets/678848/9011162/c57ca29c-37ab-11e5-8a3e-c16e5f4c901c.png)
![image](https://cloud.githubusercontent.com/assets/678848/9011166/ca2c16e2-37ab-11e5-86cf-e2303a36f1ab.png)
![image](https://cloud.githubusercontent.com/assets/678848/9011168/cefd0a28-37ab-11e5-85a7-a0a093bc4d06.png)

**Comment by danielmewes** [comment]
Hi @gjuchault , if you use `merge`, `do`, `branch` etc. all that happens is that they modify the in-memory copy of the document that you fetched through `get` before returning it as the query result.
They do not by themselves change the data stored in the table.

In ReQL, only four commands write to the table: `insert`, `delete`, `update` and `replace`.

For your query, `update` is the most convenient because it performs the `merge` implicitly. Your query would look like this:
```js
r.db('test')
 .table('Session')
 .get('c5ce22e2-3587-4841-b9a5-bd4520de8deb')
 .update(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      { flash: {} },
      { flash: { emptyFlash: true } }
    ),
    { flash: {} }
  );
})
```

(Note that `merge` also recurses into sub documents, so `source.merge({ flash: source('flash').merge({ emptyFlash: true }) })` can be simplified to `source.merge({ flash: { emptyFlash: true } })`. In the case of `update` the outer merge is implicit, so we can omit it altogether.)

**Comment by danielmewes** [comment]
See http://www.rethinkdb.com/api/javascript/update/ for more information on the `update` command.

**Comment by gjuchault** [comment]
Note :
```
r.db('test')
 .table('Session')
 .get('c5ce22e2-3587-4841-b9a5-bd4520de8deb')
 .update(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      { flash: {} },
      { flash: { emptyFlash: true } }
    ),
    { flash: {} }
  );
})
```

Is not working but :
```js
r.db('test')
 .table('Session')
 .get('c5ce22e2-3587-4841-b9a5-bd4520de8deb')
 .update(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      { flash: r.literal({}) },
      { flash: { emptyFlash: true } }
    ),
    { flash: r.literal({}) }
  );
})
```

See http://www.rethinkdb.com/api/javascript/literal/

Thanks @danielmewes

**Comment by danielmewes** [comment]
Ah sorry, you're right.
I guess the `r.literal` solution doesn't actually work because of https://github.com/rethinkdb/rethinkdb/issues/4613 though?

You could use `replace`, which is like `update` but without the `merge` and do the `merge` manually again as you did originally:

```js
r.db('test')
 .table('Session')
 .get('c5ce22e2-3587-4841-b9a5-bd4520de8deb')
 .replace(function (source) {
  return r.branch(
    source.hasFields('flash'),
    r.branch(
      source('flash').hasFields('emptyFlash'),
      source.merge({ flash: r.literal({}) }),
      source.merge({ flash: { emptyFlash: true } })
    ),
    source.merge({ flash: r.literal({}) })
  );
})
```

That should allow `r.literal` to work, because it's then directly passed into `merge`.

**Comment by gjuchault** [comment]
Your workaround is working nicely. Thanks for the help.
