### ISSUE TITLE
Possible race condition using `get-all`

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#4616]
## Intro

https://github.com/apa512/clj-rethinkdb/issues/69 was opened with some interesting behaviour when using `get-all`. After tracing this, it seems that RethinkDB is returning different results for the same query. I'm unsure whether this is a race condition, or a standard condition that drivers should expect and handle transparently.

## Problem

Running `(r/get-all table ["id" "cake"] {:index "by-race-id"})` returns the same result ("r") but with either  `SUCCESS_SEQUENCE` (2) type or `SUCCESS_PARTIAL` (3) as the type ("t").

Two example lines from log output:

```
Writing: [4 [1,[78,[[15,[[14,["clj_rethinkdb_test"]],"example"]],"id","cake"],{"index":"by-race-id"}]]]
Reading: [4 {"t":3,"r":[{"id":"6ec8d72a-9d35-405d-92a8-fe10af537016","race-id":"id","test":"document"}],"n":[]}]
              ^^^^

Writing: [5 [1,[78,[[15,[[14,["clj_rethinkdb_test"]],"example"]],"id","cake"],{"index":"by-race-id"}]]]
Reading: [5 {"t":2,"r":[{"id":"6ec8d72a-9d35-405d-92a8-fe10af537016","race-id":"id","test":"document"}],"n":[]}]
              ^^^^
```

## Questions

* Is it expected that the same query can return either SUCCESS_SEQUENCE or SUCCESS_PARTIAL? If so then we'll handle this better in the driver.
* Alternatively, is this a race condition?

## Reproduction

A reproduction repo is available at https://github.com/danielcompton/clj-rethinkdb-test. You can run it by running `lein run` (after installing [Leiningen](http://leiningen.org))

**Comment by danielmewes** [comment]
Hi @danielcompton , this is indeed expected. RethinkDB decides when to send the first batch of a sequence based on a number of criteria.
By default a batch is sent to the driver once the results reach about 1 MB of size, or computing them takes 0.5 seconds, whichever comes first. In addition, these thresholds are reduced by a factor of 4 for the first batch. See the `*batch*` parameters that are described on http://rethinkdb.com/api/javascript/run/ for a full list of criteria.

Especially because of the time limit, the sequence of batches that RethinkDB sends to the client is not deterministic. If all results can be computed within the first batch, it will send a single SUCCESS_SEQUENCE response. In general though, any query that returns a cursor can result in an arbitrary number of SUCCESS_PARTIAL responses followed by exactly one SUCCESS_SEQUENCE response.

I hope that makes sense.

I think it's usually desirable that the driver hides these details.

**Comment by danielmewes** [comment]
If you want to test certain code paths in your driver, I recommend explicitly setting the batch parameters as global optargs to make the server behavior more consistent.

**Comment by danielmewes** [comment]
Note that the official drivers always return a cursor for both of these response types. A direct result is only returned for SUCCESS_ATOM responses.

**Comment by danielcompton** [comment]
Great, thanks a lot for the quick response!

**Comment by danielmewes** [comment]
Also thanks a lot for the great issue report and test code :+1:

**Comment by danielcompton** [comment]
I've opened https://github.com/rethinkdb/docs/pull/843 to explain this point better for future users.
