### ISSUE TITLE
Strange behaviour when doing r.row('field1') + " " + r.row('field2')

### ISSUE THREAD

**Issue by ha1331** [rethinkdb/rethinkdb#4624]
If I do: 

r.db('test').table('table3').update({description: r.row("value1") + " " + r.row("value2")})

is it the intended result really the following: 

{
"description":  "r.row("value1") r.row("value2")" ,
"name":  "137576da-500e-4c36-8ca7-e614d02b1e79" ,
"value1":  "foo" ,
"value2":  "bar"
}

On a side note, the api docs currently have these items for String manipulation (where I think people intuitively look to, when trying to do things to strings):

match
split
upcase
downcase

If people need to concatenate strings, they need to figure out that the information they need, can be found under the "Math and logic" section, and add() is the way to go. How to resolve this without repeating the functions under many sections, I don't know. Current state might be good enough, just wanted to point it out because this came up when I was answering to a question at #rethinkdb  

edit:
also at http://rethinkdb.com/api/javascript/add/  under the section that describes how to concatenate strings, it might be helpful to point out, that you don't need to do: 
r.row('field1').add(" ").add(r.row('field2')) , 
you can do: 
r.row('field1').add(" ", r.row('field2') )

Currently there is an example with array of strings, but at least to me it wasn't immediately clear that you can have multiple comma separated strings inside add() to concatenate them. This might be problem only for us n00bs and I suspect the pro's wouldn't even need to think about it.

**Comment by danielmewes** [comment]
The reason for `{description: r.row("value1") + " " + r.row("value2")}` not working is that we cannot overload the `+` operator in JavaScript. Hence JavaScript simply converts the code into a string, because you're adding a string to it (this happens client-side).
In Python and Ruby we can overload `+`, which is why this code would have worked there.

I'm not sure if we want the same term to appear multiple times in the list. I can see it being useful in this case. Have to think about it a bit.

I'll open a new issue in the docs repo to add an example (or note) for the variadic `add` command.
