### ISSUE TITLE
Starting RethinkDB causes _unsecured_ outbound port 80 connection

### ISSUE THREAD

**Issue by haf** [rethinkdb/rethinkdb#4643]
Giving a :hankey:  here. Blocking the outbound connection gives: `warn: Problem when checking for new versions of RethinkDB: HTTP request to update.rethinkdb.com failed.`

I don't want to have my server-software talk unencrypted over the internet. Please.

To give a  :rose:  though: you only listen on localhost by default!

**Comment by larkost** [comment]
This is just the server checking in with ours for two reasons:
1. Checking to see if there is a newer version
2. Giving us some rough usage numbers so we can prioritize development (so order-of-magnitude on number of servers and tables, etc..)

To disable this you can supply the `--no-update-check` flag and no such connection will be made.

On the assumption that this solves your worry I am going to close this issue, but if I am wrong please re-open it.

**Comment by mglukhovsky** [comment]
@danielmewes: do we have a timeline for adding HTTPS?

**Comment by danielmewes** [comment]
@haf In addition to the `--no-update-check`, I also recommend turning off update checks in the web UI if you're using it. You can get to that option by clicking on the small gear icon at the top. That setting is stored in a cookie, so you'll need to turn it off in each browser you're using and for each RethinkDB server URL you're accessing (if there are multiple).
Long term we will make the web UI update notification use the server-side mechanism, so that supplying `--no-update-check` is going to disable both. We just haven't gotten around to that yet.

**Comment by danielmewes** [comment]
@mglukhovsky Let's do that soon after 2.1. It's about time.

**Comment by haf** [comment]
@larkost Well, the ticket is about me wanting HTTPS. I recognise your need for telemetry.

**Comment by danielmewes** [comment]
@haf ah, we will switch the update check over once we have done https://github.com/rethinkdb/www/issues/104 . Thanks for the reminder!
Also related to https://github.com/rethinkdb/rethinkdb/issues/3988

**Comment by danielmewes** [comment]
Re-opening until we have switched this over to HTTPS.

**Comment by RubenKelevra** [comment]
Great! Don't forget to add certificate-pinning.

**Comment by danielmewes** [comment]
Good news: We've set up an SSL certificate on the update check server (certificate pinning is still pending).
We will switch RethinkDB over to using it asap.

**Comment by danielmewes** [comment]
Starting with 6a06e7fb4d2a8ad7d2237957011620882634091f in v2.1.x and c237672e238f437b44e1008da2b2ae1b9f1df9fa in next, the update check uses https.

**Comment by danielmewes** [comment]
This shipped with RethinkDB 2.1.3.
