### ISSUE TITLE
JavaScript expected arguments errors should be RqlCompileErrors

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4646]
As exemplified in the `polyglot/arity` test the JavaScript driver is reporting a number of errors as `RqlDriverError`s when the other drivers report them as `RqlCompileError`s. The reasons for the current state are internal to how the drivers work, and so not ones that would matter for customers. I would rather we have consistency on this.

Probably every `RqlDriverError` line in `polyglot/arity` should change after this.

**Comment by deontologician** [comment]
Since I'm in the code now and we're changing the errors etc, @danielmewes any opposition to making this change for 2.1?

**Comment by danielmewes** [comment]
It's not necessary, but if it's a quick fix and you make sure that all tests are updated go for it. We will freeze 2.1 once the Python driver error changes are in today though.

**Comment by deontologician** [comment]
OK, I did this the easy way and it's not quite as simple as I'd expected. In order to unify the error specification in the polyglot tests, we'd also have to change how many arguments are reported by the error message. Right now there are numerous that say "expected 0 but found 1", whereas the other drivers say "expected 1 but found 2". I think that's a large enough change not to try to slip it in at the last moment, so I'm not doing this for now.

**Comment by deontologician** [comment]
@larkost if you pick this up later and are interested, the little bit I did is on josh/4646

**Comment by danielmewes** [comment]
Seems like there are also a few cases like this in the Ruby driver: https://github.com/rethinkdb/rethinkdb/pull/4652/files#r3668721

**Comment by danielmewes** [comment]
Was fixed as part of 4669.
