### ISSUE TITLE
Outdated secondary index warning doesn't disappear until restarted

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4664]
In 2.1.0, an outdated index issue doesn't disappear even after the index has been overwritten through `rethinkdb index-rebuild`. Only after restarting the server the issue disappears.

**Comment by Tryneus** [comment]
Looking into this.

**Comment by Tryneus** [comment]
Fix is up in review 3149.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commit 17769fc, and cherry-picked into `v2.1.x` in commit b161f2d.  Will be in release 2.1.2.

The change was actually a TODO for the raft update to have the `outdated_index_issue_tracker_t` operate on the raft state rather than the table's sindex configuration in the data file's btree.  This has the advantage of being much more accurate about the current state of indexes, as well as removing a lot of ugly code.
