### ISSUE TITLE
There's no log about raft leader election when starting without `--deamon`

### ISSUE THREAD

**Issue by ntquyen** [rethinkdb/rethinkdb#4674]
When I start a a rethinkdb node (v2.1) in ubuntu 14.04 . I can see the log about raft leader election. But when start it without `--deamon`, I don't see that log anymore. The same in Mac OS X. I wonder if this is a bug or not.

Another question, is there any way to know the leader node by queries?

**Comment by danielmewes** [comment]
Hi @ntquyen , it's expected that you don't see these messages because the leader election notifications are printed at the "info" logging priority.
We don't print those messages to the terminal. However they should still show up in the `r.db('rethinkdb').table('logs')` table and should be written to the log file. Is that the case?

**Comment by danielmewes** [comment]
About your second question: We don't currently expose which node is the Raft leader through ReQL. Would that information be useful for you?

**Comment by ntquyen** [comment]
I did see the log in the `table('logs')`. Thank you!
I'm OK for the second question! Thanks!
