### ISSUE TITLE
Index joined tables

### ISSUE THREAD

**Issue by frankleng** [rethinkdb/rethinkdb#4686]
Need the ability to create an index after eqJoin()
Ex. we have one table that acts as a collection of geotagged addresses. one table as documents.
We would like to do a geo search on the joined table, and only get documents in which the geo search holds true.

**Comment by danielmewes** [comment]
I'm not sure if I fully understand your proposal.
Do you want to perform post filtering on the results of a join, and use an index for the filtering step?

In some cases it might be possible to use an index for the filtering by inverting the join order, e.g.
```js
r.table('right').getIntersecting(geo, {index: "geo"}).eqJoin("id", r.table("left"), {index: "backIndex"})
```
instead of
```js
r.table('left').eqJoin("leftField", r.table("right")).filter(r.row('geo').intersects(geo))
```

**Comment by frankleng** [comment]
@danielmewes right. but what if you do a .zip().group()
There is no way to use an index in group()

**Comment by danielmewes** [comment]
@frankleng could you post the full query you're trying to optimize?
Would filtering before the `eqJoin` work for you? What is the grouping for?

**Comment by frankleng** [comment]
location table - 
```
[{
  id: '1234',
  geocode: geometry[lat, long],
  city: 'Palo Alto',
  street_name: 'Lyton Ave',
  street_number: 22
},
{
  id: '12345',
  geocode: geometry[lat, long],
  city: 'Mountain View',
  street_name: 'San Antonio Circle',
  street_number: 11
}]
```
```
data table - 
[{
  location_id: '1234',
  data: {...}
  id: 'abcd'
}]
```

**Comment by danielmewes** [comment]
Have you tried something like this?
```js
r.table('location')
  .getIntersecting(...)
  .filter(r.table('data').getAll(r.row('id'), {index: "location_id"}).empty())
  .delete()
```

I can't think of a more efficient way for this at the moment. I'll let you know if something comes to my mind.

**Comment by frankleng** [comment]
@danielmewes assume you mean to use .isEmpty()
but still not getting anything back from the query.

**Comment by danielmewes** [comment]
@frankleng Yes sorry, I meant `.isEmpty()` indeed.

You mean it doesn't delete anything? Do you actually have locations without any data in your table at the moment?

**Comment by frankleng** [comment]
@danielmewes sorry had to resurrect this.
I don't want to delete the orphaned docs in the other table. we need to keep all records because they still contains coordinates and geocoding is rather expensive. 

any other advice?

**Comment by danielmewes** [comment]
@frankleng Wouldn't removing the `delete()` at the end
```js
r.table('location')
  .getIntersecting(...)
  .filter(r.table('data').getAll(r.row('id'), {index: "location_id"}).empty())
```
give you the results you need?

**Comment by frankleng** [comment]
@danielmewes yes. but it's slow if the result set is large. It's useable, but all of our search queries will potentially look like this. So I was wondering if an index of sorts can be introduced.

**Comment by danielmewes** [comment]
Unfortunately an index like this is extremely tricky to implement, especially in a distributed system. The difficulty comes from the fact that we would need to update the index whenever the table `data` changes, not just when `location` changes.
There are all sorts of complicated edge cases in a distributed system with this. What if the server hosting `location` is currently down, and someone changes `data`? We could maybe require some sort of "co-location" of replicas for `location` and `data`, so that there's always a local copy of both.

The way we currently implement indexes is tightly bound to a specific table though. Making it work across two tables would be a really major architectural change. I don't think we'll be able to get to that any time soon.

With changefeeds on joins (https://github.com/rethinkdb/rethinkdb/issues/3997) it will become possible to maintain an index manually with help from your application. Though you'd need to deal with getting it back in sync after a server crash manually.
#3997 might also not cover changefeeds on geospatial joins for the first iteration, though that shouldn't be too difficult to add.

Sorry I don't have any better solution at the moment.

Maybe there's a way you could adapt your schema to have a count of data point directly stored with each location and maintain that count?

**Comment by danielmewes** [comment]
Closing because this is out of scope of our current roadmap.
But please feel free to discuss possible work-arounds further in here.
