### ISSUE TITLE
Waiting for quorum even though all servers are up

### ISSUE THREAD

**Issue by wereHamster** [rethinkdb/rethinkdb#4706]
I have a table with two replicas, both servers are up. But the primary is stuck in `waiting_for_quorum` and the secondary in `waiting_for_primary`. I tried restarting all servers to no avail.

RethinkDB v2.1.1

**Comment by danielmewes** [comment]
@wereHamster can you post the output of `r.table(...).config()` and `r.table(...).status()`?

Could you also email me the output of `r.db('rethinkdb').table('_debug_status')` (daniel@rethinkdb.com)?

After you're retrieved the output of these commands, these steps might help recover from the situation:
1. Shut down the secondary
2. On the primary, run `r.table(...).reconfigure({emergency_repair: 'unsafe_rollback'})`
3. Restart the secondary
4. Run `r.table(...).reconfigure({replicas: 2, shards: 1})` to restore the original configuration

Note that this process can in some cases lose the last few seconds worth of writes, if they hadn't been fully written to both replicas yet.

**Comment by cggaurav** [comment]
@danielmewes ![](http://d.pr/i/1e7xt+) and stuck.
```
e: Table `rethinkdb.debug_status` does not exist in:
r.db("rethinkdb").table("debug_status")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Config
![](http://d.pr/i/16ujV+)

Status
![](http://d.pr/i/19TFx+)

**Comment by danielmewes** [comment]
Thanks for the info @cggaurav .

Sorry, I meant `r.db('rethinkdb').table('_debug_table_status') ` (with an extra `_table`). I'll edit my post above...

Were you able to resolve the issue by either restarting the servers and/or doing an emergency repair as described above?

**Comment by danielmewes** [comment]
@cggaurav in https://github.com/rethinkdb/rethinkdb/issues/5206 you mention that you've since run into the same symptoms that @wereHamster described above.

In most cases where I've seen this, the issue was incomplete network connectivity within the cluster. Often servers were able to connect to another server in one direction, but the other server was unable to open a connection back.

Could you do the following checks in order to debug this?

1. Connect to each server in the cluster individually and directly (you can either use the web UI or any client driver, as long as it doesn't automatically create a connection pool to multiple servers). Then run the following query on each of them: `r.db('rethinkdb').table('server_status')`.
  This will reveal if any pair of servers can't see each other.
2. If nothing shows up in 1, run the previously mentioned `r.db('rethinkdb').table('_debug_table_status')`. The output will be pretty large. It's probably best if you just email it to me (daniel@rethinkdb.com).

**Comment by cggaurav** [comment]
@danielmewes 

1. How can I access the webUI for each of the replicas in the cluster? Wouldn't it defeat the point of a dashboard if we have more than a webUI for a cluster? We use rethinkdbdash for conneciton pooling - is there an easier way to get you server_status of each of the replicas without connecting to them individually?

2. I have emailed you the _debug_table_status?

**Comment by danielmewes** [comment]
@cggaurav Thanks for sending over the `_debug_table_status` output!

While the dashboard generally accumulates issues and stats from across the cluster, this doesn't always work for connectivity issues where the connectivity is inconsistent across servers.
(see https://github.com/rethinkdb/rethinkdb/issues/4936 for an attempt to improve this)

Unfortunately there is no other way to get the individual server's connectivity without connecting to it directly. Depending on what your network setup looks like, you might be able to just point your browser to port 8080 of the server that you want to connect to. Or if port 8080 is behind a firewall, but you are able to `ssh` into the server, you can use an ssh tunnel:
`ssh -L 8081:localhost:8080 <server>`
and then open the web UI via `http://localhost/8081` on your local machine.

**Comment by danielmewes** [comment]
You can also use rethinkdbdash to connect to the other servers, but please make sure that the `discovery` parameter is turned off and that you're only passing in one host name, or `rethinkdbdash` will automatically spread the connections over multiple servers.
See https://github.com/neumino/rethinkdbdash for how to set `discovery` (I think it actually defaults to `false`, so that should work).

**Comment by danielmewes** [comment]
@wereHamster @cggaurav Are you still seeing this?

**Comment by wereHamster** [comment]
I don't run a cluster anymore, so I can't answer that.

**Comment by danielmewes** [comment]
@cggaurav We can't effectively debug this without the connectivity information from each server unfortunately. Have you had a chance to get those outputs when you ran into the issue?

**Comment by cggaurav** [comment]
The outputs were the ones that I sent via email. I haven't faced this since
and positive this was because of initial network connectivity.

**Comment by danielmewes** [comment]
Thanks, I'm going to close this. If this happens again we can reopen.

**Comment by reactor10** [comment]
I have experienced this recently in 2.3.4 with near identical symptoms. IPs had changed, nodes could communicate with each-other, but Raft could not gain a consensus. My workaround was to add `--server-tag (master|slave)` to each of the configs. It seemed to flush any stored config.

Apologies for dragging up an old ticket.
