### ISSUE TITLE
Javascript client connecting to a high availability cluster

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4737]
When using a high availability cluster setup *(version 2.1.1)* with 3 nodes, did the syntax for connecting in the Javascript client change? Currently I am just specifying the primary nodes ip `10.240.102.7` like:

````javascript
r.connect({
    host: '10.240.102.7',
    port: 28015,
    db: 'macd',
    table: 'playground',
    timeout: 10
}, function(error, connection) {
    ...
});
`````

Do I now have to provide all of the nodes in the clusters config host? If not, how does this work if `10.240.102.7` is down?

**Comment by danielmewes** [comment]
You can only provide one server to `r.connect`. If it is down, you need to handle the error provided by `r.connect` to the callback function and try to connect to another server.
There is no `table` argument by the way.

An alternative is rethinkdbdash (https://github.com/neumino/rethinkdbdash), a third-party driver that comes with a connection pool which handles such cases automatically.

**Comment by nodesocket** [comment]
Does the following connection logic make sense, and is it the best way to do this?

    var hosts = ['10.0.0.1', '10.0.0.2', '10.0.0.3'];

Randomly grab one of the hosts out of the `hosts` array and try to connect. If the connection fails, grab another from the hosts array excluding the first host and retry. If that still fails, grab the last host from the array and try to connect. If finally that fails, `return callback(error);`

**Comment by chrisvariety** [comment]
A proxy node would do this sort of thing too, right? http://rethinkdb.com/docs/sharding-and-replication/#running-a-proxy-node

**Comment by neumino** [comment]
I can chime in a bit about rethinkdbdash. Basically with rethinkdbdash you never take care of the connection. It manages its own set of connections and you just call `run()` on a query, and the driver will run the query (or reject the query if no connection is no server is available)

The connection pool (let's call it the pools master) keep one connection pool per available server (servers provided in the `server` field). If you set the mode `discovery: true`, rethinkdbdash will open a changefeed on server_status and kill/create pools as servers join/disconnect from the cluster.

Basically if you do
```
var r = require('rethinkdbdash')({
  discovery: true,
  servers: [ { host: ..., port: ...}, { host: ..., port: ...}, ... ]
})
```

Then you can try to kill/restart a server, you'll see that it's pretty cool :-)

The only caveat (as far as I know) is if the following happen:
- Two server A and B that are not seeds join the cluster
- All the seeds die
- A dies
- B dies
- A restart
At that time you won't be connected because:
- All the seeds are down
- The last server that was available before all server go down is not available

The driver may be updated to reconnect to A at some point, but this its kind of an extreme scenario since it requires all your server to die at some point.

**Comment by danielmewes** [comment]
(closing because it's not a bug or feature request, other than what's already covered by #281)
