### ISSUE TITLE
weird issues with reported table numbers

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#4747]
I've been writing a lot of integration tests using randomly generated uuids for database/table names, and repeatedly slamming a local database with tableCreates/tableDrops, etc. I've found two weird things crop up as a result:

   * the front page of my admin panel now just says:
    ```
    Error

    The request to retrieve data failed. You can try to refresh

    Error:
    ```

   * even though my "Tables" tab in the admin panel indicates I have two tables in the cluster, the "tables" badge on the top right indicates: "Tables - 52/52 ready"

Possibly related. This is with RethinkDB 2.1.1 on OSX 10.10.4

**Comment by danielmewes** [comment]
After talking to @mbroadst on IRC, it looks like the tables aren't visible because their database is missing. They show up in `r.db('rethinkdb').table('table_config')` with `{db: '__deleted_database__'}`,

We're not sure what causes the tables to get into that state yet.
The obvious suspect would be https://github.com/rethinkdb/rethinkdb/issues/4465 , but we think that this operation doesn't happen in @mbroadst's tests.

**Comment by mbroadst** [comment]
duplicate of #4727
