### ISSUE TITLE
Still unable to have secondary indexes migrated in 2.1.2

### ISSUE THREAD

**Issue by bfqrst** [rethinkdb/rethinkdb#4775]
Hi guys,

since Version 2.1.0 and onwards I'm suffering from the `error: Found a secondary index from unsupported RethinkDB version 1.13.  You can migrate this secondary index using RethinkDB 2.0.` In 2.0.x everything was fine. I'm on Yosemite 10.10.5, installed RethinkDB via Homebrew. Here's what I'm getting:

> Running rethinkdb 2.1.2 (CLANG 6.1.0 (clang-602.0.53))...
> Running on Darwin 14.5.0 x86_64
> Loading data from directory /Users/username/rethinkdb_data
> Migrating cluster metadata
> Version: rethinkdb 2.1.2 (CLANG 6.1.0 (clang-602.0.53))
> error: Found a secondary index from unsupported RethinkDB version 1.13.  You can migrate this > secondary index using RethinkDB 2.0.
> Trace/BPT trap: 5

I'm more than happy to hand over the rethinkdb_data folder since it was dummy/test data anyway... Please let me know how I can assist. Love your work!

Cheers
Ralph

**Comment by mlucy** [comment]
Hi Ralph,

Sometimes new features and bugfixes break backward compatibility with old indexes, and those indexes have to be upgraded.  Since it isn't always convenient for users to do this right at release, we usually support older un-upgraded indexes for a few versions.  In 2.1 we dropped support for indexes created with RethinkDB 1.3, so those indexes won't work any more until they're upgraded.

If you re-install RethinkDB 2.0 and open up the web UI, there should be an issue saying something like "this index needs to be upgraded" with a button you can press.  If you upgrade that index and then re-install 2.1, everything should work.

**Comment by danielmewes** [comment]
@bfqrst Note that due to an oversight on our end, additional steps in addition to what @mlucy said might be necessary if you have old tables without any indexes.

If you have previously been on 2.0.x and it didn't show any warnings bout indexes needing to be upgraded, you might need to perform one of the following steps (either works):

1. For each table that does not have any secondary indexes, create a new index and then delete it again. The index does not need to make sense (it can be on a non-existing field), and you do not need to wait for it to complete construction. It's enough to create and immediately delete it again.

2. Wait until we release RethinkDB 2.0.5. This should happen in the next days. Then install RethinkDB 2.0.5 and start it once. That will make sure that all tables without indexes are made compatible with 2.1.x. You can then upgrade back to 2.1.2 and it should start fine.

**Comment by bfqrst** [comment]
@danielmewes Thanks Daniel, installing 2.0.4 an creating a bunch of bogus secondary indexes for each table worked like a charm. After brew installing 2.1.2 I'm back in business. @mlucy As Daniel assumed, there was no complaining about "this index needs to be upgraded"... Anyway, it's working again!

Thanks for the workaround guys. Case closed.

Cheers
Ralph

**Comment by danielmewes** [comment]
For others reading this: We just released RethinkDB 2.0.5, which can be used to automatically upgrade all tables to the secondary index format that RethinkDB 2.1.x can understand.
