### ISSUE TITLE
Rename `new_semaphore_acq_t` to `new_semaphore_in_line_t`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4779]
It behaves like `new_mutex_in_line_t` and `rwlock_in_line_t`, and behaves notably unlike `new_mutex_acq_t` and `rwlock_acq_t`.

**Comment by danielmewes** [comment]
:+1:

**Comment by danielmewes** [comment]
We might also want to give getting rid of the old `static_semaphore_t` and `adjustable_semaphore_t` another shot. The last time this was difficult because of a certain piece of throttling code in the clustering layer. But I think this code is no longer there, so this might have become easier now.
If we can remove these types, we will be able to rename `new_semaphore_t` to `semaphore_t`.

**Comment by mlucy** [comment]
In CR 3372 by @danielmewes .

**Comment by mlucy** [comment]
This is in next.

@danielmewes -- do you think we should put this in 2.2.x too just to reduce the probability of merge conflicts, since it's just a type rename and is unlikely to break anything?

**Comment by danielmewes** [comment]
@mlucy Backporting sounds good.

**Comment by mlucy** [comment]
It looks like this was merged into next but not backported.  Just cherry-picked it into 2.2.x, so I think this issue is done.
