### ISSUE TITLE
Show server processing time, not round trip processing time in Data Explorer

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#4804]
When running queries in the Data Explorer the processing time returned is the round trip time. I would argue that it's more useful to present the server processing time as the primary metric, the RTT includes HTTP which isn't something that any of the drivers do.

I can think of a few options here, but I'm sure there are others too:

1. Show Server time/RTT next to each other
2. Show Server time or RTT as part of the hover text

I know you can see the Server time in the Query profile, but this isn't the default view and could easily be overlooked. As a nice side effect, this would prevent new users from accidentally thinking RethinkDB has high/fluctuating latencies when they are exploring from the Data Explorer.

**Comment by danielmewes** [comment]
Hi @danielcompton, we actually just did that change with RethinkDB 2.1.2: https://github.com/rethinkdb/rethinkdb/issues/4752 :-)

We also stopped reporting timings for queries that return a cursor as part of that change, since we think that those can be misleading (they're hard to properly measure without involving client roundtrips, and if a cursor isn't fully consumed, they wouldn't show the full processing time needed).

**Comment by danielcompton** [comment]
Oops, sorry! I need to upgrade :)
