### ISSUE TITLE
Sync JS driver version on NPM to releases on Github repo

### ISSUE THREAD

**Issue by pauliusuza** [rethinkdb/rethinkdb#4805]
Please publish JS driver v2.1.3 on NPM

**Comment by danielmewes** [comment]
‎It's actually already there except that it's version number is 2.1.1. This is simply because RethinkDB 2.1.1 and 2.1.2 didn't come with updated drivers, so the one we released on Friday with RethinkDB 2.1.3 has the version number 2.1.1.

**Comment by pauliusuza** [comment]
Thanks for the explanation. Since JS driver does not have it's own repo, one can easily assume (like I did) that the versions on NPM correspond to releases on github repo.

Would it not make sense to have these synced in the future?

**Comment by danielmewes** [comment]
That makes sense. I'm not sure if there is a reason for not doing it.
The only one I can think of is if we want to update the JS driver without releasing a new server version. In that case both versions could still get out of sync (unless there's a way in Semver versions to have a fourth version number?).
This is less of a problem in the other drivers, since we use an additional fourth number for driver releases there anyway. That is in addition to the three version numbers that we use to version our server releases.

@AtnNn any thoughts on this?

**Comment by pauliusuza** [comment]
If syncing versions is prohibitive, then maybe it would be better to move the drivers to their separate repositories, and link them as submodules in the server repo?

**Comment by AtnNn** [comment]
We've been keeping only the first two numbers in sync because that's when the driver version syncs up with the server version. Point releases to the driver and to RethinkDB are often done separately.

I believe the current situation is that the latest `x.y.*` driver should work with all `x.y.*` versions of RethinkDB.

I think that ideally the development of the driver and the server would be decoupled and split into separate repositories. Their versions would diverge from each other even more. That would require investing a lot more love and magic into the driver.

Making the drivers submodules would be a good solution in my opinion, but it would require convincing anyone who's used git submodules before that they're worth the trouble.

**Comment by danielmewes** [comment]
Related: https://github.com/rethinkdb/rethinkdb/issues/1740
