### ISSUE TITLE
Missing declare dead option when one of the two servers in a cluster is dead

### ISSUE THREAD

**Issue by kulbirsaini** [rethinkdb/rethinkdb#4806]
This is my current setup

* Linux Mint 17 with Linux 3.13.0-37 x64
* Rethinkdb 2.1.2~0trusty (GCC 4.8.2) (Upgraded from 2.0 to 2.1, 2.1.1 and then to 2.1.2 right after the respective release)
* Two clustered rethinkdb instances on the same machine
* SSD as storage

I go ahead and kill one of the instances. Now, I hunt for the option to declare this instance dead but there is no option anywhere. Two tables (which were replicated/sharded over both instances) are now showing outdated reads. The killed server is also not listed in the `Server` tab in the admin panel. My impression was if I killed one of the two servers, I should be able to declare one of them dead two recover data and to be able to proceed without much headache.

I head over to the affected tables page and manually reduce the shards (2 to 1) and replicas per shard (2 to 1) and click `Apply Configuration`. It takes some time but then does absolutely nothing. No reads/write happening anywhere. I thought it must be doing some internal magic stuff but it stays like that for a few hours and I give up.

![Table Status Page](https://cloud.githubusercontent.com/assets/127315/9736303/f8cd4c98-565d-11e5-9b96-62f4efaf9700.png)

Notice that how it says `Table reconfiguring` but it's a lie :-)

@AtnNn (via IRC) suggests that I should try to use `emergencyRepair` which I did and have everything back to to normal now. I am not sure if I lost any data in the process as I don't really have a way of finding that.

But I still would want the declare dead thing because I don't want to issue any reconfigure commands for wrong tables in a panic situation while dealing with this in a production environment.

**Comment by danielmewes** [comment]
Thank you for the issue report @kulbirsaini .
I've opened https://github.com/rethinkdb/rethinkdb/issues/4811 for the problem that the web UI doesn't show a proper error when it can't apply the configuration change.

The behavior of a RethinkDB cluster has changed considerably with RethinkDB 2.1.0. There is no real concept of a server being dead or even of a server being a member of a cluster anymore. Instead a server can merely be responsible for some replicas of a table. This is why there is no global "declare server dead" option anymore.
Unfortunately the user experience when using the web UI has degraded a bit when trying to remove a server. We're planning to expose the `emergency_repair` option through the web UI in one of the upcoming releases again (see https://github.com/rethinkdb/rethinkdb/issues/4392 ).

For now, you might be happy to hear that `emergency_repair` is actually less dangerous than it sounds. It is *at least* as safe as the old "declare server dead" function. Additionally, trying to apply `emergency_repair` to a table that doesn't need to be repaired will fail, so there's little risk of applying it accidentally.
If your tables only have two replicas, `{emergency_repair: 'unsafe_rollback'}` cannot lose any acknowledged writes. So your data should be in a good state. This is because with two replicas, both replicas have to acknowledge any write before it gets acknowledged back to the user anyway, since that's the only way to reach a majority.

**Comment by danielmewes** [comment]
Unless you have further questions or think we should change anything else, I'd like to close this issue in favor of
#4392 and #4811.

With #4392 it will again be possible to resolve situations like this one directly through the web UI without needing to run any ReQL queries.

**Comment by kulbirsaini** [comment]
Closing this as per above comment.

**Comment by samkelleher** [comment]
I have, 2 servers with a table that has 1 shard (marked as shard1), and 2 replicas - the 'primary replica' on the current server, and the 'secondary replica' on the second server.

Then I kill server 2. I expected the primary server to not be bothered in the slightest since it has the primary, just a secondary replica, an echo of itself, has gone missing.

Instead the primary becomes unreadable and returns `'Cannot perform read: primary replica for shard ["", +inf) not available ` for any query.

I am no longer able to make any changes, such as forcing the primary to forget about the secondary and just carry on.

To frustrate matters, since I'm using dockers I can fire up a hundred more new secondary in the cluster but since they have random names I can't slip in a replacement for the server it's looking for. Nor can make any readjustments to the replication as it times out - I wonder if it's trying to contact the dead server.

**Comment by mglukhovsky** [comment]
@samkelleher: automatic failover requires at least three servers to function, as a Raft election requires a majority of nodes to agree on a new primary. You will need to add a third server.

You can read more about automatic failover here: http://rethinkdb.com/docs/failover/

**Comment by samkelleher** [comment]
Thanks for the pointer @mglukhovsky - I guess I expected a missing secondary replica to have no impact, and the table config had a primary specifically chosen - no no primaries were missing, so nothing to have voted on.  I'm going to continue testing with a minimum of 3 nodes per cluster from now on. I felt that the failure when there were just 2 was amplified since I resolved the issue by manually emergency repairing each table (which set the missing node as disconnected), then reduce the replication to 1, table by table.  Once I had done this, I was free to create new replicas on other nodes.

**Comment by deontologician** [comment]
I believe you can set the secondary as "non-voting" to solve this problem as well in a 2 server cluster

**Comment by danielmewes** [comment]
@samkelleher you can use the `emergencyRepair` option to remove the missing secondary from the table configuration. See http://www.rethinkdb.com/api/javascript/reconfigure . Afterwards you can reconfigure the table normally to add a new secondary.
