### ISSUE TITLE
Crash while building secondary index

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4808]
Brad Gardner reported this on the mailing list: https://groups.google.com/forum/#!topic/rethinkdb/-BgbC473KgI

He tried to migrate indexes for a table, but at some point during the index construction one of his two servers got stuck and wouldn't reply to queries anymore. He had to kill and restart it.
This seems to happen every time for the table.

There are some indications of memory exhaustion. However
- There shouldn't be a reason for index construction to use a lot of memory (unless there are a lot of writes to the table going on while construction is running maybe?)
- The mode of crash, with the server just hanging, isn't typical for an out-of-memory issue. Unless maybe it went into swap...

I'm somewhat concerned that there might have been a table corruption at some point in the past, that's now showing up (https://github.com/rethinkdb/rethinkdb/issues/4769 maybe?).

I'll ask Brad to provide some additional info on this issue.

**Comment by bgardner87** [comment]
I'll dump all of the info I can so far:

We have a RethinkDB cluster of 2 nodes each running on 16GB Digital Ocean VMs.  Neither machine has any swap space configured currently.  I've increased the RethinkDB cache size to 10GB on both installations.

One table in particular is 23 million records so far and we expect it to grow somewhat rapidly.  This table was located on one node 1 with no replication at the time.  Each record in this table should be about 750 Bytes.

I recently upgraded RethinkDB from v1.15 to v2.1.3 and as a result had out of date index issues, so I started to rebuild all indices.  All rebuilt fine except for the largest table which ran for quite some time (I went to bed) and eventually just failed.

The failure was RethinkDB on that node becoming unresponsive, the Web UI was dead and it had disconnected from the cluster.  The process, however, kept running. The next day I couldn't find any issues in the log files, and the only message to the console was that the connection had terminated.  

For my next attempt, I increased the shards for the table to 2, so it's split between the 2 nodes.  My hope was that by splitting the data it would be able to index easier.  During this rebuild, I was watching with htop and noticed that the memory on the systems climbed steadily and eventually completely overwhelmed the system I was connected to, to the point that I was unable to run any commands at all due to lack of memory.  I used Digital Ocean's console to reboot the system.  This time, I did see out of memory errors in dmesg as well as the RethinkDB logs.

My next thought was to delete the index entirely and just re-create it.  After the crashes I had temp indices that, after a 2 more crash/reboot cycles, actually did build themselves.  My thought was I could probably do this with a new index even if it takes a couple of crashes and at least I'd have it built.

If any more information is needed, I'll gladly supply it.

**Comment by bgardner87** [comment]
One more bit of info....

Daniel had me run a count query, which finally returned: 23178452

I'm assuming that was to test that each record could be read to rule out corruption?  In any case, it completed.

**Comment by danielmewes** [comment]
Thanks for all the info @bgardner87 !

Ok so it sounds like this is indeed a memory consumption issue of some sort.

Were there any writes going on to the table or was it mostly inactive or read-only during the index construction?

Assuming you left the replication factor at 2, the sharding might not actually have done anything for this, because each replica would still build the index over the full data set. Only with a replication factor of 1 and 2 shards, the amount of data per server would actually be reduced as far as the index construction is concerned.

You mention that some of the temporary indexes eventually finished constructing. As mentioned in the mailing list, you can make one of them the new main index by running the following query:
```js
r.db('production').table('equipment_point_records').indexRename(`<tmp name>_syrx_num`, `syrx_num`, {overwrite: true})
```
This will complete the index migration.

@bgardner87 I know it's probably going to be a pretty big data set, but is there a chance you could send us a copy of it? We're happy to sign an NDA if necessary. This would allow us to reproduce the issue locally and debug it further. We can give you access to an upload server.

**Comment by bgardner87** [comment]
There were definitely writes happening during indexing throughout the process but I don't recall the throughput.

I left the replication factor at 1 when I added the additional shard for exactly that reason, I wanted to split the data, though long term I don't plan to leave it that way.

I also already deleted the temporary indexes :(

For the data, I'll relay to the client I'm working with but under NDA I don't think that he would have any issues with it.

**Comment by danielmewes** [comment]
Ok, the writes could theoretically explain the memory consumption, assuming there were enough of them.
The reason for this is that secondary index construction in its current implementation uses an in-memory snapshot of the table, so all data modifications that happen during the index construction will be kept in cache.
We have started working on a solution for this in https://github.com/rethinkdb/rethinkdb/issues/2134 , but it hasn't made it in yet (it's a relatively big change).

**Comment by bgardner87** [comment]
By writes happening, I believe it was only during indexing.  I'm running a new rebuild right now and have a series of screenshots I'm taking.  I'll upload the first batch here.

![table-before](https://cloud.githubusercontent.com/assets/4692885/9750515/f5e55954-5666-11e5-823d-45c0e49717c6.png)
![servers-before](https://cloud.githubusercontent.com/assets/4692885/9750517/f5e5c4ca-5666-11e5-99e7-7d695dd9e472.png)
![table-just-started](https://cloud.githubusercontent.com/assets/4692885/9750519/f5e67a78-5666-11e5-8127-2a41fd8cdbde.png)
![servers-just-started](https://cloud.githubusercontent.com/assets/4692885/9750518/f5e64b70-5666-11e5-9107-f4ea1880dc31.png)
![servers-2mins-in](https://cloud.githubusercontent.com/assets/4692885/9750516/f5e57bb4-5666-11e5-82eb-f319b6af1e1d.png)
![table-2mins-in](https://cloud.githubusercontent.com/assets/4692885/9750520/f5e6913e-5666-11e5-9756-b215e5133583.png)
![servers-15mins-in](https://cloud.githubusercontent.com/assets/4692885/9750522/f5eeacca-5666-11e5-9027-714db6941774.png)
![table-15mins-in](https://cloud.githubusercontent.com/assets/4692885/9750521/f5eeb080-5666-11e5-8b9d-41a6c46adc67.png)

**Comment by bgardner87** [comment]
Last batch of screenshots, this time the index rebuild did finish but used quite a bit of memory across both nodes, it seems splitting the data was a good choice in this instance.

![servers-30mins](https://cloud.githubusercontent.com/assets/4692885/9750829/3177195e-566b-11e5-9264-421b7740904e.png)
![table-30mins](https://cloud.githubusercontent.com/assets/4692885/9750831/3178351e-566b-11e5-80ef-eafec722f6fe.png)
![servers-40mins](https://cloud.githubusercontent.com/assets/4692885/9750830/31780b52-566b-11e5-9961-f0a8902227fe.png)
![table-40mins](https://cloud.githubusercontent.com/assets/4692885/9750832/31791cb8-566b-11e5-9f9e-c3a8db30316f.png)

**Comment by danielmewes** [comment]
Thanks for the screenshots @bgardner87, that's a great documentation of what's going on throughout the process. :-)

So it seems like my write theory doesn't apply here, since the writes were only those that came from the secondary index construction itself.

The maximum memory usage appears to be 13.0 GB on each server, which is 3 GB above the 10 GB array size limit. This is certainly more than I would expect, and it's also concerning that it appears to grow further when the table is not sharded.

I wonder if there might be a problem due to which the snapshot used by the secondary index construction somehow keeps snapshot metadata for the very index that's being constructed around. So it would basically snapshot the very data it's writing (except that since the (temporary) index didn't exist before, it would only keep some metadata and no actual data blocks).
I'll check if that could be the case.
If it is, there's probably an easy fix in that we could snapshot only the primary branch of the btree, and not the secondary index trees.

@bgardner87 I'm going to see if I can reproduce this with an artificial test data set first. If I'm not successful, I might email you later about the NDA + data upload. Thanks for your help so far in tracking this down!

**Comment by danielmewes** [comment]
It definitely looks like we're snapshotting everything during a secondary index construction.
I think this might become an even bigger problem if someone migrates multiple indexes on the same table, and one of them finishes first and causes the old index to get deleted. In that case the remaining index construction would force the creation of a full snapshot of the old index, which would be kept in memory.

So in any case I'm going to limit the snapshotting to the primary btree.
I'm also going to try to reproduce the specific issue @bgardner87 ran into, and see if that would be solved by the same change as well.

**Comment by danielmewes** [comment]
Uhm never mind. My theory about the snapshotting issue was wrong (once we release the superblock, we automatically stop keeping snapshots for the index trees it seems).

**Comment by bgardner87** [comment]
I don't know if this is related, but I am working towards a 3 node + proxy deployment and have added the 3rd node tonight.  During rebalancing, I'm having similar issues and the servers are running out of memory and crashing in rotation.  I've dropped the cache size back to default, so that will take affect on the next round of reboots and I'll see if that helps keep things alive.

In either case, it may not just be index rebuilding, right now the only thing happening is backfilling.  I've set the large table to 3 shards with 3 replicas.

**Comment by bgardner87** [comment]
If it helps with reproduction, this is the format of our record with field names obscured:

{
"a1": Fri Jan 30 2015 23:41:02 GMT+00:00 ,
"a2": Thu Jul 31 2014 04:45:00 GMT+00:00 ,
"a3": 0.25 ,
"id":  "000002dc-ac1b-4b67-8056-801b23657865" ,
"a4": 31 ,
"a5": 3 ,
"a6": 4 ,
"a7": 7 ,
"a8": 2014 ,
"a9":  "test" ,
"a10":  "330938-246-238216001005001004-EP-187" ,
"a11": 70.5 ,
"b": {
	"b1": 30.06 ,
	"b2": false ,
	"b3": Thu Jul 31 2014 04:00:00 GMT+00:00 ,
	"b4": 63 ,
	"b5": false ,
	"b6": 29 ,
	"b7": false ,
	"b8":  "9508240e-5d40-4793-8e80-113bd3a46039" ,
	"b9": 2014 ,
	"b10": 67 ,
	"b11": false ,
	"b12":  "7f931d5e-1efa-4650-bfd7-4e2ca12aebf4"
	}
}

**Comment by danielmewes** [comment]
Quick update for other readers on this issue: We've worked together to track down this issue, and so far it looks a lot like memory consumption is simply too high. @bgardner87 reduced the cache size on the servers which appears to have helped.

Part of the memory overhead stems from https://github.com/rethinkdb/rethinkdb/issues/1951 , which we are working on fixing.

**Comment by danielmewes** [comment]
I'm closing this since it looked like this was mainly a memory consumption issue.
RethinkDB 2.2 came with a redesign of secondary index construction logic and it also reduced the general memory overhead for large data sets.

@bgardner87 please let me know if there are still any issues that we need to look into.
