### ISSUE TITLE
JS SSL doesn't work with node 0.10.7 (but works with 0.12.2)

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4816]
Running this code:

``` js
var r = require('./rethinkdb');
var fs = require('fs');  

   r.connect({
     host: 'aws-us-east-1-portal.3.dblayer.com',
     port: 10575,
     authKey: 'XXX',
     ssl: {
       ca: fs.readFileSync('/tmp/daniel/cacert')
     }
   }, function(error, conn) {
     if (error) { console.log(error); return; }
   });
```

I'm getting the following error with node 0.10.7:

```
Could not connect to aws-us-east-1-portal.3.dblayer.com:10575, operation timed out.
```

However it works with node 0.12.2.

We should check that we aren't relying on some behavior or timing that's not guaranteed (though it might obviously be a bug in the older version of Node.js).

**Comment by cwohlman** [comment]
I ran into this bug as well. There are two problems:

1. Whatever kind of stream is being returned by the tls connection doesn't appear to have a connect event. Instead you need to handle the connect/error using a callback.
2. Node 0.10's version of pbkdf2 doesn't support passing a digest argument and uses HMAC-SHA1 by default, instead you need to use this npm package: pbkdf2-sha256

In order to fix this I cloned the rethinkdbdash npm package (I'm not very familiar with coffeescript and was in a rush), the code is almost identical to your connection code. Here's the diff: https://github.com/neumino/rethinkdbdash/pull/264/files

**Comment by chrisvariety** [comment]
FYI, Node 0.10 has its end of life in October 2016, so personally I wouldn't put too much effort into it.

**Comment by gabor-boros** [comment]
Since 4 years passed since EOL of Node 0.10, I'm closing this issue.
