### ISSUE TITLE
I can not access to 28015 port from out side world in Google cloud engine vm

### ISSUE THREAD

**Issue by aokudan** [rethinkdb/rethinkdb#4817]
I am developing nodejs application. And also new Linux systems. I installed RethinkDB to google compute engine instance. I can access to 28015 driver port locally. But I can not access to the driver port (28015) so that it cannot be accessed from the outside world. So I did it below commands. But I got some errors.

test@rethinkdbserver:~$ sudo iptables -A INPUT -i eth0 -p tcp --dport 28015 -j DROP
test@rethinkdbserver:~$ sudo iptables -I INPUT -i eth0 -s 127.0.0.1 -p tcp --dport 28015 -j ACCEPT
test@rethinkdbserver:~$ ssh -L 28000:localhost:28015 100.100.63.63
The authenticity of host '100.100.63.63 (100.100.63.63)' can't be established.
ECDSA key fingerprint is cc:21:56:de:f1:72:j3:64:50:k4:0b:42:e2:5f:db:63.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '100.100.63.63' (ECDSA) to the list of known hosts.
Permission denied (publickey).
I get this error

The authenticity of host '100.100.63.63 (100.100.63.63)' can't be established. ECDSA key fingerprint is cc:21:56:de:f1:72:j3:64:50:k4:0b:42:e2:5f:db:63. Are you sure you want to continue connecting (yes/no)? yes Warning: Permanently added '100.100.63.63' (ECDSA) to the list of known hosts. Permission denied (publickey).

**Comment by beefsack** [comment]
This may not be the best place to be asking general Linux questions, perhaps http://unix.stackexchange.com/ is a better place to try.

**Comment by mlucy** [comment]
@aokudan -- Does it work if you pass `--bind all` when launching RethinkDB.

**Comment by danielmewes** [comment]
This looks like a problem with your SSH configuration. Like @beefsack says, you might be able to get better help for that problem in a Linux-specific forum.
How do you normally connect to your server through SSH? You can simply add the `-L` option to your usual `ssh` command and it should start forwarding the port.

What are you intending to do with the `iptables` rules? If you use an SSH tunnel to bind the RethinkDB port to `localhost` on your local server, the `iptables` rules are probably unnecessary.

Finally, note that using `--bind all` is dangerous because it opens up access to your RethinkDB database for *everyone* on the Internet, unless you also set up a firewall to restrict it. Using an SSH tunnel is usually the much safer option.
