### ISSUE TITLE
Feature: Support for ES6 Lambda in JS API

### ISSUE THREAD

**Issue by AdamBrodzinski** [rethinkdb/rethinkdb#4821]
I'm just starting out and I noticed how awesome the API is. I think it would be an awesome feature if you could match the Python syntax.

example:

```
    // in JavaScript
    r.table('users').filter(user => user.age > 30).run(conn, callback)
 
    // instead of 
    r.table('users').filter(r.row('age').gt(30)).run(conn, callback)

   // python eq.
    r.table('users').filter(lambda user: user['age'] > 30).run(conn)
```

**Comment by danielmewes** [comment]
I think this should already work, with one small modification:
```js
r.table('users').filter(user => user('age').gt(30)).run(conn, callback)
```

We cannot overload the `>` operator in JavaScript, because it doesn't support operator overloading (we use operator overloading in the Python and Ruby drivers to enable this syntax). As far as I know that's still true in ES6.

There seems to be a way to turn `user.age` into `user('age')` in ES6 using proxy objects (I found this SO thread on the topic http://stackoverflow.com/questions/20147081/javascript-catch-access-to-property-of-object ). I'm not sure how well it would work in practice, because we would have to make sure that all ReQL commands can still be called on a query object without being turned into a `getField` call. But it sounds worth considering.

**Comment by neumino** [comment]
I tried in rethinkdbdash to use ES6 proxy go replace the bracket term with a dot. It's actually surprisingly tricky to do. I ran into tons of issues.

**Comment by marshall007** [comment]
@danielmewes like @neumino said we were working on exactly this over in neumino/rethinkdbdash#95. The only real issue I ran into was after wrapping `Term` in a `Proxy` object I could no longer get those objects to pass `instanceof Term` checks.

It's really awesome to use, though. If someone can figure that part out I think we should definitely do it in the official driver.

**Comment by neumino** [comment]
Yea I had this issue with `instanceof`. I patched by adding a new method like `_isTerm`. But then I ran into other issues like `Object.keys(<proxy>)`, `<proxy>.hasOwnProperty`, `JSON.stringify` etc. Every time I was patching something, another issue was coming up.

It's probably doable, but it's just a bit tedious I think.

**Comment by deontologician** [comment]
Since lambdas work and operator overloading isn't possible [yet](http://www.slideshare.net/BrendanEich/value-objects). I think we should close this issue. The bracket syntax vs. attribute syntax seems nice, but that wasn't in the original request. I have some qualms about the attribute syntax, but I think we should open a new issue for that if it's something people want.

**Comment by danielmewes** [comment]
Ok let's keep an eye on the dot syntax for field access (though it seems difficult enough that it's probably not worth doing at the moment). Closing this.

**Comment by AdamBrodzinski** [comment]
Sounds good to me. Thanks for all the feedback!

**Comment by deontologician** [comment]
@AdamBrodzinski I just remembered, if you're really interested in infix operators for js, I wrote a small sweet.js preprocessor that works (mostly, there are lots of edge cases): https://gist.github.com/deontologician/e65923823e0c3111c880

**Comment by AdamBrodzinski** [comment]
@deontologician cool i'll check it out!
