### ISSUE TITLE
Crash when stopping service after lock-up

### ISSUE THREAD

**Issue by Cherry** [rethinkdb/rethinkdb#4823]
After upgrading our code-base to 2.1.3, we've been experiencing complete lock-ups where RethinkDB will stop accepting connections entirely, and any active ones no longer function. We haven't been able to isolate an exact cause for this phenomenon, however appears to be happening pretty much every day or so. It's worth noting that we didn't experience this issue with 2.0.4.

After issuing a "service rethinkdb stop", it takes quite a while to fully stop, and then the log looks like the following: http://pastebin.com/BsSp0y9Y

We're only using 1 server, with no additional replicas or shards at this time. Our database sits at around 3.6GB, with 25 tables, and 5 secondary indexes. Our database config file can be found at http://pastebin.com/Ad7uZ3LD. I'm happy to provide any further information, as I know the lack of information here isn't fantastic!

**Comment by VeXocide** [comment]
It's the guarantee at https://github.com/rethinkdb/rethinkdb/blob/next/src/clustering/administration/namespace_interface_repository.cc#L163 that's triggered, the formatted backtrace is below.

```
1: backtrace_t::backtrace_t() at 0xb0cb10 (/usr/bin/rethinkdb)
2: format_backtrace(bool) at 0xb0ce70 (/usr/bin/rethinkdb)
3: report_fatal_error(char const*, int, char const*, ...) at 0xd0ed00 (/usr/bin/rethinkdb)
4: namespace_repo_t::create_and_destroy_namespace_interface(namespace_repo_t::namespace_cache_t*, uuid_u const&, auto_drainer_t::lock_t) at 0xbf1bc5 (/usr/bin/rethinkdb)
5: callable_action_instance_t<boost::_bi::bind_t<void, boost::_mfi::mf3<void, namespace_repo_t, namespace_repo_t::namespace_cache_t*, uuid_u const&, auto_drainer_t::lock_t>, boost::_bi::list4<boost::_bi::value<namespace_repo_t*>, boost::_bi::value<namespace_repo_t::namespace_cache_t*>, boost::_bi::value<uuid_u>, boost::_bi::value<auto_drainer_t::lock_t> > > >::run_action() at 0xbf1fff (/usr/bin/rethinkdb)
6: coro_t::run() at 0xa34668 (/usr/bin/rethinkdb)
```

**Comment by danielmewes** [comment]
Sorry you're running into this, and thanks for reporting it @Cherry .

I think the crash on shutdown might be a red herring, since it looks like it would be a side-effect of the lock-up. It might still give us some pointers about where to look for the lock up though.

@Cherry A few questions:
Are you performing any meta operations, such as table creation, dropping tables, reconfiguring tables (I assume not, since it's a single server?), creating secondary indexes, etc.?

What are the rough types of queries that are being run? Do you use changefeeds? Are there writes? Mostly single-document writes or also large range writes (write queries affecting many documents)?

I can see in your config file that you set the number of cores to 4 (`cores=4`). How many logical cores does the server actually have?

The next time the lock-up happened, could you check how much RAM is available (e.g. through htop)?
Is the server configured with a swap partition (or file)? If you look at the output of `free -m`, is any of the swap space currently in use? I'm just wondering if the rethinkdb process might somehow end up going into swap, which could theoretically explain the stalls (how much RAM does the server have?).

**Comment by Cherry** [comment]
Thanks for follow-up @danielmewes!

We're not doing any meta operations in real-time, no. We do have a handful of secondary indexes (5) but these aren't ever created/destroyed in our code-base automatically, and the same for table creates/destroys.

In regards to queries, we do a very large number of reads almost constantly, and only ever single document writes. RethinkDB powers our core internal API, which can push about 5000rpm, the majority of which would interface with RethinkDB in some mechanism.
We do a lot of reads on large data sets (some 3M+) using secondary indexes, and then a lot of joins, etc between various tables using filters and such where necessary. Changefeeds aren't used yet. Here's a quick example of what our WebUI generally looks like: http://jross.me/l/maux5

The machine running our DB sports 16GB of ECC RAM, and an E5-1650 v3 (6 physical cores, 12 threads). All RethinkDB data sits on a 240GB SSD. Swap is currently configured at 8GB and completely empty. The OS is on a 1TB HDD.

I'll watch for the next time this happens and try to get some more statistics on RAM usage, CPU, swap, etc. Thanks for your help!

**Comment by danielmewes** [comment]
@Cherry Has this happened again?

**Comment by Cherry** [comment]
Unfortunately not. The only change we've made internally is disabling a script that had a couple of constant running change-feeds, for monitoring purposes.

For reference, the disabled script was performing the following queries:

```javascript
r.connect(config.rethinkdb).then(function(c){
	r.table("stats").filter(r.row("id")(0).eq("cluster")).changes().run(c)
	.then(function(cursor){
		cursor.each(function(err, item){
			io.to('stats').emit("rethink_stats", item);
		});
	});

	r.table("server_status").changes().run(c)
	.then(function(cursor){
		cursor.each(function(err, item){
			io.to('stats').emit("rethink_servers", item);
		});
	});
});
```
where `io` is a socket.io server. We highly doubt this was causing any issues, but it hasn't been enabled since reporting this issue.

**Comment by danielmewes** [comment]
It has been a while, so I'm going to close this since we don't have any current leads on this and the issue has disappeared for @Cherry as far as I know.

Please re-open if you see this again.
