### ISSUE TITLE
Analytics use-cases, and full text search

### ISSUE THREAD

**Issue by stephanbuys** [rethinkdb/rethinkdb#4828]
Hi,

I'm very interested in trying RethinkDB for some analytics use-cases, but also possibly search. We have a long history of using Splunk (commercial time-series db), and the similarities between Splunk's SPL (query language) and the ReQL paradigm which makes RethinkDB incredible compelling. We've been using Elasticsearch extensively as it allows for full-text search across massive datasets (its not unheard off to have millions or billions events - think authentication logs in large business) and supports "aggregations", the ability to roll up certain columns (sum, avg, max, etc).

I would love to try Rethink and get going with ReQL, as it seems very intuitive and powerful, so my questions are:

1) Can RethinkDB handle massive time-series datasets? Other DBs such as MySQL and Postrgresql often start struggling when tables get massive and index-updating-time starts to hinder inserts.
2) Can RethinkDB be configured to be an efficient 'search engine'? One of the great things of Elasticsearch is that it indexes everything by default which makes investigating massive event datasets feasible.

Would be awesome to hear from the minds behind RethinkDB as to the feasibility of these use-cases.

Cheers!

**Comment by danielmewes** [comment]
Hi @stephanbuys,
RethinkDB can generally handle large data sets. However there are a few limitations to be aware of. Firstly, RethinkDB is primarily optimized for SSD storage. With large data sets on rotational drives, you might see reduced performance for analytical queries. Secondly, there is a memory overhead of about 2-5% of the total data size (#1951).

RethinkDB doesn't currently have good built-in full-text search. We typically recommend replicating the data into ElasticSearch, and using that for full-text indexing (see http://rethinkdb.com/docs/elasticsearch/).

**Comment by stephanbuys** [comment]
Hi @danielmewes,

Thanks very much for the response. Do you have any numbers to share wrt table size, etc. Are there any special considerations when it comes to 'analytics' data? You mention a memory overhead, I'm not sure how that will be triggered? 

I'm under the impression that Elasticsearch is deprecating the 'rivers' plugins in favour of just ingesting data using Logstash. That said I image it would be easy to integrate RethinkDB with something like RabbitMQ to publish any changes (as per some sort of ReQL query), and then push those to Elasticsearch via Logstash (consuming form RabbitMQ or Kafka)?

**Comment by deontologician** [comment]
@stephanbuys Just a quick note, we do have a beta for our logstash plugin : https://github.com/rethinkdb/logstash-input-rethinkdb

**Comment by danielmewes** [comment]
@stephanbuys The general rule of thumb for the memory overhead at the moment is that you'll need 5% of your total data size times the replication factor to be available as RAM in your cluster.

If for example you're storing 1 TB of data, and you want to replicate your data to two servers, you should have a total of 50*2=100 GB of RAM available in your cluster. For example four servers with at least 25 GB each, or two servers with at least 50 GB each.
(We're soon going to reduce this requirement a bit.)

For analytics data specifically, I strongly recommend using SSD storage rather than rotational drives. Analytical queries can become very slow in RethinkDB when run against data stored on rotational drives.

**Comment by stephanbuys** [comment]
@danielmewes thanks again for your patience, this is sounding better and better :)

My next question is related to indexing, by default Elasticsearch with its Lucene shards indexes everything by default, and a common pattern would be to dump everything into an "index" (read db, mostly called logstash-YYYY-MM-DD) and use filters to quickly find all docs with certain tags/keywords for a certain time-range, then run aggregations on those.

My intuition is that with RethinkDB instead of dumping everything into one table one would create a table per 'data-source', then make the timestamp the primary key. I think I read that its indexed by default. Lets image I'm saving a bunch of syslog messages, primary key is the timestamp, then I have a 'message', a 'service' and a 'host' field. If I want to do something like "Give me the count of messages by host and then by service", would it make any sense to add additional indexes to the 'host' or 'service' fields?

I might then subscribe to that query and send updated 'count by host by service' messages to a front-end dashboard.

Products like Splunk and Elasticsearch then go one step further and create new 'buckets'/'tables'/'indexes' at a semi regular interval (maybe once a day), to assist with closing out and archiving old analytics data - does that model map to RethinkDB (and not seriously break something)?

**Comment by danielmewes** [comment]
For a query like "Give me the count of messages by host and then by service" it's not really necessary to add a special index. Since all data will have to be traversed anyway to get the final result, the index doesn't significantly reduce the amount of data the query has to look at in this case.
Indexes are most useful if your query only selects a small part of the data, and you can use the index to efficiently filter the data accordingly.

Note that you cannot subscribe to queries of this type directly yet, though we're working on it (see #1118). You can simulate a changefeed on such a query by getting a changefeed on the whole underlying table, and updating the counts on the client whenever a document in the table gets changed/inserted/deleted.

You can definitely use a similar architecture for archiving data periodically with RethinkDB, and I know that some people are using such a system. You will just need to implement the logic for moving data over yourself.
