### ISSUE TITLE
Ability to provide an array/list as a parameter in .table(...).get_all( [..., ..., ...] )

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4849]
Although @larkost mentioned there would be some implementation problems I think this would be a lot more natural way to retrieving an array of documents given that I have their associated `id`s. 

Right now in Python I have to add the `*` splat to take the list and apply the contents as individual parameters this: 

```python
list_of_ids = [...]

r.table("test").table("test").get_all(*list_of_ids) 
```

My other options are using `.map` but that doesn't seem very intuitive or ergonomic for this use case, or running `r.get(...)` for each element in the list which seems inefficient.

**Comment by danielmewes** [comment]
We can't do this directly for `get_all`, because your keys might be arrays and we couldn't distinguish a get for a single key `get_all([component1, component2, ...])` from a get for multiple keys `get_all([key1, key2, ...])`.

Apart from `*`, you can use `r.args` for this:
`get_all(r.args([key1, key2, ...]))`

In the PHP driver I have a separate `getMultiple([key1, key2, ...])` method, but that's primarily because I'm not using variadic methods in the driver in general. I think adding that to our official drivers would be overkill.
