### ISSUE TITLE
is rethinkdb python driver eventlet compatible?

### ISSUE THREAD

**Issue by cad** [rethinkdb/rethinkdb#4865]
Is it safe to use RethinkDB python driver w/ eventlet library at the moment?

**Comment by deontologician** [comment]
gevent support was started in a branch ( see #4433) but I don't know if that helps with eventlet support. In any case, it doesn't look like support for either has made it into a released driver (@Tryneus feel free to correct me)

**Comment by Cad** [comment]
so obviously it is not. Thanks for the reply.

**Comment by larkost** [comment]
@Cad From my brief read of `eventlet` it looks like it might be trivial to create a version of our runloop that would support it, namely replacing `import socket` in `./drivers/python/rethinkdb/net.py` with:
```
import eventless
eventlet.import_patched('socket')
``` 
Because it is only patching the i/o methods, we can probably get away with that change only (plus some additional support files). If this is important to you please re-open and maybe we can schedule this. Note that I am slightly on-the-fence about whether it would be ok to use the same connection in multiple `eventlet` "threads".

**Comment by Cad** [comment]
@larkost to have it would be great. Frameworks that use eventlet for concurrency, can not use rethinkdb currently. Thus they are missing out and technically forced to use mongo or other stuff.
