### ISSUE TITLE
Sync error when running inside Docker

### ISSUE THREAD

**Issue by ggarnier** [rethinkdb/rethinkdb#4881]
I'm running RethinkDB 2.1.3 inside Docker (using the [official image](https://hub.docker.com/_/rethinkdb/)). It's working fine, but I'm getting this error message:

    Failed to sync parent directory of "/data/rethinkdb_data/tmp/post_construction_a82ec30f-02ce-47a1-8849-7f1beff19570.create" (errno: 22 - Invalid argument). You may encounter data loss in case of a system failure. (Is the file located on a filesystem that doesn't support directory sync? e.g. VirtualBox shared folders)

I'm in a Mac with Mountain Lion, and Docker is running with boot2docker. Here is my `docker info` output:

```
Containers: 4
Images: 121
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 130
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: J24G:HNJY:2UWF:V7GS:RIQI:OY2W:ABLV:HS7K:O6M3:E4E3:46QX:7O3A
Debug mode (server): true
File Descriptors: 21
Goroutines: 34
System Time: 2015-09-24T15:08:15.026859417Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

**Comment by encryptio** [comment]
The only thing that failure warning is telling you is that if the system (the virtual machine OR its host) crashes or is forcefully shut down, you might get corrupted (and possibly unrecoverable) data files. If you see this on real hardware in production, that's a warning to heed, but for `boot2docker`'s typical use cases it should be fine to ignore; you can likely just start over if you need to.

From looking around, lack of `fsync` support on dirs is a common issue with `boot2docker`: see [this gist about a workaround using sshfs](https://gist.github.com/sevastos/2fa4c86f01541351efe8) and [this SO question](http://stackoverflow.com/questions/29818433/boot2docker-on-windows-running-mongo-with-shared-folder-this-file-system-is-n), among various others. They all mention MongoDB because it's more aggressive about this risk, but it should be easily to do the same for RethinkDB as well, if you want to.

**Comment by danielmewes** [comment]
Like @encryptio this is expected currently. We cannot fully guarantee data durability and consistency in case of crashes on these file systems, but in practice things are likely to still work fine.
