### ISSUE TITLE
Allow TLS for all connections.

### ISSUE THREAD

**Issue by kevincox** [rethinkdb/rethinkdb#4953]
It is becoming very common for all intra-datacenter connections to be encrypted. Currently rethinkdb makes this very difficult. For the client connections there are recommendations for SSH tunnelling in the docs and TLS connections support in most drivers. However running TLS requires a manual proxy that is not integrated with rethinkdb. Furthermore there appears to be no way to encrypt server-to-server traffic.

The primary benefits of integrating TLS into the server are:
- Intra-cluster traffic can be encrypted.
- Strong and simple authorization can be supported using the SSH key infrastructure.
  - Client certificates can be used for authentication.
  - A CA key can be used to sign all of the clients certificates.
  - Authorized keys (and CA keys) can be managed in rethinkdb tables.

This allows a better authentication system that can be easily managed from rethinkdb itself, without requiring orchestration of many proxy processes that have to be managed individually.

Another eventual target for this could be the webui but personally I see that as a much lower priority.

**Comment by kevincox** [comment]
Related to:
- https://github.com/rethinkdb/rethinkdb/issues/4074
- https://github.com/rethinkdb/rethinkdb/issues/3158

**Comment by danielmewes** [comment]
I agree that this is becoming very important to simplify the setup on distributed cluster infrastructure.

Since we already have https://github.com/rethinkdb/rethinkdb/issues/3151 for intra-cluster and https://github.com/rethinkdb/rethinkdb/issues/3158 for client connections, I'm going to close this as a duplicate.
Would you mind commenting in those threads?
