### ISSUE TITLE
Insert behavior change when `id` = null

### ISSUE THREAD

**Issue by al3xandru** [rethinkdb/rethinkdb#498]
In the previous version this worked (generating a server side id):

```
r.table('t').insert({ id: None })
```

In the current version (1.4) it fails:

```
Primary keys must be either a number or a string (got null of type NULL).
```

I think the behavior in the previous version is what an user would expect. (The app initializes a new model instance, thus having a null id, and JSON serializes it to { 'id': None })

**Comment by spiffytech** [comment]
*bump*

Running into this in my own code, where it's irritating to strip null `id` fields from my records before transmitting. Any chance of getting this back on the roadmap?

**Comment by coffeemug** [comment]
@mlucy -- how do you feel about this now that some time has passed? Do you think `r.table('t').insert({ id: null })` should generate a key instead of throwing an error?

**Comment by mlucy** [comment]
@coffeemug -- it doesn't seem obviously correct or obviously incorrect to me.  We've been trying to make `null` and non-existence more similar, but in this particular case it doesn't quite feel right (especially since we've considered making `null` a legal index value before, and are probably going to make it a legal secondary-index value to support the `orderBy` thing).

Marking this as a ReQL_proposal and moving into `subsequent` so we can discuss it in-depth next ReQL discussion period.

**Comment by srh** [comment]
Closing because old.  FWIW my take is that allowing null would silently some permit end-user bugs, make users spend more time debugging.
