### ISSUE TITLE
Raft election causing rethink to crash

### ISSUE THREAD

**Issue by mariostallone** [rethinkdb/rethinkdb#4980]
I've been using rethinkdb in production over the last 15 days on a fairly high scale environment. I've had it fail twice. 
I have a 3 machine cluster setup.
The first time it threw errors was when it was trying to elect a new raft leader. The other 2 servers were disconnected from the machine I was using my application server to connect to. This lasted in all for about 8 mins and it stabilised by itself.

The second instance was fatal. The first machine in the cluster died, i.e. rethinkdb was terminated. It had to be brought back up manually.

These were the last few logs before it died.
```
2015-10-22T08:25:53.554220227 1870727.610543s notice: Disconnected from server "rethinkdb3"  <hash>
2015-10-22T08:26:04.410635825 1870738.466958s info: Table <hash>: Starting a new Raft election for term 187.
2015-10-22T08:26:14.290542789 1870748.346865s info: Table <hash>: Raft election timed out. Starting a new election for term 188.
```

Questions.
1) Where can I find out additional logging as to why rethink might have shut down? Previously when rethink had shutdown, there were genuine errors I could refer to, to see the problem
2) Does using rethindb-proxy in such a situation help? Would it better for me to connect my app server to the proxy instead?

**Comment by coffeemug** [comment]
@mariostallone -- I have a few questions that should help diagnose this:

- What exactly do you mean by "when it was trying to elect a new raft leader"? Do you remember what operation you tried to perform (since leader election is something that happens internally, not something a user does).
- Could you check the RethinkDB log files on each machine for stack traces? (Depending on how you run Rethink, log files will probably be in `/var/log/rethinkdb.log`)

FYI, RethinkDB processes don't automatically restart if there is a crash. If a node fails, the other two nodes will continue handle the requests if sharding/replication is properly set up. Your app server does need to reconnect to other working nodes. Depending on which driver you use, the driver might support that automatically (I believe `rethinkdbdash` does), you can do it manually, or you can connect your app server to the proxy.

The proxy would help in this situation -- if one of the nodes fails, the proxy will automatically reroute your app's requests to other nodes.

**Comment by danielmewes** [comment]
To clarify the first incident: Do you mean the two other servers got disconnected due to some problem in RethinkDB, or were they disconnected due to unrelated reasons (maintenance, networking issues etc.)?
Note that Raft elections are expected to fail if only one out of three servers are left.

For the second issue where RethinkDB terminated: In addition to RethinkDB's log files, you might also want to check your kernel log (`dmesg -T`, might also be logged to `/var/log/syslog` and/or `/var/log/messages`) for messages concerning out of memory conditions. If RethinkDB ran out of RAM, the kernel's OOM killer might have terminated it, in which case you wouldn't see anything in the RethinkDB log (but it would generate a message in the kernel log).

**Comment by mariostallone** [comment]
@coffeemug @danielmewes Thanks for your responses..

Answers to the questions above...

"when it was trying to elect a new raft leader" - I was referring to the logs where leader election was happening internally, which seems to have been the cause for the disconnection... I assumed that it might have been the cause as these were the last few messages in the logs...

To clarify the first incident : I believe the other two servers got disconnected due to some problem that might have arisen from the raft election process, as these were the last few logs I saw before the other servers were disconnected...

About the second incident, which occurred once again, I noticed that it might have been due to an OOM situation as you suggested...
I'm looking at migrating to using rethinkdbdash and might look at using monit or another process monitor which would help in restarting rethinkdb if it were to fail again...

My only open question now: Is there a possibility that the raft election process would have caused the other 2 nodes to get disconnected?

**Comment by danielmewes** [comment]
Did you see any messages about a "heartbeat timeout" in the logs when the disconnects happened by any chance?

The raft election should not cause disconnects (unless of course there's a bug, which is possible). I think it's more likely that something else caused a disconnect, and as a consequence the servers started raft leader elections since they had lost contact to the previous leader. This is an expected reaction to losing connectivity to one or multiple other servers.

**Comment by mariostallone** [comment]
These were the logs for the first incident.
```
DATE20:42:19.548510057 1482913.604833s info: Table <hash>: Starting a new Raft election for term 2.
DATE20:42:19.611979850 1482913.668302s notice: Disconnected from server "rethinkdb2" <hash>
DATE20:42:19.612051802 1482913.668374s notice: Disconnected from server "rethinkdb3" <hash>
```

The most recent incident has a `Heartbeat timeout` which caused the disconnection and eventually the crash...

**Comment by danielmewes** [comment]
@mariostallone Are there any log messages on the other servers at the time the first incident happened?

**Comment by mariostallone** [comment]
Yes @danielmewes.
The logs on both the other servers were similar to the one below.

```
DATET20:39:50.723437503 1482605.220926s notice: Disconnected from server "rethinkdb1" <hash>
DATET20:47:19.283573311 1483053.781061s notice: Connected to server "rethinkdb1" <hash>
```

There was another crash today as well. None of the crashes seem to have happened due to oom. Can't find a single log pointing in that direction. The only thing we observed is high disk usage before the crash. 

Additional Info.
I'm running rethinkdb v2.1.4
Running on Linux 2.6.32-431.29.2.el6.x86_64 x86_64
The only table on the DB has 3 shards with 2 replicas per shard.

I've just made a change to use rethinkdbdash. I'm hoping making connections via a pool to all the machines in the cluster as opposed to just one would increase availability.

**Comment by coffeemug** [comment]
@mariostallone -- is there anything in the logs about the latest crash? This is unfortunately very challenging to debug because there is almost no information.

Another possibility (which would help enormously) is to enable core dumps on the servers that run RethinkDB, and then send us the dumps. Do you think it would be possible to do that?

**Comment by danielmewes** [comment]
@mariostallone Is it the one you mention in https://github.com/rethinkdb/rethinkdb/issues/4675#issuecomment-150931694 ? Was that still on 2.1.4? I recommend upgrading to 2.1.5 first. We've fixed a bunch of potential segmentation faults in that release (see the release notes for details: https://github.com/rethinkdb/rethinkdb/releases/tag/v2.1.5-2 )

**Comment by danielmewes** [comment]
@mariostallone Another question: Is there swap configured on the servers? Could one of them have run into swap? (this could explain the heartbeat timeouts and disconnects, though not the server crash which is probably a separate problem).

**Comment by mariostallone** [comment]
@danielmewes @coffeemug Sorry for the delayed response.

Unfortunately the logs dont give much info about the crash, neither do they seem to be due to an OOM

We do have swap configured. That could definitely be a possibility.

Here's an update since last week.

I believe a lot of the issues were due to high load. We saw sudden peaks in the system (writes to the system), when these issues emerged. I had since turned on soft durability, and it has been fairly stable since. Its been 6 days since the last crash.

But, Im still a little worried about the crashes, Im unsure of why it occurred and whether they will occur again.

I'll check on the core dumps and get back to you. (This is sensitive data)

I'm looking at upgrading to 2.1.5-2 this coming week. Just wanted to understand how long would rebuilding the index post the update take?

**Comment by danielmewes** [comment]
‎A quick note on the 2.1.5-2 update: you'll not need to rebuild indexes for a minor update like that. Rebuilding indexes is only recommended for updates where the second number in the version changes (e.g. From 2.0.5 to 2.1.0).

**Comment by mariostallone** [comment]
Thank you @danielmewes. That's a huge sigh of relief...

The situation is a lot better except for a crash yesterday...One of the servers in the cluster crashed due to high load. Once again, no sign of the O/S having killed it, neither is there anything in the logs to indicate any reason for the crash...

**Comment by coffeemug** [comment]
This is concerning because RethinkDB doesn't just crash during high load -- there must be something else going on. If there is nothing in the logs, the most likely culprit is the OOM killer (because it doesn't give the process the opportunity to log a segfault). 

How are you deploying/running RethinkDB? One possibility is that your deployment tools might be spinning up a new VM every time you restart RethinkDB, so you wouldn't see the OOM killer in the `dmesg` logs. 

If we can't figure this out in the next day or two, would it be possible for us to get access to the servers? (we can sign an NDA if necessary)

**Comment by danielmewes** [comment]
@mariostallone was the latest crash you mention after your upgrade to 2.1.5?
Was the process actually gone or is it possible that it simply became too slow to handle requests anymore? The latter could happen if the process went into swap. It would appear almost as if the server was completely stuck, but obviously the `rethinkdb` process itself would still be running.

You might want to try reducing the cache size to free up some memory and stop RethinkDB from going into swap. You can see its current value in `r.db('rethinkdb').table('server_status')`. The cache size can be changed through the `--cache-size <MB>` command line argument to `rethinkdb`, or by adding a line `cache-size=<MB>` to the instance configuration file.

**Comment by mariostallone** [comment]
@coffeemug These are physical servers, and Im fairly certain that the logs are not purged between rethinkdb restarts...

@danielmewes I'm still on 2.1.4. Will be doing the upgrade today. If it crashes even after that, we'll work out a way to give you access to the server.
There have been instances where the server was unreachable but hadn't crashed, earlier. But this instance was a genuine crash.

I'll look into the swap issue. If there's a lot of memory being dumped into swap, i'll reduce the cache size.

**Comment by danielmewes** [comment]
Sorry for the bumpy experience @mariostallone . If the issues persist after upgrading to 2.1.5, getting access to the servers for debugging would definitely be extremely helpful.

**Comment by danielmewes** [comment]
@mariostallone have you seen this again since upgrading?

**Comment by mariostallone** [comment]
@danielmewes Nope... It hasn't crashed since the upgrade... Would you like to close this ticket for now? I could open it if I face the issue again?

**Comment by danielmewes** [comment]
Yeah let's do that. Please re-open if you see this again.

**Comment by cggaurav** [comment]
@danielmewes I just experienced it. ![](http://d.pr/i/1kGQ6+)

**Comment by danielmewes** [comment]
@cggaurav I don't see a crash in there. Did the RethinkDB server actually terminate?
Can you double-check that all servers in the cluster have full network connectivity to each other?

**Comment by coffenbacher** [comment]
@cggaurav I saw the same repetitive raft election timeouts and was able to fix it by double-checking (and subsequently fixing) the network connections between servers as Daniel suggested. It didn't lead to a crash for me but I did end up here searching for it...

**Comment by cggaurav** [comment]
@coffenbacher @danielmewes I didn't experience a crash but I presume these were initial network errors as I was configuring connectivity between the replicas. Can the error message tells you which connections are failing in addition to the raft election errors?

**Comment by coffenbacher** [comment]
That would be helpful, I just had to guess until I found the issue.
