### ISSUE TITLE
Delete selections?

### ISSUE THREAD

**Issue by jasonkuhrt** [rethinkdb/rethinkdb#4981]
When I try something like this:

```js
rql
.table('foo')
.getAll('bar')
.merge({
  qux: r.table('oop').getAll('bar', { index: 'lop' })
})
.delete()
```

I get an error like:

```
ReqlLogicError: Expected type DATUM but found SELECTION:
SELECTION ON table(oop) in: 
```

I believe another way to phrase this question/feature request is: Can deletes be used on joins?

My current solution looks like:

```js
  Promise.all([
    r.table('devices').get(id),
    r.table('relations').getAll(id, { index: 'subject' }),
    r.table('relations').getAll(id, { index: 'observer' }),
  ].map((selection) => (
      selection.delete({ returnChanges: true }).run()
    ))
  )
  .then(...)

```

**Comment by deontologician** [comment]
```
ReqlLogicError: Expected type DATUM but found SELECTION:
```

This is happening because you can't put a selection into an object. You'd need to cast it to array like:

```
rql
.table('foo')
.getAll('bar')
.merge({
  qux: r.table('oop').getAll('bar', { index: 'lop' }).coerceTo('array')
})
.delete()
```

But then you'll get the error for the reason you expect which is that you can only do a delete on a selection, and merge turns the selection into a stream (I believe), so delete won't work since it isn't referring to an actual document on disk, but a new transformed document in memory (with the extra "qux" field).

Personally, I think the way you're doing it is fine. RethinkDB doesn't have transactions, so there's no real benefit to trying to do a join and then a delete, it's just extra work the server has to do copying all the elements into an array etc. There is, however, issue #4853 which proposes a reference type. If that were implemented we might be able to make a cascading delete like this easier to write.

**Comment by danielmewes** [comment]
@mlucy would it be easy to make `union` maintain selections?

In that case you could write this in a single query like this:
```js
r.union(
  r.table('devices').get(id),
  r.table('relations').getAll(id, { index: 'subject' }),
  r.table('relations').getAll(id, { index: 'observer' })
).delete()
```
(it doesn't currently work, so I think your work-around of doing it separately is indeed the best option right now)

**Comment by mlucy** [comment]
@danielmewes -- that should be pretty easy.

**Comment by marshall007** [comment]
@danielmewes `r.union` maintaining selections would be really cool. I've been using the exact same workaround @jasonkuhrt suggested, actually. In addition to `delete`, I assume this would work for any table selection operation (i.e. `insert`, `update`, etc), correct?

Would this also apply when selecting tables themselves?

```js
r.union(
  r.table('tasks'),
  r.table('sources')
).indexCreate('customer_id')

r.union(
  r.table('tasks'),
  r.table('sources')
).getAll(id, { index: 'customer_id' })
```

**Comment by jasonkuhrt** [comment]
I'm happy to see I hit a point of interest with this issue. Happy to rephrase the title if needed.

**Comment by danielmewes** [comment]
@marshall007 Yeah it would automatically work with all write operations, except for `insert`.

The `index` example I think would be a separate step. Do you think this would actually be useful compared to putting the `getAll` inside the `union`? 
```js
r.union(
  r.table('tasks').getAll(id, { index: 'customer_id' }),
  r.table('sources').getAll(id, { index: 'customer_id' })
)
```

**Comment by danielmewes** [comment]
I opened https://github.com/rethinkdb/rethinkdb/issues/4986 to track the `union` extension for selections.

@jasonkuhrt No need to rename this issue. We usually try to avoid renames, because some of use use Gmail to keep track of issues and it can't keep track of email threads when the subject changes. Opened the new issue instead.

I'll close this one, since the original question has been answered and we have a follow-up issue for a specific new functionality. We can still discuss the "table operations on unions" proposal here.

**Comment by jasonkuhrt** [comment]
@danielmewes Thanks for shepherding this forward.
