### ISSUE TITLE
Error in data_block_manager causing crash and data corruption

### ISSUE THREAD

**Issue by mpoon** [rethinkdb/rethinkdb#4989]
Experiencing odd issue in our production db:

```
error: Error in src/serializer/log/data_block_manager.cc at line 1177:
error: Guarantee failed: [gc_state->current_entry == __null] 0x7ff2ff0bd140: 2096640 garbage bytes left on the extent, 512 index-referenced bytes, 0 token-referenced bytes, at offset 16777216.  block dump:
[16777216..+512)
[16777728..+512)  
[16778240..+512)   
[16778752..+897)  
[16779776..+846)  
[16780800..+424)
...
error: Backtrace:
notice: Server got SIGTERM from pid 0, uid 0; shutting down...
notice: Shutting down client connections...
```

On reboot of the db, we get the following messages in our log

```
notice: Running rethinkdb 2.1.4~0jessie (GCC 4.9.1)...
notice: Running on Linux 3.13.0-57-generic x86_64
notice: Loading data from directory /var/kimochi/db
info: Automatically using cache size of 100 MB
warn: Cache size does not leave much memory for server and query overhead (available memory: 157 MB).
warn: Cache size is very low and may impact performance.
notice: Listening for intracluster connections on port 29015
error: Error in src/btree/reql_specific.cc at line 251:
error: Guarantee failed: [sb_size == REQL_BTREE_SUPERBLOCK_SIZE] 
error: Backtrace:
```

The backtraces are empty in the log file unfortunately. I'm not too much concerned with the initial crash, as that's possibly due to memory issues (we have a 2GB server with some other stuff on it), but it seems like our data is corrupted. I can't get rethinkdb to boot with the data at all.

Any ideas?

**Comment by coffeemug** [comment]
@mpoon -- thanks for reporting this. What file system are you running on? Can you post the output of `mount`?

**Comment by mpoon** [comment]
Our server is on `ext4` but our db directory was on a mounted `glusterfs` volume.

```
/dev/vda1 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
kimochi-live-app:kimochi-vol on /var/kimochi type fuse.glusterfs (rw,default_permissions,allow_other,max_read=131072)
```

**Comment by coffeemug** [comment]
@mpoon -- ok, I see. RethinkDB (and any other database) depends on certain guarantees from the file system. For example, if the file system says a write is on disk, the write needs to actually be on disk for the database to guarantee consistency. Many distributed file systems (e.g. nfs, etc.) lie about these guarantees to software built on top of them for performance reasons (otherwise, distributed file system performance would be dismal). Unfortunately, these file systems aren't suitable to run databases on top of them, and RethinkDB isn't an exception here.

I'm closing the issue since there isn't anything we can do on file systems that don't offer posix guarantees. However, please feel free to post here so we can help you recover your data. Do you have a recent backup that you can use?

**Comment by mpoon** [comment]
Thanks for your prompt response! We luckily had a very recent backup, but I appreciate your offer.
