### ISSUE TITLE
Question (not issue)

### ISSUE THREAD

**Issue by levin-kelevra** [rethinkdb/rethinkdb#4990]
Hi, i have a question about RethinkDB and Python3

python3 + rethinkdb

pre_query_a = " .filter (r.row('vehicleID').match('%s')) " % (request.args['vehicleID'])
pre_query_b = " .filter (r.row('vehicleName').match('%s')) " % (request.args['vehicleName'])
query = pre_query_a + pre_query_b
result = r.db(PROJECT_DB).table(PROJECT_TABLE) query .run(db_connection)

```
#./app.py
    result = r.db(PROJECT_DB).table(PROJECT_TABLE) query .run(db_connection)
                                                       ^
SyntaxError: invalid syntax
```

How to use variable as query body???

**Comment by deontologician** [comment]
In general, if you need to defer calling a method on something because you don't have it yet, you just need to turn it into a function (lambdas are a quick way to do this). Since reql queries aren't strings, you can't use them like you're trying to. Here I've also changed `match` to `==` since you don't want to do a regex match for ids

```py
pre_query_a = lambda q: q.filter(r.row['vehicleId'] == request.args['vehicleId'])
pre_query_b = lambda q: q.filter(r.row['vehicleName'] == request.args['vehicleName'])

query = lambda q: pre_query_b(pre_query_a(q))

table = r.db(PROJECT_DB).table(PROJECT_TABLE)
result = query(table).run(db_connection)
```

I'm going to close this issue since it isn't a bug, but feel free to ask more questions in this thread.

**Comment by larkost** [comment]
@levin-kelevra: I ran into a similar desire working in one area of the tests and wrote up issue #4576 "allow query fragments". You can currently only use what I referred to as "fragments" if that fragment is the one that starts with `r`. So the following is already possible:

```
import rethinkdb as r
record = r.db('test').table('users').get(1)
record.update({'name':'smith'}).run(conn)
record.delete().run(conn)
```
I found the limiting, since I had to write `lambda`'s or functions when I wanted to have the latter (normally more complicated) part to be the shared part, and run it with multiple data source parts.

I should also note that this is the case in all of our first-party drivers, and that this is completely a driver-side issue. The server would not be involved at all.

Unfortunately your approach of trying to use strings a proxies for query fragments is not going to work without turning the entire query (at least the part before `run()` into a string, and then using `eval` on that. And that particular approach gives me the willies.
