### ISSUE TITLE
Remove spurious uses of r.row from polyglot tests

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5014]
There are many polyglot yaml tests that contain usages of r.row but that aren't directly attempting to test the r.row term itself. It's convenient because the same syntax can be used for both javascript and python tests, without having to specify them independently.

Unfortunately, it's pretty difficult to do an ast transformation from a python test that uses r.row to a python ast that uses a lambda. This limits the ability to translate the python tests to other languages like Java/C# that don't implement r.row. It's possible, but would be pretty nasty code and it would probably be easier to just rewrite the ~90 or so tests that use it currently.

Obviously, some tests would actually be for the r.row term itself, and those shouldn't be rewritten to use lambdas.

I added the Java tag because this is blocking the Java driver from running the full battery of polyglot tests. It just skips any tests were r.row is used in any definition in the file, and this unfortunately skips a large number of perfectly reasonable tests that just happen to use r.row for convenience.

**Comment by larkost** [comment]
This is one of the reasons we have the ability to have different implementations for different languages in the polyglot tests, rather than forcing everything to be auto-translated. Those tests should simply have a `java` entry in the polyglot files. Auto-translating sounds nice, but I don't think it should be hamstringing existing tests.

**Comment by deontologician** [comment]
It's about the same amount of work to add the java specializations as it is to just rewrite these entries, and it's more scalable long-term since manipulating python asts is more robust than the translation heuristics used now in the polyglot tests for `cd` entries. Theoretically, this could be used to remove a lot of the ruby specializations as well, since that driver doesn't have r.row either.

**Comment by larkost** [comment]
Some points against trying to use ast-translation:
1. We often need to produce multiple versions of the same test to check that different text that all produce the same ast all work.
2. Our testing base serves as a repository of coed examples of how the commands work in different languages. Using ast-translation produces no examples, defeating this purpose. I agree that our auto-translation of some things partially defeats this, but the translation for Java is far more different that what we have had before.
3. It is significantly tougher to back-track test failures, since we are not going through a computer-generated intermediary.

So the TL;DR version is I don't think we should be using ast-translation in the testing system.

I would much rather have a tool to auto-translate (ast is a perfectly good approach here) the text, and put that in the polyglot files. I have been playing with this idea for some time, but don't quite have all the kinks worked out yet.

**Comment by deontologician** [comment]
The `convert_tests.py` script can output individual lines of code, which is what @chipotle is using to translate a lot of the existing docs examples to java. It's a good point that some of the tests attempt to use several different syntaxes to generate the same underlying query, but I think that's rare enough it could be pulled into a specialized driver test. There are thousands of polyglot tests at this point and hand-translating them is quite a job.

I don't see a point to auto-translating a test and then putting it back into the yaml file. The polyglot file isn't the final test output, it gets translated again. Ideally there would be one specification for a test intended for all drivers (with language specific tests separated out), and you could use whatever method to generate the specific code for your specific driver (probably with some kind of helper to make the translation easier).

| 3. It is significantly tougher to back-track test failures, since we are not going through a computer-generated intermediary.

In the java test translation, I output the filename/line number from the yaml file provided by the processPolyglot parser so you can find the original specification. Originally I had the test number with the old yaml parser, which was much less helpful. I also dump out the python version of the test that it was translated from into a comment above the test. That makes it pretty easy to figure out what was wrong and where the issue came from.

**Comment by deontologician** [comment]
discussed this in person with @larkost and @danielmewes and the easiest method right now is to add the java exceptions since without them we'd need to add a javascript exception anyway since the `cd` converter can't do `lambda` -> `function` conversion currently.
