### ISSUE TITLE
Wrong arguments count on ReqlCompileError

### ISSUE THREAD

**Issue by thinklinux** [rethinkdb/rethinkdb#5025]
This is the error that I got when I forgot to specify an `index` argument for `changeAt` - `ReqlCompileError: Expected 3 arguments but found 2.` The query is the one from [that issue](https://github.com/rethinkdb/docs/issues/935). Without stack trace and wrong error message it was a matter of guessing which was the function with the missing argument.

From the docs - `array.changeAt(index, value) → array`. There are only two arguments for this function ofc if I'm not missing something else because I'm still really new to rethinkdb.

**Comment by mlucy** [comment]
@thinklinux -- these error messages are sort of confusing because the server doesn't know if you're using prefix or infix notation.  (The server can't distinguish between `array.changeAt(index, value)` and `r.changeAt(array, index, value)`, which some drivers allow or require.)  So when it says "3 arguments" it's counting `array` as one of the arguments.

There's an issue (https://github.com/rethinkdb/rethinkdb/issues/2463) to make the server return more structured error messages so that the drivers can produce an appropriate error message depending on whether the function was called prefix or infix, but it isn't currently scheduled.

Closing this since it isn't a bug, but feel free to ask more questions here.

**Comment by thinklinux** [comment]
@mlucy Thanks! This makes total sense now.
