### ISSUE TITLE
JS Observable integration

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5031]
Observables: https://github.com/zenparsing/es-observable

Maybe our cursors should expose an Observable interface?

I'm not actually sure how much we need to do for this, since according to above page:

> `Observable.from` converts its argument to an Observable.
> [...]
> Otherwise, the argument is assumed to be an iterable and the iteration values are delivered asynchronously in a future turn of the event loop.

@deontologician (and maybe @neumino) thoughts?

**Comment by danielmewes** [comment]
Related to https://github.com/rethinkdb/rethinkdb/issues/4280

**Comment by danielmewes** [comment]
Actually our cursors don't exactly implement the iterable interface in the JavaScript driver do they? So that work-around might not actually work...

**Comment by neumino** [comment]
I haven't used Observable so far but I think it's more a front end thing. I've never seen Observables used in backend yet.
Also it could make sense to have an observable for a changefeed but not really for a cursor.

**Comment by marshall007** [comment]
@neumino I tend to think of an `Observable` as a `Promise` that can be fulfilled multiple times. Promise-based APIs have always struggled with the limitation that you can only resolve a single value and I think solving that problem is the main idea behind observables.

If you think about it that way, they totally makes sense as a generic cursor replacement. I haven't seen anyone using them in Node yet either, though.

**Comment by danielmewes** [comment]
Thanks for your feedback on this @neumino and @marshall007 .

I thought of Observables as an option to address https://github.com/rethinkdb/rethinkdb/issues/4280 , while having a chance to see them as part of the ES7 standard in the future. I'm not too familiar with the JS standardization process, so I'm unsure how likely it is that this will happen and when it could be expected.

**Comment by coffeemug** [comment]
Just FYI, since RethinkDB cursors expose the `EventEmitter` interface (see http://rethinkdb.com/api/javascript/event_emitter-cursor/), you can trivially convert them to observables like this:

```js
var observable = Rx.Observable.fromEvent(query.run(conn), 'data');
```

**Comment by cultofmetatron** [comment]
Observables are much more powerful abstraction than a Promise that can be fullfilled multiple times. They are asynchronous sequences that can be composed with higher order functions in much the same way lodash can operate on arrays.

cursors by comparison seem limited and clumsy. It would be great if the rethinkdb driver nativly implemented cursors.

doing so would make the streaming functionality much more usable. for instance, you could write code like this.

```javascript
let joinedObservable = combineLatest(
  query1.run().filter(somefunc1), 
  query2.run().map(somefunc2).filter(somefunc3)), 
  (val1, val2) =>  combineValuesInMeaningfulWay(val1, val2));

combineLatest(latestSocket, joinedObservable, (socket, value) => {
  return {
    socket: socket,
    value: value
  };
}).subscribe((data) => data.socket.emit('someEvent', data.value));
```

I admit it seems a bit contrived. imagine combining asynchronous values coming from several sources including socket.io, rethink and rabbitmq. wrapping all theses sources behind observables makes combining them much more managable. 

The reason you don't see observables very much in the backend is because most node applications are web servers. The entire interaction revolves around a single event (http request).  Observables realy show their utility when you have lots of diffrent events to coordinate. (socket.io for instance). Observables let you do this with minimum side effects/state.

Rethink db isn't trying to be just any database. You guys want to be the database for realtime apps. As such, it would be infinitely useful to have streaming interfaces that allow composability across multiple values the way Promises allow composability over one shot asynchronous functions.  cursors in my experience are frustratingly clumsy when you want to do anything more complex than simply passing along values.

**Comment by cultofmetatron** [comment]
also, with observable interface, you could dispense with the callback entirely

```javascript

r.table('marvel').run(conn)
  .subscribe(
    (row) => doSomething(row),
    (error) => handleError(error)
 );


```

**Comment by danielmewes** [comment]
The error handling example is pretty convincing.

I'll pull this into 2.3-polish for discussion.

**Comment by neumino** [comment]
Hum, I don't think observables are that perfect for the drivers. You typically have to close your connection when you are done with a cursor. Meaning that all the examples returning a cursor end up becoming something like:

```
r.connect({}).then(function(connection) {
  query().run().subscribe({
    function next(row) { console.log(row) },
    function error(err) { console.log(err) },
    function complete() { connection.close() }
  })
})
```
When `next` is biggish, it makes a really ugly-ish syntax.

You may not need the complete method if you return one unique value, but that means people need to know if the query returns an array or a cursor.

Using streams seems more appropriate to me, and in this case you get the benefit of not having to handle errors in multiple places and you can just pipe them in your sockjs/socket.io connections.

```
query.toStream().pipe(socketio).error(function(err) {
  // handle all errors
});
```

**Comment by neumino** [comment]
To be more precise observable are a nice interface for feeds but I'm not sure that they are better than streams.

**Comment by bchavez** [comment]
For what it's worth, [the C# driver here](https://github.com/bchavez/RethinkDb.Driver) supports `Cursor.ToObservable()` via Reactive Extensions (Rx). Actually, in Rx `.ToObservable()` is the dual byproduct of implementing `IEnumerable` in C# **Cursors**. So, the following is possible with change feed cursors in C#:

```
var changes = r.db("marvel").table("heros")
               .changes()
               .runChanges<Hero>(conn);

var observable = changes.ToObservable();
observable.Subscribe(OnNext, OnError, OnCompleted);
```

It works pretty well in this case. Here, a RethinkDB change feed cursor can be bridged via **Rx** into a SingalR channel without much effort. I wish we had something like node streams in .NET but this is the best we can do in C#.... for now anyway :+1: .

**Comment by staltz** [comment]
> I haven't used Observable so far but I think it's more a front end thing. I've never seen Observables used in backend yet.

http://blog.couchbase.com/why-couchbase-chose-rxjava-new-java-sdk

**Comment by cultofmetatron** [comment]
@neumino, you're right that the syntax gets a little wierd when you have the connection object being passed in. personally I never liked that anyway. there should be a connection pool that automatically closes when there's no more data.  Rethinkdbdash does this very well.

now assuming there's some very good reason its done this way, you could still use it inside an observable

```javascript
r.connect({}).then(function(connection) {
  query().run().subscribe({
    function next(row) { console.log(row) },
    function error(err) { console.log(err) },
    function complete() { connection.close() }
  })
})
```

could be handled like so.
```javascript
r.connect({})
  .flatmap((connection) => 
      query.run(connection)
        .doOnCompleted(() => connection.close()))
  .subscribe(
      function next(row) { console.log(row) },
      function error(err) { console.log(err) }
   );
```

Its clumsier than I'd like but it'll do.  Since observables are so composable, I can create a trivial convenience method

```javascript
let closer = function(r, query) {
  return r.connect({})
    .flatmap((connection) => 
      query.run(connection)
      .doOnCompleted(() => connection.close()))
}

closer(r, query)
  .subscribe(
      function next(row) { console.log(row) },
      function error(err) { console.log(err) }
   );

```


As for the next getting potentially huge.  The next() passed to the subscribe is for mutation. ideally you should be performing as much data transformation as you can before it gets to this point.

Now was far as streams are concerned. node streams are nice. they do a descent job. However, they are still no where near as composable as observables. one great example is exception propagation and handling.

lets say the connection is flakey for whatever reason and we need to try a few times. I could modify closer to then try and connect up to n times.

```javascript
var closer = function(n, r, query) {
  return reduce(range(0, n - 1), (connectionObservable) =>
    connectionObservable.catch((err) => r.connect({})), () => r.connect({}))
    .flatMap((connection) => 
      query.run(connection)
        .doOnCompleted(() => connection.close());     
}

//returns an observble that represents 10 attempts to get a connection object before 
//erroring out
closer(10, r, query)
  .subscribe(
      function next(row) { console.log(row) },
      function error(err) { console.log(err) });

```

Please tell me how this could be done better with node streams?

**Comment by danielmewes** [comment]
We didn't really get around to discussing this for 2.3. I'm going to move this out into `subsequent`. We'll try to pick it up for the next release.

**Comment by HighOnDrive** [comment]
+1 on support for Observables. With RethinkDB handling Mongo like transformations and aggregations plus Firebase like push notifications and also Observables compatible with RxJS the worlds problems will have been greatly reduced. It's a joy to discover RethinkDB :100:

**Comment by deontologician** [comment]
I've gotten some good experience with observables recently, and I'm a huge fan now. I'll likely hold off putting them into the main driver until RxJS 5 is out of beta though. It has some awesome performance improvements, and it uses the naming conventions that will likely be standardized in the future

**Comment by deontologician** [comment]
Although, if anyone wants to build an rxjs-based library that wraps the driver (or that wraps rethinkdb-dash) it would be pretty sweet and you'd probably get all the benefits you were looking for from the official driver supporting them.

**Comment by TimCodes** [comment]
Has anyone looked more into a Rx.js wrapper for rethink?

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by lrn2prgrm** [comment]
@deontologician already standarized with ReactiveStreamsSpec and RxJava 2 is already compliant. 
but as @coffeemug said, getting an observable is trivial:
var observable = Rx.Observable.fromEvent(query.run(conn), 'data');
I would totally go with this approach for changefeeds. Looking forward to play with this awesome db.

**Comment by phaux** [comment]
@lrn2prgrm `Observable.fromEvent` won't automatically close the cursor on unsubscribe and won't repeat the query after a resubscribe. It only adds/removes the event listener.

For example the `.retry(N)` and other operators whose job is to automate resubscribing wouldn't work as the programmer probably expects.

To truly benefit from the change it would make the most sense to get rid of `.run(db)` completely. It's the Observable's job to start/stop/restart the query at the right times.

**Comment by deontologician** [comment]
The problem with getting rid of run entirely is that that's how certain
query-level options are passed. I think what you'd want is for .run to
return an observable, rather than a Cursor. Then you can stop/ start etc.

**Comment by phaux** [comment]
@deontologician That's an option too, except the name would be a little misleading since it doesn't actually "run" anything.
Another option would be to put them in the initial `r(…)` call.

**Comment by phaux** [comment]
There's also one drawback of Observable – the current most popular implementation (RxJS) doesn't provide any backpressure mechanism ([although there is a spec for that](https://github.com/jhusain/asyncgenerator#the-asynchronous-observable)). It's basically only great for subscribing to changes. You wouldn't be able to query whole table and consume the results at your own pace.

Other alternative worth looking at would be [ECMAScript Streams](https://github.com/whatwg/streams)
