### ISSUE TITLE
The `return_changes` optarg (for mutation commands) should return the changes in order

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#5041]
Suppose I run the following command:

```js
r.table('foo').insert([{a: 1}, {a: r.minval }, {a: r.minval }, {a: 2}],
                      { returnChanges: 'always' })
```

In the current implementation, the changes don't come back in the same order as the documents inserted (the order isn't specified). That makes the `always` mode essentially useless.

The changes in this case should be guaranteed to come back in order.

/cc @mlucy (we just discussed this) and @Tryneus (he needs this for a secret super-project he's working on)

**Comment by danielmewes** [comment]
Would this be only for `insert`?

**Comment by deontologician** [comment]
Also, it would be nice if there were error documents inserted if the documents fail to insert properly, rather than fake keys like generated_keys

**Comment by coffeemug** [comment]
I was going to add -- including errors would be *really* helpful.

I think this should be the case for all commands where you can pass `{ returnChanges: 'always' }`, not just `insert`.

**Comment by danielmewes** [comment]
The reason I was asking is because `insert` is somewhat different from the other write operations.

In the case of `insert`, the order is explicitly specified in the command itself, as you pass an array with documents.

For an `update`, `replace` or `delete`, the order is not provided in the same way. Instead it's implicit in the selection that the command is applied on. We could return changes in the "right" order if the selection is ordered, such as in `r.table('test').orderBy({index: "id"}).delete()`. Unless this is something that will occur in Fusion, I think that's a pretty rare use case though.

I suspect that we'll also need separate code to ensure this for `insert` vs. the other write terms.

I suggest that we implement it for `insert` first. Does that sound reasonable?

**Comment by danielmewes** [comment]
Also +1 on that `error` syntax.

**Comment by deontologician** [comment]
I think we only actually need it for insert since that's the only place where we don't have an id for a failed document operation and have to rely on stuff like ordering to figure out what went wrong

**Comment by neumino** [comment]
It's the same as #3853 -- and would be really nice as thinky now has to do it itself (and that it's annoying when primary keys are not string).

**Comment by danielmewes** [comment]
Ah thanks @neumino . I had a feeling you had brought this up before for Thinky, but I couldn't find the issue when I looked for it.

**Comment by karlgrz** [comment]
This is slightly annoying for us, as well. Any date on 2.3 release candidates?

**Comment by danielmewes** [comment]
@karlgrz Our current estimate for 2.3 is 1-2 months from now.

**Comment by karlgrz** [comment]
@danielmewes thank you!

**Comment by nighelles** [comment]
This is in review 3452.
Implemented in nighelles/5041
https://github.com/rethinkdb/rethinkdb/tree/nighelles/5041

**Comment by nighelles** [comment]
This is in next.

**Comment by karlgrz** [comment]
Fantastic news, thank you!
