### ISSUE TITLE
Running dump spikes memory usage and causes inter-cluster disconnects

### ISSUE THREAD

**Issue by freiksenet** [rethinkdb/rethinkdb#5078]
We have a three-node cluster with quite a big number of databases and tables (about 200 databases, 10-30 tables per database). Running rethinkdb dump causes memory usage to spike and then connections being lost to other nodes of the cluster.

**Comment by freiksenet** [comment]
RethinkDB 2.1.4

**Comment by freiksenet** [comment]
More details - we have 3 nodes in cluster, 1100 tables evenly distributed between them (so 1 shard per table, no replication). Web interface drops when I do the dump, but otherwise cluster is not under heavy load and cache fullness is just at 3%.

**Comment by danielmewes** [comment]
This *might* be caused by https://github.com/rethinkdb/rethinkdb/issues/4809 , but I have to verify that.

Are you on Compose?

**Comment by freiksenet** [comment]
Yep.

**Comment by encryptio** [comment]
Reproduced this locally (and in fact, froze my machine doing so; through a vm, no less.)

I think the culprit is that we're calling `table().count()` in unlimited concurrency just before doing the dump of the data itself in limited concurrency. Since our implementation of `.count()` reads the data, effectively this reads all tables simultaneously, causing a massive spike in load.

I think we can skip that and use the table's approximate counts (which are already being retrieved and stored in the `.info` files) to avoid doing any heavy queries outside the concurrency limiting semaphore.

**Comment by encryptio** [comment]
Looking at this a bit closer, we are using the approximate counts, and that seems to work okay wrt the memory usage in the server process. (It still could be better if we limited concurrency properly at this stage.)

The python worker processes use 13-17MB each when they're idle, and the few active ones sit at 22-30MB before they exit. Overall memory usage for the system linearly dwindles down to normal as the export continues. Meanwhile, the `rethinkdb` server memory only changes a relatively small amount (100MB total when exporting 600 tables.)

Looks like limiting the `export` process count is the best use of development time by far to fix this problem (see #4809).

**Comment by encryptio** [comment]
Realized my comment isn't perfectly clear; I'll be continuing to work on this as #4809.

**Comment by freiksenet** [comment]
Thanks!
