### ISSUE TITLE
Question: Is it possible and how to upgrade rethinkdb cluster (>= 3 instances) without downtime?

### ISSUE THREAD

**Issue by ntquyen** [rethinkdb/rethinkdb#5084]
I have 3 nodes of rethinkdb version 2.1.5 in my cluster. I want to upgrade them to version 2.2 with zero downtime. There are some limitations prevent me from achieving that goal:
1. Need to restart node, lead to disconnect from the cluster one by one.
2. New version instance cannot join cluster with older version. Once 1 node down and up with new version, it is disconnected forever from old cluster.

Been searching for answer of this question without result, so I posted my own here, hoping for a strategy to achieve the goal, or at least limit as much downtime as possible.

**Comment by mlucy** [comment]
Hi @ntquyen -- I don't think it's possible to upgrade with 0 downtime right now.  (@danielmewes, am I right about this?)  I think the best thing to do is to take down all your nodes at once and bring up the new version as quickly as possible.

Closing since this isn't a bug, but feel free to continue asking questions here.
