### ISSUE TITLE
Rethinkdb VM clone GUID change

### ISSUE THREAD

**Issue by ryanaverill** [rethinkdb/rethinkdb#5107]
Hello, 

I am trying to build autoscaling for my rethinkdb cluster. I've scripted the entire process on Digitalocean but all my new machines were all cloned from my third DO droplet snapshot - which has this GUID assigned by the rethinkdb process: e5aadd93-f949-4ed6-b1f1-7a78a2d40005. So every time I spin up more droplets I get this error.

2015-11-17T22:56:02.993103410 121.799358s info: Rejected a connection from server e5aadd93-f949-4ed6-b1f1-7a78a2d40005 since one is open already.

I've already tried setting new hostnames and manually set this option in my default.conf file as well:

server-name=server1

Any idea how to change this or dynamically reassign?

**Comment by danielmewes** [comment]
Hi @ryanaverill, copying the data directory for cloning RethinkDB servers is not supported. From the perspective of the cluster, a cloned node connecting to the cluster looks like a server travelling back in time. This is risky, because it violates a bunch of invariants and guarantees that RethinkDB's clustering layer relies on for its correctness.

The recommended way for joining a new server into a cluster is by starting out with an empty data directory.
I recommend moving away (or deleting) the RethinkDB data directory on all but one of your droplets. RethinkDB will create a new data directory together with a new server ID the next time it starts up, and will be able to join the other servers with its new ID.

**Comment by danielmewes** [comment]
If you want to build a single image for auto-scaling, you might want to make sure that the RethinkDB data directory is empty in the image, so that each node can start with a fresh directory after being created.

**Comment by ryanaverill** [comment]
That worked great. Thank you very much for your help!
