### ISSUE TITLE
Bump the version of v8

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#5112]
We currently use v8 3.30.33.16, but I wasn't able to build it easily on windows.

Newer versions of v8 fix the issues I had and include a lot of bugfixes and performance improvements.

Unfortunately, the API is not backwards-compatible.

**Comment by analytik** [comment]
Is there any specific version of v8 you're aiming for?

Node.js 6 will be built on v8 5.0, which has an extensive ES6 support. Since Node.js 6 will be a long term support release, I think it would be great if RethinkDB had the same or newer v8 (probably not for 2.3, but some time during 2016 would be nice). 

This is just a nice to have feature, I guess mostly to keep syntax the same between newer ES6 Node.js projects and the Administration interface (if that's relevant at all, and the code entered there is processed by the v8 and not some driver translating the code before it gets to the server).

**Comment by danielmewes** [comment]
@analytik The version we pick isn't all that important, since it only affects the `r.js` command. The Data Explorer relies on the browser to parse the JavaScript, so it will support whatever language features are available in your browser.

**Comment by AtnNn** [comment]
V8 also fails to build on Ubuntu Yakkety (16.10) which has GCC 6.1 (see #5757).

The current stable version of V8 is 5.4.500.41 (ahttps://omahaproxy.appspot.com/)

We're still using V8 3.30.33.16 on Linux. On Windows we use 4.7.80.23, but the build process is more fragile, and it takes a lot longer.

**Comment by AtnNn** [comment]
One of the obstacles of upgrading V8 is making their new build system compatible with ours.

Simply fetching the source of V8 requires over 500GiB of space, a lot of which is taken up by custom, platform specific versions of clang, python and other tools.

Our build and packaging system assumes it can fetch or create platform-independent tarballs of fetched dependencies, and that the subsequent build step can be performed offline.

**Comment by srh** [comment]
> 500GiB

I assume this is supposed to say 500 MB.

**Comment by srh** [comment]
See #6401 for an alternative.

**Comment by gabor-boros** [comment]
@srh  I'm closing this as QuickJS replaced V8
