### ISSUE TITLE
Look into using Jackson for java driver json serialization

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5128]
We now have several corner cases in the pojo <-> json code that it may make sense to look at a library that's already dealt with those corner cases.

**Comment by pires** [comment]
Jackson or Gson are good choices. I prefer the latter because of the [support for polymorphism](https://futurestud.io/blog/how-to-deserialize-a-list-of-polymorphic-objects-with-gson/).

**Comment by kclay** [comment]
@pires fyi Jackson supports polymorphism ad well by the use of annotations http://stackoverflow.com/a/30386694

**Comment by pires** [comment]
Warning: Don't use `is` prefix for boolean getters, e.g. `isConnected()` for accessing `boolean connected`. **Always** use `get` prefix, e.g. `getConnected()` for accessing `boolean connected`.

**Comment by dbolotin** [comment]
+1

I think Jeckson is a better option here, as it is used as a core JSON module in two most popular reactive web frameworks in Java world: Vert.x and Play. So users of these frameworks will be able to use the same annotated classes to store in DB and send/receive over http/websockets.

Anyway, I also agree with @kclay, that some simple interchangeable abstraction here would be a nice option.

... it looks like in current architecture maps are used as an intermediate objects, and pojos are constructed from maps rather than raw JSON, so incorporation of any JSON framework will not be a trivial task... However, I don't think that simple map to pojo converter (com.rethinkdb.net.Util#toPojo) as implemented now, can satisfy demand for "ORM" in real-world projects (at least in my current project). Flexibility of serialization/deserialization through annotations substantially simplifies development.

Maybe I will come up with some simple solution, after more digging into current code of the library (I understand that code is generated by python scripts :) ) and send you a pull request.

**Comment by n3integration** [comment]
+1

FWIW - I agree that Jackson may be a preferable choice since it is already bundled with a lot of frameworks, as @dbolotin pointed out. For an example, the Play framework's Json serialization [implementation](https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/java/play/libs/Json.java) is a fairly straight foreword implementation and handles most use cases.

I think that RethinkDB is a great product and improved serialization support would really help foster further adoption from the Java community.

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. Jackson support is implemented in the main branch. This issue can be closed.
