### ISSUE TITLE
Servers with minor version discrepancies can't connect together.

### ISSUE THREAD

**Issue by grantwork** [rethinkdb/rethinkdb#5133]
I run 12 Rethink servers on Debian Wheezy using the apt package manager. I have one master no shards with 11 other replicating servers. I also have a script that apt auto updates packages every night. 

I had some small issues a few months back where 5 of the 11 replica servers did a minor version update from 2.1.2 to 2.1.5, but the rest of the servers didn't do the update at the same time, so all the upgraded servers failed to connect. 

Then last week we had an issue where only the primary/master server upgraded but the 11 replicas didn't upgrade at the same time, so not only couldn't the replicas connect but all writes to the master failed with this message `Cannot perform write: primary replica for shard ["", +inf) not available`. This seems strange that the single master would fail on writes just because no replicas are currently connected. 

My suggestions are:
* Allow servers with minor version changes to still connect
* Allow writes to a single master server regardless if replicas are connected.

Our solution was to keep back the RethinkDB package from upgrades and we will now have to manually upgrade some of the replicas first before doing the master.

As we do use this in a production environment, it's just for cacheing so it's not a critical part of the system. I would be worried to use this in a critical production environment though as it would be difficult to upgrade all the servers without interruption.

**Comment by danielmewes** [comment]
Thanks for the feedback @grantwork .

We generally try to maintain intra-cluster compatibility between minor versions. Unfortunately a few important fixes we did within the 2.1.x series required protocol changes to work properly, so we had to break compatibility there. We hope that we can avoid this in the future.

I recommend pinning RethinkDB to a particular release, and updating it manually. The release notes (e.g. https://github.com/rethinkdb/rethinkdb/releases/tag/v2.1.5-2) will have a corresponding note if intra-cluster compatibility is not maintained for a minor update.

Regarding writes to a single server: RethinkDB by default relies on quorums to guarantee the completeness and consistency of all data even in the case of netsplits or server failures. It is not possible to allow a single master to keep accepting writes, while at the same time providing automatic failover and maintaining consistency guarantees.

It is possible to manually configure a given table to have the behavior you describe. However automatic failover will no longer occur. This is a very important restriction. If automatic failover was still occurring, the database could lose an arbitrary number of already acknowledged writes due to any sort of brief network glitch or temporary server shutdown.

To set up a single primary (master) that keeps accepting writes even if secondaries are missing, you can use the following configuration:
```
r.db(...).table(...).config().update({
    shards: [
        nonvoting_replicas: ["secondary1", "secondary2", ...],
        primary_replica: ["primary"],
        replicas: [
            "primary", "secondary1", "secondary2", ...
        ]
    ]
})
```
The strings "secondary1", "secondary2" etc. need to be replaced by the server names of the secondary replicas, and "primary" should be the server that you want to use as the master.

**Comment by danielmewes** [comment]
I'm going to close this since there's nothing to do about this right now.

It's very useful for us to hear that connectivity between different minor versions is important for your setup. We'll be extra careful about such compatibility-breaking changes in the future (I'm optimistic about this since 2.1 was a bit of an exception. We had just completely replaced the way clustering worked in RethinkDB, and had to fix a few critical issues that showed up. Hopefully this won't happen again any time soon).

**Comment by danielmewes** [comment]
@grantwork I'd be interested in learning more about how you use RethinkDB by the way. Would you mind shooting me a quick email to daniel@rethinkdb.com ?
