### ISSUE TITLE
The table is not getting updated if old servers are removed. How can I fix this?

### ISSUE THREAD

**Issue by cggaurav** [rethinkdb/rethinkdb#5186]
![](http://d.pr/i/1b2pj+)

**Comment by danielmewes** [comment]
In order to relocate the missing replicas to different server, you need to reconfigure the table.
As long as a majority of replicas is still available, you can do this through the web UI or by running `reconfigure` on the table.

If a majority of the previous replicas is no longer available, that operation will fail. In that case you need to run
```js
r.db('tsab').table('refreshTokens').reconfigure({emergencyRepair: "unsafe_rollback"})
```
first.

Afterwards, you'll be able to reconfigure the table normally to bring it back to the desired number of replicas.

See http://rethinkdb.com/api/javascript/reconfigure/ for more details.

**Comment by danielmewes** [comment]
(closing because it's not a bug. We're working on improving the documentation for this: https://github.com/rethinkdb/docs/issues/876 )
