### ISSUE TITLE
Why do I land up in __deleted_database__._migrations is not available state?

### ISSUE THREAD

**Issue by cggaurav** [rethinkdb/rethinkdb#5191]
![](http://d.pr/i/19Ybq+)

How can fix this?

**Comment by danielmewes** [comment]
This can happen if either a database is deleted while the cluster is not fully connected, or if you delete a database from the `r.db('rethinkdb').table('db_config')` table, rather than through the `dbDrop` command (the web UI also uses `dbDrop` internally).

To recover from this by moving all tables from `__deleted_database__` into the `test` database:
```js
r.db('rethinkdb').table('table_config').filter({db: "__deleted_database__"}).update({db: "test"})
```

**Comment by danielmewes** [comment]
The issue that deleting a database through `db_config` leaves all the tables behind is tracked in https://github.com/rethinkdb/rethinkdb/issues/4465.

Closing this since it doesn't look like a bug from what I can tell. Please let us know if you think there's something else going on.

**Comment by danielmewes** [comment]
... actually, moving the table to a different DB might not work since it has no available replicas.
If you are sure that you no longer need the table and the data in it, including any copies of the data that might still exist on other (disconnected) servers, you can instead delete it like this:

```js
r.db('rethinkdb').table('table_config').filter({db: "__deleted_database__", name: "_migrations"}).delete()
```
