### ISSUE TITLE
Allow for persistent configuration of RethinkDB across homebrew installs

### ISSUE THREAD

**Issue by aknuds1** [rethinkdb/rethinkdb#5203]
The [official](https://www.rethinkdb.com/docs/start-on-startup/) method of configuring the RethinkDB daemon on OS X, when installed with Homebrew, says to modify the corresponding .plist file so that `rethinkdb` is run with the option `--config-file /etc/rethinkdb.conf`.

However, the .plist file installed by Homebrew, i.e. ~/Library/LaunchAgents/homebrew.mxcl.rethinkdb.plist, is overwritten upon every upgrade of RethinkDB, so this is not really a viable way of configuring RethinkDB. See also [my question on StackOverflow](http://stackoverflow.com/q/34223941/265261) about this problem.

Could you please implement a more viable way of configuring RethinkDB as installed by Homebrew, that persists across upgrades?

**Comment by danielmewes** [comment]
@larkost @AtnNn Any ideas for this?

Is there a way to mark a file as a "configuration" file in Homebrew, similar to Debian, so that it isn't replaced if it was modified since it was first installed?

**Comment by danielmewes** [comment]
... actually reading the explanation in the answer http://stackoverflow.com/a/34229672/2413884 , I think a configuration flag wouldn't help. Any other ideas?

**Comment by AtnNn** [comment]
It seems the plist file is overwritten on purpose: https://github.com/Homebrew/homebrew/issues/15849

**Comment by aknuds1** [comment]
Yeah, plist files are launch scripts and as such I guess it makes sense to
overwrite them. Maybe it would rather make sense for the launch script to
specify a configuration file out of the box, instead of forcing the user to
modify the installation?

Arve

**Comment by larkost** [comment]
I answered on StackOverflow yesterday, but forgot to also include my answer here:

1. Rather than trying to fight `homebrew` to change the configuration file location, use their `launchd` plist (soft-linking to it from either from `~/Library/LaunchAgents` as they advise, or from `/Library/LaunchDaemons`), and make the config modifications you want in the file at the location they choose (defaults to `/usr/local/etc/rethinkdb.conf` assuming you have not change the `homebrew` location). From my limited testing it does not seem that they do anything to modify this file on upgrades.

2. Don't use `homebrew`'s launchd plist, but rather modify our example one to point at the binary created by `homebrew`. This does put you in the odd situation of running a user-owned binary from a root-owned launchd item, but if you are already using `homebrew`, then you are already in similar waters.

If it was me, I would skip homebrew altogether, and just use the .pkg available on the website (full disclosure: I work on that .pkg). The docs that you linked to include how to setup a launchd plist for that, and since the .pkg does not include that, you don't have to worry about that messing with your configuration. It has the nice benefit of making you as close to our tested version as possible (and I mean to make it exactly our tested version at some point).

**Comment by aknuds1** [comment]
@larkost Dang, the brew package must've changed, since I'm pretty sure they didn't specify `--config-file` before.

**Comment by aknuds1** [comment]
Well, I guess this issue should be changed to update the documentation to take into account that the configuration file is /usr/local/etc/rethinkdb.conf if installing with brew.

**Comment by danielmewes** [comment]
Closing in favor of https://github.com/rethinkdb/docs/issues/986
