### ISSUE TITLE
Provide a warning when RethinkDB begins using swap

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#5235]
I was discussing this with @coffeemug this morning -- when there is insufficient memory on a machine for a given data set / workload, RethinkDB will start to use swap, which cause a massive slowdown in performance.

It would be good to provide a warning on a per-server basis when the `rethinkdb` process starts using swap, in the web UI and/or the `current_issues` table.

**Comment by coffeemug** [comment]
:+1: people make this mistake over and over again -- their system goes into swap, they don't know, but think it's RethinkDB's fault. A clear warning in the WebUI that part of the cluster is in swap would go a long way towards pointing people in the right direction, and will result in a dramatically better experience.

**Comment by thinklinux** [comment]
I agree with you guys. I don't know if there is an easy way to check this right now but I believe the hard part is to even come to the idea that RethinkDB is using swap. A warning will indeed help a lot.

**Comment by danielmewes** [comment]
This is closely related to https://github.com/rethinkdb/rethinkdb/issues/3565 , and I think we should address both.

I don't know if we can detect if the `rethinkdb` process specifically has gone into swap (we might!), but we can certainly detect when swap is being used at all on a server.

One edge case to consider is when someone uses suspend to disk on Linux. In that case, after resuming from the suspended state, everything will be in swap (since that's how suspend to disk / hibernation is implemented). It can take many days after that until all data has been paged back into RAM again, or it might never happen. There are three options I can think of:

1. Ignore this issue. Hibernation is probably less common now than it used to be, since suspend to RAM is working much better on Linux these days. It's also obviously uncommon on servers.
2. Try to measure swap usage in a smarter way. For example we could watch system statistics for how many pages are *paged out* to swap at a given moment. We could try to measure this instead of the total amount of pages in swap. Then we could generate an issue saying something along the lines of "Swapping detected within the past 24 hours".
3. Allow users to disable the check or dismiss the issue.

Option 3 would be nice, but could be a lot of work depending on how we want to implement it. I think option 2 would be the best one if it works.

Other warnings we can consider:
* less than 10% RAM available
* less than 10% (or so) disk space available

For these the thresholds would probably need to be configurable.


This seems pretty important. Let's try to do this for 2.3.

**Comment by nighelles** [comment]
Forgot to mention this was in review 3470,
implemented in nighelles/5235.

**Comment by nighelles** [comment]
This is in next.
