### ISSUE TITLE
test/rql_test/polyglot/aggregation.rb1.9 failing in next

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/rethinkdb#5251]
Several instances of `Sorry, r.row is not available in the ruby driver.  Use blocks instead.`.

The other (dynamic) languages (Javascript, Python) pass just fine.

Seems to be introduced by #4846; pinging @deontologician and @marshall007

**Comment by deontologician** [comment]
OK, just looks like we need specific rb sections in the new tests from #4846 : https://github.com/rethinkdb/rethinkdb/pull/4846/files#diff-af5d717b6b9e59303e71132b12f70866R555

**Comment by marshall007** [comment]
Whoops, I tried to write these in a way that would be language-agnostic and didn't know about the `r.row` limitation in the Ruby driver. PR is up with the fix.

@deontologician @larkost could we add Ruby 2.2 to the default `rb` interpreter? That's what ships with OSX as the system default now and I didn't notice they weren't passing before submitting my previous PR (since I just ran `./test-runner polyglot/aggregation`).

**Comment by larkost** [comment]
I am trying to keep the base default interpreter to the lowest version of every language (so: py2.6, rb1.9, and node0.12 [1]). That being said, if you just use the default it will search for the first version that you have installed (on MacOS is would be py2.6, rb2.0, and an error for Node). This is deliberate as our problems more often come out of older versions of interpreters rather than newer. I do make regular runs of all of our supported interpreters, so cover all my bases.

[1] The Java testing is not yet integrated, but it will wind up with Java1.8
