### ISSUE TITLE
Core dump on FC23

### ISSUE THREAD

**Issue by zopyx** [rethinkdb/rethinkdb#5264]
Linux vmd9666.contabo.host 4.2.7-300.fc23.x86_64 #1 SMP Wed Dec 9 22:28:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[ajung@vmd9666 ~]$ rethinkdb  -d /tmp
Recursively removing directory /tmp/tmp
Running rethinkdb 2.2.2 (GCC 4.8.3)...
Running on Linux 4.2.7-300.fc23.x86_64 x86_64
Loading data from directory /tmp
Version: rethinkdb 2.2.2 (GCC 4.8.3)
error: Inaccessible database file: "/tmp/metadata": No such file or directory
       Some possible reasons:
       - the database file couldn't be created or opened for reading and writing
       - the user which was used to start the database is not an owner of the file
Trace/breakpoint trap (core dumped)

**Comment by danielmewes** [comment]
This sounds like there is no data directory at `/tmp`. Usually RethinkDB will initialize the path passed into `/tmp` as a data directory on first launch, but only if the directory is empty. I assume this isn't the case for `/tmp`.

Can you try starting it with `rethinkdb -d /tmp/rethinkdb_data`?
`rethinkdb` should then create a new subdirectory and initialize that as a data directory, creating the mentioned `metadata` file.

**Comment by zopyx** [comment]
Such an error condition is not a reason for creating a core dump.This is a bug.

**Comment by danielmewes** [comment]
Yeah, we already have https://github.com/rethinkdb/rethinkdb/issues/1310 for that.

On the other hand setting a breakpoint (which outside a debugger causes a core dump on Linux) can make debugging easier if an i/o error like this one occur in an unexpected way.

**Comment by rightbraindev** [comment]
I've the same problem after restarting a server: the metadata and table files are deleted.

Everything is correct configured for systemd like in the documentation. The -d switch doesn't help here.
The data directory is set in the config file and the log says: "Loading data from directory /run/rethinkdb/node1" - the data directory is known.

Here is the log_file:
```
2016-01-12T11:53:48.170107320 0.000639s notice: Recursively removing directory /run/rethinkdb/node1/tmp
2016-01-12T11:53:48.172162108 0.002694s notice: Running rethinkdb 2.2.1~0wily (GCC 5.2.1)...
2016-01-12T11:53:48.174578082 0.005111s notice: Running on Linux 4.2.0-23-generic x86_64
2016-01-12T11:53:48.174616531 0.005148s notice: Loading data from directory /run/rethinkdb/node1
2016-01-12T11:53:48.175302209 0.005834s error: Inaccessible database file: "/run/rethinkdb/node1/metadata": No such file or directory\nSome possible reasons:\n- the database file couldn't be created or opened for reading and writing\n- the user which was used to start the database is not an owner of the file```

**Comment by danielmewes** [comment]
@rightbraindev Do you mean that the files were there at first, but disappeared after a restart?
Could there be any startup scripts in your system that clear out `/run` on startup? (This is common for `/var/run`, which is why I'm asking)

The error suggests that there is at least some data left in the `/run/rethinkdb/node1` directory. Which files are still in there?

**Comment by rightbraindev** [comment]
Yes they disappeared after restart. I stopped the systemd service rethinkdb@node1 (looking whether the processes really have disappeared) 
The data files where already there. The I restarted the server and found the following files/folders:
/run/rethinkdb/node1, /run/rethinkdb/node1/tmp, /run/rethinkdb/node1/log_file. 

No data files (the uuid named ones) and no metadata anymore.

**Comment by danielmewes** [comment]
@rightbraindev  This is a separate issue from the OP's, since in your case the already existing data files were deleted. Have you setup your own systemd configuration for starting RethinkDB, or are you using the init.d script that we provide? If you've configured your own, could you post the systemd RethinkDB configuration please? Maybe something in there is clearing out the directory...

Could you also send us a copy of the `log_file` that's still there (share on http://gist.github.com , or email to daniel@rethinkdb.com)? It might contain hints on whether RethinkDB deleted those files itself or not.

**Comment by rightbraindev** [comment]
Hallo Daniel,

here are some files of interest for you. In my configuration there are 3 
servers running, one db node on each one, sharding=1, replicas=3.

By the way for me this problem is not critical at the moment but maybe 
for other users. And ... I really like this database. I often thought: 
"They have done right really everything!"


Best regards,
Daniel

Am 13.01.2016 um 23:41 schrieb Daniel Mewes:
>
> @rightbraindev <https://github.com/rightbraindev> This is a separate 
> issue from the OP's, since in your case the already existing data 
> files were deleted. Have you setup your own systemd configuration for 
> starting RethinkDB, or are you using the init.d script that we 
> provide? If you've configured your own, could you post the systemd 
> RethinkDB configuration please? Maybe something in there is clearing 
> out the directory...
>
> Could you also send us a copy of the |log_file| that's still there 
> (share on http://gist.github.com , or email to daniel@rethinkdb.com 
> <mailto:daniel@rethinkdb.com>)? It might contain hints on whether 
> RethinkDB deleted those files itself or not.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rethinkdb/rethinkdb/issues/5264#issuecomment-171460405>.
>



[Unit]
Description=RethinkDB database server for instance '%i'

[Service]
User=rethinkdb
Group=rethinkdb
ExecStart=/usr/bin/rethinkdb serve --config-file /etc/rethinkdb/instances.d/%i.conf
KillMode=process
PrivateTmp=true

[Install]
WantedBy=multi-user.target
2016-01-12T11:53:48.170107320 0.000639s notice: Recursively removing directory /run/rethinkdb/node1/tmp
2016-01-12T11:53:48.172162108 0.002694s notice: Running rethinkdb 2.2.1~0wily (GCC 5.2.1)...
2016-01-12T11:53:48.174578082 0.005111s notice: Running on Linux 4.2.0-23-generic x86_64
2016-01-12T11:53:48.174616531 0.005148s notice: Loading data from directory /run/rethinkdb/node1
2016-01-12T11:53:48.175302209 0.005834s error: Inaccessible database file: "/run/rethinkdb/node1/metadata": No such file or directory\nSome possible reasons:\n- the database file couldn't be created or opened for reading and writing\n- the user which was used to start the database is not an owner of the file

#
# RethinkDB instance configuration sample
#
# - Give this file the extension .conf and put it in /etc/rethinkdb/instances.d in order to enable it.
# - See http://www.rethinkdb.com/docs/guides/startup/ for the complete documentation
# - Uncomment an option to change its value.
#

###############################
## RethinkDB configuration
###############################

### Process options

## User and group used to run rethinkdb
## Command line default: do not change user or group
## Init script default: rethinkdb user and group
# runuser=rethinkdb
# rungroup=rethinkdb

## Stash the pid in this file when the process is running
## Command line default: none
## Init script default: /var/run/rethinkdb/<name>/pid_file (where <name> is the name of this config file without the extension)
# pid-file=/var/run/rethinkdb/rethinkdb.pid

### File path options

## Directory to store data and metadata
## Command line default: ./rethinkdb_data
## Init script default: /var/lib/rethinkdb/<name>/ (where <name> is the name of this file without the extension)
directory=/run/rethinkdb/node1

## Log file options
## Default: <directory>/log_file
# log-file=/var/log/rethinkdb

### Network options

## Address of local interfaces to listen on when accepting connections
## May be 'all' or an IP address, loopback addresses are enabled by default
    ## Default: all local addresses
bind=192.168.100.18

## Address that other rethinkdb instances will use to connect to this server.
## It can be specified multiple times
# canonical-address=

## The port for rethinkdb protocol for client drivers
## Default: 28015 + port-offset
# driver-port=28015

## The port for receiving connections from other nodes
## Default: 29015 + port-offset
# cluster-port=29015

## The host:port of a node that rethinkdb will connect to
## This option can be specified multiple times.
## Default: none
join=192.168.100.17:29015
join=192.168.100.16:29015

## All ports used locally will have this value added
## Default: 0
# port-offset=0

## r.http(...) queries will use the given server as a web proxy
## Default: no proxy
# reql-http-proxy=socks5://example.com:1080

### Web options

## Port for the http admin console
## Default: 8080 + port-offset
# http-port=8080

## Disable web administration console
# no-http-admin

### CPU options

## The number of cores to use
## Default: total number of cores of the CPU
cores=4

### Memory options

## Size of the cache in MB
## Default: Half of the available RAM on startup
cache-size=2048

### Disk

## How many simultaneous I/O operations can happen at the same time
# io-threads=64

## Enable direct I/O
# direct-io

### Meta

## The name for this server (as will appear in the metadata).
## If not specified, it will be randomly chosen from a short list of names.
server-name=server18
