### ISSUE TITLE
r.error could be more flexible with incoming types

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#5296]
I'm not sure if this is just a driver error, but if you try to use a variable in `r.error` in the following ways it will not work:
 * `r.error('some string: ' + doc('field'))`
 * `r.error(r.expr('some string: ') + doc('field'))`

The work around in my case was to use: `r.error(r.expr('some string: ').add(doc('field1'))`, which is totally fine, if not totally intuitive initially.

**Comment by danielmewes** [comment]
Assuming this is JavaScript, that's just because we cannot overload the `+` operator. So you have to use `.add` in combination with `r.expr`. Unfortunately there's nothing we can do about this as far as I know.
In the Python and Ruby driver we overload the `+` operator. You still need to use `r.expr` there to turn the string into a ReQL string, but you can avoid the `add`.

**Comment by mbroadst** [comment]
thanks for the info
