### ISSUE TITLE
Java driver doesn't automatically reconnect.

### ISSUE THREAD

**Issue by pires** [rethinkdb/rethinkdb#5305]
While `Connection.reconnect(...)` is available, it's not used anywhere in the code.

**Comment by danielmewes** [comment]
That's intentional. Right now connection management is completely explicit (nicer word for manual) in the Java driver. This is consistent with our other official drivers.
`reconnect` is meant to be called by the user or application.

**Comment by pires** [comment]
Validating a connection is up every time a read/write is made feels terrible to me as an user.

Does RethinkDB protocol provide something like PostgreSQL `ping`? Something the driver could expose so the user could run this on a scheduled task to prevent disconnections?

**Comment by danielmewes** [comment]
Well you can run something like `r.expr(1)` from time to time to keep the connection alive if that's an issue. Though we're also turning on TCP keepalive, so the connections shouldn't usually expire.

Note that even if we did check for a connection to be up before running a query, you would still need to catch errors since the connection might go down in the middle of the `run` after the check. And if the network or server is actually down, an automatic `reconnect` wouldn't help either. We would need some more complex logic that backs off and retries the connect for a configurable time. This goes more into the terrain of a connection pool.

I'm not saying we shouldn't do it, but it's a bit more work than just checking if the connection is open and then calling `reconnect` if it's not.

**Comment by pires** [comment]
@danielmewes `r.expr(1)` should work.

Regarding TCP keepalive, I'm not sure how that works with proxies in between, particularly because TCP said mechanism does not transport any data (_null_ payload).

I had this experience with Compose.io.

**Comment by danielmewes** [comment]
> Regarding TCP keepalive, I'm not sure how that works with proxies in between, particularly because TCP said mechanism does not transport any data (null payload).

I think you're right. Depending on the proxy the TCP keepalive might not have the desired effect.
