### ISSUE TITLE
--direct-io option in virtual environments

### ISSUE THREAD

**Issue by LMnet** [rethinkdb/rethinkdb#5340]
I didn't find any information about this moment in the docs. How can I use --direct-io in virtual environments? Any limitations, advices? Will rethinkdb throw explicit error if I can't use --direct-io in the current environment?

**Comment by danielmewes** [comment]
Hi @LMnet, we don't usually recommend enabling `--direct-io`. The reason for this is that some file systems have had bugs in the O_DIRECT mode that this is based on in the past.

If direct I/O is not supported at all, RethinkDB will print a warning when you start it with `--direct-io`, and run with normal buffered I/O instead (or maybe it will exit, I don't remember). However it can't detect whether the file system's or storage driver's implementation of this mode is buggy or not. Some file systems pretend to support direct I/O, but then behave incorrectly.

Unless there is a strong need to or you see significantly higher performance with this option, I'd advise against enabling it in a virtual environment.

If you are running on bare hardware with something like ext3 or ext4 it's a safe option to enable, but since you're using a virtualized environment, I wouldn't necessarily trust its storage backend in this respect (especially if the volume is network-mounted).
