### ISSUE TITLE
match() on indexes

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#5343]
It would be cool if I could run .match() on the raw string generated from compound indexes and return its documents!

**Comment by deontologician** [comment]
Are you trying to get all documents in the index?

**Comment by thelinuxlich** [comment]
Just those that would fit a regex on the compound index raw string

**Comment by danielmewes** [comment]
@thelinuxlich Could you show an example?
I'm not sure if I understand what you mean by the raw string of the compound index.

**Comment by thelinuxlich** [comment]
A compound index like [99,"Alisson",31], and you wanna write a regex to get the row based on a fragment of the index:
```
r.table("test").match("/[0-9]{2}[a-zA-Z]+31{/",{index: "client_id_name_age"})
```

**Comment by danielmewes** [comment]
I see. It seems to me that the limiting part here is really that we don't allow access to the secondary index values of a table. This isn't a problem for performance, since they can be easily recomputed. But might be an issue for convenience in some cases.

The other missing piece is that we don't have a canonical conversion from an array to a string. However you could use `.toJsonString()`, or write your own function.
For example to get simply the concatenation of the array elements:
```js
r.expr([99, "Alisson", 31]).reduce(function(l, r) { return l.coerceTo('string').add(r.coerceTo('string')); })
```
(in the future, the `fold` term will be a better replacement to the `reduce` in this https://github.com/rethinkdb/rethinkdb/issues/3736 )

That being said, you can do this already by re-applying the secondary index function manually:
```js
r.table("test").filter(
    r.expr([r.row("client_id",), r.row("name"), r.row("age")])
     .reduce(function(l, r) { return l.coerceTo('string').add(r.coerceTo('string')); })
     .match("/^[0-9]{2}[a-zA-Z]+31$/")
  )
```

The index doesn't really help here anyway, since we can't query it efficiently when using `match`.

**Comment by thelinuxlich** [comment]
I'm gonna close this because #5351 solves this issue

**Comment by goors** [comment]
@thelinuxlich were you able to solve this? regex on secondary indexes? if yes can you please share (point me to right docs)?

**Comment by thelinuxlich** [comment]
There is no workaround, if .match() without index doesn't give you a good performance, wait for #5351
