### ISSUE TITLE
Async backend for Java driver

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5345]
To make the Java driver really useful for realtime applications, we need to add a way for handling changefeeds asynchronously.

A good first step is going to be making the Java connections thread-save, which @pires has started working on in https://github.com/rethinkdb/rethinkdb/pull/5292 .

However we should also integrate with some of the available frameworks for this type of thing that exist apart from raw threads. Here are a few that we should consider:
- RxJava https://github.com/ReactiveX/RxJava (interesting read: http://blog.couchbase.com/why-couchbase-chose-rxjava-new-java-sdk )
- Reactive Streams https://github.com/reactive-streams/reactive-streams-jvm
- Netty http://netty.io/ https://github.com/rethinkdb/rethinkdb/issues/4802

As far as I understand, RxJava and Reactive Streams are higher-level APIs, while netty is a bit more low-level.

We should discuss which one we want to focus on first. Ideally we'll provide support for all of these APIs / frameworks eventually, similar to the Python driver, but let's start with one.

**Comment by danielmewes** [comment]
(mentioning @deontologician, @hepin1989, @kofalt, @danielcompton who have commented on the netty issue before)

**Comment by bchavez** [comment]
if `RxJava` is conceptually the same as `Rx.NET` then with the architectural changes @pires is making to line up with the .NET driver, `RxJava` should work pretty much out of the box with little to no changes.

##### `async` `Changefeeds` with .NET driver:
https://github.com/bchavez/RethinkDb.Driver/wiki/Extra-C%23-Driver-Features#reactive-extensions-rx-support

**Comment by deontologician** [comment]
Given that we're using RxJS for another project, and the interfaces are similar, I think it'll be easy to dive into RxJava first

**Comment by rocketraman** [comment]
You really should consider exposing a reactive-streams interface for client code. If you do this, the driver will be compatible with all sorts of java async libraries your users might be using, *including* RxJava but also man others like Akka, Quasar, Vert.X and others (see http://www.reactive-streams.org/announce-1.0.0). In addition, it has a nice TCK to verify your implementation against the spec (https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.0/tck/README.md).

See for example: https://github.com/ReactiveX/RxJava/wiki/Reactive-Streams

**Comment by dazito** [comment]
I completly agree with @rocketraman

**Comment by danielcompton** [comment]
From a Clojure perspective, we could use RxJava or ReactiveStreams, combined with https://github.com/ztellman/manifold for translation into Clojure land.

**Comment by danielmewes** [comment]
After reading up on ReactiveStreams a bit, I think I agree that it makes sense to support that (first). It seems to be becoming the quasi-standard API for asynchronous streams, and is designed to interoperate with other higher-level frameworks.

**Comment by Torpexx** [comment]
Any update on this? I think it would be a great addition and a lot of people will benefit from it! :)

**Comment by danielmewes** [comment]
@Torpexx We haven't started working on this yet. We'll hopefully get to it for RethinkDB 2.4 (within the next two months or so).

**Comment by foliot** [comment]
Anybody know how much garbage is produced by these reactive frameworks? I'm hoping to minimize garbage collection in my application to keep latency under control. 

What I'm envisioning is to have a single buffer for each connection that is never de-allocated, and provide a way for users to define a callback that would be notified when the buffer has changed. The callback could clone the data from the buffer and send it off into a reactive stream or handle it in any other way, but the buffer will be reused for the next response from the server and can be considered unsafe to use after the callback has completed.

**Comment by gordysc** [comment]
Any update on this?

**Comment by 20zinnm** [comment]
I'm working on this, stay tuned 😄

**Comment by KrzysztofKowalczyk** [comment]
Delivering only RxJava implementation would not be the best option.

There are 2 consumers of the reactive API, one is the actual developer, another would be framework trying to integrate with it. For instance having Reactive-Stream implemented does not make it "compatible" with Vert.x, one can't use such api without special care any way. Same with RxJava as one still need to take care of how threading is done and on what threads callbacks are done.

Couchbase, for instance, has reasonable RxJava client. It is nice for the consumer but creates ~20 extra threads because it is using its own netty and it's own rx schedulers with 2 or 3 thread pools. Vert.x has its own support for RxJava and netty thread pools as well. That creates all sort of issues because vert.x has its own threading model that has special assumptions to be thread safe, asyc and limit context switches. In this particular case one need to switch thread 2 times for every db operation (Couchbase IO -> couchbase computation -> vertx computation), where one switch (IO -> Computation) should be enough. Plus it requires one to remember context (to use custom rx scheduler or use runOnContext) before calling the DB, otherwise one risk dozens of nondeterministic problems.
Once done it does work, though, and it gc back to 50 mb of heap usage after few weeks of running 1k/s requests which contact db 3 times call other services etc.  Even though rx has significant overhead in synthetic tests, real service is still IO not CPU bound and there might be no visible difference. Db still responds in <1ms.

So from the user perspective, it is good to have an async framework with bells and weasels. Unless user already use one or uses it differently. Thus such support could be still divided into 2 parts. One that gives the minimum, even if it is based on callbacks and second that builds on top of first.

Maybe the first one should give user the ability to offload work to user selected threads (for computation threads, rather not for IO) or just runs callbacks on the IO threads but inform users that this is api for extensions, not for end user. Thus one should take care of offloading the work right away to other thread. Of course, it would be nice to have reactive streams support as there is an adapter for every other significant async framework right now. Having backpressure handled on db side would be great for streaming scenario.

Then based on this core, a core vert.x could use core api. Rx guys could use RxJava and Spring guys could use Reactor. You will need to support both RxJava 1 and 2, as 1 is and will be used for a while were 2 is getting traction fast even if it's not final (also is better for end user because of clear types of streams).

**Comment by triplem** [comment]
Sorry für necromancing.
Aber good way to go, would be to implement a fully async driver. This would then be used in an reactive Implementation. No way to implement something for all reactive Frameworks in one go. Abstract it in an async driver and then add specifics above.

**Comment by tipsy** [comment]
Any update on this?

**Comment by srh** [comment]
No

**Comment by tipsy** [comment]
@srh I just discovered rethink a few hours ago, so please forgive my ignorance. Are there any major downsides to doing something like this?

```kotlin
class AsyncReqlExpr(reqlExpr: ReqlExpr) {

    private val callbacks = ConcurrentHashMap.newKeySet<(Any) -> Unit>()

    init {
        Thread {
            val cursor = reqlExpr.changes().run<Cursor<*>>(DbUtil.getConnection())
            for (doc in cursor) { // this loop is blocking
                callbacks.forEach { it.invoke(doc) }
            }
        }.start()
    }

    fun onNew(func: (Any) -> Unit) = callbacks.add(func)

}
```

Usage
```kotlin
Javalin.create().apply {
    port(8081)
    enableStaticFiles("/public")
    ws("/rethink-test") { ws ->
        val clients = ConcurrentHashMap.newKeySet<WsSession>()
        AsyncReqlExpr(RethinkDB.r.table("authors")).onNew { result ->
            clients.filter { it.isOpen }.forEach {
                it.send(result.toString())
            }
        }
        ws.onConnect({ session -> clients.add(session) })
        ws.onClose({ session, _, _ -> clients.remove(session) })
    }
}.start()
```

**Comment by srh** [comment]
If that's sharing a connection then I think that doesn't work. If it's not sharing a connection then it would generally be OK.

**Comment by adriantodt** [comment]
I implemented this without even knowing that this issue existed. This is now implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/12) of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed. Please, share feedback and discuss it on the PR :)
