### ISSUE TITLE
Performance impact of changefeed

### ISSUE THREAD

**Issue by gjuchault** [rethinkdb/rethinkdb#5367]
Hi,

I would like to know what would be the performance impact of listening for a changefeed on a whole database ? Or on one table. Does it slow (relatively) the server ?

Thanks

**Comment by danielmewes** [comment]
Hi @gjuchault The overhead of a changefeed is going to be very small. The exception is that if you have a high rate of write operations, it will generate a significant amount of additional network load because it needs to send out the change events to the client.

In the other extreme, if you don't do any writes, the performance impact of having the changefeed is basically zero.
