### ISSUE TITLE
r.error() doesn't always result in an error in the node.js driver

### ISSUE THREAD

**Issue by Prinzhorn** [rethinkdb/rethinkdb#5395]
I've just started working with RethinkDB but it seems like I found a bug right away. Or I'm doing something really edge-casey. Or wrong? Or both.

node v5.1.0
driver 2.2.1
rethinkdb 2.2.4~0trusty (GCC 4.8.2)

Here's the code to reproduce together with an explanation. I'm basically trying to implemented optimistic locking using `r.branch`. I know it's not atomic and thus there's no guarantee, but that's good enough for my use case (it's not a banking software...). Every doc in the `thing` database has a `version` property. When updating a thing, I compare the two versions to make sure the update is based on the most recent document. The example code has a conflict hard coded. The version is already at 3 but the update tries to update the version from 1 to 2.

```js
var r = require('rethinkdb');

var dbConfig = {
	host: 'localhost',
	port: 28015,
	db: 'test'
};

r.connect(dbConfig, function(err, conn) {
	if(err) {
		console.error(err);
		process.exit(1);
	}

	r.tableCreate('thing').run(conn, function(err) {
		//We silently ignore the error because the table likely exists already.

		r.table('thing').insert({
			id: 'foobar',
			version: 3
		}).run(conn, function(err) {
			if(err) {
				console.error(err);
				process.exit(1);
			}

			r.table('thing').get('foobar').replace(function(thing) {
				return r.branch(
					thing('version').eq(1),
					thing.merge({version: 2}),
					r.error('version conflict')
				)
			}).run(conn, function(err, ironman) {
				console.log(err, ironman);
				conn.close();
			})
		});
	});
});
```

**Instead of an error I get the following response (error parameter is `null`)**

```js
{ deleted: 0,
  errors: 1,
  first_error: 'version conflict',
  inserted: 0,
  replaced: 0,
  skipped: 0,
  unchanged: 0 }
```

In other cases, like the one in the [documentation](https://rethinkdb.com/api/javascript/error/), `r.error` inside `r.branch` actually results in an error.

**Comment by Prinzhorn** [comment]
I now think this is intended behavior, because multiple documents could be affected, some with errors others successful. It still confuses me though, because in one case `r.error` results in an error in the other it only kind of does. But I guess it's a philosophical question if the error parameter should be filled if some documents where successful and others weren't. Can someone point to discussion if there was some?

**Comment by danielmewes** [comment]
@Prinzhorn This is indeed intended behavior, but I can see that it can be confusing / non-obvious.

The fundamental reason for write operations to return an error document rather than throwing the error directly is that they can generally be applied to multiple documents at once (e.g. if you did `r.table().update()` that would update all documents in the table). If the update of one document fails with an error, some of the other updates might still have been performed.

So we return this document with the `deleted`, `errors`, `inserted`, `replaced` etc. fields to give some information about how many of the writes have succeeded vs. failed.

You can look at https://github.com/rethinkdb/rethinkdb/issues/3440 and the links in there for some more details.

**Comment by danielmewes** [comment]
I opened an issue on our documentation issue tracker to make this behavior clearer in the API docs: https://github.com/rethinkdb/docs/issues/1018

**Comment by Prinzhorn** [comment]
@danielmewes thank you very much
