### ISSUE TITLE
Inverted getAll()

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#5423]
Suppose I want to get all documents which doesn't match a blacklist in a fast way:

```
r.table("users").getAll(...id_blacklist).not()
```
or
```
r.table("users").getAllNot(...id_blacklist)
```

**Comment by VeXocide** [comment]
This depends on the number of users compared to those blacklisted. If it's a relatively small number that are blacklisted you'll effectively do a table scan and simply using a filter is your best option, don't overthink this. If the majority is blacklisted that isn't the case anymore, and I'm not quite sure how you'd best handle that, setting a flag on the user and indexing that would likely be the way to go.

I'll close this issue since it's not a bug, but feel free to ask more questions here.

**Comment by danielmewes** [comment]
There's actually a way for doing this, though it's a bit cumbersome:
```js
r.expr(id_blacklist).orderBy(r.row).do(function(sortedBlacklist) {
    lowerBounds = r.expr([r.minval]).add(sortedBlacklist);
    upperBounds = sortedBlacklist.append(r.maxval);
    unionArgs = lowerBounds.map(upperBounds, function(lo, up) {
        return r.table('users').between(lo, up, {lowerBound: "open", upperBound: "open"});
    });
    return r.union(r.args(unionArgs));
})
```

I haven't tried it yet. But I hope you get the idea. Basically you construct a bunch of open ranges *around* the blacklist IDs and combine them into in a union.

**Comment by danielmewes** [comment]
...Actually I think this doesn't quite work, because you can't put the `r.table.between` into an `r.args` since it's a stream. You could cast those to an array if the result is expected to be small, but that's not ideal.

There's probably a slightly different way of getting the same query that works better. Or you could do a part of the query construction logic on the client.

**Comment by VeXocide** [comment]
I had this thought as well but it doesn't scale well as you mention, and in that situation it's a premature optimization in my opinion.

**Comment by danielmewes** [comment]
Well it scales about as well as a filter I think, except for the case where you use a secondary index and the blacklisted IDs have lots of matches in which case it scales better.

But I agree that unless the latter is the case, a `filter` is probably the way to go because it's simple.
@thelinuxlich Does that work for you?

**Comment by thelinuxlich** [comment]
Yes, it can do the job
