### ISSUE TITLE
iOS and Android SDK?

### ISSUE THREAD

**Issue by TofPlay** [rethinkdb/rethinkdb#5496]
Do you have an SDK for iOS and Android?

**Comment by Wargog** [comment]
You can use the [Java API](http://rethinkdb.com/docs/install-drivers/java/) for Android, and as far as I know there are no APIs for iOS.

**Comment by danielmewes** [comment]
For iOS, there's a chance that you can use this Objective C driver https://github.com/dparnell/rethink-db-client , but I don't understand the iOS environment very well.

Usually an iOS or Android application would not access a RethinkDB server directly, but instead would connect to an application-specific backend that you implement, which in turn would talk to RethinkDB. 

This is important because a RethinkDB server cannot be exposed publicly on the Internet without severely risking the security of the server and the safety of the stored data.

We're working on a new backend and API that's aimed specifically at writing frontend applications without having to deal with custom backend code. It's going to be called Horizon, and there's some info on it in this comment: https://github.com/rethinkdb/rethinkdb/issues/3711#issuecomment-151639571

The very first release of Horizon is going to target browser-based web applications, but support for mobile applications should follow soon. I think Horizon might be closer to what you're looking for, depending on your requirements.

**Comment by TofPlay** [comment]
@danielmewes Thanks for your answer
> I think Horizon might be closer to what you're looking for, depending on your requirements.
I don't know about Horizon but why not. My requirements are simple have an open solution that I can install on my server with same features as Firebase or better. SDKs for iOS and Android are an absolute requirement too.

**Comment by danielmewes** [comment]
> My requirements are simple have an open solution that I can install on my server with same features as Firebase or better

Sounds like Horizon will work for you. It's basically what you describe, though the SDKs for iOS and Android will follow later (the first release will target browser-based applications, but I'm pretty sure we'll add SDKs for mobile apps soon after).

**Comment by richardbarabe** [comment]
@TofPlay 
Hi, I have pretty much the same requirements (firebase like with native SDKs).  What did you end up using ?

I was thrilled by Horizon and rethinkDB but unfortunately I'm not sure native SDKs will be there soon.

**Comment by TofPlay** [comment]
@richardbarabe with no real native support for iOS and Android rethinkDB has been set aside.

**Comment by boumitran** [comment]
same here. need an opensource firebase like thing..

**Comment by nicomontanari98** [comment]
@TofPlay 

> For Android there is Java SDK [https://www.rethinkdb.com/docs/install-drivers/java/](url)

> For iOS there are Object-c SDK [https://github.com/dparnell/rethink-db-client](url) and Swift SDK [https://github.com/pixelspark/rethink-swift](url) (## Object-c SDK features are limited!)

**Comment by TofPlay** [comment]
@nicomontanari98 your urls are invalids. When I click I have this page
![image](https://user-images.githubusercontent.com/1082222/35323793-13bcf952-00ef-11e8-88fd-5634cb80e476.png)

**Comment by nicomontanari98** [comment]
@TofPlay Try now, i corrected URLs
