### ISSUE TITLE
Physical references to records

### ISSUE THREAD

**Issue by sinfex** [rethinkdb/rethinkdb#5497]
How about introducing a way of referring to records using their physical location? I don't believe such a way of referencing is common among DBs, but it might be pretty neat and go hand-in-hand with #4853. Excerpt from the documentation of a Graph database:

> A RID (Record ID) is the physical position of the record inside the database. This means that loading a record by its RID is blazing fast, even with a growing database. With document and relational DBMS the more data you have, the slower the database will be. Joins have a heavy runtime cost. The DB handles relationships as physical links to the records. The relationship is assigned only once when the edge is created O(1). Compare this to an RDBMS that "computes" the relationship every single time you query a database O(LogN). Traversing speed is not affected by the database size. It is always constant, whether for one record or 100 billion records. This is critical in the age of Big Data

**Comment by danielmewes** [comment]
Thanks for the proposal @sinfex .

I don't think we can support this in RethinkDB. RethinkDB stores small documents (< 250 bytes) inline in the (primary key) index tree. That means that their physical location can change at any time if any rebalancing occurs on the tree. The physical location of the record would change.
(in this scenario I'm already assuming that we use something we call "logical block IDs" as the "physical" location. It's slightly more stable than an actual physical location, which would be even worse (RethinkDB frequently relocates data within the file during garbage collection))

Physical references would also not work (well) in a clustered environment, since the reference would likely be a different one on each replica.

Which database are you citing from? If they are a distributed database, I'm curious how they implement this ID and what its limitations are.

On a side note, I think that the quote is somewhat misleading. The quote is making the implication that O(1) rather than O(log N) lookup time is "critical in the age of Big Data". However for realistic distributions on `N`, I think that those two complexity classes should be considered equivalent. `log N` gets very very close to a constant once `N` reaches a certain size.

**Comment by sinfex** [comment]
@danielmewes this is cited from OrientDB: http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Record-ID.html

The way they deal with it is pretty simple: the record IDs are in the form `#<cluster-id>:<cluster-position>`.

I'm not sure about the limitations; in fact, it's the only way to access records directly without defining a separate property+index. The only thing I ran into is that if you expose these IDs to the outside world and manually move the records to another cluster (they have a [MOVE VERTEX](http://orientdb.com/docs/2.1/SQL-Move-Vertex.html) command for sharding purposes), you should know that the old RIDs will no longer be accessible.

**Comment by danielmewes** [comment]
I see, thanks for the link.

Unfortunately as mentioned, this concept doesn't really work with RethinkDB's storage engine.
