### ISSUE TITLE
rethink-dump issue with python.

### ISSUE THREAD

**Issue by scottder** [rethinkdb/rethinkdb#5651]
I am running 2.3.0~0trusty on an Ubuntu 14.04 machine. I used pip to install the Python drivers (2.3.0). I am getting the following error.

`NOTE: 'rethinkdb-dump' saves data and secondary indexes, but does *not* save
 cluster metadata.  You will need to recreate your cluster setup yourself after
 you run 'rethinkdb-restore'.
Exporting to directory...
ReQL error during 'version check': Could not connect to localhost:28015. Error: %d format: a number is required, not str
Error: rethinkdb-export failed`

with --tls-cert set I get

`NOTE: 'rethinkdb-dump' saves data and secondary indexes, but does *not* save
 cluster metadata.  You will need to recreate your cluster setup yourself after
 you run 'rethinkdb-restore'.
Exporting to directory...
ReQL error during 'version check': Could not connect to localhost:28015. Error: 'module' object has no attribute 'SSLContext'
Error: rethinkdb-export failed`

**Comment by danielmewes** [comment]
Hi @scottder, the first issue might indicate a wrong password. Do you have an admin password (previously auth key) set on your cluster? If yes, you can try passing in the `-p` option.
If you have TLS enabled for the driver port on the server though, this won't work since you'll still need the `--tls-cert` option. (In either case the error message is bad, which we have fixed in https://github.com/rethinkdb/rethinkdb/issues/5624 but not released yet.)

The second issue is https://github.com/rethinkdb/rethinkdb/issues/4815. I'll bump that issue and mark this as a duplicate. Do you have a more recent version of Python installed that you could use for the meantime?

**Comment by scottder** [comment]
@danielmewes Thanks, it was thge wrong PW.
