### ISSUE TITLE
Weird error with r.args

### ISSUE THREAD

**Issue by bgnorlov** [rethinkdb/rethinkdb#5662]
I tried to retrieve all folders and merge them with all boards which stored as array of ids but got error which I don't understand 
```javascript
r.connect(config.rethinkdb).then(dbConn=> {
  var time = Date.now();
  r.db('codesign').table('folders').getAll('26711', {index: 'users_id'}).merge((folder)=> {
    return {boards: r.db('codesign').table('boards').getAll(r.args(folder('boards')), {index: 'id'}).coerceTo('array')}
  }).coerceTo('array').run(dbConn).then((res)=> {
    console.log(Date.now() - time, res.length);
  })
});

Unhandled rejection ReqlQueryLogicError: Expected 2 or more arguments but found 1 in:
r.db("codesign").table("folders").getAll("26711", {"index": "users_id"}).merge(function(var_0) { return {"boards": r.db("codesign").table("boards").getAll(r.args(var_0("boards")), {"index": "id"}).coerceTo("array")}; }).coerceTo("array")

```
Seems like r.args not working with brackets operator. I tried to change to r.args(folder('boards').coerceTo('array')) or  r.args(r.expr(folder('boards').coerceTo('array')) but the same result

**Comment by encryptio** [comment]
This occurred in <=2.2 when the `r.args` expanded to zero arguments. https://github.com/rethinkdb/rethinkdb/issues/2588 fixes it in 2.3.

There's a workaround in that issue's first comment that you might be able to use if you're not ready to upgrade to 2.3: `r.getAll(r.args(dynamicThing.append('prevent-empty-error')), {index: ...})`

Closing because I think that solves it. If you have any further questions, feel free to continue to comment here.
