### ISSUE TITLE
Percolate feature like Elasticsearch

### ISSUE THREAD

**Issue by gebrits** [rethinkdb/rethinkdb#5682]
This might already be possible with subscribing to streams but just to be sure: 

is it possible to create a percolate feature like [Elasticsearch Percolate](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-percolate.html) with RethinkDB? 
I.e.: the ability to get notified (server side in our case) when a document matches a particular query? 

usecase: say you were to implement google alerts. A user has a defined query and wants to be notified when a new page is found that matches said query.

**Comment by mlucy** [comment]
RethinkDB doesn't currently have a way to store queries in tables.  We're thinking of adding persistent changefeeds in the future (https://github.com/rethinkdb/rethinkdb/issues/3471), which would be similar in some ways to what you want.

Closing since this isn't a bug, but feel free to continue asking questions here.
