### ISSUE TITLE
.fold() vs .reduce() performance

### ISSUE THREAD

**Issue by frankleng** [rethinkdb/rethinkdb#5685]
Since  ```.reduce()``` simply returns the 1st element if the sequence has 1 element.
I ended up used the new ```.fold()``` instead. It returns the base, so we don't run into inconsistent results when dealing with single and multi element sequences.

Tested them both on a small dataset, but the profiler indicated that ```.fold()``` took consistently 2-3x longer in server time.
Is this because ```.reduce()``` runs in parallel and ```.fold()``` does not?
Can we just have ```.reduce()``` run even when the sequence has 1 element... catch it with ```r.branch()```?

**Comment by danielmewes** [comment]
@frankleng Your interpretation of the performance difference sounds correct. `fold` does not parallelize the way `reduce` does.

You can use the following to provide a default with `reduce` in case of an empty input stream:
`r.expr([]).reduce(function(a, b) {...}).default(base)`

**Comment by danielmewes** [comment]
@frankleng Does the `default` work-around work for you? Maybe we should put such an example in the `reduce` API docs...

**Comment by frankleng** [comment]
@danielmewes ```default``` has no effect since the result is not empty.

**Comment by danielmewes** [comment]
I was thinking about the 0-element input case, but I now see that you mentioned the 1-element scenario.

This comment mentions another work-around https://github.com/rethinkdb/rethinkdb/issues/2629#issuecomment-47708929 by using `.union(['base']).reduce`. However I think that will stop the `reduce` from being parallelized, so it will degrade to the same performance as `fold` more or less.

Can you describe your data and query a bit more? There's probably a way for using a `map` operation in front of the `reduce` in order to get the behavior you need.

**Comment by mlucy** [comment]
@danielmewes -- I'm not 100% sure, but I *think* `union` is smart enough to parallelize the `reduce` if some of its arguments are lazy streams.

@frankleng -- what reduction are you trying to do?  Usually if your reduction is something `reduce` can do correctly, it's also correct to never call it in the one-element case.

**Comment by frankleng** [comment]
@danielmewes @mlucy Thanks for the tips!
I moved up some transformations into ```.map()``` and it's working as intended.
