### ISSUE TITLE
how can i use replication like mysql ??

### ISSUE THREAD

**Issue by c941010623** [rethinkdb/rethinkdb#5688]
this db can use master-slave like mysql ??

**Comment by felixis-1** [comment]
The RethinkDB documentation on sharding and replication [here](https://www.rethinkdb.com/docs/sharding-and-replication/) will help you out.

**Comment by larkost** [comment]
To expand a bit, it is hard to compare our replication directly to what MySQL has but in general what we do is better for almost all cases. I encourage reading the document that @felixis-1 linked to, but here is a short summary:

We allow you to split any table into multiple shards, each of these shards needs to have a `primary` server (they can all be on one, or any combination of servers that makes sense for your workload). Additionally you can tell the system that you also want additional copies of those shards (`replica`s), that typically will placed so that each replica exists on a different server (our tools will automatically do this for you). Doing this makes sure that if any one server goes down that the data is still saved, and still available for queries (after a short outage). The more servers you add to the system, the safer it can be.

Assuming you have at least 3 servers designated for the shards this will work automatically, meaning you don't have to ever "promote" a server as you would in MySQL replication.

Since this is not really a bug I am going to close this issue, but feel free to ask further questions here if you wish. Otherwise we usually recommend a few other routes to ask questions like this: http://rethinkdb.com/community/

**Comment by c941010623** [comment]
if i have two rethinkdb (a and b)
but now i want a asnyc b how can i do it ?
ex: 
a=> ip:192.168.0.1
b=>ip:192.168.0.2

**Comment by larkost** [comment]
I am not sure that I understand you, so here is what I thin you are saying: you have two `rethinkdb` servers ('a' and 'b'), possibly with different tables on them, and you want make sure that data from one is replicated on the other. Is that correct?

Assuming so, then the solution is to either restart one of the servers using the `--join` option to inform it of the other one, or to start a third server (one using `proxy` would work, and not involve a data on disk) and give it two `--join` options to the first two. They will find each other through that third server, which you can immediately take down again.

Once your servers see each other, then you need to use the [`reconfigure`](http://rethinkdb.com/api/python/reconfigure/) command on the tables with `replicas` equal to the number of servers you have running. That will make sure that the data exists on that number of servers.

And as a side note: the way the logic works out it is MUCH safer to have 3 servers rather than 2. In that case we can automatically failover if any one server drops out. In the case of just 2 servers the cluster can't make good decisions when one goes down.
