### ISSUE TITLE
after upgrading 2.3, .limit and then pluck or merge and then .changes gives error

### ISSUE THREAD

**Issue by abovemike** [rethinkdb/rethinkdb#5721]
i recently upgraded to 2.3 and some of my changefeed queries now give the following error:

> "Getting a changefeed on a filter after a limit is not supported in: ((snip query error message))"

worked before:
```
query
.between( [ true, r.minval ], [ true, start ], { index: 'myindex' } )
.orderBy({ index: r.desc('myindex') })         
.limit( limit )
.merge( function (obj) { return {
            hash: obj('id').nth(0),
            multiTenantKey: obj('id').nth(1)
}; } )  
.pluck( pluckMap )
.changes({ includeInitial: true, includeStates: true })
```

i moved the order of operations around and it seems any .pluck or .merge that takes place after .limit is recognized as a .filter and not allowed. so i now have to do this:

```
query
.between( [ true, r.minval ], [ true, start ], { index: 'myindex' } )
.orderBy({ index: r.desc('myindex') })         
.merge( function (obj) { return {
            hash: obj('id').nth(0),
            multiTenantKey: obj('id').nth(1)
}; } )  
.pluck( pluckMap )
.limit( limit )
.changes({ includeInitial: true, includeStates: true })
```

it works fine. i didn't see anything in the docs about this limitation, so maybe it should be included
theoretically is some performance hit because some operations are taking place before the limit and therefore a waste?

thanks for your help

**Comment by danielmewes** [comment]
Hi @abovemike, this change was due to the previous behavior being wrong in certain cases. See https://github.com/rethinkdb/rethinkdb/issues/5325 .

We noted this for the case of `filter` in the 2.3.0 release notes under API-breaking changes https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.0 .

However we missed that this would also affect non-filter queries, such as the `pluck` you are using. The error message is also misleading in that respect.

Putting the `pluck` in front of the `limit` is fine in this case, and won't degrade performance because its evaluation is "lazy" and will only happen for results that are within the limit, so your rewrite should be fine.

Sorry for the confusion.

@nighelles I think we should extend the error message to mention transformations on the data in general, rather than just filters.
I'm also wondering if it was actually necessary to forbid non-filter transformations, though I vaguely remember that it was to guarantee correct `orderBy.limit` changefeed behavior?

**Comment by nighelles** [comment]
I think I spoke with @mlucy about exactly what behavior was necessary to forbid, maybe he has a comment on what it is ok to allow.

I'll improve the error message for this.

**Comment by mlucy** [comment]
`pluck` can never reduce the number of elements in the stream, so it should be safe after a `.limit` in a changefeed.  We should probably change it to be legal again.  (It isn't terribly important though because it has the same semantics as putting it before the `limit`.)

**Comment by danielmewes** [comment]
@mlucy Can you think of a more general criteria for distinguishing allowed from disallowed terms? If we make `pluck` work, we should also make a bunch of other terms work. Anything that can be reduced to a `map` is probably ok, but `concatMap` and similar ones are not, right?

I think I'd prefer to disallow all of them for consistency, rather than white-listing a few particular transformations.

Maybe we should also change add a note to the error message that suggests moving the transformation(s) to before the `limit` to make it more helpful.

**Comment by mlucy** [comment]
@danielmewes -- the general rule is that any operation which can change the number of elements in the stream can't be put after the `filter`.

**Comment by nighelles** [comment]
This is fixed in next.
