### ISSUE TITLE
Server Error on jobs table changefeed

### ISSUE THREAD

**Issue by sagivf** [rethinkdb/rethinkdb#5756]
`r.db('rethinkdb').table('jobs').changes({ squash: true })`

Rehinkdb 2.3.0

![image](https://cloud.githubusercontent.com/assets/1857466/15118915/f9fa07f4-1616-11e6-8f95-c38ef5ac2b5b.png)

**Comment by danielmewes** [comment]
Thanks for reporting @sagivf .
This is very likely the same as https://github.com/rethinkdb/rethinkdb/issues/5644 , which we recently fixed in RethinkDB 2.3.1. As a work-around, you can remove the `{suqash: true}`. It doesn't currently have any effects on the jobs table anyway (changefeeds on `jobs` always have squash semantics).

**Comment by sagivf** [comment]
Thanks @danielmewes , seems like the squash on `jobs` seems it a little to fast, I thought I'd lower it to once every few seconds. But It's fine for now, Thanks again.
