### ISSUE TITLE
`r.expr` error (cannot wrap undefined)

### ISSUE THREAD

**Issue by alexeygolev** [rethinkdb/rethinkdb#5764]
I'm experiencing a weird issue with using javascript driver's `r.expr`. I'm calling it with an array of 
15323 objects to update the records in a table
```js
r.expr(xs).forEach(x => r.table('name').get(x('id')).update({image: x('image')}))
```
It seems like `r.expr` has a limit for an array length. The code works for 10000 but not for the full set.
Any ideas of where to look for a possible solution?

**Comment by danielmewes** [comment]
Hi @alexeygolev, are you getting any error message?

15,323 objects should normally be fine. There's a limit at 100,000 which can be changed through the `arrayLimit` argument to `run` (see http://rethinkdb.com/api/javascript/run/ ). Since your seem to be hitting a limit much earlier, I suspect that there's something else going on (could be an issue with our JavaScript driver).

**Comment by alexeygolev** [comment]
@danielmewes 
The error is
```
 name: 'ReqlDriverCompileError',
  msg: 'Cannot wrap undefined with r.expr().',
  frames: undefined,
  message: 'Cannot wrap undefined with r.expr().' 
```

**Comment by danielmewes** [comment]
That indeed doesn't sound like a length issue. Can you double-check that the input array doesn't contain any `undefined` fields or unsupported data types?

**Comment by alexeygolev** [comment]
@danielmewes I'm not entirely sure I know what data types could be considered unsupported in this scenario. Any ideas of what to look for besides undefined? Thanks

**Comment by alexeygolev** [comment]
@dalanmiller Found it. One of the deeply nested elements was `null`. My bad.

**Comment by danielmewes** [comment]
Glad it's now working! :)
