### ISSUE TITLE
console.log in data explorer

### ISSUE THREAD

**Issue by ivan-kleshnin** [rethinkdb/rethinkdb#5804]
```js
r.db("test").table("foo").filter((d) => {
  console.log(d) // !!!
  return true
})
```

`console.log` in data explorer leads to syntax error.

> SyntaxError: Unexpected token return

 Instead, it would be great to be able to log something (into additional output panel perphaps) 
to inspect data structures and query appropriately. 

Or is it technically impossible (because of caches etc.)?

**Comment by danielmewes** [comment]
You just need to add semicolon:
```js
r.db("test").table("foo").filter((d) => {
  console.log(d);
  return true;
})
```

However this code is not going to do what you want it to do, since the JavaScript function is executed only once in the Data Explorer with `d` being a placeholder object, and is then sent over to the server as a ReQL function where it actually gets executed on each document (http://rethinkdb.com/blog/lambda-functions/ has all the details if you're interested). There is currently no equivalent to `console.log` in ReQL. We will probably add it at some point in the future though, see https://github.com/rethinkdb/rethinkdb/issues/329 .
