### ISSUE TITLE
Single-node insert performance

### ISSUE THREAD

**Issue by jwr** [rethinkdb/rethinkdb#5805]
This isn't really a bug report, I'd like to check whether what I'm seeing is to be expected.

Running RethinkDB on Mac OS X, performance drops with time when inserting larger numbers of records — from about 8-10k inserts/s at the beginning down to 1-2k inserts/s after 23M records have been inserted (it's for a table with no indexes, and the data is very homogeneous, records of around 1kB in size). Overall DB size approaches 35GB, and this is the largest table. The machine is a MacBook Pro with an SSD.

There are no indexes on the table, the table has soft durability, and I expected a consistent write speed, pretty much regardless of table size. I am surprised by the 8x decrease I'm seeing.

Nothing is CPU-bound, system stats show RethinkDB writing quite a bit (to be expected), and *reading* a lot (which I found puzzling). In fact, the process is reading much, much more than it is writing.

If this is to be expected, I think it might be worth considering mentioning it in the documentation, perhaps suggesting configuration changes.

**Comment by danielmewes** [comment]
Hi @jwr, there are two things that can cause disk reads in a write workload:

* Garbage collection; RethinkDB implements an incremental garbage collector for the on-disk data that operates in the background. While it gets scheduled more agressively if it can't keep up with the writes and can start impacting write throughput at that point, I think it would be unusual for it to suddenly kick in at 23M records. It usually becomes active really early on.

* Once the data size becomes too large to fit into RethinkDB's cache, RethinkDB will have to read index blocks from disk in order to perform a write. The performance difference between in-memory data sets and out-of-memory data sets can be dramatic. My suspicion is that this is what's happening in your case.

The dashboard of the web UI has a "cache used" indicator under the "Resources" headline. What percentage are you seeing there? (note that if you've restarted RethinkDB in the meantime, you might have to perform some read and/or write operations to fill it back up). Once it hits 100%, RethinkDB will need to evict data from cache and then reload it from disk when it's needed.

By default, RethinkDB automatically uses roughly half the available RAM for its cache. You can increase this limit by passing the `--cache-size <size in MB>` command line option to `rethinkdb`.

**Comment by jwr** [comment]
Thank you. I verified again and indeed the huge performance drop happens when the cache fills up — at 99% I'm getting 1k instead of 10k inserts/s. I'm very glad we know why this happens!

But, I didn't expect this and this has important implications — so I now went back and re-read the manual section titled "Understanding RethinkDB memory requirements" — and I still don't quite understand what cache size I should reserve. I tried multiplying 26 bytes per block times the number of records (24M), which gives ~600MB. I have 16GB of RAM, so the cache size is likely just under 8GB and I should not be seeing these problems.

How can I calculate the required cache size?

**Comment by danielmewes** [comment]
@jwr The 26 bytes are used in addition to the cache, and can't be configured. The cache comes on top of all other memory requirements, and is used to reduce disk access. This is common in all database management systems. Some rely on the operating system's page cache instead of implementing their own, but it's basically the same thing.

You get the best performance as long as the complete data fits into cache. The amount of cache RethinkDB needs to accommodate the whole database is typically somewhere between the raw JSON size of the stored data and the on-disk size.

If RethinkDB is the only major thing running on the computer, you can try to maximize it while making sure that you don't exceed your machine's total RAM when including any other components that use the system's memory. For example if you expect everything else on your system to use at most 4 GB, you could set the cache size to 10 GB.

I'm not sure yet where in our documentation the best place for explaining this would be. I'll think about it. The Architecture FAQ ( http://rethinkdb.com/docs/architecture/ ) might be the obvious location for explaining RethinkDB's cache architecture.

**Comment by jwr** [comment]
Thanks for the answer. As for other DBMSs, I would normally expect reasonably flat append-only performance when inserting tons of data into a table with no indexes. But then, RethinkDB tables always have a primary index, so perhaps I should not have expected that.

As for cache size, I do understand that it's great to keep all data in RAM :-) But is that really the recommended cache size? Again, perhaps my expectations are completely off, but I would have expected to be able to hold indexes and structures in the cache, with most data sitting on disk, which would mean good append-only performance even when not everything fits into the cache.

Anyway, thanks, and additional hints in the documentation would be very much appreciated.

**Comment by danielmewes** [comment]
May I ask how you're doing the inserts? Specifically:
* Are you using soft or hard durability (hard durability is the default)?
* Are you calling `insert` with a single document, or are you passing it an array of documents?
* Are you running more than one `insert` at a time, or do you wait for the previous one to complete before issuing the next one?

I think we know why the drop-off happens at this point, but 1K inserts/s sounds relatively low considering the fast SSD.

Depending on how you run the inserts (e.g. whether you insert one document at a time vs. multiple, and whether you do it in series or in parallel), the added latency of a disk read - even if it's from a fast SSD - can make a tremendous difference. Even if overall throughput for a higher number of concurrent clients would still be pretty good.

**Comment by jwr** [comment]
I explicitly created the table with soft durability, `insert` gets batches of 1024 documents and I do wait for it to complete before issuing the next one.
