### ISSUE TITLE
Backup / Restore Snapshots of Cluster Data using Backfill Method

### ISSUE THREAD

**Issue by ember-graab** [rethinkdb/rethinkdb#5840]
I've been trying to setup a Backup/Restore scheme to take a snapshot of the data in a cluster and then later be able to restore that snapshot as the authoritative/primary data for recovery purposes. I've been running into some issues while trying a number of different variations of the scheme - errors about hosting server(s) being unreachable; tables being available for outdated reads, but not up-to-date reads or writes (which makes sense but I'd like to override); etc. I've tried some emergency repairs using table reconfigures, but haven't gotten the cluster back into a healthy state.

I'm using a Backfill technique where I attach a new instance to the cluster as a nonvoting replica, wait for it to collect all the latest data, terminate it, then take a snapshot of the hard drive. For the Restore step, I then restore this snapshot into a new volume and attach it to a new instance which gets added to the cluster as the primary replica. The restore step is where things go wonky.

I've tried a few different setups with this - terminating the backup server without reconfiguring it out of the cluster as nonvoting first (causes the RDB dash to flag errors about the missing backup server), reconfiguring it out before terminating it (fixes those errors but might not work the same way to do iterative backfilling backups), restoring into a brand new cluster with no existing data, restoring into the original existing cluster where the snapshot was sourced, etc. Ultimately I think we'll want to be able to do either a new cluster or the original existing one for recovery.

Any ideas how to force the cluster to recognize old data as authoritative? Or how to force the cluster to forget known to be non-existent replicas from when the snapshot was created?

For reference I'm using AWS EC2 volumes and their Snapshot flow.

**Comment by danielmewes** [comment]
Backups through backfilling are not something we officially recommend at the moment, because there are a lot of tricky aspects to it, and things can go wrong easily, leaving you with an incomplete backup or even a permanently damaged production cluster, as you have also discovered.

The really important thing that must be avoided at all cost is "duplicating" a server within a cluster. That means that once you take a snapshot of the data directory, you must either
1) never start the server that you took the snapshot from up again
2) or, start the server back up but never restore using that snapshot within the same cluster.

If you leave the existing server running as a cluster member for a while and later start a server with the data directory from the snapshot, that will look to the cluster as if the same replica had reappeared with its data having gone "gone back in time". There are many parts in RethinkDB's protocol where servers have to provide guarantees that they have written data to persistent storage and that this change to the data will never be undone. Using a snapshot within the same cluster violates that guarantee and things can go pretty wrong (from crashes to data loss).

Restoring should work if you start a completely new cluster (but make sure it never connects to a server from the old cluster, or you might be in trouble) with the server with the snapshot being the only one that has data for a given table. Then you should be able to use emergency_repair to promote it back to a full replica.
As long as there's another replica in the cluster with more up-to-date data, even emergency_repair will never discard the newer data in favor of a more out-of-date replica.

Another variation that you could try, but which is still risky, is starting a server up from the snapshot with no `--bind` option and without any `--join` / `-j` options, so that it doesn't join the cluster and cannot be contacted by the other servers in the cluster. Then you can connect to that server, use emergency_repair to promote it to a working replica, and use `rethinkdb dump` to extract a backup from it. You can then restore that backup into any cluster you like.

**Comment by danielmewes** [comment]
Hmm actually does `emergency_repair: unsafe_rollback` not work when you start the non-voting replica in an isolated (empty) cluster? If that is the case, I think that's a bug or oversight on our end, and we need to look into that.

**Comment by ember-graab** [comment]
Hey Daniel, apologies in the delay in getting back to you on this issue. I wound up finally getting a restored cluster from a backup. It required a specific series of steps. I had to ensure that the backfill volume/server doesn't get removed from the cluster prior to terminating the instance for one to make sure that when the volume is restored it sees the data as simply out of date (as opposed to being completely unworkable due to primary replicas being missing). That was the biggest error I was making. On restore, I do the emergency repair to get the data from outdated read-only to current read/write. I then reconfigure the tables to make the backup the primary and dictate replicas out of the backup and the intended future primary replica (currently secondary until restore is complete). I then wait for all replicas to ready. Then reconfigure the backup out of the cluster and then everything's golden.

I'm going to do some more tests with backfilling in the near future to ensure that I'm able to repeatedly reattach the backfill backup volume/server to get the latest changes and perform a snapshot at regular intervals.

From what you were saying, it sounds like for the restore step, we won't be able to work with an existing/active cluster to essentially rollback in a sense. So we'll just need to restore from scratch. We don't intend to ever need to restore, never have in history, and hopefully if we ever do need to it's rare. So the re-up time for a restore could bite us with server downtime with large data sets, but it shouldn't be frequent.

Thanks for the help!
