### ISSUE TITLE
v2.3.4 executable for Windows

### ISSUE THREAD

**Issue by ColdCold** [rethinkdb/rethinkdb#5851]
Presently, rethinkdb-2.3.4.zip contains the v2.3.3 executable.

https://download.rethinkdb.com/windows/rethinkdb-2.3.4.zip

**Comment by danielmewes** [comment]
Thanks for reporting this @ColdCold .

The `rethinkdb.exe` in the 2.3.4 zip file is actually the v2.3.4 version, but due to an issue with the particular build it incorrectly prints "Running rethinkdb 2.3.3-windows" on startup (and it subsequently notifies about a newer version of RethinkDB being available). If you check the web UI and click on the gear icon, it will correctly show the 2.3.4-windows version.

Replacing the download in-place on our server is probably a bad idea because some people might rely on checksums to verify a correct download. We'll address this with the next RethinkDB point release.

**Comment by danielmewes** [comment]
Closing this since there's nothing to do for this. The next release will have correct version numbers.
