### ISSUE TITLE
Issue with dump - server load

### ISSUE THREAD

**Issue by goors** [rethinkdb/rethinkdb#5856]
When i do dump on my database with about 2 milion docs, my application (nodejs) can not access db anymore and memory goes into 16GB out of 16GB. I am using 2.3.4 version. Someone with same problem?

What is faster doing dump of database or table by table in database?

**Comment by danielmewes** [comment]
Hi @goors, is the server configured with swap? If it goes out of memory and then goes into swap, that could explain why the application can no longer access the DB, since it would become extremely slow.

The important question then of course still is why it's exhausting memory during the `rethinkdb dump`. Have you checked `htop` or a similar tool? Is the `rethinkdb` server itself using most of the 16 GB, or is it the `rethinkdb-dump` / `python` process of the dump utility (`rethinkdb dump` is implemented using Python underneath)?

It can sometimes help to run `rethinkdb dump` with the `--clients 1` option, which limits it to dumping one table at a time. By default, `rethinkdb dump` will backup up to three tables simultaneously to increase throughput.

**Comment by goors** [comment]
Hi,

I will try with --clients 1 for one table at the time. As far as I can see dump is using all of the memory (that script for dump).

I will close issue for now and give back report when I try with clients.

**Comment by danielmewes** [comment]
I'm going to reopen this. If the `rethinkdb dump` script uses a lot of memory, that might be an indication of a bug in the script so we should investigate this on our end as well.

@goors Do any of your tables have particularly large documents or is there anything else "special" about your data?

**Comment by danielmewes** [comment]
@goors another question: Which version of the RethinkDB Python driver do you have installed (`pip show rethinkdb` or on older pip versions `pip freeze | grep rethinkdb`)?
Also what is the output of `python --version` on the server where you run the backup?

**Comment by larkost** [comment]
@goors: If you can also send me (karl @ rethinkdb.com) a sample document that might help me reproduce the case. Please strip/randomize anything that you think might be sensitive, as I don't need something that makes sense, only something to give me an idea of size/complexity of the documents.

**Comment by larkost** [comment]
And to put the conversation I had with @danielmewes into the record: my initial guess is that the memory spike is because we use a producer/consumer model, and on these systems the producer is reading much faster then the consumer can push out the door so the excess winds up building up in memory. 

Assuming that proves to be the main problem then it would be easy to switch away from `multiprocessing.SimpleQueue` to `multiprocessing.Queue` which has the option to limit the number of items in-flight. That switch would require some testing, as I am uncertain why `SimpleQueue` was chosen in the first place. There could be demons waiting in the corners.

**Comment by goors** [comment]
```
pip freeze | grep rethinkdb
rethinkdb==2.3.0.post2 
python --version
Python 2.7.6
```

With --clients 1 it uses around 10 GB of 16GB and app is ok now.
Last night database crashed but there is nothing in log, like nothing happened.

If this is problem with dump what do you think of next scenario.

1. Have proxy on each app server
2. Have like 3 servers in cluster
3. Do just backup on "third server" for example

I do not understand why dumping simple json to some file takes 11GB RAM.

**Comment by danielmewes** [comment]
> Last night database crashed but there is nothing in log, like nothing happened.

If the system runs out of RAM, the database server might get killed by the operating system. In that case there won't be anything in the RethinkDB log, because the rethinkdb process doesn't get a chance to write anything. You might find some messages in the syslog or in `dmesg` about the out-of-memory killer terminating rethinkdb.

> I do not understand why dumping simple json to some file takes 11GB RAM.

It definitely shouldn't, we're investigating this now and will try to release a fix soon.

**Comment by larkost** [comment]
@goors: I don't see anything in the structure of your document that would obviously be the cause. But I already have developed a theory that I want to test. Would you be willing to try a slightly hacked version of our driver to see if my theory is correct? In the hope that you agree I just emailed you a driver modified to avoid this potential issue.

For anyone who wants to follow along at home, this is from branch `larkost/5856-dump-queue-trial`.

**Comment by larkost** [comment]
I presume from the closure that we found the solution in our email conversation, so I want to sum that up here. Both @danielmewes and I had assumed that the issue was that the `dump` script was the one taking up the memory, but it turned out that it was the `rethinkdb` process that was sucking up the memory. Likely this was because the `cache-size` option was set to larger than the available memory, making this an expected behavior.

We do print a warning into the log files at startup, but that could be easy to miss if you don't know to look for it. There might be a better way for us to try and mitigate this, but we need to balance the user's ability to set things against protecting people from theirselves, and I don't immediately see a better strategy then we have now.
