### ISSUE TITLE
Unpacking optional arguments throws error

### ISSUE THREAD

**Issue by Calavoow** [rethinkdb/rethinkdb#5884]
I'm trying to create multiple tables in a database called `test` at once in one query, and I tried to construct a query using `forEach` on the web interface as follows:
```js
r.expr([
  {name:'test1', opt:{}},
  {name: 'test2', opt:{}}
]).forEach(r.db('test')
  .tableCreate(r.row('name'), r.row('opt'))
)
```
Where `opt` would later contain my options such as custom primary keys. This query however throws:
```
e: Expected 1 argument (not including options) but found 2.
```

The variant without opt keys does work:
```js

r.expr([
  {name:'test1', opt:{}},
  {name: 'test2', opt:{}}
]).forEach(r.db('test')
  .tableCreate(r.row('name'))
)
```
so does
```js

r.expr([
  {name:'test1', primarykey: 'id'},
  {name: 'test2', primarykey: 'id'}
]).forEach(r.db('test')
  .tableCreate(r.row('name'), {primaryKey: r.row('primarykey')})
)
```

So I figured it may be cause by packing the objects to rethink objects, i.e. `{}` -> `r.expr({})`. But I run into the same issue as my first example query:
```js

r.expr([
  {name:'test1', opt:r.expr({})},
  {name: 'test2', opt:r.expr({})}
]).forEach(r.db('test')
  .tableCreate(r.row('name'), r.row('opt'))
)
```

Thus it seems rethink somehow wrongly parses optional arguments if they are not explicit in the query (i.e. `tableCreate(r.row('name'), {primaryKey: r.row('primarykey')})`).
What could be the issue here?

**Comment by danielmewes** [comment]
Hi @Calavoow , the first version doesn't work because the object syntax that you are relying on for specifying the options only exists on the JavaScript client.
Internally (server-side), each optional argument is its own independent argument, and there is no single object to specify all the options. The JavaScript client is what "unpacks" the option object, and hence this doesn't work for server-side functions.

Your second attempt of specifying the primaryKey as a separate option works in principle, but I think our driver isn't smart enough to handle `r.row` inside an optional argument.

This should work:
```js
r.expr([
  {name:'test1', primarykey: 'id'},
  {name: 'test2', primarykey: 'id'}
]).forEach(function(x) {
  return r.db('test').tableCreate(x('name'), {primaryKey: x('primarykey')});
})
```

**Comment by Calavoow** [comment]
Thank you for your reply. And don't fear, specifying the optional argument with `r.row` does work.

I find it strange that the function can discern between arguments given explicitly and in an object. Given a function `f` it should not be able to know the difference between `f({})` and `x= {}; f(x)`.

**Comment by encryptio** [comment]
It's not that it can discern between the variable and literal cases, it's that optargs aren't encoded as regular arguments in the driver's wire protocol, so the drivers have to split them out to send them over that protocol. Since the JS driver doesn't see a non-ReQL-term object as its last argument, it assumes you meant an extra positional argument when doing the argument splitting.

If you want to dive into the code, have a look at [the definition of `r.tableCreate`](https://github.com/rethinkdb/rethinkdb/blob/d22ca667b08feb9b04add76d45e7cd1c83fdc819/drivers/javascript/ast.coffee#L1273) which uses [a helper function called `aropt`](https://github.com/rethinkdb/rethinkdb/blob/d22ca667b08feb9b04add76d45e7cd1c83fdc819/drivers/javascript/util.coffee#L28) that implements the argument splitting logic. After that, [`RDBOp.build`](https://github.com/rethinkdb/rethinkdb/blob/d22ca66/drivers/javascript/ast.coffee#L446)  puts each piece in the right place on the wire.

**Comment by Calavoow** [comment]
@encryptio I took a look at `aropt` but wouldn't passing an object dictonary in a variable still work here? It is the case that
```
Object::toString.call(perhapsOptDict) isnt '[object Object]'
```
would return false (questionable way to test this btw). Thus the `numPosArguments = 2` which is what the anonymous function for `tableCreate` expects.

**Comment by marshall007** [comment]
@Calavoow yes, passing an object does work. Passing `r.row` doesn't because `Object::toString.call(r.row('foo')) === [object Function]`.
