### ISSUE TITLE
Question about memory (RAM) requirements

### ISSUE THREAD

**Issue by ttmc** [rethinkdb/rethinkdb#5902]
I'm confused by the documentation about RethinkDB's memory (RAM) requirements, especially for clusters.

From the page on [Limitations in RethinkDB](https://rethinkdb.com/limitations/):

> RethinkDB requires data structures in RAM on each server proportional to the size of the data on that server’s disk, usually around 1% of the size of the total data set.

Is "the total data set" referring to the data _on that server_ or in the entire cluster?

<hr>

From the page about [RethinkDB Architecture](https://www.rethinkdb.com/docs/architecture/):

> RethinkDB can operate on a terabyte of data with about ten gigabytes of free RAM.

Assuming that "a terabyte of data" is referring to the entire data set (i.e. the sum of the data in all primary replica shards), is the "ten gigabytes of free RAM" the RAM on _each server_ or the total RAM across all servers?

<hr>

There's also a documentation page titled [Understanding RethinkDB memory requirements](https://rethinkdb.com/docs/memory-usage/), and it breaks apart the RAM requirements. I'm most concerned about the RAM requirements that grow with the data set, i.e. the RAM required for the metadata and indexes.

That's discussed in the last subsection ("Internal metadata"), but again it's not clear if the required memory is per server, or across the entire cluster.

**Comment by danielmewes** [comment]
@ttmc "the total data set" here is referring to only the data stored on the particular server.
Hence 10 GB of RAM spread across the cluster are enough to operate on a Terabyte of data, as long as the data is not replicated. If you replicate the data, the amount of data per server increases accordingly, because multiple copies of the same data will be held by different servers in the cluster.

For reasonable performance, you should probably aim at something closer to 5-10% of the data size. The 1% is the bare minimum and doesn't include any caching. If you want to run near the minimum, you'll also need to manually lower RethinkDB's cache size through the `--cache-size` parameter to free up enough RAM for the metadata overhead (or by adding `cache-size=<size in MB>` to the configuration file in /etc/rethinkdb/instances.d if you're starting RethinkDB through the init script).

**Comment by ttmc** [comment]
@danielmewes Thanks! I have a follow-up question: If I increase the data replication factor from 1 to 2 (i.e. the primary plus one copy), will that double the RAM needed for metadata?

**Comment by danielmewes** [comment]
@ttmc 
1. Yes
2. Yes. Going into swap is usually pretty bad for RethinkDB, and RethinkDB servers that have gone into swap often become so slow that other nodes in the cluster consider them unavailable and terminate the connection to them. I recommend adjusting RethinkDB's cache size conservatively to avoid this scenario. RethinkDB will still make use of additional RAM through the operating system's block cache (though less efficiently than when it can keep data in its own cache).
