### ISSUE TITLE
What does read_mode=single mean for changefeed consistency?

### ISSUE THREAD

**Issue by ttmc** [rethinkdb/rethinkdb#5968]
The [page about RethinkDB consistency guarantees](https://www.rethinkdb.com/docs/consistency/) says:

"Note that changefeeds will ignore the `read_mode` flag, and will always behave as if it is set to `single`."

"`single` returns values that are in memory (but not necessarily written to disk) on the primary replica."

"`majority` will only return values that are safely committed on disk on a majority of replicas. This requires sending a message to every replica on each read, so it is the slowest but most consistent."

Can someone explain what this means for changefeed consistency? What are the worst-case inconsistencies that might arise because of changefeeds using read_mode=single?

**Comment by larkost** [comment]
Changefeeds always get their data from the primary for each shard, so if any primary involved in a changefeed goes down that changefeed is always broken, and will need to be restarted. There has been some work on fixing this problem in #3471, but it is a rather thorny one that will involve some carefully planned changes to our underlying data structures.

Separately the main problem of the implicit `single` read mode is that because the data is not guaranteed to have hit the disk on the Primary (let alone on a majority of the replicas) there is a chance that if that server dies (e.g.: someone pulls the power cord(s)) immediately after sending the data you could get a change in the changefeed that (once recovery happens) will not be reflected in the database.

Since you also have a second question about identical changefeeds going to multiple machines, in the same scenario the two subscribers could differ in whether they saw a singe change or not, depending entirely on the timing.

And a general request: rather than asking questions here (as a bug) please ask them in one of the channels from our [community page](http://rethinkdb.com/community/). The Slack channel is especially active, but we generally monitor all of them.

Since this is not really a bug, I am closing it as such, but if you need more clarification feel free to further ask in this issue.
