### ISSUE TITLE
Showing 2.3.3 with latest 2.3.4 zip - Windows OS

### ISSUE THREAD

**Issue by slevr** [rethinkdb/rethinkdb#5983]
Just trying things out with the Getting Started. Used the link provided to download latest ( rethinkdb-2.3.4.zip ) for windows OS but when running it states it's 2.3.3 with the 'newer version is available' message. Seems maybe the 2.3.3 binary made it into the 2.3.4 zip? Or perhaps it's just the version number wasn't updated prior to build/zip.

**Comment by danielmewes** [comment]
Thanks for reporting this @slevr .

This was just a glitch with how the version number was generated in this executable. If you want to make sure that you're running the 2.3.4 binary, you can check the version in the web UI when clicking on the gear symbol at the top of the UI. It should display `2.3.4-windows` there.

We decided to not replace the zip archive, since that would change its checksums. Instead this issue will be addressed by the next release (2.3.5). See https://github.com/rethinkdb/rethinkdb/issues/5851
