### ISSUE TITLE
Permit access to raw response object for Java client library

### ISSUE THREAD

**Issue by venantius** [rethinkdb/rethinkdb#5996]
I've been tinkering with working on a Clojure driver that would wrap the existing official Java driver (I'm already aware of https://github.com/apa512/clj-rethinkdb). I'm far enough along that I have a functioning prototype, but all queries currently respond with core Java types (e.g. an instance of `java.util.ArrayList`, etc.). 

In my mind, it would be great if the `com.rethinkdb.net.Connection` class offered me a way to handle the query response myself so that I could directly cast the response into the appropriate Clojure data structure (whether that ended up being an instance of `clojure.lang.PersistentVector` or something more like a `core.async` channel, as appropriate). 

I think the simplest way to go about this would probably just be to make `sendQuery` public, but if we wanted to we could also keep it private and open up a different public method interface to support this use case. 

Anyways, figured I'd open an issue up for discussion 😄

**Comment by bchavez** [comment]
In your solution would you still consider using the internal executor / response pump / `Future<T>` threading mechanism?  If not, then I think there could be more motivation to consider https://github.com/rethinkdb/rethinkdb/issues/5380 and move the Future/awaiter mechanics down to `SocketWrapper`.

This way, maybe, if we pushed the awatier/threading mechanics down to `SocketWrapper` (#5380) then allowed you to replace/implement `SocketWrapper` with your own `ClojureSocketWrapper` it could work.

The only trouble ahead I see would be the need for `ClojureSocketWrapper` to be respectful of the `Response.*` members `Connection` expects to see in `Response` when making decisions about deserialized responses, ie: if the response is a sequence, make and keep track of a `Cursor` 'n stuff...

Alternatively, allow you to replace the entire `Connection` :sunglasses: .

:rocket: 

:cloud: :sunny: [**Bassnectar - Chasing Heaven - Into the Sun**](https://www.youtube.com/watch?v=a2BAia075lE)

**Comment by venantius** [comment]
I was assuming that I'd keep using the current mechanism, yes. If we wanted to get crazy and focus on implementing Clojure-specific future interfaces (e.g. `IDeref`, etc.) then we could move that logic down to the `SocketWrapper`, but I don't see that as a necessity personally. 

Perhaps OT, but I expect `SocketWrapper` to be pretty limited in scope and would probably feel twitchy about having too much going on down there. Of course, I can also see the argument for cleaning up `Connection`, so...

Ultimately, this is a question about where `Response` deserialization goes. The most Clojuresque interface I could imagine the Java driver providing would be one in which you allowed me to pass `Connection.run` a Clojure function [callback] that would be take a single argument, `res` (a `Response`), and could handle it however it wanted. My proposal for making `sendQuery` public is basically only so that I can implement that functionality anyways.

I did in fact try to implement my own `CljConnection` first, but unfortunately there are a number of other classes that take and return `Connection` objects explicitly - if we modified those to take `IConnection` then that would work too. 

I'm mildly resistant to the idea of creating new Clojure-specific classes; I think it'd be cleaner to just open up the existing Java classes to be friendlier to access and extension by other JVM languages.

**Comment by bchavez** [comment]
Hey there. Apologies up front, my working set memory is very small and have little to zero experience with Java and Clojure. Pls excuse my misgivings. I'm still trying to understand what changes in the Java driver you need to accomplish your goal in a reasonable way.

Here's what I'm trying to reconcile in my mind:
> it would be great if the `com.rethinkdb.net.Connection` class offered me a way to handle the query response myself

***1. So I think you want a way to process responses*** :heavy_check_mark: 

and 

> I think the simplest way to go about this would probably just be to make `sendQuery` public

***2. So I think you want a way to send queries*** :heavy_check_mark:

But only handling one (`sendQuery`) doesn't get you the other (`processing responses off the wire`) with the current architecture. **1. Handling responses** and **2. sending queries** are two distinct operations, ***and*** both currently happen on different threads (and you mention things like `core.async` so I don't know exactly where that fits in). Both sending and receiving query/response are complementary enough to "live together" and go hand-in-hand with each other given the current threading architecture (hence the effort for #5380).

The problem with the way the current Java implementation (motivation for #5380), is that both of these (send/receive) **1. and 2.** implementations currently co-exist in `Connection`, that is, in the same strata along with `Response` / `Cursor` logic. The `Cursor` logic is still important enough to live on its own strata separate from the underlying threading architecture IMHO (ie motivation for #5380).

-------

So, given the current state of Java things. Maybe, your best bet, is to implement an abstraction like `IConnection`, but unfortunately, this means you'll need to re-implement **1) some kind of threading architecture thing for sending / receiving stuff** and **2) have some reasonable `Cursor` management stuff**. Handling `IConnection` will most definitely get you both **1 and 2** but also adds some additional responsibility like handling `Cursor` management. I hope that kinda makes sense in a weird way??

So, #5380 (sorry repeating myself) would push the threading stuff down lower to `SocketWrapper` so that you could still use `Connection`'s `Cursor` management stuff up above, but gives you **1 and 2** with your own response mechanism assuming `Future<T>` works for you.
 
----

Or, maybe just simply overriding `SocketWrapper:write()` and `Response SocketWrapper:read()` would work? That gets you both **1 and 2** very simply. I don't know. ¯ \ _ (ツ) _ /¯  :crying_cat_face: 

---

Could you provide a more detailed example of what it means to "handle it however it wanted"?

> The most Clojuresque interface I could imagine the Java driver providing would be one in which you allowed me to pass Connection.run a Clojure function [callback] that would be take a single argument, res (a Response), and could handle it however it wanted.

The immediate problem I see with "handling it however it wanted" is the Java callstack. For example, `query.run(conn)` would look something like this, IIRC: 

```
-> conn.sendQuery(query) & wait for Response type
-> conn.runQuery(query)
-> conn.run(query)
-> ReqlAst.run(Connection conn)
```
How does your Clojure callback plan on backing out / unwinding the callstack cleanly after your "Clojure [callback] handles it"? What do we do with the response check [here](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L255)? It ***kinda*** effects cursor management. Or are you looking to completely bypass [these](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L255) response checks in `conn.runQuery` and have `runQuery` blindly return whatever your callback returns?

-----

Thinking out loud, if your Clojure callback is something like:
```
var callback = (Response res) =>{
       //handle it however it wants?
     });
```
By the time your callback is executed, the wire-JSON is already deserialized into a Java `Response` type. But the `Response.Data` is still a `JSONArray` and is ***that okay*** for your Clojure callback?

-----

Or, are you looking at just deserialization at this level? Hooking occurrences of Lines [258 and 259](
https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L258) so you can return a **POCO** instead of a **POJO**?:question:  

-----

Sorry for all the scatter mindedness, this is sort of the things I'm having difficulty with understanding your situation in my mind just cuz there's a lot of stuff going on. =(

BTW FWIW, the C# driver has both [`IConnection` here](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/IConnection.cs) and #5380 .

Thanks,
Brian

:crescent_moon: :stars: [***"Nothing good happens past 2am..."***](https://www.youtube.com/watch?v=VOlcDBXKhSU)

**Comment by venantius** [comment]
Whew, that's quite a response! Let me do my best to respond:

> 1. So I think you want a way to process responses ✔️
> 2. So I think you want a way to send queries ❓

I do not need a way to send queries necessarily; I was just noticing that the return value of `sendQuery` seems to be the first place in which I'm able to obtain the `Response` object before it's been re-serialized into basic Java data structures. My thinking was that if I wanted to avoid multiple serialization trips, that'd be the place to put my efforts. I could very well have just misunderstood the code, however. 

> 1. Handling responses and 2. sending queries are two distinct operations, and both currently happen on different threads (and you mention things like core.async so I don't know exactly where that fits in). 

`core.async` would most likely come into play if the query returned a cursor; rather than leave it as a cursor and have to wrangle the Java interop we'd probably wrap it in a `core.async` channel in the driver and let people pull values from the `core.async` channel as values became available to the underlying cursor. 

> The problem with the way the current Java implementation (motivation for #5380), is that both of these (send/receive) 1. and 2. implementations currently co-exist in Connection, that is, in the same strata along with Response / Cursor logic. The Cursor logic is still important enough to live on its own strata separate from the underlying threading architecture IMHO (ie motivation for #5380).

Right. 

> So, given the current state of Java things. Maybe, your best bet, is to implement an abstraction like IConnection, but unfortunately, this means you'll need to re-implement 1) some kind of threading architecture thing for sending / receiving stuff and 2) have some reasonable Cursor management stuff. Handling IConnection will most definitely get you both 1 and 2 but also adds some additional responsibility like handling Cursor management. I hope that kinda makes sense in a weird way??

In an ideal world we wouldn't have to re-implement the threading architecture and could leverage the existing Java driver (or generalize the Java driver's logic in such a way that consuming it from Clojure doesn't require jumping through any special hoops). I would, however, expect that we'd need to do some cursor management, per my section on `core.async` above. 

> So, #5380 (sorry repeating myself) would push the threading stuff down lower to SocketWrapper so that you could still use Connection's Cursor management stuff up above, but gives you 1 and 2 with your own response mechanism assuming Future<T> works for you.

I *think* `Future<T>` should work fine. Though, again, I suspect that a proper Clojure driver would probably want to do a fair amount of its own Cursor management. 

> Or, maybe just simply overriding SocketWrapper:write() and Response SocketWrapper:read() would work? That gets you both 1 and 2 very simply. I don't know. ¯ \ _ (ツ) _ /¯ 😿

Being able to override `SocketWrapper.read()` could work, but I couldn't see a way with the current driver architecture to do that. I'm not sure how I'd integrate that into the rest of the `Connection.run` call stack; would I just be allowed to pass in my own `SocketWrapper` instance as part of the `run` invocation? 

> The immediate problem I see with "handling it however it wanted" is the Java callstack. For example, query.run(conn) would look something like this, IIRC:
> 
> -> conn.sendQuery(query) 
> -> conn.runQuery(query) & wait for Response type
> -> conn.run(query)
> -> ReqlAst.run(Connection conn)
> 
> How does your Clojure callback plan on backing out / unwinding the callstack cleanly after your "Clojure [callback] handles it"? What do we do with the response check here? if (res.isAtom()) It kinda effects cursor management. Or are you looking to completely bypass these if (res.isAtom()) response checks in conn.runQuery and have runQuery blindly return whatever your callback returns?

Yes. We'd create an interface for all of the functions in the call stack that just return `Object`, and call `.Invoke` on the Clojure function that's passed in and return that. The callback itself would be responsible for handling, e.g., the case for when `res.isAtom()`. 

> By the time your callback is executed, the wire-JSON is already deserialized into a Java Response type. But the Response.Data is still a JSONArray and is that okay for your Clojure callback?

Ideally we're avoiding the multiple deserializations, as noted above. Now, it's worth noting of course that I could just be making a bunch of fuss about nothing and this could be a totally unimportant optimization. I haven't measured anything, after all. 

> Or, are you looking at just deserialization at this level? Hooking semantic occurrences of Lines 277 and 278 so you can return a POCO instead of a POJO?❓
> 
> Object value = ((List) Converter.convertPseudotypes(res.data, fmt)).get(0);
> return Util.convertToPojo(value, pojoClass);

Yes. This is, in my mind, the ideal solution. However, this solution only really works fluidly when we're talking about straightforward responses (i.e. non-Cursor objects). I don't know what happens in this logical branch when the response is a Cursor. 

> Sorry for all the scatter mindedness, this is sort of the things I'm having difficulty with understanding your situation in my mind just cuz there's a lot of stuff going on. =(

No worries! Thanks for the detailed response in the first place :)

**Comment by bchavez** [comment]
Okay, so after reading your response a few times, I'm starting to slowly see what things you'll need to implement your changes. But there are still some things that need to be worked out.

> I was just noticing that the return value of `sendQuery` seems to be the first place in which I'm able to obtain the Response object before it's been re-serialized into basic Java data structures.

The return value of `sendQuery` is `Future<Response>`. Here's the problem I see with placing your code in `sendQuery`. Since `sendQuery` returns a `Future<T>`; there's really no place for you inside `sendQuery` to "obtain" the actual response in `sendQuery` unless you want to do something with the totality of the `Future<Response>` object as an instance of `Future<T>`. To obtain the response in `sendQuery` you would have to forcefully `Future<Response>.get()` in order to obtain the actual response at some point, at a later time, in the future. By that time, you no longer are dealing with `Future<Response>` but the actual `Response` in `sendQuery`. Handling and *blocking* in `sendQuery` for the actual response, IMHO, is bad karma and breaks the current contract with everyone else who is expecting `Future<Response>`, not `Response`.

-----

> My thinking was that if I wanted to avoid multiple serialization trips, that'd be the place to put my efforts. I could very well have just misunderstood the code, however.

Serialization round trips? You mean DE-serialization round trips? Actually, though, this brings up another important question... When passing native Clojure types into the underlying Java AST `r.query.term(clojure_thing)` does `clojure_thing` derive from Java types like `Map`, `List`, `Integer`, `Number`?

If Clojure native types don't directly inherit from Java base types (or if Java doesn't understand what `clojure_thing` is really composed of) then you're going to need a way to convert `clojure_thing` and decompose it into AST datums when they are passed as arguments into the AST. Specifically, you're going to need a way to hook into `Util.java:toReqlAst(Object val)` where `val` would be your `clojure_thing` that you'd need to deconstruct into datums.

-----

>`core.async` would most likely come into play if the query returned a cursor; rather than leave it as a cursor and have to wrangle the Java interop we'd probably wrap it in a `core.async` channel in the driver and let people pull values from the `core.async` channel as values became available to the underlying cursor.

Coo... so, you want to wrap the cursor implementation. Just so we're on the same page with the inner workings of a cursor, when a response arrives over the wire, the `Response` is checked for `.isPartial || .isSequence`. If either is true, then the `Response` is used to build a `Cursor`. If the first `Response` is a complete response, all the data items from the `Response` are placed into a cursor's buffer. If the first `Response` is a partial response, the initial response data items are loaded into the `Cursor`'s buffer, while firing off a `CONTINUE` message to the server (for eventually more items). 

As a consumer iterates over the cursor, a buffered item is pulled off the internal `Cursor` buffer. When, and only when, the buffer is zero, an attempt is made to read from a pending `CONTINUE` response. Here the consuming thread will either 1) block on `Future<Response>` because the `CONTINUE` response hasn't arrived yet, or 2) immediately process the `Future<Response>` because of its arrival. When the `Response` is consumed, the internal buffer is refilled, and subsequently another `CONTINUE` is fired off to the server. And the process repeats.

So, `core.async` would have to be okay with this underlying functionality/operation when wrapping `Cursor<T>`.

-----

> Ideally we're avoiding the multiple deserializations, as noted above. Now, it's worth noting of course that I could just be making a bunch of fuss about nothing and this could be a totally unimportant optimization. I haven't measured anything, after all.

Well, the threading architecture is mostly responsible for picking up JSON strings off the wire and turning the JSON strings into real `Response` types for `Future<Response>` awaiters. This is Step 1 of the deserialization process.

Step 2 deserialization comes about after the decision has been made either to return an object or a cursor for a given `Response`. As alluded to in my previous response, `Converter.convertPseudotypes` takes `Response.Data` and internally fixes up `$reql_type$` pseudo types and transforms them into Java types. IE: `$reql_type$: BINARY -> byte[]`.  Finally, after the `$reql_type$` psuedo types are fixed up, Step 3.

Step 3 takes whatever is left from the `convertPseudotypes` process and turns it into a POJO like type of thing.

So yea... hm. You probably need to decide which place you want to hook into (or all of them).

------

> Yes. We'd create an interface for all of the functions in the call stack that just return Object, and call .Invoke on the Clojure function that's passed in and return that. The callback itself would be responsible for handling, e.g., the case for when `res.isAtom()`.

So if I'm understanding this correctly, you want to stub out this whole section of code here and replace it with some kind of Clojure callback?  

https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L274-L289

TBH, this is probably the most appropriate place to hook the response processing mechanism from `Response` to `something` conversion. By the time your Clojure callback occurs, we'd have a `Response` available for you, not a `Future<Response>` as with `sendQuery`.

----

So judging by what I'm understanding so far, I think it would take a mediumish effort to push the Java driver to a place where you could do this.

Alternatively, if the .NET Clojure CLR is an option for you... I'd be willing to refactor the C# driver's architecture a little more to accommodate your Clojure callbacks. As I mentioned earlier, the C# driver has [`IConnection`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/IConnection.cs#L13) and #5380 and the ability to hook [`Util.ToReqlAst`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Ast/Util.cs#L15)... so the C# driver is a bit further along the trail for these kinds of changes.

Hope that helps,
Brian

:tropical_drink: :wine_glass: [***"Some people drink Pepsi... Some people drink Coke..."***](https://www.youtube.com/watch?v=p99a6K81zqM)

**Comment by venantius** [comment]
> The return value of sendQuery is Future<Response>. Here's the problem I see with placing your code in sendQuery. Since sendQuery returns a Future<T>; there's really no place for you inside sendQuery to "obtain" the actual response in sendQuery unless you want to do something with the totality of the Future<Response> object as an instance of Future<T>. To obtain the response in sendQuery you would have to forcefully Future<Response>.get() in order to obtain the actual response which arrives at some point, at a later time, in the future. By that time, you no longer are dealing with Future<Response> but the actual Response in sendQuery. Handling and blocking in sendQuery for the actual response, IMHO, is bad karma and breaks the current contract with everyone else who is expecting Future<Response>, not Response.

The reason I'm asking for `sendQuery` to be public isn't so that I can override it, but so that I can access its return value. 

> Serialization round trips? You mean de-serialization round trips? Actually, though, this brings up another important question... When passing native Clojure types into the underlying Java AST r.query.term(clojure_thing) does clojure_thing derive from Java types like Map, List, Integer, Number?

Whoops, I did mean de-serialization, yes. 

Re: serialization - Clojure data structures do implement core interfaces (i.e. vector implements list, map implements map, etc.). At the moment I've got some logic that maps from term-type to initializer and then passes in a created Arguments and Optargs object (which are created when the application calls `run` in my code; these code paths could be memoized to reduce computational overhead). I'll try to get you a preview of what I've currently got so you can see what's going on there; it's not the prettiest logic but it works fine for right now. 

> Coo... so, you want to wrap the cursor implementation. Just so we're on the same page with the inner workings of a cursor, when an initial response to a query arrives over the wire, the Response is checked for .isPartial || .isSequence. If either is true, then the Response is used to build a Cursor. If the first Response is a complete response, all the data items from the Response are placed into a cursor's buffer. If the first Response is a partial response, the initial response data items are loaded into the Cursor's buffer, while firing off a CONTINUE message to the server (for eventually more items).
> 
> As a consumer iterates over the cursor, a buffered item is pulled off the internal Cursor buffer. When, and only when, the buffer is zero, an attempt is made to read from a pending CONTINUE response. Here the consuming thread will either 1) block on Future<Response> because the CONTINUE response hasn't arrived yet, or 2) immediately process the Future<Response> because of its arrival. When the Response is consumed, the internal buffer is refilled, and subsequently another CONTINUE is fired off to the server. And the process repeats.
> 
> So, core.async would have to be okay with this underlying functionality/operation when wrapping Cursor<T>.

I've actually started taking a different approach with this for now by using `iterator-seq` on the Cursor object since it implements Iterable; this means that the application can lazily pull from it in a way that'll map well to idiomatic Clojure data structures. The downside to this approach is that it doesn't provide the application with a way to call `.close()` on the Cursor in a preliminary fashion - I might end up writing a simple class that implements `ISeq` in Clojure while still supporting `.close` as necessary, but it seemed like overkill for now while I'm still working on the overall driver architecture. 

If the object isn't a cursor, I just convert it to native Clojure data types immediately and return those. 

> Well, the threading architecture is mostly responsible for picking up JSON strings off the wire and turning the JSON strings into real Response types for Future<Response> awaiters. This is Step 1 of the deserialization process.

> Step 2 deserialization comes about after the decision has been made either to return an object or a cursor for a given Response. As alluded to in my previous response, > Converter.convertPseudotypes takes Response.Data and internally fixes up $reql_type$ pseudo types and transforms them into Java types. IE: $reql_type$: BINARY -> byte[]. Finally, after the $reql_type$ psuedo types are fixed up, Step 3.

> Step 3 takes whatever is left from the convertPseudotypes process and turns it into a POJO like type of thing.

> So yea... hm. You probably need to decide which place you want to hook into (or all of them).

Right. For the moment I'm just working on taking what I get from step 3 and running with that since that doesn't require changes to the existing Java driver. But if I look forward to what the future Java driver could be in terms of providing better support for Clojure, I think we'd probably want to move a little earlier in the stack and provide flexibility for Clojure drivers to access the response at an earlier part of the process to avoid having to do un-necessary conversions (to-POJO/from-POJO). 

> So if I'm understanding this correctly, you want to stub out this whole section of code here and replace it with some kind of Clojure callback?
> 
> https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L274-L289

Yep, that's exactly what I had in mind. 

> Alternatively, if the .NET Clojure CLR is an option for you... I'd be willing to refactor the C# driver's architecture a little more to accommodate your Clojure callbacks. As I mentioned earlier, the C# driver has IConnection and #5380 and the ability to hook Util.ToReqlAst... so the C# driver is a bit further along the trail for these kinds of changes. At the very least, it could help with experimentation of what you'll ultimately need.

I'm afraid it's not - I know the Clojure CLR does get some use, but not by most Clojure folks.

**Comment by adriantodt** [comment]
This is now implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/12) of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.
