### ISSUE TITLE
coerceTo with enum (or at least String constant) argument in java driver

### ISSUE THREAD

**Issue by Suvitruf** [rethinkdb/rethinkdb#6002]
https://www.rethinkdb.com/api/java/coerce_to/

We should write:

```
sequence.coerceTo('array') → array
value.coerceTo('string') → string
string.coerceTo('number') → number
array.coerceTo('object') → object
sequence.coerceTo('object') → object
object.coerceTo('array') → array
binary.coerceTo('string') → string
string.coerceTo('binary') → binary
```

Mb pass argument to `coerceTo` as `enum`? Something like:

```
enum CoerceType{
  ARRAY,
  STRING,
  ...
}
```

And using `sequence.coerceTo(CoerceType.ARRAY)`. Or, at least, make them as String constants.

**Comment by danielmewes** [comment]
The current syntax is convenient and consistent, because it follows the same argument types that ReQL has elsewhere. In particular, the current syntax also allows you to use the result of another ReQL expression as the input to `coerceTo`.

I think adding named `String` constants might be a good middle-ground though.

I think this isn't very high priority, but we can look into it at some point.

**Comment by adriantodt** [comment]
This implemented to one of the branches of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.
