### ISSUE TITLE
swap issue

### ISSUE THREAD

**Issue by tsypa** [rethinkdb/rethinkdb#6003]
I had to disable the swap file
because the message about swap seated
despite the fact that
              total used free shared buff / cache available
Mem: 7.8G 3.1G 985M 108M 3.8G 4.6G
Swap: 0B 0B 0B

**Comment by danielmewes** [comment]
Depending on its configuration, Linux can place things into swap even before all RAM is exhausted. Its behavior can be controlled through the `swappiness` parameter.

This answer has a great explanation of how the parameter works and how to configure it: http://askubuntu.com/a/103916/209792

The swapping issue is not critical by itself, and you can ignore it. However parts of RethinkDB being in swap can lead to very bad performance behavior in some circumstances, and can cause disconnects (due to heartbeat timeouts) in clusters, which in turn lead to table unavailability.

**Comment by danielmewes** [comment]
@tsypa Note that the RethinkDB message about swap stays active for an hour since a part of the RethinkDB process was put onto swap. So it's possible that by the time you checked, it was already paged back into RAM.
