### ISSUE TITLE
Add native Reql hash function

### ISSUE THREAD

**Issue by internalfx** [rethinkdb/rethinkdb#6017]
I've written a library called [Thinker](https://github.com/internalfx/thinker) for quickly synchronizing two databases locally or over a network.

To decide what records to copy I use this query...

```javascript
    r.db(sourceDB).table(table).orderBy({index: r.asc('id')})
      .map(function (row) { return {id: row('id'), raw: row.toJSON()} })
      .map(r.js(`(function (data) {
        // JS hash function here
        return {id: data.id, hash: hash(data.raw)}
      })`))
      .run({cursor: true})
```

I have to imagine that it would be far more performant if I could do this...

```javascript
    r.db(sourceDB).table(table).orderBy({index: r.asc('id')})
      .map(function (row) { return {id: row('id'), raw: r.hash(row.toJSON())} })
      .run({cursor: true})
```

**Comment by deontologician** [comment]
Try this:

```js
r.db(sourceDB).table(table).orderBy({index: r.asc('id')})
      .map(function (row) { return {id: row('id'), raw: r.uuid(row.toJSON())} })
      .run({cursor: true})
```

**Comment by internalfx** [comment]
@deontologician I didn't know you could do that!

I'll try that, thanks!

**Comment by internalfx** [comment]
Performance was off the charts!...this is awesome!

I can synchronize the changes between two 20GB databases in 6 minutes! :astonished:

**Comment by robertjpayne** [comment]
@deontologician is `toJSON` guaranteed to generate a canonical JSON string? Are there any docs relating to this?

**Comment by danielmewes** [comment]
@robertjpayne It is deterministic, though the details of the generated JSON string could change in some future version (so I'd recommend using the hashing only for things for which you can regenerate the hashes without too much hassle if necessary).

You might also need to be careful if you have floating point numbers in your documents. The generated JSON should be stable on a given platform, but might not be identical across different platforms (e.g. Linux vs. OS X) due to potential differences in rounding.
