### ISSUE TITLE
Lexicographically sortable Unique IDs support

### ISSUE THREAD

**Issue by v3ss0n** [rethinkdb/rethinkdb#6021]
i think it will be very beneficial if Rethinkdb supports Universally Unique Lexicographically Sortable Identifier. It is very efficient and avaliable in JS + Python now :

https://github.com/alizain/ulid
https://github.com/mdipierro/ulid

Not sure it is ok for sharding. Any ideas?

**Comment by mdipierro** [comment]
Yes. It is perfect for sharding. You just convert the first or the second part back into a number and do mod the number partitions you have. It will tell you which partition to use.

**Comment by v3ss0n** [comment]
thanks a lot @mdipierro  that will be perfect fit here.

**Comment by danielmewes** [comment]
Is the key idea that the IDs will be sorted by time (approximately)?

Like with other time-based primary keys in RethinkDB, it will be problematic with our current sharding scheme, because new documents always end up in the last shard until you rebalance the table.
I think it will be more useful as a built-in feature after we add https://github.com/rethinkdb/rethinkdb/issues/4237 .

Related issues:
https://github.com/rethinkdb/rethinkdb/issues/117
https://github.com/rethinkdb/rethinkdb/issues/5231

**Comment by thelinuxlich** [comment]
@srh we should close this and anything related should be added to #117
