### ISSUE TITLE
Branch executes both the true and false

### ISSUE THREAD

**Issue by hyperh** [rethinkdb/rethinkdb#6039]
I'm a little confused about `r.branch`. Here's an example

```
const collNameExists = false;

  const groupFunc = row => {
    const receivedAt = row('receivedAt');
    const baseGroup = {
      year: receivedAt.year(),
      month: receivedAt.month(),
      day: receivedAt.day(),
      dayOfWeek: receivedAt.dayOfWeek(),
    };
    const group = collName ?
      baseGroup :
      Object.assign(baseGroup, { collectionName: row('data')('collectionName') });
    return group;
  };

r.table('mytable')
    .coerceTo('array')
    .do(
      result => r.branch(
        collNameExists,
        result.filter(doc => doc('data')('collectionName').eq(collName))
          .group(groupFunc)
          .count(),
        result.group(groupFunc)
          .count(),
      )
```

So in the branch statement, even though the condition is hard set to `false`, branch complains that 

```
W20160808-12:14:27.166(8)? (STDERR) #####################
W20160808-12:14:27.326(8)? (STDERR) [Error] ReqlDriverCompileError : Argument 1 to eq may not be `undefined`.
W20160808-12:14:27.326(8)? (STDERR) Argument 1 to eq may not be `undefined`.
W20160808-12:14:27.326(8)? (STDERR) #####################
```

If I change 
```
 result.filter(doc => doc('data')('collectionName').eq(collName))
```

to
```
result.filter(doc => doc('data')('collectionName').eq(collName ? collName : ''))
```

or even just change it to 
```
[]
```

It will give me the proper `false` results that I was expecting.

Shouldn't Rethink not even execute the `true` path, since I hard coded the condition to be `false`?

**Comment by thinklinux** [comment]
The rethinkdb driver is there to actually compile your code to a query that will be later executed on the database itself. You can think about ReQL as a language that will compile to something that the database will understand. The compiler have no idea how the branch will resolve later on so it have to compile everything and it hits your undefined variable. That's why you have `ReqlDriverCompileError`.

I think that's not an issue. It's just that when the driver is so integrated with the language we sometimes tend to forget that it's actually not the same thing that it runs on the database.

Hope that helps.

**Comment by hyperh** [comment]
@thinklinux Ahh ok, so in reality, it's not really running the `true` path, it just compiles it and finds out that one of the variables is undefined? Is my understanding correct?

**Comment by thinklinux** [comment]
@hyperh Yeap, that's right :) It's kind of checking things before it actually runs them on the database. Later when it actually execute the query it will check for `collNameExists` and it will go the correct path.

**Comment by hyperh** [comment]
@thinklinux Thanks for the explanation!
