### ISSUE TITLE
asyncio loop type unavailable when installing via setup.py

### ISSUE THREAD

**Issue by byronh** [rethinkdb/rethinkdb#6043]
Installing the `rethinkdb` Python driver as a required package of a project's `setup.py` seems to make the `asyncio` loop type unavailable.

setup.py:
```python
import setuptools

setuptools.setup(
    name='example',
    install_requires=['rethinkdb'],
    ....
)
```
```bash
python setup.py install
```
```
Python 3.5.2 (default, Aug  8 2016, 20:46:29) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rethinkdb as r
>>> r.set_loop_type('asyncio')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/rethinkdb-2.3.0-py3.5.egg/rethinkdb/net.py", line 673, in set_loop_type
ValueError: Unknown loop type: 'asyncio'
```

However, when installing via pip, everything is fine:
```bash
pip install rethinkdb
```
```
Python 3.5.2 (default, Aug  8 2016, 20:46:29) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rethinkdb as r
>>> r.set_loop_type('asyncio')
>>>
```

I tried a number of versions including `2.3.0` and `2.3.0post1` through `2.3.0post5` and have replicated it in different clean virtual environments as well as docker images based on `python:3.5.2`.

My suspicion is that this is because of the logic at https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/net.py#L676 which is looking for a file in a specific place in the file system - does this work from inside a `.egg`?

**Comment by larkost** [comment]
I can confirm that that logic is the problem, and that the same problem occurs if use `easy_install` rather than `pip` (the only normal way of getting true `egg`s). I have a possible solution to this that I am testing now.

And it does not seem that in your setup that you will run into it, but FYI: there is logic in `setup.py` that will only include the `asyncio` file on versions of Python that support it. So you need to do your packaging with a version of Python that supports it (by default 3.4+).

**Comment by larkost** [comment]
This is working in my local testing, so it is up for review in CR 3722 from branch `larkost/6043-loop-type-fix`.

**Comment by larkost** [comment]
This is in `next` with bf4be17f and `v2.3.x` with a1054107. It will ship with the next version of the Python driver (probably 2.3.5).
