### ISSUE TITLE
Official golang driver

### ISSUE THREAD

**Issue by ghost** [rethinkdb/rethinkdb#6065]
Please, write official golang driver for RethinkDB.

**Comment by qwertythefish** [comment]
Agree with @fdhadzh, RethinkDB is really cool, but it would be nice to have a go-client

**Comment by larkost** [comment]
Just to be clear, there is already a [third-party driver (gorethink)](https://github.com/dancannon/gorethink) that I know people are using. And the list of generally-up-to-date drivers is kept here: http://rethinkdb.com/docs/install-drivers/

But if you are specifically looking for a first-party driver then please elaborate on why the existing third-party driver does not meet you needs. As with any engineering effort, energy spent in one place means we can't spend it in another, so we need to have good justification to consider re-doing work that someone else has already done.

**Comment by kofalt** [comment]
For what it's worth I think @dancannon has done an excellent job with his driver. I would be excited to see that driver become official to establish a clear promise of support & compatibility, but right now I'm not sure I see a burning need for that given finite RDB resources. Just one dev's opinion :smile:

**Comment by arekkas** [comment]
I can second what @kofalt has said, the driver works really well and is supported by the developer.

**Comment by haggerty-william** [comment]
https://github.com/GoRethink/gorethink is no longer supported and is tagged as "No Maintenance Intended"

**Comment by bchavez** [comment]
@haggerty-william there are no good drivers for C#? Check: https://github.com/bchavez/RethinkDb.Driver

**Comment by haggerty-william** [comment]
"A commercial license is required if any part of this driver is used to communicate with a RethinkDB (server or proxy) using SSL/TLS encryption."
Is that even acceptable for most people? I've never had to pay for the api to connect to a database before. maybe pay for the db itself but not the driver.

**Comment by bchavez** [comment]
Hey @haggerty-william 

> I've never had to pay for the api to connect to a database before. 

You don't have to. The commercial driver license only applies if you are using the C# driver over an SSL/TLS connection. Otherwise, absent SSL/TLS, the C# driver is free to use which applies to the vast majority of use cases & users using the C# driver.

> "maybe pay for the db itself but not the driver"

When paying for a database itself, I think the cost of the database subsidizes the cost of driver development. Truth be told: *everything has a cost*.

Regardless, though, some people prefer to support open-source financially in exchange for having some assurance that the software they use and rely upon is maintained, up-to-date, and bug-free. The point is they have someone they can turn to get their problems solved and that carries real business value.

Food for thought:
* What work would you rather pay a senior .NET developer $120,000/year for? 
  * Spending time tracking down some low-level database driver issue?
  * Spending time understanding database driver architecture, driver protocols, driver ASTs, just to add new features, bug fixes, and support newer versions of RethinkDB?
  * And then possibly take ownership of a driver codebase if the maintainer cannot be reached?
  * Or would you rather have them solve current business-value problems at hand?

Either way, when you have a problem or feature request on a piece of unmaintained software you're paying for it. Every business is different but for some businesses that look at productivity, the choice is clear.

I chose to add a financial mechanism in the C# driver after the RethinkDB company closed because **1)** there was demand for it and **2)** I wanted to prevent the very situation I've seen many other community drivers find themselves in. Maintainers burn out, move on, lethargy takes hold, drivers get abandoned along with its users, and users are stuck powerless using an outdated version of RethinkDB and/or API.

I am doing everything I can to ensure that will not be happening with the bchavez/C# driver. The driver numbers in the C#/.NET community are growing, slowly but surely. Devs using the bchavez/C# driver are successful in their endeavors. I think that's what matters most. And I'm very grateful, fortunate, and happy to be apart of it.

**Comment by gabor-boros** [comment]
Closing as the Go driver is located at rethinkdb/rethinkdb-go repo. It is up-to-date and if any changes required, it can be done there. (AFAIK, it is maintained)
