### ISSUE TITLE
admin ui has no csrf protection

### ISSUE THREAD

**Issue by vikstrous** [rethinkdb/rethinkdb#6068]
I didn't see any CSRF protection in the admin UI requests. Let me know if I missed something. This would be essential for exposing the rethinkdb UI to users. We can add an authentication proxy in front of it, but we can't fix the CSRF issue without modifying rethinkdb's javascript.

**Comment by deontologician** [comment]
This is for database admin users?

**Comment by danielmewes** [comment]
In order to run any queries, you will need to retrieve a connection token first, which is cryptographically generated by the server. So unless the forger can get access to the server response to the connection setup request, it can't actually do anything.

I might be missing some case?

**Comment by danielmewes** [comment]
If you look at the network connections that the web UI uses in your browser, you can see a request that looks like this:
`open-new-connection?cacheBuster=...`

The server responds to this with a connection token.

Then, in order to actually do anything, you have to pass that connection token (`conn_id`) to the subsequent calls (e.g. `?conn_id=...`). If the ID doesn't match up, the query isn't executed.

An attacker could perform a DoS attack on the server, by opening a large number of connections through `open-new-connection` which would consume memory on the RethinkDB server until the connections eventually time out. But they shouldn't be able to run queries.

**Comment by vikstrous** [comment]
Okay, this is good. The admin server has only one endpoint? Is there any reason not to allow users to connect to the admin ui if they are authenticated by a proxy?

On August 23, 2016 1:52:33 PM PDT, Daniel Mewes <notifications@github.com> wrote:
>If you look at the network connections that the web UI uses in your
>browser, you can see a request that looks like this:
>`open-new-connection?cacheBuster=...`
>
>The server responds to this with a connection token.
>
>Then, in order to actually do anything, you have to pass that
>connection token (`conn_id`) to the subsequent calls (e.g.
>`?conn_id=...`). If the ID doesn't match up, the query isn't executed.
>
>An attacker could perform a DoS attack on the server, by opening a
>large number of connections through `open-new-connection` which would
>consume memory on the RethinkDB server until the connections eventually
>time out. But they shouldn't be able to run queries.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rethinkdb/rethinkdb/issues/6068#issuecomment-241874508

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielmewes** [comment]
@vikstrous Yeah, it only has the main end-point for running queries and the open-new-connection and close-connection endpoints.

I can't think of a reason for not exposing the UI through a proxy to users who are admins on the database anyway, but I might be missing something.
