### ISSUE TITLE
Avoid going through unsaved data limit throttler for reads

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#6072]
At the moment both read and write transactions go through the throttle in the cache that limits the amount of unsaved data. If the unsaved data limit is exhausted, this means that even reads will queue up on the throttle and need to get in line with writes.

This was originally necessary to ensure ordering of writes and reads, but we have since changed the mechanism by which the ordering of transaction is ensured (it now happens in the cluster layer rather than the cache). In fact we have special code elsewhere that allows reads to skip ahead of writes when acquiring the superblock.

I need to double-check, but I believe that we can just ignore the throttler for read transactions. That would avoid potentially extremely high latencies for read transactions during heavy write load.

If this turns out to be safe, I'd like to try getting this into 2.3.5 actually. (@larkost that means that we will have to run the tests again on at least one platform).

**Comment by danielmewes** [comment]
A fix is in code review 3740 .

**Comment by danielmewes** [comment]
Pushed into `next` via bc7f998 and `v2.3.x` via c3061fa. Will ship with RethinkDB 2.3.5.

**Comment by analytik** [comment]
I don't have any proof, but I believe this change caused a lot of problems in our production servers, especially in three scenarios:

* inserting 50MB of JSON data at once with hard durability (~22k documents)
* running a complex query with a bunch of subselects and a few filters like "field X not one of these 2000 integers", which is very CPU intensive
* filtering a poorly get_all'd chunk of data of a table with 20M rows (probably millions of rows at a time)

What's curious in these scenarios is that RethinkDB doesn't "die" instantly - it responds normally, then a few seconds/minutes later it starts responding slower, and within 5-10 minutes even simple get() queries are 100x-1000x slower.

I don't have a well documented proof, as all this is in production, and I don't think it's safe to roll back production to 2.3.4 because of some other bugs / memory leaks there, but I would like to run a few tests in 2.3.5 vs 2.3.5 without these changes. Any comments about any related changes in 2.3.5 that might have affected performance in such way?
