### ISSUE TITLE
Consider making non-indexed `.orderBy(...)` stable

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#6094]
Prior to some discussion with @danielmewes on Slack today, I had assumed all sorting operations in RethinkDB were stable. In particular, when comparing the field value of two documents, I assumed if the values were equal, we would fall back to comparing the documents in some deterministic fashion. Instead, it appears that document order is simply preserved from the input stream in this case.

It's worth noting that indexed `orderBy` is in fact stable since, internally, the secondary index is suffixed with the document's primary key. The discrepancy between an indexed and non-indexed sort is what caused confusion for me and it seems kinda bad as default behavior.

I think we should consider making `orderBy` stable by default. In other words I think the following should produce the same (stable) result when multiple documents contain the same value for `foo`:

- `.orderBy(index: 'foo')`
- `.orderBy('foo')`
- `.orderBy('foo', r.row)`

Doesn't seem like there would be huge perf costs associated with this change, but even if there were I think I'd prefer a stable sort by default with an optarg to disable over the existing behavior.

**Comment by danielmewes** [comment]
Three additional notes from our conversation:
* The property `stable` of a sorting algorithm usually refers to our current behavior, that is maintaining the input order for elements with equal sorting keys. The proposed change would make the sorting unstable in that sense, but in a deterministic way.
* The main case where this comes up is if someone does `r.table(...).orderBy('foo')` (possibly with a `getAll` or `between` before the `orderBy`). The result if this is not deterministic if there are duplicate values for a given `foo`, since `r.table(...)` does not return results in a deterministic order.
* For this case, there is usually an easy work-around by adding an index-based `orderBy` in front of the final `orderBy`: `r.table(...).orderBy({index: "id"}).orderBy('foo')`. This makes the order of the input to `orderBy('foo')` deterministic, and hence the overall result is deterministic since `orderBy` is "stable".

**Comment by marshall007** [comment]
This is actually just a dupe of #2243. Looks like similar discussions have taken place in the past.

**Comment by danielmewes** [comment]
Oh good find! I didn't remember that issue. Closing this as a duplicate then.
