### ISSUE TITLE
Connection authentication error is followed by uncaught timeout error

### ISSUE THREAD

**Issue by kvnvelasco** [rethinkdb/rethinkdb#6103]
I'm not entirely too familiar with coffeescript but 

```
        # If any other kind of error occurs, we also want to cancel
        # the timeout error callback. Otherwise a connection error
        # would be followed shortly by a spurious timeout error.
        @rawSocket.once 'error', => clearTimeout(timeout)
```

Comes out to be 

```
    this.rawSocket.once('error', (function(_this) {
      return function() {
        return clearTimeout(timeout);
      };
    })(this));
```

corrects the issue

```
    this.once('error', (function(_this) {
      return function() {
        return clearTimeout(timeout);
      };
    })(this));
```

I'm pretty new to JS dev, so.. I could be missing something.

**Comment by danielmewes** [comment]
I'm not sure which version is correct. @deontologician do you understand why this code is the way it is?

**Comment by deontologician** [comment]
So the reason it's probably like this is because the underlying rawSocket does emit the errors. The reason the second version works is because we re-emit socket errors on the parent object (see [line 1219 in net.coffee](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L1219). Since it's hard to track which order these handlers are executed in, it may be preferable to do it @kvnvelasco 's way.

@kvnvelasco under what circumstances are you getting an exception here? This code as-is seems like it should work to me

**Comment by kvnvelasco** [comment]
@deontologician 

```
handshake_error = function(code, message) {
          if ((10 <= code && code <= 20)) {
            return _this.emit('error', new err.ReqlAuthError(message));
          } else {
            return _this.emit('error', new err.ReqlDriverError(message));
          }
        };
```

The firing of this piece of code does not unset the timeout.
