### ISSUE TITLE
RethinkDB's Java driver blocks forever if the RethinkDB database connection dies.

### ISSUE THREAD

**Issue by jlove-nz** [rethinkdb/rethinkdb#6112]
RethinkDB's Java driver blocks forever (or at least that is the symptom) if the RethinkDB database connection dies - e.g. because the database is shut down, or because an intermediate firewall or load balancer (e.g. AWS's load balancer) kills the TCP connection.

If I run the following code with a local rethink DB database, then shut the rethinkDB database down, the application will block indefinitely when it runs the next rethinkDB command (either insert or query).

	package rethink_connectivity_test;
	
	import com.rethinkdb.RethinkDB;
	import com.rethinkdb.net.Connection;
	
	public class ConnectivityTest {
	
		public static void main(String [] args) throws Exception {
			
			RethinkDB r = RethinkDB.r;
			Connection c = r.connection()
				    .hostname("localhost")
				    .port(28015)
				    .connect();
			r.db("test").tableCreate("bucket").run(c);
			
			int counter = 0;
			while(true) { 
				r.db("test").table("bucket").insert(r.hashMap("counter", counter)).run(c);
				long total = r.db("test").table("bucket").count().run(c);
				
				System.out.println("Document count is " + total);
				
				Thread.sleep(1000);
			}
		}
	}
	
I would anticipate that the application code could in some way be informed and handle this scenario.

**Comment by bchavez** [comment]
@jlove-nz Can you enable Java driver logging and show us what the driver's log output traces look like? Also, if there's a way for you to suspend the application when it hangs showing the call stack of relevant threads in suspension would be helpful too.

:point_down: :point_down: [***"...Get low, get, get, get, get low... when the whistle blow..."***](https://www.youtube.com/watch?v=7nUdHAVSLr4)

**Comment by jlove-nz** [comment]
This is the output I get with debug on:

```
  Document count is 49
  10:03:27.722 [main] DEBUG com.rethinkdb.ast.Query - JSON Send: Token: 43 [1,[56,[[15,[[14,["test"]],"bucket"]],[3,[],{"counter":0}]]]]
  10:03:27.727 [pool-1-thread-1] DEBUG com.rethinkdb.ast.Query - JSON Recv: Token: 43 {"t":1,"r":[{"deleted":0,"errors":0,"generated_keys":["577f399f-faaf-48c6-9622-e03ad5ca4062"],"inserted":1,"replaced":0,"skipped":0,"unchanged":0}]}
  10:03:27.727 [main] DEBUG com.rethinkdb.ast.Query - JSON Send: Token: 44 [1,[43,[[15,[[14,["test"]],"bucket"]]]]]
  10:03:27.729 [pool-1-thread-1] DEBUG com.rethinkdb.ast.Query - JSON Recv: Token: 44 {"t":1,"r":[50]}
  Document count is 50
  10:03:28.730 [main] DEBUG com.rethinkdb.ast.Query - JSON Send: Token: 45 [1,[56,[[15,[[14,["test"]],"bucket"]],[3,[],{"counter":0}]]]]
```
I'll attached the thread dump I get using `jstack`.
[waiting_thread_dump.txt](https://github.com/rethinkdb/rethinkdb/files/479013/waiting_thread_dump.txt)

**Comment by bchavez** [comment]
Hi @jlove-nz,

You have an interesting problem. I have not been able to reproduce your issue. Could you elaborate:
* What version of **Java runtime** are you using?
* What version of the RethinkDB **Java Client Driver** are you using?
* Can you double check your `CLASSPATH` and ensure there are no duplicate **Java Driver** libs anywhere?
* What **Operating System** are you using to run the RethinkDB **Java Client** driver?
* What **Operating System** are you using to run **RethinkDB Server**?

---
:package: :dizzy: WOMB (works on my box)
```
Document count is 3
15:34:40.749 [main] DEBUG com.rethinkdb.ast.Query - JSON Send: Token: 8 [1,[56,[[15,[[14,["test"]],"bucket"]],[3,[],{"counter":0}]]]]
15:34:40.751 [pool-3-thread-1] DEBUG com.rethinkdb.ast.Query - JSON Recv: Token: 8 {"t":1,"r":[{"deleted":0,"errors":0,"generated_keys":["0c165bf4-6464-4450-b788-6cc544fe0667"],"inserted":1,"replaced":0,"skipped":0,"unchanged":0}]}
15:34:42.751 [main] DEBUG com.rethinkdb.ast.Query - JSON Send: Token: 9 [1,[43,[[15,[[14,["test"]],"bucket"]]]]]
15:34:42.753 [pool-3-thread-1] DEBUG com.rethinkdb.ast.Query - JSON Recv: Token: 9 {"t":1,"r":[4]}
Document count is 4

com.rethinkdb.gen.exc.ReqlDriverError: Can't write query because response pump is not running.
```
-----

So, after looking at your `jstack`, the call stack for the `main` thread makes sense: `Thread.State: WAITING (parking)` waiting for `.get()` which is the core reason why your application appears to hang. There are two scenarios that should have played out to get out of the `.get()`. **1)** The [`Future<Response>/awaiter`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L165) should have already been signaled by  `pool-1-thread-1` (response pump) when [`close()`ing down](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L124) the network connection on a network read error or **2)** the `main` thread should have thrown if the query [`write` failed](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L210) on the network socket.

But neither seem to be the case in your situation.

I'm not totally sure what `pool-1-thread-1` (response pump) thread is doing. The `pool-1-thread-1` (response pump) thread is also in a state of `Thread.State: WAITING (parking)`; however there is no sign of any calls into the driver.  I do not know if **a)** `pool-1-thread-1`'s thread state of `WAITING (parking)` is a normal state for a completed thread returning back to the thread pool (waiting for more work) or if **b)** `pool-1-thread-1` thread is blocking on some native IO socket read function.

I'm hoping (and leaning toward) the former **a)**. If it's **a)** then I kinda see a *very*, **very**, ***very***, obscure way you could land in a situation like this.

So, assuming **a)**, I suppose the `main` thread passes the [check here](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L204-L205) while the connection is shutting down. Then the scheduler suspends `main` thread on [**Line 205**](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L205). Once `main` thread is suspended, `pool-1-thread-1` (response pump) thread moves in to signal the awaiters in [L165](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L165), but `main` thread's awaiter [**has not been added yet**](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L206); so `main` thread would miss the [`completeExceptionally` signal](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L168) that the response pump is currently sending. The  `pool-1-thread-1` (response pump) thread finishes clean up; and `main` is allowed to resume. Except, this time, it `.put`s the awaiter in the concurrent map, and then attempts to [`write` to a broken network socket](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L210) and [***the `write` magically (or silently) succeeds***](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java#L95-L102) without throwing an exception. I think that's the only way you can get around by calling [Line 211](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L211) to return an awaiter that will never complete.

--------

Since I can't reproduce the error, here's what you could do...

1. Checkout the rethinkdb source.
2. Build the Java driver.
3. Write a test with an exact copy/paste of your program in [RethinkDBTest.java](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/test/java/com/rethinkdb/RethinkDBTest.java#L414)
4. Go crazy and add logging statements throughout [this section of code](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L105-L128) and in this section of the [`close()`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L165-L172) method.
5. I'd add a bunch of logging [statements here too](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L204-L215).

Then you should be getting a clearer idea of what's happening and if that pesky [`SocketWrapper.write()`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java#L95-L102) is succeeding when it should not be over a broken socket.

With that, I'm out of ideas.

 :shell: :tiger2: [**SHELLS - Jagwar**](https://www.youtube.com/watch?v=WVfjotINxsk)

**Comment by jlove-nz** [comment]
Hi Brian,

Right, tracked it down. v2.3.0 has this problem, while v2.3.3 doesn't.  Upgrading to v2.3.3 has solved the problem. Looks like we were not keeping as up-to-date as we thought.

Sorry for the bother. Should have checked that first myself. I made a false assumption.

**Comment by bchavez** [comment]
Hi @jlove-nz , fantastic. I'm very happy you found the problem :smiley_cat:!

:violin: :palm_tree: [***"'Cause it's a bittersweet symphony, this life..."***](https://www.youtube.com/watch?v=1lyu1KKwC74)

**Comment by danielmewes** [comment]
Glad to hear it's working with the latest version.
