### ISSUE TITLE
Zero elements for logical conditions

### ISSUE THREAD

**Issue by ivan-kleshnin** [rethinkdb/rethinkdb#6117]
RethinkDB lacks (obvious) logical identities ("zero" elements) which are required
to assemble conditions on the fly.

Suppose we need to build a filter to find all conflicting entries before model edit.
RethinkDB does not have UNIQUE secondaries so one possible approach is to tolerate potential concurrency problems and check for uniqueness in additional read.

Let `fields` be an array of fields which must be unique among all table rows
and `model` be a model object.

Without "zero" element it's messy:

```js
let [headField, ...tailFields] = fields
let cond = D.row(headField).eq(model[headField]).and(D.row("id").ne(model.id))
let conflictsC = reduce((cond, field) => {
 return cond.or(D.row(field).eq(model[field]).and(D.row("id").ne(model.id)))
}, cond, tailFields)

let conflictsQ = D.table(table).filter(conflictsC)
```

And with "zero" element it's better:

```js
let andID = D.row("id") // logical ONE, supposed to always be true
let orID = D.row("_never_happens_") // logical ZERO, supposed to always be false

let conflictsC = reduce((cond, field) => {
  return cond.or(D.row(field).eq(model[field]).and(D.row("id").ne(model.id)))
}, orID, fields)

let conflictsQ = D.table(table).filter(conflictsC)
```

Unless I missed an easier way to achieve such functionality, I'd like to have equivalents of `andID` and `orID` elements among RethinkDB exports.

**Comment by danielmewes** [comment]
Support for zero-argument logical operations was added in RethinkDB 2.3 https://github.com/rethinkdb/rethinkdb/issues/4696 , which will give you the correct result if you simply pass all conditions into a single `r.and` or `r.or` call through `r.args` (i.e. `r.and(r.args([array of conditions]))`).

Does that solve your use case?

You can also just use `false` and `true` obviously. No need to use fields on `D.row`:
```js
let andID = r.expr(true);
let orID = r.expr(false);
```
The `r.expr` is so that you can call ReQL functions on the values directly.

**Comment by ivan-kleshnin** [comment]
> Does that solve your use case?

Yes. That is exactly what I was asking for. Thank!
