### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by yspb** [rethinkdb/rethinkdb#6143]
Simple problem, but I can't understand how to solve it reading official docs.

Have table of tags:

```
{
"autocomplete": ["c" ,"ca" ,"cat" ,"catc" ,"catch"] ,
"count": 3184 ,
"id":  "003eee04-f383-4b30-b0c5-4fc91b064dac" ,
"name":  "catch"
} 
{
"autocomplete": ["m" ,"mo" ,"mov" ,"move"] ,
"count": 5104 ,
"id":  "00066703-0ee8-405f-af4b-b67786d0a3b5" ,
"name":  "move"
}
```

I want to implement autocomplete on user input.

Created two indexes:
```
r.db('store').table('tags').indexCreate('autocomplete', {multi: true});
r.db('store').table('tags').indexCreate('count');
```

1)
This does not work

```
r.db('store').table('tags')
.getAll('s', {index : 'autocomplete'})
.orderBy({index:r.desc('count')}).pluck('name').limit(20);
```

2)
If sort in memory, then it is > 100ms... too much

```
r.db('store').table('tags')
.getAll('s', {index : 'autocomplete'})
.orderBy(r.desc('count')).pluck('name').limit(20);
```

How to create multiple index on array and count field? Thx!

**Comment by marshall007** [comment]
@yspb you're definitely on the right track. The issue with your first query is that you can only chain an indexed `.orderBy` using the same index in the previous expression. The trick is to create a compound index that you can use to both filter the results and sort them:

```js
r.db('store').table('tags')
.indexCreate('autocomplete', (row) => {
  return row('autocomplete').map((edge) => [ edge, row('count') ])
}, { multi: true })

r.db('store').table('tags')
.between(
  [ 's', r.minval ],
  [ 's', r.maxval ],
  { index : 'autocomplete' }
)
.orderBy({ index: r.desc('autocomplete') })
.pluck('name').limit(20);
```

Also note that if all you need for your autocomplete implementation is a prefix match, then you could just use the `name` field directly instead of creating all the left edge nGrams yourself. This also massively reduces the size of the index:

```js
r.db('store').table('tags').indexCreate('autocomplete', [ r.row('name'), r.row('count') ])

r.db('store').table('tags')
.between(
  [ 's', r.minval ],
  [ r.maxval, r.maxval ], // note the query changes slightly here
  { index : 'autocomplete' }
)
.orderBy({ index: r.desc('autocomplete') })
.pluck('name').limit(20);
```

Let me know if you have any other questions.

**Comment by yspb** [comment]
Ok, all I need is to think a bit different :-)
That works! Thank you.
