### ISSUE TITLE
heap-overflow in cJSON parser leading to code execution

### ISSUE THREAD

**Issue by PaulCher** [rethinkdb/rethinkdb#6183]
Due to issues in src/cjson/cJSON.cc it should not be used, it is recommended to use rapidjson instead.

**Description:**
UTF characters handling in string parsing function is implemented incorrectly and results a heap overflow that leads to code execution. "Length" of the string is computed [the following way](https://github.com/rethinkdb/rethinkdb/blob/next/src/cjson/cJSON.cc#L230) by symbols from start until next quote symbol, but we may trick parser to iterpret quote as part of UTF character, then [take this branch](https://github.com/rethinkdb/rethinkdb/blob/next/src/cjson/cJSON.cc#L270) and thus bypass the length resctriction to overflow other heap regions. 

**PoC:**
To reproduce this issue you can pass the following string as an argument to cJSON_Parse() function:
`"AAAA\ud800\uxxx"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"`

You can contact me if you need more details on vulnerability.

**Comment by AtnNn** [comment]
If you are running RethinkDB version 2.1 and above and don't have any [outdated indexes](https://www.rethinkdb.com/docs/migration/#rebuild-indexes), you shouldn't be affected by this bug.

Thanks for the report, but CJSON is only used for backwards compatibility, RethinkDB has been using rapidjson since version 2.1 (see #3844).
