### ISSUE TITLE
i am having a problem when trying to insert data . pls help

### ISSUE THREAD

**Issue by rohitdesigner** [rethinkdb/rethinkdb#6199]
hey coders i am getting error when trying to insert data in a table..
please check this out

![ad](https://cloud.githubusercontent.com/assets/17812216/21288284/76988bd8-c412-11e6-905a-9a81447219ac.PNG)
![db](https://cloud.githubusercontent.com/assets/17812216/21288292/9722f348-c412-11e6-8540-52617ea23883.PNG)

Note : the server is running on port:
see this also...

![sac](https://cloud.githubusercontent.com/assets/17812216/21288304/c36d2a9a-c412-11e6-9318-82cccbb8b4b5.PNG)
 guys help me with this

**Comment by raffi-minassian** [comment]
I think what is happening here is that your tableCreate statement is running before your connection variable has any value ... in other words it is still null. This is because the r.connect runs async via the callback. In other words, execution does not stop at the line for r.connect(). The result returns through the callback function. By then the next line has already executed while connection is still null. If you are new to node.js, at first this can be confusing, but once you catch on, you will be fine. Unfortunately, I'm not so good at explaining.

So I think you if you change your code to something like this, you will see the result you want...

```
r.connect({host:'localhost', port:28015}, function(err, conn){
  if(err) throw err;
  r.db('test').tableCreate('authors').run(conn, function(err, result){
   if(err) throw err;
   console.log(JSON.stringify(result, null, 2));
  });
});
```

Assuming I didn't introduce any typos transcribing the image of your code, it should work. Give it a shot. You can "unnest" the code if it bothers you by using something like Async http://caolan.github.io/async/ . There are many other options as well.

Cheers

**Comment by grantcarthew** [comment]
Can you use Promises? You will find it a lot easier.
https://www.rethinkdb.com/api/javascript/connect/

**Comment by rohitdesigner** [comment]
it worked.. but why the previous code is exactly written on rethinkdb
documentation

**Comment by grantcarthew** [comment]
Hey @rohitdesigner, it sounds like you are just getting into JS.
Read this: http://rowanmanning.com/posts/javascript-for-beginners-async/

I had the same trouble when I started working with it.

**Comment by AtnNn** [comment]
The example code from the [ten minute guide](https://www.rethinkdb.com/docs/guide/javascript/) was meant to run sequentially on the `nodejs` command line, not asynchronously. Here are [some examples](https://www.rethinkdb.com/docs/examples/) of how you would integrate RethinkDB queries into a JavaScript application.
