### ISSUE TITLE
Porting rethinkDB to z(s390x)

### ISSUE THREAD

**Issue by cwsolee** [rethinkdb/rethinkdb#6242]
We are currently porting over RethinkDB to z Systems aka s390x. 
Our team have been trying to get rethinkDB build with this instruction: https://github.com/linux-on-ibm-z/docs/wiki/Building-RethinkDB-DRAFT . They have been mostly working around the inline assemblies, as well as making things work with V8 3.28 instead of 3.30 (not available and hard to move to on z). We're working on context switching code to enable z at this time.

Could you please take a look at the link above to check, whether something obvious is missing?

**Comment by AtnNn** [comment]
You seem to be on the right track. After talking to your team on slack, it seems like many of the remaining issues are due to missing context switching and big endianness.

I see you've made many one-way changes, for example by replacing code instead of using `#ifdef`. Too many of those will make it harder to have your code merged upstream, or to merge upstream patches.

**Comment by cwsolee** [comment]
Thanks Etienne, we uploaded another version yesterday, please review the newer version too. 
U're right, our changes right now is trying to get rethinkDB built and function, these code are not good enough for PR. We'll do a major clean up before we submit any PR to the community, we likely will try to join your CI to ensure we build ok on z and not breaking intel also.

**Comment by AtnNn** [comment]
Closing in favour on #6295
