### ISSUE TITLE
Proposal: r.write_time() in write hooks.

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6267]
This proposal is that
(1) Like in v2.3, `r.now()` in a particular query should never change what value it evaluates to.
(2) `r.write_time()` should evaluate to the "write time" in certain contexts:  In write hooks, and maybe in changefeed maps and filters later.
(3) `r.now()` should be disallowed in write hooks (like with secondary index functions).

----

The reason for (1) is, having `r.now()` change meaning depending on exactly where it is, and having this depend on evaluation order, can be confusing.  Evaluation order is not exactly well-defined in RethinkDB.  This is a particular problem in changefeeds.  In next, `.changes().merge({'time': r.now()})` will compute different values of `r.now()`, because `.merge` takes its argument with call-by-name behavior.  (*That* is fixed by pull request #6191.)

The reason for (2) is, we need some way to refer to the write's timestamp in write hooks.  Another option would be to make write hooks take a fourth function parameter.  The main reason I went with `r.write_time()` is because before the plan was to use `r.now()`.

The reasons for (3) is,
  - first of all, setting a write hook that uses `r.now()` would be weird
  - people might do it by accident, expecting `r.write_time()` behavior, and never get a warning
  - if you really want to use `r.now()`, you can work around it with `.do`.

----

This is implemented in https://github.com/srh/rethinkdb/tree/sam/write_hook  as of commit c9bf5074a06f4eac59a3babb1510a9819140e341.  (Except the Java driver, for which I have no freakin' clue.)  It uses the command name `r.write_timestamp()`.

----

Handy link to the initial write hooks proposal: It has some discussion of this. #5813

**Comment by marshall007** [comment]
I really like this proposal and cheeky agree on all three points. My only suggestion would be that we consider introducing a term for exposing arbitrary metadata related to the query and execution context. This would lend itself well to also exposing the secondary index name and its value associated with the current row, shard the row is being written to/read from, etc without introducing new terms in the future.

Something like `r.context` and/or `r.ctx`?

**Comment by mlucy** [comment]
+1 on keeping `r.now` like v2.3 and disallowing it in write hooks.

I'm torn on `r.write_time`.  I worry a little bit about ending up in a world where there are a bunch of terms with unusual behavior that are only legal in certain contexts.  But on the other hand we already did that with `r.literal` and it's been basically fine; people seem to treat it as syntax rather than a magic term which is sometimes illegal.

I would lean toward passing a fourth parameter to the write hook because it feels slightly less magical.  I don't think there are actually that many other contexts where you'd want to use `r.write_time`, and introducing a new term that's only legal in one super narrow context feels kinda ugh.

I don't feel super strongly if people like `r.write_time` better though.

**Comment by mlucy** [comment]
Some other thoughts:
* If we go with a fourth parameter to the write hook, we should make it continue to work if you pass a function that only takes three parameters.
* If we expect people to need other metadata in write hooks in the future, maybe we should do something like what Marshall suggested and make the fourth argument a context object with a bunch of fields set on it.  I don't really have a good sense of what other things people might want, but if we expect we're going to want to do this we should probably do it now.  Otherwise we'll either have to break backward compatibility or pass `id, old_val, new_val, write_timestamp, context` which would be awful.

**Comment by marshall007** [comment]
@mlucy if we decide to go with the metadata object, I don't think it should be a parameter of the write hook. Getting the secondary index value for a row in the context of an indexed read, for example, would be really useful. That's why I think it should be a new term.

**Comment by srh** [comment]
I sometimes want objects that aren't really *objects* -- I want a value with fields you can access like `val('field')`, and convert the thing to an object with `val.pluck('field1', 'field2', ...)`, and that's it.  That way it can be extended in future versions of RethinkDB without worrying about breaking stuff.

**Comment by marshall007** [comment]
@srh yea that's what I was getting at with `r.ctx(field)`. I was thinking it would behave just like `r.row` or any other object expression.

**Comment by srh** [comment]
We have the following examples of dynamic scope in ReQL:
 - the variable holding the query timestamp for `r.now()`, which is available in some contexts 
 - the hidden variable that lets you run "single_server" deterministic operations
 - the hidden variable that lets you run nondeterministic operations
 - potentially, `r.write_timestamp()`
 - potentially, `r.context(...)`

Right now, we can statically inspect a query and see whether it might access a particular dynamic variable.  We can prohibit `r.now()` and non-deterministic operations from secondary indexes, for example.  We can do this at installation time, instead of seeing the error (or silently ignoring it) at run-time.

Generally speaking, you couldn't do that with `r.context('now')` or `r.context('write_timestamp')`.

You could do it with `r.context.write_timestamp()` though.

So I think instead of `r.context(...)` the right answer would be to add separate reql commands for any new stuff like secondary index values, and namespace them in `r.context` in the drivers if you want.

----

Do we have any other functions with multiple acceptable arities in ReQL?

**Comment by mlucy** [comment]
> Do we have any other functions with multiple acceptable arities in ReQL?

Most functions can be arity 0 without throwing an error, but I can't think of any other cases where there are two legal non-0 arities.

> if we decide to go with the metadata object, I don't think it should be a parameter of the write hook. Getting the secondary index value for a row in the context of an indexed read, for example, would be really useful. That's why I think it should be a new term.

I don't think we should have a single global context term that can be used for that as well.  The set of useful things while doing an indexed read is wildly different from the set of useful things while evaluating a write hook.  I think it would be confusing to have a term which provides totally different information depending on what the ongoing operation is.

(Personally, the way I would handle the "get the secondary index value" case is I would define a new term `sindex_val` on objects, where `table.between(0, 1, index: 'foo').merge{|row| {foo: row.sindex_val()}}` gets the sindex value of `row` using the current sindex, `table.merge{|row| {foo: row.sindex_val('foo')}}` gets the sindex value of `row` using a named sindex on the current table, and `OBJ.sindex_val('foo', table)` gets the sindex value of `row` using a named sindex on a named table.  That seems clearer and more flexible than storing it in a context.)

> So I think instead of r.context(...) the right answer would be to add separate reql commands for any new stuff like secondary index values, and namespace them in r.context in the drivers if you want.

I agree, I think multiple global terms is better than a single global context term.  (I think if we go the "pass an extra argument to the function" route, it's less obvious that multiple arguments is better than a single context argument.)

**Comment by srh** [comment]
Thank you for the feedback @mlucy.

This introduces the idea of having `row.sindex_val` -- which implies some mysterious property of "what table or table+index it comes from" being carried along with an object.

What do you think of the idea of having the same be carried along for a context function parameter, instead of it being an object with fields?  In other words, a write hook might be defined:

`function(id, old_val, new_val, ctx) { return new_val.merge({'lastModified': ctx.write_timestamp()}; }`

One reason to do this is to prevent people from writing `new_val.merge(ctx)`.  The implementation can examine the write hook and see what it needs to compute, you've got future compatibility.

**Comment by mlucy** [comment]
I'm not sure.

Advantages:
* If people get the field name wrong, they can get a static error when they try to create the write hook instead of just failing to find the field when it runs.
* We can know for sure by examining a function what fields people use.
  - This is maybe less of an advantage than it seems.  Most usages of `ctx` will probably be like `ctx['write_timestamp']`, so I would guess for 99% of functions we could just statically examine the code to see what fields of `ctx` are accessed and get the same performance savings.  For the very small number of functions that do something more complicated like `.merge(ctx)` we'd just include all of them.
Disadvantages:
* We'd probably need to introduce a new type for `ctx`.
* It's slightly harder to explain than just "you get passed a context object".

I would lean slightly toward making `ctx` a normal object, but I can see the argument for both ways.  If I had to rank the options in order of my personal inclination:

1. Pass a context object to the function.
2. Pass a special context type to the function.
3. Pass a new argument to the function every time we add something new a write hook might need.
3. Have several terms that are only legal inside write hooks.
4. Have a global `context` term.

**Comment by danielmewes** [comment]
I'm somewhat ignorant to the history of this, so please let me know if you've been through this and it's nonsense. But this sounds kind of unnecessary complex, both on the ReQL level, as well as on the implementation level.

Why not:
* Fix the problem that the deterministic time in the environment changes across batches by storing the timestamp in the query_cache. This restores the same semantics as the old `r. now`.
* Mark the `r.now` term as deterministic. I think it was a bug that we marked it as non-deterministic. This will recover the ability to use `r.now` in all places where it was previously usable.
* This will raise the issue that it can break secondary indexes, since it will allow `r.now` to appear in secondary indexes. We had previously agreed during the 2.4 development that we would disallow `r.now` in secondary index functions.
  * Option 1: Actually implement this. There are various ways to do this, from scanning the term tree when creating an index, to adding a new flag on `term_t` such as `bool ok_in_sindex_func() const` that works analogously to `is_deterministic()`. I think that the latter is similar to what @AtnNn did in https://github.com/rethinkdb/rethinkdb/pull/6191, though I haven't looked at the precise implementation there yet.
   * Option 2: Punt on this! Document that `r.now` is undefined in secondary index functions and that you shouldn't use it. Secondary index functions use a default-constructed env_t to evaluate in. So we simply default initialize the timestamp in the environment to e.g. 0. All uses of `r.now` in a secondary index function will evaluate to 01-01-1970 or something like that. We can still add a check for `r.now` in a later release so that newly created indexes can no longer use it.

If we do this, write hooks using `r.now` will automatically work. They will get the timestamp from the environment, which will contain the timestamp of the write query. In general the semantics of `r.now` will be (both in queries as well as in write hooks) that it will evaluate to the timestamp at which the query evaluation began, and is constant throughout any given query.

**Comment by danielmewes** [comment]
* ...handling `r.now` in index functions...
  * Option 3: Fail inside of `r.now` when evaluating it in a secondary index environment. E.g. `get_deterministic_time()` could throw when called on such an environment. There's even a chance that `r.now` already does that, since it has an `r_sanity_check` on `env->env->get_deterministic_time().has()`, though we should probably make that a regular check if we want to use this.
    This would mean that secondary indexes that use `r.now` would be empty, because we don't have any error reporting for failures in secondary index functions. I think that's ok in this edge case, and probably slightly better than using a dummy value for `r.now`.

Arguably this is even an improvement over 2.3 behavior, where `r.now` in a secondary index function resolves to the timestamp at which the index was created. I think that's almost never what a user wants/expects, so leaving the index empty in that case seems at least no worse to me.

**Comment by srh** [comment]
@danielmewes At least your first suggestion is already implemented in https://github.com/srh/rethinkdb/tree/sam/write_hook and maybe originally in sam/deterministic_now.

Having `r.now()` change meaning inside of a write hook starts becoming iffy when you raise questions about evaluation order. Also, prohibiting it in secondary index functions is easy, so I don't see why we wouldn't do that.  Like, this stuff is already implemented.  `r.write_timestamp()` is implemented, but it's probably not the best choice.

Right now I agree with @mlucy that you should just make it pass a plain-old context object in to the write hook, instead of passing just the id or some fancy object.

Regarding your Option 3: I like that idea too, I also brought it up somewhere, maybe here up-thread.  But we already have code prohibiting `r.now()` when we setup the secondary index function, and I don't see anything about about that.  It would be simpler to do all these prohibitions at run-time, based on what info is present in the environment.

Anyway, what this conversation boils down to is:  `r.write_timestamp()` is a somewhat decent design and is already implemented.  But replacing the `id` parameter to a write hook with an object `{"id": ..., "write_timestamp": ...}` is what @mlucy and I now prefer.  And that's super easy to implement, if I didn't do it yet.  (I forget whether I did!)

**Comment by srh** [comment]
I'm currently implementing passing an object `{"primary_key": ..., "timestamp": ...}`

Which do you prefer:  `"primary_key"` or `"key"` as the key for the document id?
Which do you prefer:  `"timestamp"` or `"write_timestamp"` as the key for the write timestamp?

**Comment by srh** [comment]
Passing a document, removal of `r.write_timestamp()` (the branch being based on sam/write_hook) is implemented in branch https://github.com/srh/rethinkdb/tree/sam/write_hook_doc

**Comment by marshall007** [comment]
@srh I like the way you have it implemented as-is with `{ primary_key, timestamp }`.

We already restored v2.3.x deterministic behavior of `r.now()` and your first pass in `sam/write_hook` disallowed `r.now()` in the context of write hooks, correct?

**Comment by srh** [comment]
That's correct.

**Comment by srh** [comment]
I've made a pull request.  Somebody else will have to pull the trigger on that one, considering there's been some disagreement on how the API should be and I'm not particularly interested in corralling people.

**Comment by danielmewes** [comment]
https://github.com/rethinkdb/rethinkdb/pull/6396 is merged.
