### ISSUE TITLE
Do I need to `conn.close()` for every thread close or the connection will close automatically?

### ISSUE THREAD

**Issue by notalentgeek** [rethinkdb/rethinkdb#6278]
I hope the title is self explanatory. I am using RethinkDB in Python.

**Comment by srh** [comment]
It's considered good practice to use a `with` statement or to otherwise ensure that `close` is called even if an exception happens.  This is true in Python in general.

If you don't close it, the connection's socket will only close when Python's garbage collection system cleans up cycles, because the connection object has an internal reference cycle.

**Comment by notalentgeek** [comment]
Alright thank you.
