### ISSUE TITLE
Other type of Reactive Data Structures and Operators to Manipulate them

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6286]
Can we have more paradigms than just tables:

 - graphs
 - documents
 - objects
 - Key Value
 - Multidimensional Data Cubes, Spreadsheet like structures, Pandas Like Panels, tensors, vectors, matrices
 - General persisted reactive collections like queues (you will need this for https://github.com/rethinkdb/rethinkdb/issues/6285 at least) 

Also special operators for:

 - graph traversals
 - linear algebra / machine learning (http://madlib.incubator.apache.org/)
 - etc.

**Comment by AtnNn** [comment]
Thanks for the suggestions. When choosing to implement new types or operations, I ask myself the following questions:

* Which are harder to implement on top of existing primitives?
* Which provide the most benefit from being performed on the database instead of the client?
* Which could be implemented and maintained easily, perhaps by simply wrapping an external library?
* Which best complement the set of existing features?

The main obstacle to implementing any new features is the current shortage of active developers.

There is a general issue for plugins: #4785
There are existing issues for graph related features: #3142 #3711
There are existing issues for more math primitives: #3898 #3769
I can't find any issues related to machine learning, but I've seen it discussed before.

What do you mean by document, object and key/value? We already support JSON documents, JSON objects and simple key/value style collections.

**Comment by sirinath** [comment]
You just need the results in the client. It is best to do the number crunching on where the data is.

**Comment by internalfx** [comment]
I would be very interested to see graph data structures in RethinkDB

**Comment by thelinuxlich** [comment]
@srh I think this is too broad and should be closed
