### ISSUE TITLE
Continuous Benchmarks

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6287]
Can we have release by release benchmarking against:

- PipelineDB
- Aerospike
- Scylladb
- arangodb
- Clickhouse
- Druid
- CrateDB
- Dgraph
- etc.

Also regular benchmarks on snapshots.

**Comment by thelinuxlich** [comment]
In my opinion, that would be comparing apples to oranges, these DBs all have very different architectures and purposes.

**Comment by sirinath** [comment]
This will be comparing speed of common operations. If you were to use this DB for low latency, hard real time, high throughput application, speed does matter. This being a reactive DB, importance should be given to speed and predictability of response times.

**Comment by sirinath** [comment]
Ideally you should compare but even if you do not there should be a benchmark suite for ReThinkDB which is published release by release with comparison with changes over the last release.

**Comment by AtnNn** [comment]
More benchmarks and comparisons seems like a great idea. Here are some pointers for anyone wanting to work on this.

* For comparing performance differences across different releases or snapshots, there are scripts in `test/performance/`

* For comparing against other databases, the YCSB benchmarks can be used. We have our own branch of YCSB with added RethinkDB support: https://github.com/rethinkdb/YCSB

**Comment by analytik** [comment]
Comparing the speed of "common operations" is meaningless, because benchmarks always operate on "ideal" data sets, in the sense they're extremely predictable, and thus completely unlike software development realities.

If it helps, I'm _slowly_ working on a rethinkdb-load-test project in Node.js, which would simulate a more noisy environment. Benchmarking other DBs is out of my scope of interest, and I would rather focus on more complex, RethinkDB specific use cases, complicated unions, group-map-reduce operations, joins, changefeeds, inefficient updates and filter queries and similar.

I agree with sirinath that having results of any benchmarks in general, by release or nightly build, would be cool to see, although this is a big project that needs a bunch of infrastructure. We can get inspired by [elasticsearch though](https://elasticsearch-benchmarks.elastic.co/geonames/index.html).

**Comment by srh** [comment]
Closing.  ScyllaDB got a lot of funding, so you should ask them to make the benchmarks.
