### ISSUE TITLE
Document internal serialization formats, because they matter for PKs (as they're size-limited)

### ISSUE THREAD

**Issue by drdaeman** [rethinkdb/rethinkdb#6304]
Please consider documenting how arrays are serialized, in regards to their use for primary keys. On RethinkDB 2.3.5, a simple `r.table("test").get([...])` query shows me this error:

    Primary key too long (max 127 characters): [
    	123,
    	1234567890,
    	123,
    	"foobar12",
    	"0123456789abcdefghijklmnopqrstuvwxyz0123456"
    ] in ...

I've incorrectly assumed - for no particular reason, just had the impression - that the format was JSON or alike, but it doesn't seem to be the case. At least, I can't imagine how this data could be 128 octets-long (value is accepted if I remove any single character anywhere). Result of `r.expr([123, 1234567890, 123, "foobar12", "0123456789abcdefghijklmnopqrstuvwxyz0123456"]).toJsonString().count()` is 77, and use of `info()` on such expression returns a 88-character value (because of extra `\n`s and `\t`s).

Can someone please enlighten me? Thanks a lot!

**Comment by drdaeman** [comment]
Would've appreciated if someone can just show me exact (byte-wise) serialization of the PK from the example above. I would be probably able to figure the rules on my own.

**Comment by AtnNn** [comment]
Here it is.

```
00000000  41 4e 63 30 35 65 63 30  30 30 30 30 30 30 30 30  |ANc05ec000000000|
00000010  30 30 23 31 32 33 00 4e  63 31 64 32 36 35 38 30  |00#123.Nc1d26580|
00000020  62 34 38 30 30 30 30 30  23 31 32 33 34 35 36 37  |b4800000#1234567|
00000030  38 39 30 00 4e 63 30 35  65 63 30 30 30 30 30 30  |890.Nc05ec000000|
00000040  30 30 30 30 30 23 31 32  33 00 53 66 6f 6f 62 61  |00000#123.Sfooba|
00000050  72 31 32 00 53 30 31 32  33 34 35 36 37 38 39 61  |r12.S0123456789a|
00000060  62 63 64 65 66 67 68 69  6a 6b 6c 6d 6e 6f 70 71  |bcdefghijklmnopq|
00000070  72 73 74 75 76 77 78 79  7a 30 31 32 33 34 35 00  |rstuvwxyz012345.|
```

I'm not sure why there's so much padding.

**Comment by AtnNn** [comment]
Related to #3453

**Comment by drdaeman** [comment]
Oh. I haven't thought that number serializations are *so* expensive. If I'd knew, I would've used strings instead, as I don't do any math on those identifiers anyway.

If I got it right, [`datum_t::num_to_str_key`](https://github.com/rethinkdb/rethinkdb/blob/3ad28ada67594a0d8073a733696a04d7b0d70418/src/rdb_protocol/datum.cc#L619) returns what's essentially `strprintf("N%.*I64x#%.20g", value_mangled_uint64, value)`, where `value_mangled_uint64` is double-as-int64 with some bit-flipping.

    >>> hex(struct.unpack("=Q", struct.pack("=d", 123.0))[0] ^ (1 << 63))  # for positive values
    '0xc05ec00000000000'

This is probably outside of this issue's scope, but I'm sure there must be some better way to encode numbers, that doesn't require `strlen(n) + 18` octets.

I've lost my way looking for where deserialization takes place, but I wonder:
- Why there's a second piece (`PR_RECONSTRUCTABLE_DOUBLE`, after the `#`)? Given that `datum_t::as_num()` returns a `double` anyway, no precision could be lost when if it's in-memory representation is serialized.
- Could there be something better than hexadecimal? Something like base64 or base85 shouldn't be much more expensive than hexadecimal encoding. And why not just keep 1-octet "N" prefix followed with 8-octets binary data? PKs already have `\x00`s in them?

**Comment by srh** [comment]
I think keys in the b-tree don't get deserialized -- the document gets deserialized, and the key gets re-read out of that (or not re-read, because there happens to be no reason).  I think the PR_RECONSTRUCTABLE_DOUBLE thing is complete waste.  If you remove it, you'll have to change the key comparison function(s) used by btree/ code, in order to maintain backwards compatibility.  (Or, use different serialization functions for old tables vs. new tables.)

It looks like arrays use `\x00` as separators and there's a bunch of comments in `print_primary`'s callees about avoiding `\x00` for that reason.

You could use base-255 encoding (or whatever's convenient, base-139 would suffice) and use 9 bytes for numbers.

You could compress further while maintaining lexicographical ordering (favoring integers like we do in document serialization -- see `datum_serialize`).  It's just more annoying to implement than non-lexicographic.

**Comment by srh** [comment]
Closing in favor of https://github.com/rethinkdb/docs/issues/1205 and #6369.
