### ISSUE TITLE
Issue with group query with filter in array of object

### ISSUE THREAD

**Issue by DipakTechifySolutions** [rethinkdb/rethinkdb#6381]
Guys, I am working on a project, where I use rethinkdb. There is a contact table. I should give a feature to merge contact by firstname-lastname, firstname-phonenumber and firstname-emails. But when I applied following query it will show me ambiguous result. I don't know how to solve this issue. 

**Table** 
```
[  
   {  
      "firstName":"A1",
      "phones":[  
         {"value":"9067672585"},
         {"value":"9067672586"},
         {"value":"9067672587"}
      ],
      "id":"3ab630c3",
      "user_id":"ab1"
   },
   {  
      "firstName":"B1",
      "phones":[  
         {"value":"9067672515"},
         {"value":"9067672526"},
         {"value":"9067672537"}
      ],
      "id":"3ab630c8",
      "user_id":"ab1"
   },
   {  
      "firstName":"D1",
      "phones":[  
         {"value":"9067672737"}
      ],
      "id":"3ab630c7",
      "user_id":"ab1"
   },
   {  
      "firstName":"C1",
      "phones":[],
      "id":"3ab630c9",
      "user_id":"ab1"
   },
   {  
      "firstName":"C1",
      "phones":[{"value":"9067672585"}],
      "id":"3ab63010",
      "user_id":"ab1"
   },
   {  
      "firstName":"A1",
      "phones":[  
         {"value":"9067672585"},
         {"value":"9067672588"},
         {"value":"9067672589"}
      ],
      "id":"3ab630c5",
      "user_id":"ab1"
   }
]
```

**Query:** 

```
r.table("person")
.group("firstName", "phones[value]")
.filter(r.row('user_id').eq(userId).and(r.row('phones').count().gt(0)))
.run()
```

Above query returns some result but it was not accurate. I want to filter accurately by firstname and phones. Right now it shows some result, but as per my assumption if there is no phone number matches then it matches firstname and group it by firstname, that is actually wrong. So I want to group contacts exactly by phones numbers and firstname. Can anyone give me solution that how to do this?

**Comment by srh** [comment]
I don't think you can group by "phones[value]" and have it do what you want.  That would look for a property name "phones[value]".  You have to group by a function, like `r.row('phones')('value')`.

**Comment by DipakTechifySolutions** [comment]
@srh  Thank you but can you give proper query guideline.. I am new for rethinkdb that is why I am requesting for proper guidelines.

**Comment by srh** [comment]
See the example "How many matches have been played this year by month?" in `https://www.rethinkdb.com/api/javascript/group/`.

**Comment by DipakTechifySolutions** [comment]
I reffered it @srh But still I am not getting that where is my fault. because in  my local server same query has been run and in my stagging servet it does not working. It would be nice that if you point me.

**Comment by riyadhzen** [comment]
Hi
I assumed that you want to group based on ['firstName', 'phones.value'] and based on the last query you provided, you are only interested in the person whose user_id is '3ab630c5-28ed-497e-b0b6-65167ac34195'. This id in your data set is '3ab630c5'
so here is the query
```
r.db('quarterly').table('person').group("firstName", r.row('phones')('value'), {multi:true}).filter(r.row('id').eq('3ab630c5'))('id')
```

If you want to see all the records remove the filter function. I also added ('id') at the end so you can see only the id of the record, if you want to see the whole record just remove ('id) at the end.

Let me know if this solved your issue and thank you for using Rethinkdb (The open-source database for the realtime web)

**Comment by DipakTechifySolutions** [comment]
@riyadhzen  Thank you for your help but still it is not working. Again I am repeating some important points. Yes it was my mistake that I forget to add user_id in document structure. So now I add user_id in my document structure in question.

Again I am explaining that I have a feature to merge contacts. So Above was contact document structure. The document show you in question is only demo purpose but the id in my query is real and exists in database.

Now What is my actual requirement please follow.
I required to show first duplicate contacts based on following combinations. 
- Firstname, lastname : done
- FirstName, phones

Now I required to fulfill following conditions.
- phone number should not be empty
- firstname should not be empty

And I followed below query but still it does not succeed.

```
r.table("person").group(r.row("firstName"), r.row("phones")("value"),{multi:true}).filter(r.and(r.row('user_id').eq('7e0d4bb2-f38a-4f6a-b6da-a45466742d14'), r.row("firstName").ne(""), r.row("phones").count().gt(0)))
```
```
ReqlQueryLogicError: Cannot perform bracket on a sequence of sequences in:
r.table("person").group(r.row("firstName"), r.row("phones")("value"), {"multi": true}).filter(r.row("user_id").eq("7e0d4bb2-f38a-4f6a-b6da-a45466742d14").and(r.row("firstName").ne(""), r.row("phones").count().gt(0)))
```
**pointing to me on the following text : "ow("phones").count().gt(0)"**

I am really thanking to you all guys for help. But I stuck on this point since 2 days.

**Comment by tatsujin1** [comment]
Are you sure you actually want to group by the phone? What would those entries tell you? Even grouping at all, from your question it sounds like your simply trying to get some entries that fulfill some requirements.

What would be lacking if you simply dropped the group? Like so:

`r.table("person").filter(r.row("user_id").eq("7e0d4bb2-f38a-4f6a-b6da-a45466742d14").and(r.row("firstName").ne(""), r.row("phones").count().gt(0)))`

That would return the entries for a specific `user_id` with non-empty `firstName` and `phones`.

Anyway, the error occurs because `r.row("phones")` returns an array, so there is no sub-field `value` in that array (arrays have only numerical indices).

If you really want to group by phone, perhaps something like `r.row("phones").nth(0)("value")` could work. However, I doubt it, as it only uses the first phone number.

**Comment by riyadhzen** [comment]
Hi guys
@tatsujin1 I just want to clarify that the error doesn't come from r.row("phones")("value"). It actually works on my pc and here we are specifying to group by name and phone number. We also set multi to true so that we group the name with each number in the phones array.

@DipakTechifySolutions if you want only one user with given id then use the query provided by @tatsujin1.

Otherwise to follow your spec:
- phone number should not be empty
- firstname should not be empty

use the following query which returns [firstname, phone] combination where firstname is not empty and phone number list is not empty

```
r.db('DB_NAME').table('TABLE_NAME').group("firstName", r.row('phones')('value'), {multi:true}).filter(r.row('firstName').ne('').and(r.row('phones').count().gt(0)))
```

Make sure that you change DB_NAME and TABLE_NAME
(I tested the query and it worked in my pc)

Cheers

**Comment by DipakTechifySolutions** [comment]
@riyadhzen No I think there is an issue with data. Can I show you my database somehow and you may get an idea.
I think. Is it possible to you ?

**Comment by riyadhzen** [comment]
OK

**Comment by riyadhzen** [comment]
OK

**Comment by DipakTechifySolutions** [comment]
.table("person").filter(r.and(r.row("user_id").eq("7e0d4bb2-f38a-4f6a-b6da-a45466742d14"), r.row("firstName").ne(""), r.row("phones").count().gt(0))).group(r.row("phones")("value")) 

I just change sequence of group and filter and it is working.

**Comment by riyadhzen** [comment]
Very good

Don't forget to close this issue.

Cheers
