### ISSUE TITLE
Question - Socketio rethinkdb server monitoring - Good approach

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6418]
What kind of information I could query for statistical purpose? (Without affecting the database too much)

I'm building a dashboard to monitor my servers (with socketio) and I would like to know what I can get without causing too much issues on the database.

Querying table_status every second is a no-no. But, is there a list of events I can monitor?
Would it have a performance impact to check the read/write every 30 seconds?

This isn't only for rethinkdb, I currently have the port status and some basic infos, but it would be super nice to have all information in one place.

I know it is related, in part, to the server spec, but even so, as a guideline, what would be ~~the best~~ a good approach?

**Comment by grandquista** [comment]
Is it possible to have the dashboard detect that it is connected to a RethinkDB cluster? I ask because of this:

> This isn't only for rethinkdb, 

If it can detect that then changefeeds would be the obvious route for performance. I seem to remember a blog post in the last year about a demo dashboard that used changefeeds by one of the regular contributors.

**Comment by grandquista** [comment]
Blog post was from more than a year ago. [https://rethinkdb.com/blog/realtime-cluster-monitoring](https://rethinkdb.com/blog/realtime-cluster-monitoring)

**Comment by Extarys** [comment]
OH thank you very much ! I didn't see this one!
