### ISSUE TITLE
Advice Needed: Using rethink db as main database?

### ISSUE THREAD

**Issue by kiodou** [rethinkdb/rethinkdb#6420]
THIS IS NOT AN ISSUE.

Herd about realtime databases and after extensive research i've decided to use rethink db. I'm using it so my user's can get realtime data, my question is, is this okay to use as a full-time database? Or must I use this on top another db like psql? How is the right way to use a realtime database?

**Comment by thelinuxlich** [comment]
RethinkDB is strongly consistent, so it is adequate as the main database

**Comment by Extarys** [comment]
And it scale **so** well it's magical! And very fast!

**Comment by marshall007** [comment]
Yea, RethinkDB ideal as a primary store. Changefeeds in particular make it much easier to use RethinkDB as your primary store to populate/synchronize secondary stores (Elasticsearch, Postgres, and other databases that don't have a mechanism for observing realtime changes) than the other way around.

Closing since this is just a question, but feel free to continue discussion here.

**Comment by thelinuxlich** [comment]
I wouldn't trust changefeeds to sync databases until there is a way to do it reliably.

**Comment by marshall007** [comment]
@thelinuxlich right, if you need strong guarantees around consistency then you'd have to have something like resumable changefeeds from #3471. There are certainly cases where this is not necessary though.

For example, we have an append-only table where documents are never modified, only added, and a timestamp is recorded as part of the primary key. In this scenario we are able to reliably keep our Elasticsearch index synchronized even when the changefeed process dies because we can easily restart the feed and include documents that were created while the process was being restarted.

Even if you do need to handle actual document updates, it's really just a matter of having enough changefeed listeners to where you're comfortable in terms of reliability (preferably through a RethinkDB proxy node), have all those workers write each change to a redis queue, then process each item off that queue for synchronization.

**Comment by kiodou** [comment]
Thanks for all the info guys.

**Comment by grantcarthew** [comment]
Hi @kiorq. I was researching reconnecting change feeds with `rethinkdb-changefeed-reconnect` and found this post. Thought you may be interested in the job queue I maintain.

https://github.com/grantcarthew/node-rethinkdb-job-queue

**Comment by bearcatsandor** [comment]
Wouldn't a traditional dbms be faster if you don't have the need for updates in realtime, if data changes only occasionally?
