### ISSUE TITLE
slice/limit big difference in round-trip time

### ISSUE THREAD

**Issue by goors** [rethinkdb/rethinkdb#6465]
Hi,

i got `25338` records in my table. When doing `.limit(3)` to get first three records exec time is: `152ms` and when doing  `.slice(25338-3, 25338`) to get three last records exec time is `651ms`(with query on index).

Is this normal and if yes, is there any other way to get last `N` records faster?

**Comment by goors** [comment]
Maybe somehow to make index with last three records but I do not know how to do that.

**Comment by lbguilherme** [comment]
`r.table("aaa").limit(3)` does not give the first three records because `r.table("aaa")` is not ordered. Which elements are returned is kind of undefined. You can do `r.table("aaa").orderBy({index: "id"}).limit(3)` and `r.table("aaa").orderBy({index: r.desc("id")}).limit(3)`. Or use any other index as criteria for your order.

**Comment by neumino** [comment]
`slice(x, x+3)` has to skip the first x elements, that's why it's slower than `slice(0, 3)`

What you want is probably do use a secondary index and paginate based on an doc's id (or whatever index you are using).
