### ISSUE TITLE
Delete Large Documents

### ISSUE THREAD

**Issue by becerriljc** [rethinkdb/rethinkdb#6469]
hi, i need delete millions of rows with filter, Can you help me?

**Comment by lbguilherme** [comment]
If you want to delete almost all the table, the fastest solution is to copy the remaining part to a new table (`r.table("new_table").insert(r.table("old_table").filter(r.not(....)))`), note that it will be much faster if you can use an index. Or else filter will scan the whole huge table. Then drop the table, recreate it, and move back.

Otherwise you are hopeless... just delete it the usual way. Will take some time indeed.

`r.table("table").filter(...).delete()`

**Comment by marshall007** [comment]
As @lbguilherme mentioned, the big thing is to make sure you're using a secondary index rather than a `.filter()`. I'm closing the issue since this is just a question, but feel free to continue discussion.
