### ISSUE TITLE
TTL / Expire Document

### ISSUE THREAD

**Issue by DoppelnullYT** [rethinkdb/rethinkdb#6481]
I'd like to know to which version the TTL / expire document was be postponed (or will it even be implemented?).
Also why it was postponed, because its actually a feature which is requested so often since years and it's gonna be called "a short implementation" o:

**Comment by marshall007** [comment]
The company behind RethinkDB [shut down in September 2016](https://rethinkdb.com/blog/rethinkdb-shutdown/). Since then we have been doing our best to keep the project moving forward as a community-driven, open-source organization. In February 2017 [we joined The Linux Foundation](https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/) and with their support we were able to get back on our feet and ensure we had everything squared away from a licensing/legal perspective.

As such, there has not been much active feature development during that period. That said, we [released v2.3.6 in July](https://rethinkdb.com/blog/2.3.6-release/) and will be releasing v2.4 as soon as we can. Everyone involved contributes on a voluntary basis and we're all busy with our day jobs just like you guys!

As always, we appreciate everyone's feedback, questions, contributions, and community support.

Let's keep the discussion around TTL/document expiration to the original issue #5823.
