### ISSUE TITLE
Java driver is not published since v2.3.3

### ISSUE THREAD

**Issue by cardamo** [rethinkdb/rethinkdb#6497]
The latest published java driver [is 2.3.3](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.rethinkdb%22%20AND%20a%3A%22rethinkdb-driver%22)
But 2.3.5 contains very important fix #6010

**Comment by Hronom** [comment]
Yes, please guys can you update it to the latest version, or RethinkDB is dead?

**Comment by Extarys** [comment]
Wow this is definitely overdue.

**Comment by Kodehawa** [comment]
Please update it, it's necessary.

**Comment by chenzhekl** [comment]
Not just for Java, all official drivers are long overdue.

**Comment by queer** [comment]
Yes please. This lack of updates makes me worry about choosing RethinkDB for projects :(

**Comment by srh** [comment]
I invite and encourage any of you to make an unofficial driver (as a fork or unmodified mirror of the official one) and release it under some name (on Maven, I guess) for 2.3.6.

**Comment by srh** [comment]
I talked to a developer who was around in the last days of RethinkDB.  He's not sure we have the maven keys around for releasing the new version of the driver.  It was on his company laptop, and who knows where else?

So now it's on you to make a release.  Think of it in terms of the 2nd amendment (of the U.S. Constitution), with its reference to a well-regulated militia.  You might ask, who's part of the militia?  The answer is, "everybody".  The militia means "you".  It's "your" responsibility to defend the constitution as a citizen of your country.  Likewise, it's your responsibility to release the Java driver on Maven.  If there's no Java driver released, that's because you didn't release one.  People are happy enough using the unofficial C# driver -- it's of high quality.  So they will be happy with your semi-official Java driver.

Right now, the guy that did a lot of work getting 2.3.6 releases out is busy moving to a new country and adapting to its strange, foreign ways.  In other words, he is no longer part of the militia.  Somebody else will have to step up.  (It's not me: I am busy with things more important to me.)

You have a choice between two future timelines you can live in: One where a Java driver, version 2.3.6, is released for everybody to use, and another where it isn't.  For some reason you all chose to live in the first timeline and are unhappy about it.  If you make your own release of the Java driver, I'm sure you can get a link to it put on the website.  It could gain "official" status.

**Comment by adriantodt** [comment]
Hi hi, hello, an update:
Me and @gabor-boros are working together to get ownership of bintray (Jcenter) and sonatype (Maven Central) packages of the java driver. we'll keep updating this issue with more details as they reply.
also RethinkDB have a official Bintray organization now: https://bintray.com/rethinkdb

**Comment by adriantodt** [comment]
Another update: Bintray approved our ownership request and now we basically have control of the java-driver on jcenter: https://bintray.com/rethinkdb/maven/rethinkdb-driver

@gabor-boros is trying to get in contact with Sonatype and request ownership of the maven central package so we can release the java driver in 2.4

**Comment by gabor-boros** [comment]
Currently we have an opened ticket at Sonatype. They seems to be pretty helpful and we did the required steps to get back the access, once they review the prerequisites, we will get access.

On the other hand, when the database was forked back in 2018 we extracted all the drivers from rethinkdb repo, so the “correct” java driver (which should be developed in the future) is rethinkdb-java. 

Although I’m not a java developer I’m trying to resolve all the issues with the driver coming from extraction, like Makefile references python issues and so on. Once I’m done with that I’ll let you know here.

**Comment by adriantodt** [comment]
Java driver v2.4.0 was released to Maven Central (also known as Sonatype) and JCenter is mirroring it. You guys can update to it. Also this issue can be closed.

**Comment by gabor-boros** [comment]
Dear all,

Hereby I'm closing this issue. The v2.4.0 driver released to sonatype as Adrian wrote! 🎉

Maven
```
<dependency>
  <groupId>com.rethinkdb</groupId>
  <artifactId>rethinkdb-driver</artifactId>
  <version>2.4.0</version>
</dependency>
```

Special thanks to @adriantodt to for making it happen! 🥳
