### ISSUE TITLE
[Question] Email server with rethinkdb

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6501]
I know there is a lot of ressources regarding MongoDB for email storage or email server authentication (IMAP and/or SMTP). But do you know anything related to RethinkDB? My emial provider want to start charging for email so I'm thinking about moving my email needs to my VPS but I love RethinkDB since it's soo easy to work with. So anything that I can do with it instead of MySQL or Mongo I'll do.

On another subject, any good Nodejs mail server by any chance?

Thanks for your inputs.

**Comment by grantcarthew** [comment]
@Extarys Not a complete answer to your question however take a look at the job queue I made: https://www.npmjs.com/package/rethinkdb-job-queue

On the [README](https://www.npmjs.com/package/rethinkdb-job-queue) and the [Tutorial](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Tutorial) page I am using [Nodemailer](https://nodemailer.com/about/) with [MailGun](https://www.mailgun.com/) as examples.

By using a job queue you can make your email resilient to server outages. More on why you would want a job queue is on the [front page of the wiki](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki).

**Comment by Extarys** [comment]
Thanks! I didn't your answer until now, I'm sorry.

So technically I could use this to help me build a dovecot/postfix alternative?
I'm also sorry, I'll over-extend... can I use nodemailer as a replacement of dovecot?

RethinkDB is unfortunately not the mostly used database, it's way easier to fond mongodb plugins :\

**Comment by grantcarthew** [comment]
That's why I made `rethinkdb-job-queue`, to avoid managing yet another database. I am still working on a major web application so I don't know the full footprint yet, however I believe I will need an ElasticDB for full text searching but that should be about it. Two databases, RethinkDB and ElasticSearch.

Docker is making managing the installation of these databases easier. Make a `docker-compose.yml` file with the services in it and away you go.

It is a massive learning curve @Extarys depending on where you are coming from. Have a serious look at MailGun and see if you can foot the cost of offloading SMTP to the cloud.

**Comment by Extarys** [comment]
Thanks for MailGun but the point is for an encrypted or at least hosted alternative to google and microsoft cause I'm tired of those bastard to ask for my phone number and showing me ads. :P

I'll try to keep an eye out on the development of the stuff you make then ;)

**Comment by grantcarthew** [comment]
I am not affiliated with MailGun however they are not MS or Google: http://blog.mailgun.com/mailgun-becomes-an-independent-company/

The reason I suggest using an SMTP provider is due to managing your SMTP IP address on block lists. If you setup your own SMTP server you will also have to monitor and manage your IP being added to block lists. It's not worth the effort. If you read the [Rationale](https://github.com/grantcarthew/node-scalable-blob-store#rationale) on the Blob store I created you will see that I try to avoid cloud providers if possible. I will not try to manage my own SMTP server though.

I could be wrong. Other people probably do.

**Comment by Extarys** [comment]
MailGun looks more for big companies ot send mailling list, I'm trying bring a couple of friends :\ Maybe it's a misunderstanding, or not. But I understand the risk and hard work it involves though. God, spammers make lifes hard on everyone! GRRR.

Rationale..? You are a legend! Keep going

**Comment by grantcarthew** [comment]
Well, in that case if you are hosting your own server, use your ISP as an SMTP server. Just send the mail to the ISPs SMTP server using a package like [SMTP Connection](https://nodemailer.com/extras/smtp-connection/). If you are cloud hosting then [Azure](https://blogs.msdn.microsoft.com/mast/2016/04/04/sending-e-mail-from-azure-compute-resource-to-external-domains/), [Google](https://cloud.google.com/compute/docs/tutorials/sending-mail/), and [Amazon](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html) all have solutions. Again, I would recommend not hosting out going mail yourself.

**Comment by Extarys** [comment]
Thanks for the tips ;)
