### ISSUE TITLE
Secondary Index for Not Equal 

### ISSUE THREAD

**Issue by AaronTrazona** [rethinkdb/rethinkdb#6514]
Its is possible that I can create not equal secondary index?

sample like this query
r.db('test').table('test').filter(e => e('name').ne('John'))

thanks :)

**Comment by srh** [comment]
That wouldn't really make sense because a filter will get you just as good performance unless a large proportion of people have the same name.  If so, you can make a regular secondary index and then query using a union of `.between` queries like so:  `r.table('test').between(r.minval(), 'John', {index: 'name'}).union(r.table('test').between('John', r.maxval(), {index: 'name', leftBound: 'open'}))`

**Comment by srh** [comment]
Closing.  If you want a more convenient way to use existing secondary indexes to perform a not-equals query, I recommend writing a new Reql proposal.  It wouldn't be a new kind of secondary index, but some new command to use them, like, `r.table('test').notEqual('John', {index: 'name'})`.
