### ISSUE TITLE
something might be connecting to the wrong port

### ISSUE THREAD

**Issue by shuoyenl** [rethinkdb/rethinkdb#6537]
Hi,
Our rethinkdb cluster has been reporting a lot of warnings like
"Received invalid clustering header from [::ffff:{IP of the host which posts the warning}]:{port}, closing connection -- something might be connecting to the wrong port."

We rely on nomad to deploy the rethinkdb (in docker container) instances using the same image so all instances run the same version. It's not the case where the containers are relaunched either (that is, it kept reporting the warnings while all instances in the cluster were running.) 

The DB seems to function properly -- that is, api returns properly, admin console can be accessed, and the cluster is formed and data are in sync. And since the containers are not relaunched, the same set of host ports are mapped to the same set of container ports (for api, intra, and admin) all the time.

So what else could cause something to connect to a wrong port?

Thanks.

**Comment by srh** [comment]
The most likely cause of this is that a client is trying to connect to a clustering port.  It's easy to mix up 28015 and 29015.

**Comment by shuoyenl** [comment]
Hi,
Thanks for the quick response. But like I mentioned in the original post, the rethinkdb is running in a container and the container ports are mapped to the host ports which are dynamically assigned in our case. While the access to the api and admin are all based on the SRV records, I don't think it's likely to mix them up with the intra port.
Would it report the error when it gets a tcp connection to the intra port as a health check?
Thanks.

**Comment by gabor-boros** [comment]
@shuoyenl If I understand correctly, the port is mapped on the host OS and dynamically assigned. As I get from the latest comment, something probably calls the port meant for clustering as a "health check". IF that's the case, then sure, it can easily happen that you see the warnings because of that.

Since the clustering port meant for clustering only and not for serve health check requests or driver connections, I'm closing this issue. If the situation is/was different, feel free to ping me on this issue and I'll reopen.
