### ISSUE TITLE
.shift() & .unshift() - arrange documents in the table by offset (reordering)

### ISSUE THREAD

**Issue by PassTheMayo** [rethinkdb/rethinkdb#6549]
This kinda adds on to my previous suggestion, called `.randomify()`. This will shift all documents in a table (but no removing any, like JavaScript does to an array). For example, say I have a table with 25 documents which are perfectly sorted within a table without any use of `.orderBy()`. If I wanted to move the first 5 documents to the back of the table, then I could use `.shift(5)`. This will take the first 5 documents within the table and move it to the very back. I could also use it the other way. If I wanted to take the last 5 documents in a table and move it to the front, I could use `.unshift(5)`. I believe that this can be useful to some people. Sorry if I didn't really think this through, I kinda just thought of it as I was browsing GitHub.

EDIT: This actually moves the documents around in a table, and not like orderBy or something like that.

**Comment by srh** [comment]
Well thank you for the idea.  Documents don't have any defined order in the table they're in, and queries don't return a consistent order.  If you do a query like `r.table('foo')`, the order of the results is defined by what cluster nodes respond first, or hypothetically (but IIRC not in practice) which blocks finish loading from disk first.

You could use a field on the documents holding some number, a ranking that is used to sort them.  Then find some way to safely increase the number on some of those documents so that they're at the bottom of the ranking.  It's not that easy because RethinkDB doesn't have transactions.

**Comment by PassTheMayo** [comment]
Oh, ok. I understand now. Thanks for the help!
