### ISSUE TITLE
"The `rethinkdb` database is special, you can't grant permissions on it"

### ISSUE THREAD

**Issue by 01000101** [rethinkdb/rethinkdb#6553]
After reading the existing issue (https://github.com/rethinkdb/rethinkdb/issues/5692), I think a fundamental mistake was made in dismissing permission controls on the RethinkDB database and subsequent tables. Currently, from what I can tell and have read, only the "special" admin user can perform actions on the RethinkDB table but that user cannot assign / grant permissions to any other ("non-special") users on that database. This, to an extent, defeats the purpose of having user permissions in the first place by taking away the ability for an admin to grant permissions, even on system tables, and, instead, left the judgement of security up to the developers and not the database admins. 

I'll give a use case - 

- A RethinkDB database/cluster is configured in an environment with a modicum of security controls and one of those controls is to limit service accounts to only perform the actions they must (don't give admin rights to something that doesn't need it). The admin needs to set up a service account that only needs to read the "stats" table and feed that data elsewhere. This cannot be accomplished right now without giving the lowest service access anything besides super-admin rights. 

My proposal is to level the permissions field where there's no "special" tables, according to permission sets, and leave the application-level security to the admins. If an admin wants to create another true superuser account, they should be able to. If they want to create a user that only can read from a special database table, they should be able to.

**Comment by srh** [comment]
It sounds reasonable to me, or it might be reasonable only for certain tables like the stats table.

**Comment by 01000101** [comment]
Thanks! Though, my point was to not have such caveats. Allow permissions to be assigned by the admins, not the developers. There's nothing so dangerous and secret in the "system" tables to warrant a removal of permission assignments by the super admin(s).

**Comment by srh** [comment]
You're right, I guess.  Maybe it should only be allowed on a table-by-table basis, not the entire system database.  (In other words, `r.db('rethinkdb').grant(...)` be disallowed.)  The reason being, what if new tables get added that the admin didn't previously consider?

Also, there is an audit logging feature in rethinkdb-enterprise (still locked up in a private repo) that's worth thinking about.  (That repo should be made public.  I just realized that I, because I'm a rethinkdb org member, am capable of making a new Github repo and pushing a copy of the branches in rethinkdb-enterprise.  Or just pushing its unique branches to the main repo.  I don't know why I didn't think of that before.  I'll do that soon, like, 48-hours-ish.)  I don't know how rethinkdb permissions operate with audit logging.  (I don't know anything about audit logging except that it's there.)

It could be reasonable to grant admin privileges over the entire system db to another user, if they can't mess with the audit logging.

**Comment by florimondmanca** [comment]
Hi, I believe this can be closed since as of 2.4.0 it is now possible to grant permissions on the `rethinkdb` database, correct?

**Comment by srh** [comment]
@florimondmanca You're right, this can be closed.  Thank you.
