### ISSUE TITLE
Control schedule of disk compaction jobs?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rethinkdb/rethinkdb#6597]
We use rethinkdb in production. Once per day at 7pm, it looks like rethinkdb does disk compaction. Is this normal, does compaction always happen at the same time every day? Can this be adjusted? Would be nice to do it at our lowest hour of usage (5am or something) instead of right at peak usage, 7pm.

During compaction, some queries slow down to nearly halt (over 10s) that usually take 100ms or less, so it impacts production. This is even with readMode=outdated. Is that expected?

**Comment by srh** [comment]
That's undesirable, and if it's once per day, that's a result of increased activity at that time.  There isn't a once a day timer, for example.

Most disk compaction is an ongoing process, except for something called "LBA" GC, which, unfortunately, isn't.  The disk GC process has been modified since the last time I looked at it, so I can't make specific claims how it works.  For example, maybe this change: 3fab787247f makes your queries nearly halt.  Part of the problem might be that multiple tables all independently decide (at a time of high load) they need to perform more GC at the same time.

One possible mitigation is to run the srh-extra release: https://github.com/srh/rethinkdb/releases/tag/v2.3.6-srh-extra .  It might lower write iops considerably (if you have soft durability and configure it) and that means GC won't be such a pain.  Somebody's running it in production: https://github.com/rethinkdb/rethinkdb/pull/6392#issuecomment-359041543 .  If there isn't a package for your platform on the release page, let me know -- I'll add it.

If that doesn't address the issue for you, some improvements could surely be made to fix the problems with GC.  There's currently no mechanism to schedule GC at a different time, but this is probably not something that can be addressed that way, unless it's "LBA" GC.

**Comment by GeoffreyPlitt** [comment]
Excellent, thanks so much for the info!

It turns out our issue was due to our backup jobs, not disk compaction.

Closing
