### ISSUE TITLE
https://rethinkdb.com/faq/ has AGPLv3 as the license.

### ISSUE THREAD

**Issue by hardkrash** [rethinkdb/rethinkdb#6600]
The website FAQ is out of date for the latest release, this caused some consternation about my ability to use this project.

**Comment by srh** [comment]
If you download the 2.3.6 release you can see clearly Apache 2 in the license text.

**Comment by hardkrash** [comment]
A lawyer or other non-developer might read the FAQ on the webpage and make a decision before downloading the source file...

**Comment by LewisDeacon** [comment]
I agree with @hardkrash, I am currently facing this exact issue, blogposts state that its ASLv2 but the website FAQ references AGPLv3. Thanks for mentioning that if you download the source for the 2.3.6 tag the license is there because if you just download the windows installer from the website all you get is an exe

**Comment by navbruce** [comment]
Yup, software looks interesting, but the FAQ (and this issue) put an end to any further investigation. Not remotely interested in trying to convince anyone that all RethinkDB code is clean of AGPL viral cling.

**Comment by htetlinnoo1999** [comment]
@thelinuxlich  can you help on this  ? https://github.com/rethinkdb/rethinkdb/issues/6600

**Comment by gabor-boros** [comment]
So I checked the things mentioned here:

The license information was changed within this commit: https://github.com/rethinkdb/docs/commit/a3a5ac3ced9fbeef077c705730bb4da9604c0463#diff-85407e3661620fcf26e210e0789752ab. The only issue is that the website was not released until somewhat July of 2019.

Hereby, I'm closing this issue since it is resolved for a while now.
