### ISSUE TITLE
Table scans dirty the cache and cause RAM spikes?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rethinkdb/rethinkdb#6608]
Every time we do a backup, we use table scans. When we do this, RAM spikes, probably because the entire set of rows, for the entire set of tables, is causing cache-misses and the cache is being thrashed. RAM spikes, and often causes SWAP for us, which destroys performance and sometimes makes replicas think each other are offline-- big problem in production.

Is there any good reason you'd ever *want* tablescans to go through the cache? I can't think of a reason to. This seems like a bug.

This will affect anyone who ever runs rethinkdb in production and backs up their DB regularly, which is probably anybody who takes it seriously. This is something I wish I'd known before using rethinkdb in production.

Happy to fix it if someone can help point me in the right direction.

**Comment by GeoffreyPlitt** [comment]
@srh If you can point me in the right direction, I can try to make a fix

**Comment by GeoffreyPlitt** [comment]
Maybe an option to run() to not change cache for a particular query?

**Comment by srh** [comment]
In arc/buffer_cache is where the caching logic lies. You could change the eviction algorithm from whatever it is to add a new category of pages that is "wants to be evicted."  They'd be the first pages to get evicted instead of picking something else.  If the eviction strategy is plain LRU you could do it by fudging their usage time stamp.  You can then specify that a table scan query, or user specified query, mark newly loaded pages as such.

Your memory problems might instead be the result of the batch size option being too large. You might want to look at that query option first, try picking a smaller value.

**Comment by GeoffreyPlitt** [comment]
Where's the batch size option? https://rethinkdb.com/docs/backup/

**Comment by srh** [comment]
It's on .run(). https://rethinkdb.com/api/javascript/run/

**Comment by GeoffreyPlitt** [comment]
Oh. I think Compose does backups with the ```rethinkdb dump ...``` command. I don't see batch size on there. Do you think it would be easy to add the option?

**Comment by srh** [comment]
The command invokes a Python program _dump.py so it should be pretty easy.

**Comment by GeoffreyPlitt** [comment]
@srh Just to double-check: if the issue is batch size, the appropriate adjustment would be lowering maxBatchBytes, correct? Is that the parameter you think would best address this? Maybe decrease it to 1/2 or 1/4 of the default value?

**Comment by srh** [comment]
Yes.
