### ISSUE TITLE
Is rethinkdb dead? nobody solve 1k+ issues? where is rethinkdb js client source code?

### ISSUE THREAD

**Issue by anlexN** [rethinkdb/rethinkdb#6618]

**Comment by v3ss0n** [comment]
@srh  and @AtnNn  still maintain it from time to time , but i don't know the future or roadmap.
You can contribute in code and donation .

**Comment by anlexN** [comment]
@v3ss0n , @srh , @AtnNn , i love rethinkdb very much. rethinkdb code don't be update almost 1 year. what a pity! you say you join linux fundation, linux fundation don't help you maintain rethinkdb? or say , can you teach me rethinkdb code learning? i am willing to be your contributor!

**Comment by v3ss0n** [comment]
no , it was mearly a month ago : https://github.com/rethinkdb/rethinkdb/branches

**Comment by v3ss0n** [comment]
@anlexN  please check https://rethinkdb.slack.com  in channel  engineering. where the core developers hanging out. They can give you guides.
To date , no db reaches rethinkdb in realtime-ness and sharding.

**Comment by anlexN** [comment]
i can't enter rethinkdb slack

**Comment by srh** [comment]
The JS client source code is in drivers/javascript.

**Comment by matteo-bombelli** [comment]
Hello, should this issue be closed?

IMHO: please make a repo just for the js driver, maybe with a dist folder and the file you publish to npm

thank you!

**Comment by nigel-dewar** [comment]
I agree with you Chris, I feel the same way. It very much has a skeleton feeling. Ive never participated in an open source project because Ive never had the drive, i do feel like reaching out and assisting becuase 1k+ issues and rising doesnt make it feel very alive.

Rethinkdb is significant. Even now whilst ive had a chance to use mongo, firebase, redis, couchdb and of course i come from a sql world too, i feel rethinkdb is still 'special', and its worth keeping it alive.

I think it has a future but it only if folks do so, right now its like it barely has a pulse.

Ill reach out to the core team on slack and see what can be done.

**Comment by nigel-dewar** [comment]
Looking at a good chunk of these issues, alot of them need to be closed as they are not issues, they are folks asking questions, which is fine of course but they need to be redirected to some active support channel on gitter or stackexchange.

**Comment by srh** [comment]
Any feature request or performance complaint is an open issue, that's what inflates the issue count.

Right now the status is that 2.4 is ready to be released. Potentially the latest commit could be tagged 2.4 (except maybe for stuff like release notes, and it's possible I'm forgetting about stuff like documentation of write hook features, I haven't looked at the issue because I'm on my phone). I cleared out every known show-stopper blocking it around Christmas.

2.5 is not ready yet. It will be made ready (unless I get hit by a bus) because I want the delayed flush interval feature to be released, someone paid for it with the side effect in mind that it would be in an official release someday.  And I worked on that and other features, as have other contributors, with the same intention.

There are some problems. Currently the invite page for the slack channel is down.  Nobody with the ability to fix that has done so.

Another problem is that many private repos (like the enterprise repo and website source) have not been officially anointed Apache 2-licensed, as far as I know, so right now I'm treating it like proprietary Linux Foundation IP.  If not for this, there would be a public www repo so the website could take pull requests, and formerly enterprise-only features would be able to get put in 2.5.

It would also be nice if the website and docs page could actually get updated after pull requests get accepted. But since I don't have access to that, and nobody who has access is doing it, that's not happening.

I'm also taking people's word when they say they've agreed with the CLA in a pull request. I don't have any verification that they've put in the info like the CLA web page wants. That info is not necessary except to CYA, a checkbox in the PR suffices for me.

**Comment by v3ss0n** [comment]
@srh  can we re-do website our own ? with seperated domain , and working slack? 
I can help on that.

**Comment by srh** [comment]
Yeah, I think it'd be awesome to have that.  Please make it.

**Comment by simplygreatwork** [comment]
Stop whining so much. RethinkDB is amazing. Use an older stable version if you feel like it. Or go use LevelDB.

**Comment by srh** [comment]
Closing, this is a question.

BTW I know one person, not myself, is working on a performance improvement.
