### ISSUE TITLE
Handle undefined value in an object

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#663]
`ryexley on IRC had trouble replicating our nodejs chat application.
He got this error 

```
[ERROR] 22:47:13 RqlDriverError
{ name: 'RqlDriverError',
  msg: 'Unknown datum value `undefined`, did you forget a `return`?',
  message: 'Unknown datum value `undefined`, did you forget a `return`?' 
}
```

While this error make a lot of sense when the user forget a return in a lamda function for a filter for example, here it was failing for this query:

```
r.db("config.database.name").table("users").insert( {
    name: data.name,
    email: data.email,
    message: data.message
} )
```

And the reason why, was because one of the field had the value `undefined`.
We should catch undefined values in `r.expr()` and just ignore the key if undefined is returned.

Assigning to @wmrowan, tagging as 1.5

**Comment by thelinuxlich** [comment]
I would like this behavior, but first #4428 should be fixed

**Comment by riteshsangwan** [comment]
@neumino From the above discussion there is no clear conclusion as to how `undefined` values will be handled not just in insert operation but also for `filter` operation.

1. I have below code that fails when either `username` or `email` is `undefined`.

```
const users = yield User.filter(r.row('username').eq(username).or(r.row('email').eq(email)));
```

This will throw error
```
Cannot convert `undefined` with r.expr() in:\nr.table("users").filter(r.row("username").eq(undefined).or(r.row("email").eq(undefined)))
```

Logically since I have a users table where `email` or `username` cannot be `null/undefined` I would expect this query to return `0` results. This is what mongo returns since many of the developers actively work on mongo we would expect this to work the same way.

**What I would like is for this query to not throw error and return `0` results.**

I have been reading the docs and is not able to find the solution. How to get this done in rethink world.

2. Consider below code

```
const users = yield User.filter({ username: undefined });
```

This will return all the users and completely ignore `undefined` value for username. This is logically not correct since ideally this should not return any results because there are no records where `username` is `undefined`

**Additional Info**

`User` is a `thinky` model

```
const User = thinky.createModel('users', {
    id: type.string().uuid(4),
    fullName: type.string().required(),
    username: type.string().required(),
    email: type.string().email().required(),
    password: type.string().required(),
    firstName: type.string().alphanum().allowNull(true),
    lastName: type.string().alphanum().allowNull(true),
    bio: type.string().allowNull(true),
    // the timestamp this resource is created
    createdAt: type.number().integer().required(),
    // the timestamp this resource was last updated
    updatedAt: type.number().integer().required(),
  }, {
    enforce_extra: 'remove',
    enforce_type: 'strict',
  });
```
