### ISSUE TITLE
Fork the database and start afresh?

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#6659]
As a RethinkDB user since 2014, I find it quite frustrating that we have a freshly new release(2.4) frozen for almost a year because of inertia. I tried contacting ex-developers without success for some time. I'm one of those that still believe on the technology, a year and a half has passed since the startup failed and still I don't see any database in the market fitting the same niche of RethinkDB.
Right now the communication is awful, we have a slack channel advertised as official which new users can't enter, so the community is scattered between Slack, Discord, IRC, Gitter and Google Groups. So I'm sending this message everywhere: if we get a bunch of volunteers, we could fork the database, create a new organization and devise a plan to release the 2.4 version as soon as possible. There is already work done in the future 2.5 version and I'm paying a developer to add data compression to Rethink, we could setup a OpenCollective for other developers interested in advancing the database future. What do you think?

**Comment by thelinuxlich** [comment]
Good luck contacting the mantainers, it is radio silence since forever

**Comment by ChrisTalman** [comment]
The state of the project is certainly disappointing, but I agree with @oliverjanik's note of caution. While we'd all like to see the project flourish, breaking it apart into a separate project is a last resort.

The project seems to provide a way to contact the 'leadership team' [at the end of this page](https://www.rethinkdb.com/contribute/). Perhaps contacting them and letting them know that the community is considering a split might motivate them to become more active and communicative, and actually get things moving again. Have you considered this, @thelinuxlich?

**Comment by thelinuxlich** [comment]
Not only considered but tried contacting them and no answer. Let me stress this again: we have a major new version ready to release and nothing has been done to ship it for a year! I think the state of things beg for last resort actions.

**Comment by chovy** [comment]
just fork it already so we can start using it!

**Comment by ChrisTalman** [comment]
@thelinuxlich Wow, that's such a shame.

Frankly, I'm quite baffled how an open source foundation could purchase the rights to a project and apparently do nothing with it.

I'm also a little surprised that most of those who founded and were a big part the Rethink company seem to have stepped away from the project entirely and not looked back. I know they have new jobs and projects, but I'd have thought they'd still want the project to move forward and succeed. Perhaps, after so many years of working on this project, they just want to step away and explore new things. Whatever the reasons, the project has been left in an unfortunate state.

**Comment by sagivf** [comment]
@ChrisTalman while I agree it's totally lagit to step away, I think it's not so cool to get people to invest in something and then just walk away without even setting up some sort of minimal departure plan. Some people like mike did try with the foundation, but moving forward I don't understand why there can't be a little bit of communication on how and who has what resources and what can or can't be done.

**Comment by thelinuxlich** [comment]
Hey, listen!

We have a Spectrum channel to discuss about the new fork, RebirthDB. If you are interested in collaborate with us, check it out: https://spectrum.chat/rebirthdb

**Comment by robertjpayne** [comment]
The fact no leadership member has replied on this thread is pretty much proof that RethinkDB as it stands is dead as a doornail unless they drastically change the leadership and get people involved like @thelinuxlich that actively WANT to maintain it and will take the time to onboard new community members to work on development and issue triaging.

It's absolutely a shame the leadership team can't even come to terms of bringing onboard a few active users because at this point the project is dead without that.

**Comment by thelinuxlich** [comment]
Let's break the mold!

**Comment by chovy** [comment]
Its been forked! http://github.com/rebirthdb

**Comment by ChrisTalman** [comment]
Has, or will, the fork project outline its strategic vision? Releasing 2.4 will obviously be its first goal, but what about beyond this? Does the team behind the fork have the capability to release big features like joins in changefeeds, index intersections, and improvements to the web interface? There are a fair number of big features which have long been discussed and would really improve the viability, capability, and performance of the database, but they're often complex problems which require a lot of work.

**Comment by thelinuxlich** [comment]
Chris, we have some features scheduled for 2.5, but concerning big changes like changefeed joins, there is no free lunch, someone will have to sponsor the development, as I'm doing for the data compression feature.

**Comment by thelinuxlich** [comment]
Chris, we have some features scheduled for 2.5, but concerning big changes like changefeed joins, there is no free lunch, someone will have to sponsor the development, as I'm doing for the data compression feature.

**Comment by lbguilherme** [comment]
What about setting up something like https://salt.bountysource.com/ for regular maintenance funding?

**Comment by thelinuxlich** [comment]
We will do it and have it linked on the new web site

**Comment by Nable80** [comment]
> and still I don't see any database in the market fitting the same niche of RethinkDB.

Postgres + LISTEN/NOTIFY (or one of those logical decoding plugins) seems to be a good alternative. It supports arrays, JSON/BSON (and even indexes for sub-columns), real-time update notifications, replication, etc. The source code of existing applications has to be heavily modified for migration but could you bring any more arguments against such setup, please?

**Comment by thelinuxlich** [comment]
I didn't even think about changefeeds, since I despise their actual implementation in RethinkDB because of the unreliability, but since you mentioned, LISTEN/NOTIFY is not very good to scale.
Also, have you ever worked with Postgres JSON/BSON? It may be orders of magnitude better perf-wise than RethinkDB at the moment, but it is awful to query, doesn't compare to ReQL by any chance.
Sharding and replicating in RethinkDB is builtin and totally a breeze, in a way no database in the market can beat.

**Comment by thelinuxlich** [comment]
@ChrisTalman The problems with changefeed:

- Changefeeds in RethinkDB aren't restartable, if the connection closes, you have to devise your own logic with timestamps to get the updates in the window of disconnection, which can be very unreliable in many cases. 
- Each open changefeed introduces a noticeable performance hit to the tables observed. 
- Without the notion of "subscriber groups", each proxy gets each changefeed update.
- Changefeeds are limited to a small subset of the ReQL power.

**Comment by ChrisTalman** [comment]
@thelinuxlich Thanks for the insight. I was aware of the ReQL issue, but not the others.

To be honest, the shortcomings of changefeeds have always surprised me. The number one headline of Rethink seems to have been that it's 'for the realtime Web'. And yet, you can't join or use subqueries in changefeeds, when so much data is reasonably relational. I'd have thought that the Rethink team would have had a big focus on making most of ReQL available in changefeeds, and yet it's notably limited.

**Comment by FilipeRamalho** [comment]
Why fork, if you could just tackle on https://github.com/rethinkdb/rethinkdb/milestone/120 and https://github.com/rethinkdb/docs/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4. If both list are finished then I guess the maintainers will release 2.4.0. 


See https://github.com/rethinkdb/rethinkdb/issues/6266 for more on that.

**Comment by thelinuxlich** [comment]
@FilipeRamalho please take a look at our spectrum community and you will see our release plan. The reasons for the fork are described above.

**Comment by oliverjanik** [comment]
To be honest I never considered RethinkDB for changefeeds, It was a marketing gimmick. If you have that requirement why not use an actual message broker?

What I always needed was a solid, fast, reliable, distributed and flexible document store. 

It falls short when it comes to performance optimisation for me at the moment.

**Comment by thelinuxlich** [comment]
@oliverjanik don't know if you are still using RethinkDB, I have a good experience optimizing query performance, if you have any problems, feel free to post a question at the spectrum group

**Comment by pittAndrews** [comment]
@thelinuxlich, I dont want to see rethinkdb die. Am using it heavily. Somebody should take over and my vote is on you.

**Comment by pittAndrews** [comment]
@thelinuxlich I noticed the current python driver for rethinkdb doesnt integrate well with tornado's latest version

**Comment by ChrisTalman** [comment]
@oliverjanik 
> To be honest I never considered RethinkDB for changefeeds, It was a marketing gimmick. If you have that requirement why not use an actual message broker?

Perhaps this is a misunderstanding of message brokers on my part, but, from my understanding, changefeeds complement, rather than replace, message brokers.

Theoretically, the notion of a database informing you of changes to data, which you can then act upon, seems like a nice idea to me. For a lot of projects, the database is essentially the single source of truth for your project's data. Thus, if anyone's going to inform you of an event, why not the database itself?

If you have an API relaying events to clients in realtime, you'll still have a message broker managing the distribution of events to clients. It's just that, the source of your events would be changefeeds, rather than dispatching events manually everywhere you change data.

One alternative is to dispatch events manually everywhere you change data, but that's laborious and opens up the chance for omissions and mistakes. Listening directly to the database seems like a cleaner and safer way of doing things.

Interestingly, Rethink isn't the only project to see some value in this, with cloud services in particular offering extensive ways to listen to the database, like in the case of [DynamoDB Streams](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) and [Firebase database triggers](https://firebase.google.com/docs/functions/database-events). MongoDB has also introduced ['change streams'](https://www.mongodb.com/blog/post/an-introduction-to-change-streams).

If there's something I'm missing, please let me know. But, as I say, the basic notion of listening to a database, and then acting upon those changes, seems like a nice idea to me. It's just a shame that changefeeds in Rethink are limited in their current form.

**Comment by thelinuxlich** [comment]
@ChrisTalman if someday we fix those issues I mentioned, RethinkDB could act as Kafka replacement, a eventsourcing database, a reliable job queue, all without too much headache.

**Comment by tbolier** [comment]
Let's go for it!

**Comment by lockevn** [comment]
I'm still considering Rethink for my service. Sad to see the inactive and silent situation. I'm rather hop on Rebirth than watching this.

**Comment by jwr** [comment]
I'll pitch in with a brief comment about changefeeds, since I think this is the most widely misunderstood feature of RethinkDB.

Changefeeds are why I use RethinkDB. There is no other database out there that implements them. Comparisons to other databases that can provide you with a copy of their update log completely miss the point. Changefeeds in RethinkDB can be started transactionally: get initial state, then all updates, including those that happened while we were getting the initial state. The use case for this is: get user data (`getAll` using a secondary index of `uid` for example) when the user logs in, then feed changes. If you think this can easily be replaced with what MongoDB provides, with message brokers, or queues, I respectfully suggest that you haven't considered all the implications and constraints.

I think part of the misunderstanding is because of how changefeeds were marketed: yeah, leaderboards are a cool demo example, but the main strength is in the "boring" real-world apps, where you simply get all of the user's data.

I've used changefeeds to build PartsBox.io and I still can't find any alternative to RethinkDB. I don't know how else I could provide real-time updates to all users without a serious backend engineering project.

As for performance issues, I haven't noticed any and I'm quite happy with the performance. Sure, if you run Google, you should worry — but I suspect most of us do not build applications with bazillions of hits per second, and RethinkDB gets the job done *now*.

I am worried about RethinkDB's future, especially given how the changefeeds are misunderstood and treated as a "marketing gimmick". They are anything but.

**Comment by sagivf** [comment]
@jwr thanks for the info, it's always good the hear RethinkDB stories, especially successful ones.
Changefeeds are certainly a great feature, I use them as a message broker for events. However they don't scale for the classic use case of changefeed per user, which is what was suppose to be there big advantage. From what I have gathered you don't need more the a few thousands to start running into issues - have a look at this https://www.youtube.com/watch?v=HiQgQ88AdYo.
changefeed disconnection is also an issue.

I hope chagefeeds get more love in the future, but for now we need to focus on moving the basic db forward and some real certainty into it's future. You are welcome to come help over at https://spectrum.chat/rebirthdb

**Comment by jwr** [comment]
Well, I am quite sensitive to the expression "X doesn't scale", so I will offer some thoughts:

What does "changefeeds don't scale" actually mean? Don't scale for whom? For what kinds of workloads? Under which conditions? In what topology? With what kinds of queries?

If you consider changefeeds and webapps, you would normally use them for processing updates for users that are currently connected. That's typically a fairly small number of changefeeds. In my case, I'm actually opening *four* changefeeds per user session and things work great with hundreds of simultaneous user sessions. My testing also shows that adding servers will let me scale nicely, if I need to. So yes, changefeeds "do scale" for me.

Also, many (if not most!) applications will never need to "scale". Let's be honest, if you're building the next Google, you shouldn't be storing your data in RethinkDB anyway. This whole "doesn't scale" FUD is a red herring.

The YouTube presentation you mentioned is a good example of FUD. The speaker shows a slide with RethinkDB proxies (note that using proxies isn't mandatory) and says that every proxy receives every write to the database. That is not true. And even it if were true, it doesn't prove anything except that in *some* applications RethinkDB might not make sense. If you're doing real-time processing on a huge data stream (write-heavy workloads), I would indeed do some very careful performance testing. But that's just one application, and to take a real-world example, my application is not write-heavy — saying "changefeeds don't scale" is not true in this case. In my opinion the speaker has a very superficial knowledge of RethinkDB and has never actually tested the scalability that he's talking about.

Engineering is about compromises. Not everything needs to "scale" under all conditions. You always pick a compromise and in my opinion RethinkDB is a very good compromise for a wide range of applications. Those applications are often not the most fashionable ones at programming conferences, but they are the apps that actually make money.

So why am I writing all this? Two reasons:

1. I find the "doesn't scale" rhetoric annoying without supporting facts and precise statements: things "don't scale" under specific workloads in specific conditions, not generally. My car also "doesn't scale" and yet I find it very useful for my workloads.

2. I wanted to point out that changefeeds are the main reason why I'm using RethinkDB at all, so disregarding them as a "marketing gimmick" is like throwing the baby out with the bathwater. RethinkDB's advantages for me are: changefeeds, relatively easy deployment, and document model (a distant third). The negatives are: dockerized deployment issues, limitations of JSON, slow data conversions because of JSON, ReQL annoyances. Neglect or discard changefeeds, and I'd much rather put a layer on top of FoundationDB for a different set of compromises.

Just a data point from a real-world production user of RethinkDB.

**Comment by pittAndrews** [comment]
+1

**Comment by ChrisTalman** [comment]
@jwr Indeed.

> The speaker shows a slide with RethinkDB proxies (note that using proxies isn't mandatory) and says that every proxy receives every write to the database.

I think there's some confusion over this. To start with, proxies aren't well documented, including their relation with changefeeds. However, @danielmewes has provided a really nice explanation in #962, [here](https://github.com/rethinkdb/docs/issues/962#issuecomment-194006164).

I suppose it can be read in either way: perhaps a proxy receives every write, even if none of its changefeeds are interested in the write, or perhaps it only receives writes it's interested in.

Personally, I get the sense that it's the former, due to this sentence: '*The proxy will receive one message from the database servers for every write to the table 'test', and will check locally which changefeeds are affected by this change.*' It'd certainly be nice if it were the latter instead.

Either way, as you suggest, even if this is a limitation, it's probably not a limitation for *most projects*. I'd imagine it'd only be an issue for projects with truly massive scale or massive write frequency (i.e. a chat app). For most other projects, I'd imagine that proxies could simply be given more resources on their machine to handle greater scale, if that ever becomes any sort of issue.

**Comment by sagivf** [comment]
@jwr your points are mostly valid, but I did not just write "does not scale", I wrote "don't scale for the classic use case of changefeed per user". I'm sorry but although there are some companies that can thrive with just hundreds of concurrent user, most companies need to sale at least a few 100 of thousands. Plus this needs to be transparent to users for them to make the correct trade off for them.

**Comment by oliverjanik** [comment]
@jwr I'm happy the changefeeds work for you. That is great. 

For all my use-cases they're at the wrong abstraction level. All the events are produced in the API layer so I control when and how they're fired at which point I can just push them into Kafka or whatever. 

Why would I go through a round-trip to RethinkDB (i.e.) store something and the listen for it later?

If you have one system storing data and another system listening for changes, well that's using the database as interface and is usually a very bad idea.

Hence my lack of enthusiasm for changefeeds.

My top priorities would be performance, performance and efficient memory usage.

**Comment by ChrisTalman** [comment]
@oliverjanik I think I provided a [theoretical rationale earlier in this issue](https://github.com/rethinkdb/rethinkdb/issues/6659#issuecomment-390663394). The gist of it is that the database is typically the single source of truth for the data of a project, so it seems like a reasonable source of events about that data.

Concerning the round-trip to RethinkDB, I don't think much more is going on compared with having your API inform some alternative event dispatcher. You're going to send a write query to Rethink anyway. The only difference is that the source of the event is either the API or the database.

**Comment by oliverjanik** [comment]
That scenario is way to simplistic, typically I talk to other APIs few databases/ caches. Single source of truth not necessarily true. Not to mention for any kind of serious throughput on stream processing I actually don't want any writes to be left behind.

**Comment by thelinuxlich** [comment]
@oliverjanik but with the right issues fixed, it could become a poor man's Kafka!

**Comment by oliverjanik** [comment]
@thelinuxlich Absolutely!

**Comment by luxmidutt** [comment]
I also suggest to fork.. if later the original developers shows interest we can always merge back . One year is too long to go without activity. I don’t expect things to get better. What is surprising is that original developers not responding to people showing interest to contribute.

Thanks,
Luxmi

**Comment by thelinuxlich** [comment]
@luxmidutt we are in the process of releasing a new version, see the activity on https://spectrum.chat/rebirthdb

**Comment by maldn** [comment]
![screenshot_20180705-014412](https://user-images.githubusercontent.com/354077/42296376-7247a15e-7ff5-11e8-991d-91f080eee2d0.png)

**Comment by Glathrop** [comment]
<img width="814" alt="screen shot 2019-03-08 at 11 44 10 am" src="https://user-images.githubusercontent.com/7409273/54045547-89d7d000-4197-11e9-8b9a-bc96f8629b3a.png">

**Comment by thelinuxlich** [comment]
Thank you, I totally forgot this issue. In the meantime we merged back to the original organization and the discussion goes on here: https://spectrum.chat/rethinkdb
