### ISSUE TITLE
How to reuse serialized query in future queries

### ISSUE THREAD

**Issue by mtharrison** [rethinkdb/rethinkdb#6694]
I have a situation where I need to write a sequence of large objects to a table. I need to do this 1000s of times. In profiling the JS client I see I'm spending a lot of time in `MakeObject.build()` . This is where the object is serialized. As I'm reusing the same query every time is there a way I can cache the serialized query and reuse it in future queries?

i.e. can I write something like `connection.runRaw([ 54, [ [ 15, [Array] ] ] ])` if you get my meaning. Or would I be better just writing my own driver?

**Comment by bchavez** [comment]
Hi Matt,

AFAIK, the [**bchavez/C#**](https://github.com/bchavez/RethinkDb.Driver) driver is the only driver that "natively" supports serializing ReQL expressions to strings and then "hydrating" them back to life for execution. You can read more about the **C#** driver's query serialization feature here:

https://github.com/bchavez/RethinkDb.Driver/wiki/Extra-C%23-Driver-Features#serializing-reql-expressions

You will save on the cost of JSON query serialization by using this feature; however, there are some things you should be aware of:

1.  The implementation details of "query serialization" involve some string manipulation of the serialized query before the serialized result is given to you. This is necessary to avoid variable conflicts that could occur before and after serialization of lambda ReQL expressions. The driver implementation makes sure that a `row => row.expr` before serialization doesn't conflict with any variable `row => row.expr` after serialization. And that's really important; otherwise, you could get random "one off" queries that won't work. This is why "hydration" is necessary.

    If you don't use `row => row.expr` lambdas (like for insert queries), then the serialized ReQL query you get back won't require much "hydration".

2. If your 1000s of objects have a wide varying dynamic schema, you're going to have one hell-of-a time trying to get inserts to work. Especially if your root documents have deeply nested dynamically structured objects and types. Perhaps, prepping your objects ahead of time to make them fit into a stricter schema could help.

    The more flat and stricter schema you have for your 1000s of objects, the better off you'll be, the more a string like: `[ 54, [ [ 15, [Array], 35, [field1, field2, field3] ] ] ]` for replacing fields will work.

3. If your documents have a loose schema and contain dynamically nested time or binary types in them, you'll need to make sure you do the appropriate [`$reql_type$` pseudo type conversions](https://github.com/bchavez/RethinkDb.Driver/wiki/Extra-C%23-Driver-Features#poco-support).

4. ReQL injection attacks. I suppose when you do field replacement, you should be careful and make sure those fields don't have ReQL in them. I'm sure someone smart out there could find a way to abuse it.

This post is turning out longer than I intended, but you get the idea: when you play with fire :fire: take some precautions to avoid getting burned. :fire_engine: :sunglasses:

Hope that helps.

Thanks,
Brian

:black_circle: :dizzy: ***["Black magic... bla-a-a-ack... black magic..."](https://www.youtube.com/watch?v=3SnlsTtUZK0)***
