### ISSUE TITLE
Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by nathanburgess** [rethinkdb/rethinkdb#6738]
When trying to connect to RethinkDB through Node's REPL, I have no issue. However, when running the exact same code in my React app I get an invalid URL error. 

```js
r.connect({}, (error, conn) => {
    if (error) throw error
})
```

If I toss a breakpoint in `net.js`, I can see that `url` is set to `http://localhost:28015undefinedajax/reql/`, which is obviously incorrect. If I pass in a `pathname` with `connect`, I can get the URL to be correct, but then I run into a new error.

**Comment by srh** [comment]
Weird.  What platform is this app running on?

**Comment by nathanburgess** [comment]
Mac and NodeJS

Thanks,
Nathan Burgess

**Comment by piotr-placzek** [comment]
Hello there!
This is still a problem.
Will you do something about it?
Maybe say us how this URI should be, and we will temporary fix it localy inside our projects...

**Comment by srh** [comment]
I think the problem has something to do with the fact that the JavaScript driver is designed to be used in the web browser, in the admin UI, and simulate connections over HTTP.  Maybe there is detection code for this, instead of a private API.

I'm looking in the code right now here: https://github.com/rethinkdb/rethinkdb/blob/v2.3.x/drivers/javascript/net.coffee#L1435

 and see this line:

```
        # Next we construct an XHR with the path to the reql query
        # endpoint on the http server.
        url = "#{protocol}://#{@host}:#{@port}#{host.pathname}ajax/reql/"
```

The thing is, this line is in the constructor commented

```
    # #### HttpConnection constructor method
    #
    # This method sets up the XMLHttpRequest object that all
    # requests/responses will be sent and received on. Unlike the
    # TcpConnection, the HTTP server only allows one outstanding query
    # at a time per connection. Because of this, currently the web ui
    # creates many different connections.
```

And apparently this is the method used to determine whether a TcpConnection should be used:

```
    # #### TcpConnection isAvailable method
    #
    # The TcpConnection should never be used by the webui, so we have
    # an extra method here that decides whether it's available. This
    # is called by the constructor, but also by the `.connect`
    # function which uses it to decide what kind of connection to
    # create.
    @isAvailable: () -> !(process.browser)
```

The `connect` function has logic here: https://github.com/rethinkdb/rethinkdb/blob/v2.3.x/drivers/javascript/net.coffee#L1655

that determines whether to try to create a Tcp or Http connection, when in the browser.

I think this is really messed up.  The admin UI should just use a private API to create HttpConnections, without this tcp/http availability detection logic.

I'm not familiar with Electron (that's what you're using, right?) but [this link](https://stackoverflow.com/questions/41674063/is-it-possible-to-create-a-tcp-client-with-electron) seems to imply that a node connection would work.

So the quickest way to fix this yourself is to change the definition of TcpConnection.isAvailable to return true.

**Comment by srh** [comment]
@piotr-placzek I just made a fix, and uploaded the built js driver at https://github.com/srh/rethinkdb/releases/tag/v2.3.7.srh.jsdriver in the attached file js_driver.tgz.

I'm not familiar with JavaScript packaging, so let me know if that's not usable for you.

If you could try it out in Electron and verify that it works, it would be much appreciated, and then we could get this fix in 2.4.

**Comment by nookbros** [comment]
@srh I am also having this problem trying to connect to my local rethinkdb using a local react app.

How can I get this fix?

**Comment by srh** [comment]
Use the link in my post.

**Comment by Protean-Man** [comment]
Does it work? Updating through Putty into Raspberry Pi?

**Comment by prawesshh** [comment]
I got the same issue there was "/" missing in my case. Do check your endpoint properly

**Comment by iAbhinav** [comment]
Same issue on MacOS and node/angular 4. Issue is also there using docker in mac.

But then I use node cli.. it somehow works.
