### ISSUE TITLE
docker image update

### ISSUE THREAD

**Issue by madagon** [rethinkdb/rethinkdb#6772]
Hi, I'm thrilled to see RethinkDB has recently resumed the active development. We are planning to use rethink under a heavy loaded production API for serving feeds data.
Has anyone had such experience? Please share your insights.

BTW, I'd be happy to have the official docker image updated with the latest version. (2.3.7 if I'm not mistaken)

Thank you so much in advance.

**Comment by gabor-boros** [comment]
Hello @madagon,

> BTW, I'd be happy to have the official docker image updated with the latest version. (2.3.7 if I'm not mistaken)

I have some things on my plate for November, but Docker update is on it for sure! I'll update this thread when we pushed the latest docker image.

Stay tuned 🙏

**Comment by PaulSearcy** [comment]
Just wanted to let you know @madagon  that there is a deprecation notice on dockerhub
https://hub.docker.com/_/rethinkdb

I've used rethinkdb in the past and thinking about using it again for logs.

Read an issue where you guys mentioned that you were resurrecting rethinkDB #6747.

Thought I should point out that people might erroneously think RethinkDB is officially deprecated due to this notice.

**Comment by gabor-boros** [comment]
@PaulSearcy thank you so much for letting us know! I’ll contact docker (again) to retrieve the credentials for that account so we will be able to push out new images 🥳 by new releases I mean 2.3.7 and 2.4.0

**Comment by gabor-boros** [comment]
Hey all,
Here is the PR for 2.3.7: https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/46/
When The PR is merged I'll open a PR to Docker to update their site. 😊 🎉

**Comment by gabor-boros** [comment]
Hello @PaulSearcy and @madagon :wave:,
A short update here. We just released 2.3.7 with bionic on hub.docker.com :tada: :rocket: more good things will come later! Stay in the loop :hugging_face:

Since we released 2.3.7 on docker hub I’m closing this issue, but we will update docker images for 2.4.x as well later

**Comment by daveisfera** [comment]
Thanks for getting this done and all of your hard work to get the project going again! Are there plans to make the centos bases available in Docker Hub as well?

**Comment by gabor-boros** [comment]
@daveisfera would you like to have a Centos8 image? Feel free to open a new issue for that and I can do that 🤓
