### ISSUE TITLE
Removing update checker

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb#6791]
## Background
The update checker is only causing some cost for us, both in maintenance and credits, and occasionally crashes when parsing the response. Keeping in mind the things as mentioned earlier and that no one in the last ~3 years uses this feature, we would like to remove it.

## Let's have a discussion
I want to ask you to raise your hand and let us know if you disagree with removing the update checker. Since we can not do voting synchronously, we will use lazy consensus, which means that we will keep this issue for three days, and if no concerns emerged, we close it.

**Comment by yaneony** [comment]
If rethinkdb will be distributed over some package managers, like apt, then there is no purpose in maintaining additional layer for checking.

**Comment by gabor-boros** [comment]
@yaneony you are right. Just as now, RethinkDB is distributed through apt, yum etc so this is already covered

**Comment by srh** [comment]
This has been implemented in branch https://github.com/srh/rethinkdb/tree/srh/24x/no_update_check

**Comment by gabor-boros** [comment]
@srh I think we are good to remove the update checker and close this issue. If anyone has concerns please reopen

**Comment by srh** [comment]
PR #6795

**Comment by sholladay** [comment]
I only saw this in the release notes, after the release was already done...

I don't understand the rationale here. I have absolutely used the update checker and I always appreciated when the admin UI would tell me about a new version. I much prefer seeing it there than email notifications.

The problem with the last three years years hasn't been the update checker. It's that there were no updates to check for because RethinkDB was an inactive project.

**Comment by gabor-boros** [comment]
FYI @srh

**Comment by srh** [comment]
The update server still needs to be updated, so that 2.3.x users get a notification.  @gabor-boros 

I suggested removing the update checker from the rethinkdb server for a few reasons.  One is that updating the update server is another thing to do every release, which adds friction to the release process, which I would recommend making as low-effort as possible.  Another reason is that RethinkDB had some bugs from the periodic update checker -- one user had a crash after 2 years of update checks piled up enough failures to exhibit an extproc process bug.  I think that got fixed.  Another bug is that servers were occasionally crashing on misparsed update server responses.  A third reason is that it's a moving part and call out to the external network that just doesn't need to happen.

These don't really apply to the admin UI, except for the first.

I don't think the update server needs to exist in the complicated form that it does.  It's producing dynamic responses, calculating server-side whether you need an update or not, based on the user's version and adding some mysterious jquery callback wrapper.  Why isn't it just a static file?  It could be located at `https://download.rethinkdb.com/latest_version`, with contents 2.3.6, or now 2.4.0.

**Comment by gabor-boros** [comment]
@srh thank you for pointing this out. I’ll update the update server today or latest tomorrow morning

**Comment by gabor-boros** [comment]
@sholladay The PR for putting back the update notification: https://github.com/rethinkdb/rethinkdb/pull/6879
