### ISSUE TITLE
Injecting more than 10K of documents - ReqlRuntimeError: Connection is closed in

### ISSUE THREAD

**Issue by lautiamkok** [rethinkdb/rethinkdb#6798]
When I try to insert more than 10K rows of data/ documents, I get this error:

```
ReqlRuntimeError: Connection is closed in:
r.table("user").insert({...})
```
I use forEach to loop the data from another API and then inject them into the rethinkdb database:

  ```
data.forEach(async (element, index) => {
    var document = {
      ...
    }
    var result = await r.table('user')
      .insert(document, {returnChanges: true})
      .run(connection)
  })
```

What should I do instead?

**Comment by srh** [comment]
Probably you're creating a ton of concurrent queries and the server is booting you.  Either rate limit your active queries with a semaphore, or, probably, the better solution is to use the fact that `insert` can insert multiple documents at once, if you pass an array.   Break your set of documents into chunks of size N (where N is sufficiently large but not too large) and pass each chunk to `insert` in sequence, instead of performing concurrent queries.  This still leaves some room to be even more clever/complicated if you want to improve mass insertion performance.
