### ISSUE TITLE
r.sample operation on a sorted data makes it's unsorted

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [rethinkdb/rethinkdb#6817]
When I ran sample(n) on a sorted time series data resulting data are unsorted.
Can someone please explain the reason for this.

**Comment by lbguilherme** [comment]
`sequence.sample(n)` takes n random items of a sequence. By random, it means uniformly distributed among the sequence, the only guarantee is that the same item won't be returned twice. The returned elements aren't sorted by anything, by definition.

**Comment by srh** [comment]
It's because the fastest or simplest algorithms for sampling the data returns it unsorted, except in some circumstances.

**Comment by srh** [comment]
You can see the algorithm in `src/rdb_protocol/terms/random.cc`.  Sadly, it doesn't take advantage of the situation where the entire data set is already an array loaded in memory.  The way it works is that it iterates through all the elements, maintaining a set of n uniformly random elements (not stored in the array with uniformly random order) out of those seen so far.  Each new element, it considers whether it should put that element into that set, replacing a randomly selected prior element.

Then it actually randomly shuffles the set at the end.  The reason is probably that otherwise, the first n elements of the sequence could only appear in specific locations, but the subsequent elements are uniformly randomly positioned in the output.  And that would be kind of grotesque.  The algorithm could have been tweaked so the set was uniformly randomly ordered by construction, but it doesn't matter.

I don't know a way to construct the set in order without a log(n) overhead (n being the size of the sample) unless you know the number of elements up front.
