### ISSUE TITLE
Rethindb v2.4 for centos 6?

### ISSUE THREAD

**Issue by motniemtin** [rethinkdb/rethinkdb#6834]
Currently I can't find the latest version 2.4 for centos 6, do you still support centos 6?

**Comment by srh** [comment]
It could probably (almost certainly) be built for CentOS 6.

**Comment by motniemtin** [comment]
![build](https://user-images.githubusercontent.com/23047848/75001345-b1e93d80-5493-11ea-8dea-e9b1dd361668.png)
not now :(

**Comment by srh** [comment]
Right, there is no 2.4 release for CentOS 6.  There could be.

If you look at https://github.com/srh/rethinkdb-package-builder/ , there is a system set up, that uses Docker, for building the release packages.  All that needs to be done is to add centos6 to that (and then I'd be happy to use it to build the packages).

There will be some difficulties because CentOS 6's compilers and glibc are old, and RethinkDB uses C++11.  See https://edwards.sdsu.edu/research/c11-on-centos-6/ or maybe https://forums.centos.org/viewtopic.php?t=68077 .

**Comment by gabor-boros** [comment]
As a side note, we agreed on to support LTS and not deprecated OS versions, which does not mean that it can not be built but we would like to take care of those issues which are affecting the supported platforms instead of those which are only occurs on deprecated OS versions.

Again, it does not mean that you can not open a PR to the package builder or the rethinkdb-dockerfiles repo. 😇

**Comment by srh** [comment]
CentOS 6 EOL is Nov. 2020.

**Comment by srh** [comment]
With the latest changes at https://github.com/srh/rethinkdb-package-builder/ , I have managed to build a CentOS 6 package.

**Comment by gabor-boros** [comment]
Ohh, I overlooked this. Sorry

**Comment by srh** [comment]
Oh no, I never implemented it in the package builder, because I thought it was just going to be a bunch of work.  But then I found the instructions at https://rethinkdb.com/docs/install/centos/ .  It only required changing a URL for one of the keys.

**Comment by gabor-boros** [comment]
Then I’ll build the image and upload it if you have no concerns @srh

**Comment by gabor-boros** [comment]
Ok, I forgot this issue, but uploaded the package to the [new download server](https://rethinkdb.com/blog/download-server-changes):
<img width="535" alt="Screenshot 2020-08-07 at 13 35 53" src="https://user-images.githubusercontent.com/19173947/89641857-ed958980-d8b2-11ea-919d-c8e965e646c8.png">
