### ISSUE TITLE
Support Direct Connect to DB without Driver

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6846]
Instead of going through a driver which requires some work to write is it possible to add support for direct connection to the DB server instance using common fast serialisation formats like:

- [Fast Binary Encoding (FBE)](https://chronoxor.github.io/FastBinaryEncoding/)
- [Simple Binary Encoding (SBE)](https://real-logic.github.io/simple-binary-encoding/)
- [gRPC](https://grpc.io/)
- [MessagePack](https://msgpack.org/)
- [Concise Binary Object Representation (CBOR)](http://cbor.io/)

Essentially this bypass the need of the client-side driver, The data retuned would be directly usable by the program without much pre-processing. This can have metadata which gives row ID, and status: new, update, deleted along with the data.

The query also can be sent as a user-friendly encoded object with all data to execute without client-side pre-processing. 

All query and DB features should be available without the driver. But alternative wrapper driver can be written to build the query and messages resembling the current drivers.

Also where possible zero-copy.

**Comment by srh** [comment]
The client protocol originally used protocol buffers.  It switched to the JSON-wrapped thing it uses now because the protocol buffer libraries available for some subset of the JavaScript, Python, and Ruby clients were too slow.  (I think they weren't native, or they weren't very good.)

This would still be nice to have, for driver developers.  Another option would be a text-based query language.  (And I'd have some things to say about parameterized queries, streaming writes, and huge blobs, if it came to that.)

**Comment by sirinath** [comment]
Text-based query language would be very much easier to use. Also, [GraphQL](https://graphql.org/) inspired binary query system may also be great to have if this can be faster.

Any way writing a driver for RethinkDB is too much work, so some way to bypass drivers would be great.

**Comment by srh** [comment]
I'm closing.  Cleaning up issues. If any user has a pain point with client query serialization performance it's still possible to do.
