### ISSUE TITLE
Rethinkdb 2.4.0 Failed to build on Arch Linux

### ISSUE THREAD

**Issue by sain801028** [rethinkdb/rethinkdb#6850]
Full error log: ./build/external/v8_3.30.33.16-patched_install.log
make[1]:  [mk/support/build.mk:149: build/external/v8_3.30.33.16-patched/lib/libv8.a] Error 1
make:  [Makefile:53: make] Error 2

![Screenshot_2020-03-29_06-06-08](https://user-images.githubusercontent.com/17377422/77850005-adecc180-719d-11ea-90f3-2375e0de44e1.png)

![Screenshot_2020-03-29_06-07-42](https://user-images.githubusercontent.com/17377422/77850006-b0e7b200-719d-11ea-9e8d-518020d020c7.png)

**Comment by srh** [comment]
Try adding `CXX=clang++` to the configure line.

**Comment by srh** [comment]
I have made a PR to update the build instructions: https://github.com/rethinkdb/docs/pull/1267

**Comment by srh** [comment]
Also, I've added Arch Linux to https://github.com/srh/rethinkdb-package-builder so precise build instructions can also be observed there (or you can use that to run a build for Arch Linux).

**Comment by sain801028** [comment]
I use Clang ++ and it works, thanks for the help

**Comment by zool2001** [comment]
Just to add if it helps anyone in the future, I ran into the exact same error point sain801028 notes above, and WAS using Clang++ (11.0.1) on a RazPi 4+ with Debian (11) bullseye.  I realized the issue was my system was set up for Python 3 (3.9.2).  I installed Python 2.7, replace /usr/bin/python --> python3 with /usr/bin/python --> python2 - fixed same issue.

**Comment by srh** [comment]
On v2.4.x, with the changes made for the upcoming release v2.4.2, you should now be able to use Python 3, with your choice of g++ or clang++, on Bullseye.  But Python 2 should also work.
