### ISSUE TITLE
PrestoDB Connector support

### ISSUE THREAD

**Issue by smeadows-abb** [rethinkdb/rethinkdb#6891]
We use Presto extensive for number of data source and interested integrating rethinkDB. Do you have future plans for integration with Presto SQL engine or do you have work around for integration?

**Comment by yaneony** [comment]
Rethink DB and Presto DB are very different databases, since one is NoSQL and the other SQL database. Right now there is no integration, and i see none even in the nearest feature since there are much important thing to do right now. If you really need and integration, you can do one with JS/JAVA/RUBY or other driver by yourself. It all depends on what kind of integration you are looking for.

**Comment by srh** [comment]
There are no such plans.
