### ISSUE TITLE
Your founder is a clown

### ISSUE THREAD

**Issue by zsperske** [rethinkdb/rethinkdb#6929]
https://twitter.com/spakhm/status/1333514691533025284

**Comment by bobsbarrels** [comment]
+1

Toxic culture warning.

**Comment by clovergaze** [comment]
This is unrelated, please use more appropriate channels to express your dissatisfaction with certain peoples opinions.. he tweeted, so how about commenting there .. 🙂

**Comment by gusbelmar** [comment]
I agree

**Comment by v3ss0n** [comment]
He is no longer part of rethinkdb since many years ago,even tho RethinkDB  as a startup company failed , he gave us the opensource realtime database that is still unrivaled till today.
Back in the days of RethinkDB he did really good job at managing his tech team and engineering the product. His tech decisions are sound and very piratical.
He have the right to sound his own opinions , this has nothing to do with the software and its users. 
This is opensource software and  not american politics so please  keep your voice to where it is related.

**Comment by pluma** [comment]
>Back in the days of RethinkDB he did really good job at managing his tech team and engineering the product.

He literally cheated on his spouse with a subordinate and then blamed his failure to monetize RethinkDB on being too districted by "hot" women at work.

> This is opensource software and not american politics so please keep your voice to where it is related.

Feel like I need to point out @v3ss0n is not a maintainer because this sentence is a perfect example of signaling agreement with that person while painting those expressing their disagreement as being "the real problem". Sexism is only an "american politics" problem to people outside America because it helps us non-Americans pretend we don't have sexism because it looks different when you look at it from a distance through social media. You're in Myanmar. Have you heard of the saying about throwing stones in a glass house? https://en.wikipedia.org/wiki/Women%27s_rights_in_Myanmar

**Comment by LarsFronius** [comment]
I've looked into this issue and don't think it reflects the matter accurately.
Did you mean to say the founder of rethinkdb is a misogynistic asshole? Please update the title to reflect reality.
Thanks 💅

**Comment by v3ss0n** [comment]
>Sexism is only an "american politics" problem to people outside America because it helps us non-Americans pretend we don't have sexism because it looks different when you look at it from a distance through social media
Here are the users of Opensource product he created 6 years ago.

**Comment by v3ss0n** [comment]
> He literally cheated on his spouse with a subordinate and then blamed his failure to monetize RethinkDB on being too districted by "hot" women at work.

Wow , how do you know?  Nice stalking! I never knew about that . His tweet was not about that either  . But again that is his personal problems.I don't care ,this is a place for users and contributors of rethinkdb .That is not his twitter , direct your anger there.

> Feel like I need to point out @v3ss0n is not a maintainer

I never claimed i was a maintainer but i am user of rethinkdb since 2014 where he is very active , replies to everyone ,  nice toward contributors and transparent about their day to day software development operation . The whole rethinkdb development team is active and fund back then. i had gave suggestions on  making rethindkb realtime changefeeds for python and help tested it . I admit not much of a contributor.


> because this sentence is a perfect example of signaling agreement with that person while painting those expressing their disagreement as being "the real problem".Sexism is only an "american politics" problem to people outside America because it helps us non-Americans pretend we don't have sexism because it looks different when you look at it from a distance through social media. 

I never said agree or not , I never said a word about sexism , what the fuck are you talking about? I just want you to keep your twitter garbage at twitter .

> You're in Myanmar. Have you heard of the saying about throwing stones in a glass house? https://en.wikipedia.org/wiki/Women%27s_rights_in_Myanmar

Nice doxxing again , since you are directly stalking me , i think i have all the rights to call you a Creep. A weirdo , and check again - Myanmar's Leader is a Nobel Pace Literate Women , we have full Woman Rights here . Sexism is so rare here . Citing wikipedia and thinking without even been in a country for a second is stupidest thing ever.  Everyone loves her and call her Mother Su . Get your facts right before calling someone hypocrite . 

Ah i guess understand why you are stalking , and bashing users of RethinkDB , making ex founder and product together look bad  - i did checked back your profile and found that you are a founder of Competing  database product called ArangoDB , that is not how you earn new users great great maintainer of Arango . I guess you are jealous afterall.

**Comment by pluma** [comment]
He literally wrote about this, you can easily find his musings about the incident online.

Also, I'm not sure what you're smoking but I'm not an employee let alone a founder of ArangoDB. I work for them as a contractor the same way I work for many other companies.

RethinkDB is a fine project. They're just unfortunate to have Slava accosted l associated with it.

**Comment by v3ss0n** [comment]
I don't care really, nothing much can do to me , i am not popular or anything.

**Comment by srh** [comment]
@pluma Your conduct here is unacceptable.

**Comment by pluma** [comment]
@srh If you want, I can delete my comments.

**Comment by srh** [comment]
Your statement here:

> He literally cheated on his spouse with a subordinate and then blamed his failure to monetize RethinkDB on being too districted by "hot" women at work.

is false and defamatory.

Your treatment of @v3ss0n goes beyond the pale.

**Comment by pluma** [comment]
@srh Out of respect for the RethinkDB project and to avoid any further derailment, I've deleted both of my replies to @v3ss0n. I think my statements are a good faith summary of what Slava has said about the incident in question on public record but I don't think this is the right place or way to have this discussion and I'm not the right person to make these points.

**Comment by v3ss0n** [comment]
thanks a lot @srh 
removed my text regarding arango .

**Comment by bobsbarrels** [comment]
> This is unrelated, please use more appropriate channels to express your dissatisfaction with certain peoples opinions.. he tweeted, so how about commenting there .. slightly_smiling_face

Because attitudes like his/this will ultimately destroy Open Source. Bigotry and toxic, destructive prejudice like he's demonstrating and actively trying to inculcate in his culture and community are accounted for at all levels, one way or another.

You guys deserve to know. His disgusting taint is on you, like it or not.

It *will* push good contributors away from your project, you know there are some exceptionally talented female DB engineers out there. You'll just never hear about it, and your project will be worse for it.

**Comment by clovergaze** [comment]
@bobsbarrels 

> Because attitudes like his/this will ultimately destroy Open Source. Bigotry and toxic, destructive prejudice like he's demonstrating and actively trying to inculcate in his culture and community are accounted for at all levels, one way or another.

This actually underlines the point I was stating when I said that this topic is unrelated. This is not the right channel to discuss the validity of someone's personal opinion or the future of Open Source software.

> You guys deserve to know. His disgusting taint is on you, like it or not.

You fail to differentiate between the founder of the company that originally developed RethinkDB and the current RethinkDB project (this one here). RethinkDB is part of The Linux Foundation and does no longer belong to Slava Akhmechet. No one here is tainted by what someone else says or does.. everyone is free to express his or her own opinions. 

> It *will* push good contributors away from your project, you know there are some exceptionally talented female DB engineers out there. You'll just never hear about it, and your project will be worse for it.

Yes of course, if these contributors also lack the ability to differentiate that statement might be true.

Again.. no one here is debating the capabilities of men and women, because this would be inappropriate in this place. Why don't you fight that out in the debate club of your choice.. how about Twitter, where he actually expressed his opinions.. 🙂

**Comment by srh** [comment]
Slava's a great guy and it does the project good to be associated with his level of integrity.

It's the Nice Guys you gotta watch out for.

**Comment by v3ss0n** [comment]
@bobsbarrels 
> Because attitudes like his/this will ultimately destroy Open Source. Bigotry and toxic, destructive prejudice like he's demonstrating and actively trying to inculcate in his culture and community are accounted for at all levels, one way or another.

Opensource software do not favor any race , gender or political idea , or do not care about your identity. 
If he is destroying RethinkDB's opensource project or not nice to users of rethinkdb , I will vote to promptly disavow him.
Stop with your delusions . 

> You guys deserve to know. His disgusting taint is on you, like it or not.

Let me remind you again, he is not part of rethinkdb , even if he want to be back , I will welcome warmly back , his technical lead and decisions are Sound  and he is a smart guy. Thats all I care.

> It will push good contributors away from your project, you know there are some exceptionally talented female DB engineers out there. You'll just never hear about it, and your project will be worse for it.

Stop with your FUD and scare tactics , that only works on bots or people who cannot think . Lets see tthe most important opensource project : Linux . If  contributors care about his opinions , nobody would be contributing Linux . If Linus Tovalds had to accept all the bad patches or reject all good patches because of "political correctness"  and Linux will be the worst OS of all time.
