### ISSUE TITLE
Is rethinkdb still dead?

### ISSUE THREAD

**Issue by manyopensource** [rethinkdb/rethinkdb#6973]
Just checking before going with a different database.

**Comment by v3ss0n** [comment]
its undead.

**Comment by manyopensource** [comment]
@v3ss0n walking dead?

**Comment by icnahom** [comment]
> Just checking before going with a different database.

I'm curious to know what other database you are considering to use. I can't find a nice RethinkDB alternative that's completely free easy to use.

**Comment by manyopensource** [comment]
@icnahom MongoDB, JaguarDB, GridDB

**Comment by beenotung** [comment]
@manyopensource does the alternatives natively support live query, or you don't need this feature?

**Comment by manyopensource** [comment]
@beenotung Right now I don't need the feature, but I would like to have it. AFAIK only MongoDB supports the "live query".

**Comment by srh** [comment]
I'm going to close this in the interest of censorship and stifling free speech.

Generally, when people say they're looking to move off of RethinkDB, I agree with them that it's a good idea.  I wouldn't recommend starting a new project on RethinkDB, if it's designed to last a long time, because you face a lot of risk.
