### ISSUE TITLE
RethinkDB high CPU load

### ISSUE THREAD

**Issue by thaodt** [rethinkdb/rethinkdb#6976]
Hi team, before I'm asking here, I tried to search the similar questions & looking for solutions on google.
But it seems that I cannot find the right solution for this case. Therefore, i need your helps.

First, my RethinkDB dedicated server setup below:
```
OS version: CentOS Linux 7
RethinkDB version: rethinkdb 2.4.1 (GCC 4.8.5)
Memery: 32 GB
CPU: 8
```
Using python rethinkdb driver to connect from my app. (using asyncio mode)
At the high traffic, reading records can be 300K ~ 500K record / sec, or over.

And this time CPU is almost 100% load.

I can show my sample to query / insert with rethinkdb:
```
async def user_exists(self, phone_number):
    await self.reconnect()
    info = []
    try:
        cursor = await r.db('Customer').table("ClientInfo") \
            .filter(lambda user: r.and_(user['phone_number'] == phone_number,
                                    user['expired_at'].in_timezone('+00:00') >= r.now())) \
            .run(self._conn, time_format="native")
        async for document in cursor:
            info.append(document)
    except ReqlOpFailedError as err:
        logger.warning(f"DB Error: {err}")
    return info
```

Do we have any suggestions / solutions to fix this case?

p/s: I'm using FastAPI. And for startup & shutdown event, I added some code to handle connect & close conn.
```
@app.on_event("startup")
async def startup_event():
    logger.info("Starting up...")
    await r_conn.setup_db()


@app.on_event("shutdown")
async def shutdown_event():
    logger.info("Shutting down...")
    await r_conn.close_connection()
```

**Comment by Thiploll** [comment]
Hey,

I don't fully understand this coding language but maybe try using an index on the row you are filtering.
My guess is your storage is SSD? If not, you know what to do.
Additionally, you can consider clustering multiple servers. I have about 8 of these servers in a cluster to read between 500k-1mil/second and write 20k-40k/second 24/7. This is probably way overkill for what I'm doing, but it nicely absorbers the extra load if my users start going a little crazy.

Feel free to refer to the following benchmark article to make a rough guess (guess because there are many other factors to consider) how many servers you need: https://rethinkdb.com/docs/2-1-5-performance-report/

**Comment by thaodt** [comment]
> Hey,
> 
> I don't fully understand this coding language but maybe try using an index on the row you are filtering.
> My guess is your storage is SSD? If not, you know what to do.
> Additionally, you can consider clustering multiple servers. I have about 8 of these servers in a cluster to read between 500k-1mil/second and write 20k-40k/second 24/7. This is probably way overkill for what I'm doing, but it nicely absorbers the extra load if my users start going a little crazy.
> 
> Feel free to refer to the following benchmark article to make a rough guess (guess because there are many other factors to consider) how many servers you need: https://rethinkdb.com/docs/2-1-5-performance-report/

thank for ur suggestion. Our system is upgraded, this issue was resolved.
