### ISSUE TITLE
Cannot install/build 2.4.1 on Debian 11 (Bullseye)

### ISSUE THREAD

**Issue by dettus** [rethinkdb/rethinkdb#6989]
I like RethinkDB.
I really really do.

However, I am having trouble using it, after I updated my machine to Debian 11 Bullseye.

1. There is no repository for it. Using the buster repository ends in an unresolvable libprotobuf17 dependency
2. Downloading the sources breaks in datum.cc, because of 2 reasons:
    a. include "boost/detail/endian.hpp" should be include "boost/endian.hpp"
    b. BOOST_LITTLE_ENDIAN needs to be defined.
Generally, there are A LOT of warnings when this file compiles.

The build process is still running on my machine, I am not sure if I will be able to see  it working.

**Comment by iwkse** [comment]
Were you successful to compile it?
I've fixed the errors and it builds on Debian 11, check here:

https://github.com/iwkse/rethinkdb/tree/2.4.1

**Comment by dettus** [comment]
To be honest: I have not tried it again. Since RethinkDB is important to my project, i downgraded the Server to Debian 10.

**Comment by srh** [comment]
@dettus This ticket has been added as a mandatory item to #6975 for the next release.

Right now I'm working on #6979, which doesn't seem to affect this ticket, but this ticket's next on my list after that.

**Comment by srh** [comment]
@iwkse I'm ignoring your tree for now because it commits `build/external`, and Github won't show anything past the first 3000 files edited, and I'm too lazy to check it out locally.  It might be useful to me later.

In any case, because #6979 has had the admin UI removed from v2.4.x, **the v2.4.x branch now builds on bullseye.**

I do want the admin UI generation branch (explaiened in #6979) to also work on Bullseye, so I'll probably need to get back to this at some point.  That will be _after_ all package dependencies are updated to the latest versions -- which is something on the "RethinkDB next release list" TODO.

So I'm leaving this ticket open.

**Comment by iwkse** [comment]
@srh thanks a lot for it. Yes I did that to have a fast quick way to get the package build, I was sure it's not the best way.

**Comment by srh** [comment]
#7021 gets Bullseye package generation working.

https://github.com/srh/rethinkdb-package-builder now supports bullseye.  Example: you could run

```
sudo ./setup.rb -c 5fba33644 --packages --copy-pkgs --distro bullseye
```

and copy the packages out of the artifacts/ folder.

----

We still need admin UI generation to be tested and working.

**Comment by srh** [comment]
Admin UI generation is tested and working on Bullseye.

(This is in the srh/old_admin branch; see #6979.)

Closing.
