### ISSUE TITLE
Is any one still using RethinkDB in production

### ISSUE THREAD

**Issue by nikhilrayaprolu** [rethinkdb/rethinkdb#7026]
I am currently planning to extend an [open-source project](https://github.com/withspectrum/spectrum/) built using RethinkDB as its database and deploy the application for a non-profit K12 Education use case. But I am worried to know that RethinkDB has no good support and wanted to know what major issues I might face if I use it in production.

Also how scalable is the change feed of rethinkDB?

Should I instead migrate the database to some other database that's more stable like MongoDB?

is anyone still using RethinkDB in production?

**Comment by lsabi** [comment]
This is not an issue related to the db itself and is an open question about the usage. Please use the [official Slack](https://join.slack.com/t/rethinkdb/shared_invite/enQtNzAxOTUzNTk1NzMzLWY5ZTA0OTNmMWJiOWFmOGVhNTUxZjQzODQyZjIzNjgzZjdjZDFjNDg1NDY3MjFhYmNhOTY1MDVkNDgzMWZiZWM) for discussing such things.

That being said, yes, there are people using it in production. A lot depends on your use case and by what you mean with "scalable" and "stable". A lot of the times nosql databases are being used because of the simplicity to develop something in place of a relational database.

Also, I see nowhere that it uses rethinkdb as it's data storage. Changing the entire data layer just to migrate to a different database, is debatable to me, especially considering that it is an open source project. Again, this should be discussed on the slack app.
