### ISSUE TITLE
Can you tell me about code of your horizontal scroll bar in table view ?

### ISSUE THREAD

**Issue by camdiep2** [rethinkdb/rethinkdb#7096]
Hello,

I really love your horizontal scroll in table view, when height of table is long than height of my monitor , the horizontal scroll bar is displayed at the bottom of my monitor. really good solution to view data. Can you tell me which code, components you use to archive this ? Thank you.

![scroll-bar](https://user-images.githubusercontent.com/80382054/197472445-12ed52fc-041d-4cfa-90fa-a5bebe9d7129.PNG)

**Comment by srh** [comment]
Specifically rethinkdb-old-admin has that code, and I presume now the new admin client in rethinkdb-admin.  However, the "official" admin UI is built out of the old_admin branch.  The code probably involve `class TableView` here or some related CSS:

https://github.com/rethinkdb/rethinkdb/blob/old_admin/admin/static/coffee/dataexplorer.coffee#L3240

It looks like there is some explicit logic relating to the scroll bar in the `set_scrollbar` function of ResultViewWrapper.  I'm not sure if that has anything to do with it.

https://github.com/rethinkdb/rethinkdb/blob/old_admin/admin/static/coffee/dataexplorer.coffee#L3775

As for the CSS, removing the `overflow: auto` attribute from `#dataexplorer .results` and `#dataexplorer .result_view` makes the scrollbar go away.  There is that `wrapper_scrollbar` div as well -- that seems not to affect the behavior.  Maybe it has to do with other tabs; I haven't investigated.

![image](https://user-images.githubusercontent.com/258437/197559184-f2e75155-ae12-4b1a-801f-227524ac1390.png)

I would guess that this is just use of the CSS `overflow: auto` attribute that you're interested in, and the reason *two* divs have `overflow: auto` is because the web UI code is a bit of a mess.  Maybe you'd want `overflow-x: auto`.
