### ISSUE TITLE
RethinkDB not fully supported on Raspberry PI OS Bullseye (32/64 bit)

### ISSUE THREAD

**Issue by denis99999** [rethinkdb/rethinkdb#7126]
Hi,

I meet an issue by running a Docker image of Rethinkdb (v2.4.1 or v2.4.2) on the latest Raspberry Pi OS (Bullseye Kernel version 6.1, 32 bit or 64 bit, Aarch64 architecture), whether this image is built on the Raspberry Pi or either an image obtained from Docker HUB, the container launches well and I can create a database via the web user interface (@IP:8080), but when I try to create a table, a fatal error occurs which causes the container to stop, here are the logs:

```
# docker run --name rethinkdb -v /opt/rethinkdb/:/data --net host rethinkdb-armv7l:2.4.1 rethinkdb --bind all
Running rethinkdb 2.4.1 (CLANG 7.0.1 (tags/RELEASE_701/final))...
Running on Linux 6.1.21-v8+ aarch64
Loading data from directory /data/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 172.17.0.1, 192.168.1.100, ::1, fe80::42:32ff:fe89:5ef4%4
Listening on driver addresses: 127.0.0.1, 172.17.0.1, 192.168.1.100, ::1, fe80::42:32ff:fe89:5ef4%4
Listening on http addresses: 127.0.0.1, 172.17.0.1, 192.168.1.100, ::1, fe80::42:32ff:fe89:5ef4%4
Server ready, "raspberrypi_phu" 9d1550a6-e7dc-48b7-9781-7fc17562a66d
Version: rethinkdb 2.4.1 (CLANG 7.0.1 (tags/RELEASE_701/final))
error: Error in thread 4 in src/arch/runtime/thread_pool.cc at line 422:
error: Bus error from accessing the address 0xf0fe6401.
error: Backtrace:
#
# docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                       PORTS     NAMES
86f2c1edd0bc   rethinkdb-armv7l:2.4.1           "rethinkdb --bind all"   19 seconds ago   Exited (139) 4 seconds ago             rethinkdb
#
# docker --version
Docker version 24.0.6, build ed223bc
# 
# uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
# 
# cat /etc/debian_version 
11.7
# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
# 
# lscpu
Architecture:                    aarch64
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
L1d cache:                       128 KiB
L1i cache:                       192 KiB
L2 cache:                        1 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
# 
# getconf LONG_BIT
32
```
Note that other Docker images work perfectly, it is only RethinkDB that does not work well on these latest Raspberry Pi OS (32/64 bit).
Thank you in advance for helping me.

**Comment by srh** [comment]
Thank you for the detailed report.

Realistically you should expect no help with this.  Unless somebody has a 64-bit raspberry pi to test with.

However, it might be useful to run in a debugger, I guess lldb in this case, and use that to see a backtrace for the bus error.

My guess is the outcomes is a straightforward unaligned memory access problem, and the 64-bit Linux kernel not fixing that up for 32-bit processes.  (Some quick reading suggests that 32-bit ARM kernels do perform such fixups, and that 64-bit ARM generally supports misaligned access with normal instructions.)  It's very likely an issue with btree node code (in leaf_node.cc or internal_node.cc), which very directly and gratuitously casts pointers and performs such accesses.

**Comment by srh** [comment]
I should add, RethinkDB "officially" doesn't support 32-bit ARM binaries.  I think we dropped support for 32-bit x86 as well, at least in the sense that we don't release packages.  Basically you should be aware that you're past the bleeding edge.

**Comment by denis99999** [comment]
@srh , thanks but as I said on my initial message, it is not specific to 32 bit, this issue occurs also with ARM 64 bit binary of rethinkDB built on the latest Raspberry Pi OS (Bullseye Kernel version 6.1, 64 bit, Aarch64 architecture) while an ARM 32 bit binary of rethinkDB  works well with a legacy Raspberry Pi operating system (Buster Kernel Version 5.x, 32-bit, armv7l architecture)

**Comment by denis99999** [comment]
@srh, now it works well with 64-bit binaries (my docker installation was not adequate), and I note that 32-bit binaries are no longer supported on the 64-bit architecture!

**Comment by srh** [comment]
@denis99999 We've had a few people come in with RPi problems (see #7124) and I think 32-bit userspace on 64-bit kernel is a reasonable idea on any device, so supporting or at least *working* without attempting misaligned memory accesses is not an unreasonable ask.

However, RethinkDB uses userland threads, which as we have it configured take up a lot of address space (131 KB), and it acts like it's free to create quite a lot of them, so that's another reason to avoid 32-bit RethinkDB.

**Comment by srh** [comment]
I've made a branch that might address the bus error issues on 32-bit ARM binaries.

https://github.com/srh/rethinkdb/tree/srh/aligned

I have an ARM device I could resurrect to test this with -- but if anybody encounters this error and wants to run in a 32-bit address space, even with a 32-bit kernel, you might try building from that branch (or try merging v2.4.x into that branch, then building).

It might not work, because maybe there are other unaligned accesses outside of btree code, or maybe I failed to exhaustively replace them.

**Comment by denis99999** [comment]
@srh, thanks for your suggestion but in my side I prefer to rely on the official rethinkDB master branch, so if a 32-bit rethinkdb binary is not officially supported on a 64-bit OS, I will take that into account in my work.

**Comment by srh** [comment]
I am investigating this.  At least in debug mode I've got RethinkDB 32-bit binaries built and running, and getting bus errors, on arm64 Linux.

It is not just confined to leaf node and internal node code.  For example, `two_level_array_t<index_block_info_t>` creates a misaligned memory access because `index_block_info_t` is a packed struct and the `repli_timestamp_t::operator==` member function passes the `*this` parameter by reference (as C++ member functions generally do) and in an array, the struct fields get misaligned.  (And knowledge of the misaligned field seems not to have a warning when passed as a `this` parameter, even though that's a common type of warning.)

**Comment by srh** [comment]
#7128 fixed the unaligned accesses issue, seemingly.

I didn't do an exhaustive scouring of the project (outside of everything in btree code, blob code, and in_memory_index code that was touching the data that encountered bus errors), but it now runs without bus errors from unaligned memory accesses, with 32-bit binaries running on a 64-bit OS.

So that may be one less barrier for others.

There might be other issues with 32/64 bit rPi; I don't know.

**Comment by denis99999** [comment]
@srh , great ! thank you for your effort, I will test that ASAP.
