### ISSUE TITLE
Why exactly do rethinkDB add null characters to response / request JSON ?

### ISSUE THREAD

**Issue by anuragvohraec** [rethinkdb/rethinkdb#7150]
hi All,

Why do rethinkdb append null characters `\0` to the HTTP response, or require it in the HTTP request ?
Its casuing a lot of trouble in our C++ code. This null character(or may be backspace characters) causes trouble in capturing it into string.
Any guidance on how to capture the response from rethinkdb  (doing it via a C++ HTTP client) appropriately in C++ ?

**Comment by srh** [comment]
@anuragvohraec RethinkDB doesn't have any official HTTP API, and I don't see where its internal admin UI HTTP client, if you're using that, adds or expects nul characters, let alone backspace characters, either.

And if it did, why would it cause you trouble capturing it into a string?

**Comment by anuragvohraec** [comment]
> And if it did, why would it cause you trouble capturing it into a string?

The null characters causes strings (in C++) to terminate in midway, rather than capturing the JSON response.
1. There is no easy way to get over it, like one need to manually iterate over the data buffer and than remove this null.
2. System which recives response from different system needs to made system aware to handle this situation to take care of response from RethinkDB in a generic way. 
3. The HTTP client which can capture JSON response, fails to capture JSON response by there build in functions. The data from RethinkDB fist needs to be updated (held in RAM) and than parssed into JSON.

**Comment by srh** [comment]
It looks like the admin UI's HTTP protocol has a 64-bit token and 32-bit size, stored in little endian, at the beginning of the response.  It does this here: https://github.com/rethinkdb/rethinkdb/blob/90c6e37472ca945b5138bc0e1d5434face691be0/src/client_protocol/server.cc#L764-L765

Looking back with git blame you can see that as of commit de379ea5ec6ec3f93a93ca6244fa17bdf10a9cd7 the logic seemed to be in `src/protob/protob.tcc` and that's where it was developed, amidst code that supported both protocol buffers and json-i-fied protocol buffer content, and preceded them with the same binary token and size values.  It's likely the client driver protocol still uses this format, even though it's not using this code.

If your C++ string handling code is sensitive to inline zero characters, there is a serious problem with how you go about writing your code.  You are writing incorrect code, in general.

Also, we don't want to make RethinkDB to be easy to use over the admin HTTP API, because it provides admin-level access to the cluster, bypassing user permissions systems.  And some web developers would use it to give client-side browsers direct access to RethinkDB.  So the binary data in front of the JSON will stay.

If you're already parsing JSON off the admin UI in C++, you could probably use the official client driver protocol without much difficulty.

**Comment by anuragvohraec** [comment]
I am thankfull for your time without doubt. Thank you so much for your time.

All this twisted attempts from my side is as I am trying to embed RethinkDB in my custom JavaScript Engine (so can't use NodeJS client).

Embedding it via RethinkDB C++ client would require adding this client it as a part of the JS Engine. The eaisiest way to embed it into it would be to use the HTTP route, as I have already implemented `fetch` in my JS Engine.  So was using the HTTP route, as I can simply write a JS Script to interact with the RethinkDB. This way I don't need to embed Rethink Client as a part of my JS Engine. 

Offcourse I am not arguing to change the code at rethinkDB, all what I was trying to understand the rationality and how to over come it. 

However in regards to this:
> If your C++ string handling code is sensitive to inline zero characters, there is a serious problem with how you go about writing your code. You are writing incorrect code, in general.

I will like to place my point.
Any straight C++ program would simply fail with null character in string:
```
#include <iostream>

int main() {
    std::string a =  "\0DataFromRethinkDB";
    std::cout <<a ;
    //prints nothing on screen as it has null string in it
    return 0;
}
```
This system `rethinkDB` is first I am facing which itself created in C++ adds null characters as part of string.
There might be rationality for its usage which is totally acceptable, which I was trying to understand.

And was trying to find a solution to it, which any way I found out, which is highly inefficient, as I have to view this data (from rethinkdb) as a memory and iterate through each byte to see it it has `\0` in it and replace it will blank spaces.

When in all it could have been done at the rethinkDB itself, but there might be its own rationality for its usage.

**Comment by srh** [comment]
You should use `cout.write(a.data(), a.size())` if you have an arbitrary octet stream.

The response is, at some level of abstraction, a (char *, size_t) pair.  You can add/subtract 12, or whatever the offset is, from the numbers, pass a string_view to whatever needs it, etc, to skip to the json part of the response.  I don't remember how RethinkDB handles zero characters in reql strings themselves, but you might have that possibility as well.
