### ISSUE TITLE
How to handle NaN error in javascript Driver?

### ISSUE THREAD

**Issue by doaortu** [rethinkdb/rethinkdb#7152]
I see a few issue mentioning this, but I got no answer.

I tried:
```typescript
try{
  r.db.table('name').get("id")update({test: NaN}).run(conn)
}
catch(err) {
  console.err(err)
}
```

but the catch block never called. It just crash my app.
But the undefined error is properly caught by the catch block.

**Comment by doaortu** [comment]
I currently doing this hack to overcome this limitation:
detect if data contains undefined or NaN before inserting/updating to db, by using this function, if anyone interested:
```typescript
export function recursiveCheckUndefinedNaN(obj: any) {
  for (var v in obj) {
    if (typeof obj[v] == "object")
      recursiveCheckUndefinedNaN(obj[v]);
    else if (obj[v] == undefined || (typeof obj[v] == 'number' && isNaN(obj[v]))) {
      return true;
    }
  }
  return false;
}
```

**Comment by srh** [comment]
The run function in the RethinkDB JS driver either takes a callback or returns a Promise.  That's why the catch block doesn't work.

Your attempt at a try/catch block involves an underlying misunderstanding of how JavaScript's event-looped programming works, so you will want to specifically correct that misunderstanding.
