### ISSUE TITLE
silly less / coffeescript deps

### ISSUE THREAD

**Issue by tj** [rethinkdb/rethinkdb#766]
pretty brutal that you can't build the thing without these executables... please consider removing these dependencies, it's nothing but annoying

**Comment by jonathanong** [comment]
any status on this? i'd love to help because the driver is way ahead of mongodb, but i'm not touching the source code in its current form.

**Comment by jonathanong** [comment]
rewriting into ES6 w/ a transpiler would be pretty cool. that's what the author of autoprefixer did (coffeescript -> es6) and i don't think he has any regrets.

**Comment by joaojeronimo** [comment]
:+1: for rewriting into ES6, :-1: for CoffeeScript

Also please please please put this in a separate repository so people don't have to clone the whole rethinkdb when fixing something in the driver. If you want the driver in this repo for the tests then just `require('rethinkdb')` where necessary.

**Comment by jonathanong** [comment]
https://github.com/eventualbuddha/decaffeinate :8ball:

**Comment by danielmewes** [comment]
There have been some thoughts on adopting https://github.com/neumino/rethinkdbdash as the official RethinkDB node.js driver. Rethinkdbdash is written in JavaScript directly. It doesn't have capabilities for connecting to the server through HTTP yet (we need that for the web UI), so we have to implement that first.

Note that we will still be using less and coffeescript for the web UI code, so the dependencies won't change.

**Comment by danielmewes** [comment]
@joaojeronimo regarding putting drivers in a separate repository, please see https://github.com/rethinkdb/rethinkdb/issues/1740

**Comment by niieani** [comment]
:+1: for move to ES6 or to `rethinkdbdash`.

**Comment by niieani** [comment]
Would the `rethinkdb` team be interested in a PR that converts the current CoffeeScript driver to TypeScript?

**Comment by joaojeronimo** [comment]
Please don't do typescript, the point of this PR is to have the rethinkdb driver in a common language for everyone that you don't have to transpile and more people understand/write/work with than any other language, writing the driver in typescript is just as bad as coffeescript except with a different syntax and type safety at compile time.

**Comment by niieani** [comment]
@joaojeronimo For backwards compatibility you'd need to transpile modern-style JS to ES5 anyway, so that's not really saving any steps. 

TS is simply JS with optional typings, it's not a different syntax like CoffeeScript. The upside of TypeScript is that, if at any time in the future the team decides to ditch TypeScript and switch to pure JavaScript, they can strip the type declarations using **one** simple command (`tsc -p . --target esnext`). Et voilà, you're back to using pure JS!

It's not possible to do the same with CoffeeScript, since CS includes many features that JS simply does not have, and the code transpiled by CS is filled with overly verbose, convoluted and hard-to-read JS with extra helper methods.

**Comment by joaojeronimo** [comment]
Well this is not about to turn into a JS vs TS conversation. My point is more people write/understand Javascript than both typescript and coffeescript and probably all the AltJS languages combined, if you want to have more people willing to contribute to a community project then you go with Javascript.

Your point about typescript compiling to JS is as valid as if it were with coffeescript, typescript also brings non JS things to the table like async/await and others.

**Comment by niieani** [comment]
I'd like to leave this decision to the `rethinkdb` team -- rather than wasting time discussing the merits of one over the other -- I'm happy to help with either a TS or a ESnext conversion. Ultimately _they'll_ be working with it the most, so _they've_ gotta be comfortable with the language choice.

I proposed TS as the better alternative, since the team is in the process of converting `horizon`'s client to TypeScript (there's a [WIP PR](https://github.com/rethinkdb/horizon/pull/741) by @deontologician), so it seemed natural that the `rethinkdb` driver would move to TypeScript too.

@joaojeronimo async/await is not TypeScript. It is a stage-3 proposal that will ship as official JS, most likely in the ES2017 standard, and most of the major browsers already have implementations ready, in fact Chrome ships with await/async enabled by default.

While it might sound contradictory, contributing to a TS codebase is much easier than to a JS one, because of things like self-documentation through types and autocompletion. You can dive into the code and understand it much quicker than a raw JS codebase. 

Plus, it's easy to refrain from using any TS-specific features in the code (actually, the only TS-specific feature are `public`/`private` fields in class constructors, the rest is all standard JS + some stage-3 ECMA proposals).

I'm not going to speak about TS vs JS anymore in this topic, since many things were said about that on the internet and it just seems like a pointless flame war -- also -- there are 19 participants to this topic, so lets respect their time and their email inboxes. 🐧

**Comment by viridia** [comment]
https://trends.google.com/trends/explore?date=today%205-y&q=TypeScript,CoffeeScript,%2Fm%2F0h52xr1

**Comment by joaojeronimo** [comment]
https://trends.google.com/trends/explore?date=today%205-y&q=TypeScript,CoffeeScript,%2Fm%2F0h52xr1,javascript

**Comment by ricardobeat** [comment]
While it might look like foresight in retrospect ('this language has no future'), the general attitude towards CoffeeScript, as seen here, likely helped it's early demise. I still feel like the years when I wrote CS full time (2010-2013) was one of my most productive periods, and can't help but grin at the sight of _'pretty brutal that you can't build this without these executables.. all these dependencies'_ considering where we are today. RIP coffeescript :)

Close this one?

**Comment by neumino** [comment]
This is a very old thread, please open a new one if you want to discuss rewriting the interface.

**Comment by srh** [comment]
I might get rid of the coffeescript dep.  If we're going to open a new one I'll... close this one.
