### ISSUE TITLE
Add a macroing system to ReQL

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#849]
We've talked before about having a macroing system in ReQL. I think now would be a really good time to do it because it makes many of the ReQL improvements we're hoping to make over the next few releases a lot easier. Issues like #838, #182 and #324 would be very simple to implement. All it would require is writing a bit of ReQL code to define a new macro. This is particularly nice because even in places where we eventually need some backend support for something to do it efficiently in a lot of places we can still create a minimal useful implementation using macros to play with the API.

I think this project will be a lot simpler if we don't expose it to users at first. Basically just have a system for doing what we already do internally for things like `join` that lets use iterate quickly on these things.

**Comment by skizzerz** [comment]
Bumping this issue, as the thought just occurred to me not too long ago that a client-visible macroing system would be incredibly useful to make it easier to use very complex queries, especially when you want to run the same query both manually in data explorer as well as multiple places throughout an application.

My thoughts on how this would look are as follows (names chosen to be consistent with the db/table/index commands):

#### r.macroCreate(macroName, function) → object
This would create a macro with the given macroName using the given function. The function can return anything and can take parameters, which are passed in when executing the macro. Macro names are case-sensitive, must be unique, and are global across all databases.

**Example:** Creates a macro to compute a golfer's score for a game.
```javascript
r.macroCreate('getscore',
    function (player, net) {
        return r.branch(
            net.default(true),
            player('gross_score').sub(player('course_handicap'),
            player('gross_score')
        );
    }
).run(conn, callback);
```

#### r.macroDrop(macroName) → object
Deletes a previously-created macro.

**Example**
```javascript
r.macroDrop('getscore').run(conn, callback);
```

#### r.macroRename(oldName, newName) → object
Renames a macro.

**Example**
```javascript
r.macroRename('getscore', 'getScore').run(conn, callback);
```

#### r.do([args]*, macroName) → any
#### any.do([args]*, macroName) → any
This adds two overloads to the existing do command to execute a macro. In both overloads, the given macroName is executed as if the macro function itself were present in the do command instead of simply the name.

For the first overload, if args are specified, they are passed in exactly as they would be if a function were passed to r.do. For the second overload, any specified arguments are passed *after* the previous result (in other words, the first argument would be the result of executing the part before .do, and any other arguments are as specified in the command).

**Examples**
```javascript
r.do(
    r.table('players').get('f19b5f16-ef14-468f-bd48-e194761df255'),
    true,
    'getscore'
).run(conn, callback);

// In this example, the "player" argument is the result of .get() and the "net" argument
// is the first argument passed into .do()
r.table('players').get('f19b5f16-ef14-468f-bd48-e194761df255').do(true, 'getscore').run(conn, callback);
```

If overloading do is not desirable (and the syntax is rather clunky in order to make it fit with existing overloads), consider the following commands instead that achieve the same purpose:
```
r.macro(macroName, [args]*) → any
any.macro(macroName, [args]*) → any
```

Note that in this version, the macroName comes first, which is convenient when it is only a string as opposed to a potentially-gigantic function. The do overloads above kept the macroName last in order to be consistent with where the function would normally be located.

**Comment by danielmewes** [comment]
Hi @skizzerz , that's a very well written proposal, thank you.
What you propose is very similar to https://github.com/rethinkdb/rethinkdb/issues/3740 . I'll copy your proposal over to that thread, so we can have everything in one place.

(also I think I'll close this issue, since rewriting how we internally write ReQL terms is not really on the table at the moment)
