### ISSUE TITLE
ReQL non proposal: Getting keys whose compound indexes has a common prefix.

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#955]
Suppose I have a compound index `cid` and I want to get all of documents that have `"foo"` as the first value in the compound index. AFAIK there isn't a great way to do this in ReQL. The best way to do this that I can come up with is:

``` Python
r.table.between(["foo"], ["fop"], id = "cid").filter(lambda x: x["cid"][0] == "foo")
```

Which isn't terribly pretty. I'm not sure I have a full proposal for this (hence the non proposal title). I'd like the support the syntax:

``` Python
r.table.prefix(["foo"], id = "cid")
```

which would be feasible. What do others think would be a good API for this?

**Comment by stuartpb** [comment]
Perhaps a note that, right now, if you want to use a prefix for an index query, you should just make another secondary index for types of prefix (using an index function to provide whatever truncation applies)?

Granted, it's not great if you're looking to do something like autocomplete, but it's *something*.

(You could also probably swing this with a `between` and some binary searching.)

**Comment by danielmewes** [comment]
@stuartpb Thanks for pointing that out. That indeed works (it's basically what @jdoliner had noted in the initial post at the top with `between(["foo"], ["fop"], id = "cid")`, except that you can cut off the `filter` now.
In fact it's going to become even easier with https://github.com/rethinkdb/rethinkdb/issues/1023:
`r.table(...).between(["foo", r.minval], ["foo", r.maxval])`.

This is still not quite as nice as a separate prefix syntax, especially since you have to use `between` instead of `getAll` and that might not be obvious to new users. So I think there's still value in this issue, but there's definitely a better work-around now.

**Comment by stuartpb** [comment]
> `r.table(...).between(["foo", r.minval], ["foo", r.maxval])`

Is that right? That's what I had written initially, but it seemed to me that even if the right bound were open (which I assume is what `r.maxval` means), that means it's still not going to find things that *start* with the prefix, as they would sort lower than it. Do they sort equivalent to the prefix?

**Comment by danielmewes** [comment]
@stuartpb Ohh I think we're talking about different things. Sorry I misunderstood your proposal.

This thread is about what we call a compound index, where you typically index by an array containing multiple fields from the document. So the keys look like `[r.row('field1'), r.row('field2'), r.row('field3')]`. Now the question was how to query such an index if you only want to filter by the value of say `field1`, but don't care what's in `field2` or `field3`. So that's what you can use `r.minval` and `r.maxval` for.

What you described I believe was filtering by a prefix of a string, didn't you? This is independent of compound indexes, and for that indeed your solution is the right one (and the only one that currently works I think).

**Comment by stuartpb** [comment]
Right - I was getting a little lost because it seems a *lot* of this discussion hinges on the implementation essentially being a "prefix" for what is, under the hood, one big string.

For only wanting a single component of a compound index, I would go back to my initial (snipped above) suggestion to consider using a separate secondary index for just the "prefix" component of the compound index.

**Comment by stuartpb** [comment]
Oh, okay, I get what the `r.minval` and `r.maxval` do in that query now - they stand in for the second part of the compound index, effectively saying "the second part can be anything". What confuses me is how the query works when they're *not* specified - what is their default value, if not these?

**Comment by mlucy** [comment]
@stuartpb -- because RethinkDB is (mostly) a JSON datastore, we don't restrict you to a particular type in your index.  A "compound index" is just an index where the type of the index is an array.  So if you specify a one-element array as e.g. the lower part of your range, we just treat that one-element array as the lower part of your range -- we don't assume that everything in the index is a two-element array, because it might not be true.

**Comment by stuartpb** [comment]
So how do one-element arrays sort relative to two-element arrays?

**Comment by mlucy** [comment]
We compare the first element of the arrays.  If one of the first elements is smaller, that array is smaller.  If the first elements are equal, the one-element array is considered smaller.

In general it's something like
```
def cmp(arr1, arr2)
  if arr1 == []
    if arr2 == []
      return 0
    else
      return -1
    end
  elsif arr2 == []
    return 1
  else
    el1cmp = cmp(arr1[0], arr2[0])
    if el1cmp != 0
      return el1cmp
    else
      return cmp(arr1[1..-1], arr2[1..-1])
    end
  end
end
```

**Comment by stuartpb** [comment]
So `r.table(...).between(["foo", r.minval], ["foo", r.maxval])` could just be reduced to `r.table(...).between(["foo"], ["foo", r.maxval])` ?

**Comment by mlucy** [comment]
Yes, except if you happened to have an entry in your index with the exact key `["foo"]`, it would be omitted from the first and included in the second.

**Comment by srh** [comment]
Closing because I'm trimming down open issues and the need for this is obviated by r.maxval.  And it's still in the proposal stage.  If you come across this and want this (because appending r.maxval is kind of annoying), be sure to chime in.
